### ISSUE TITLE
Issue with multiple routes path patterns

### ISSUE THREAD

**Issue by bgarel** [nelmio/NelmioApiDocBundle#1005]
When the config routes path_patterns array has multiple elements, the filteredRoutes list is not filled correctly.

Example in config.yml :
nelmio_api_doc:
   routes:
      path_patterns: 
      - ^/api/foo
      - ^/api/bar

**Comment by GuilhemN** [comment]
This is currently implemented as a "and" (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/Routing/FilteredRouteCollectionBuilder.php#L41) but i agree it probably makes more sense to have a "or". 
Could you submit a pr ?

**Comment by bgarel** [comment]
I created the pr : https://github.com/nelmio/NelmioApiDocBundle/pull/1007
