### ISSUE TITLE
column type guid not appearing on the api doc return

### ISSUE THREAD

**Issue by sas05** [nelmio/NelmioApiDocBundle#1008]
`* @ORM\Id
     * @ORM\Column(type="guid")`

This is not appearing but 

when 
`* @ORM\Id
     * @ORM\Column(type="integer")`
this is appearing on the doc

**Comment by GuilhemN** [comment]
What version of the bundle are you using ?

**Comment by sas05** [comment]
version 2.13.2

I checked the DataTypes class, and found guid datatype is not added.

**Comment by GuilhemN** [comment]
Ok so you already found the cause ☺ Can you submit a pr please ?

**Comment by sas05** [comment]
I would like to but only adding this datatype is not enough. but Let's see if I can. thanks
