### ISSUE TITLE
How to use groups with `@Model`

### ISSUE THREAD

**Issue by BowlingX** [nelmio/NelmioApiDocBundle#1009]
Hi,
I'm using the current 3.0 beta. Regarding to https://github.com/nelmio/NelmioApiDocBundle/issues/940 the new `@Model` annotation should support groups. But it seems groups are not supported. The property is not defined in the annotation.

--
David

**Comment by GuilhemN** [comment]
see https://github.com/nelmio/NelmioApiDocBundle/pull/1010.

However it does only support symfony serializer groups for now as the integration with the jms serializer is not really done yet.

**Comment by BowlingX** [comment]
wow, that was fast, thank you.

**Comment by GuilhemN** [comment]
You're welcome, i had to do it for a while and I knew exactly how i wanted it so it didn't take too long 😉
