### ISSUE TITLE
[3.0] Reflection does not work if building a bundle with `composer install --no-dev`

### ISSUE THREAD

**Issue by BowlingX** [nelmio/NelmioApiDocBundle#1011]
Due `phpdocumentor/reflection-docblock` defined as `devDependency`, if running composer install without dev dependencies (in production), generation of api-docs fails with missing class exception and/or `PropertyInfo component was not able to guess the type of [...] `.

Is this an indented behaviour?

**Comment by GuilhemN** [comment]
If you want to use php docs then you have to require `phpdocumentor/reflection-docblock` even in dev mode, the bundle doesn't do it for you because you can use the bundle without it (php type hints might be enough for you).

**Comment by BowlingX** [comment]
ok, thank you :)
