### ISSUE TITLE
symfony 3 support

### ISSUE THREAD

**Issue by mohsenjalalian** [nelmio/NelmioApiDocBundle#1012]
hi I install your bundle in symfony 3 . i like to know that this bundle is compatible with symfony3 or not because i can not work with that and when i go to the doc page it is blank

**Comment by GuilhemN** [comment]
Yes, this bundle works with sf 3.

Are you using the 3.x version of the bundle ?
If so can you try updating to the latest beta, check again and if it still doesn't work give me more details ?
