### ISSUE TITLE
Separate script.html.twig and sandbox.html.twig templates (proposal)

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1013]
Could you move the large `<script>` tag out if layout.html.twg and `{% include %}` it instead?  This would make overriding layout.html.twig simpler so we could embed API docs into our webapp sharing headers, footers, navigation, etc.  While we're at it, moving the sandbox_configuration `<div>` out to another included template would help the same way.  

The resulting layout.html.twig would become something like below which would be much easier to override.

```
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <meta charset="utf-8" />
        <!-- Always force latest IE rendering engine (even in intranet) and Chrome Frame -->
        <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible" />
        <title>{{ apiName }}</title>
        <style type="text/css">
            {{ css|raw }}
        </style>
        <script type="text/javascript">
            {{ js|raw }}
        </script>
    </head>
    <body>
        <div id="header">
            <a href="{{ path('nelmio_api_doc_index') }}"><h1>{{ apiName }}</h1></a>
            {% include 'NelmioApiDocBundle::sandbox.html.twig' %}
            <br style="clear: both;" />
        </div>
        {% include motdTemplate %}
        <div class="container" id="resources_container">
            <ul id="resources">
                {% block content %}{% endblock %}
            </ul>
        </div>
        <p id="colophon">
            Documentation auto-generated on {{ date }}
        </p>
        {% include 'NelmioApiDocBundle::script.html.twig' %}
    </body>
</html>
```

**Comment by GuilhemN** [comment]
We're currently focusing on the 3.0 version of the bundle so 2.x won't include new features unless we have PRs and they seems important enough.

**Comment by pdugas** [comment]
Upgrading...

**Comment by GuilhemN** [comment]
Actually, maybe I should have asked @lsmith77. Do you want to keep maintaining 2.x?

**Comment by lsmith77** [comment]
not in the midterm but in the short term I might be able to review smaller PRs. what is the intention regarding ensuring that all 2.x features make it to 3.x?

**Comment by GuilhemN** [comment]
3.0 is a complete revamp of the bundle so imo the two branches must be completely separated and a new feature in 2.0 won't necessarilly make it in 3.0.

**Comment by GuilhemN** [comment]
Ok, closing.
