### ISSUE TITLE
Force Content-Type

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1014]
I'm tinkering with "~3.0@beta" with my routing set to put the ApiDoc/Swagger page at `/api` and my actual API below as `/api/foo`, `/api/bar`, etc. I use FOSRestBundle for the API and it appears to be defaulting everything in/under `/api` to use the `application/json` which breaks the doc page. This used to work with the 2.x version I suspect because the generated page forced the content type.

A quick change in SwaggerUIController.php appears to resolve this issue.

```
    public function __invoke()
    {
        #return new Response($this->twig->render('@NelmioApiDoc/SwaggerUi/index.html.twig', ['swagger_data' => ['spec' => $this->apiDocGenerator->generate()->toArray()]]));
        return new Response(
            $this->twig->render('@NelmioApiDoc/SwaggerUi/index.html.twig', [
                'swagger_data' => [
                    'spec' => $this->apiDocGenerator->generate()->toArray()
                ]
            ]),
            Response::HTTP_OK,
            array('content-type' => 'text/html')
        );
    }
```

**Comment by GuilhemN** [comment]
I was indeed able to reproduce, see https://github.com/nelmio/NelmioApiDocBundle/pull/1015 for a fix.
Thanks for the report!
