### ISSUE TITLE
Javascript .map files referenced but not included

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1017]
The `swagger-ui-standalone-preset.js` and `swagger-ui-bundle.js` files in the composer distribution still have the `sourceMappingURL=...` entries referencing the .js.map files that are not included resulting in 404 requests for them when viewing the docs.

**Comment by GuilhemN** [comment]
Should be fixed by https://github.com/nelmio/NelmioApiDocBundle/commit/aefdca965e0e5ee050806f2360872f2baf88adcc, thanks!
