### ISSUE TITLE
Notice: Array to string conversion

### ISSUE THREAD

**Issue by fredeastside** [nelmio/NelmioApiDocBundle#1018]
Hello! When i use default key in QueryParam from FOSRestBundle like map, error:

```
     /**
     * @Rest\QueryParam(
     *     name="sort",
     *     map=true,
     *     default={
     *         "created"="asc",
     *         "discount"="desc"
     *     }
     * )
     */
```
Notice: **Array to string conversion**
vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/views/**method.html.twig**
line: **258**

**Comment by GuilhemN** [comment]
Closing as 2.0 is no longer maintained.
