### ISSUE TITLE
parameter array items enums causes javascript errors and does not load module t.map is not a function

### ISSUE THREAD

**Issue by wraycode** [nelmio/NelmioApiDocBundle#1020]
cannot get a drop down menu to work for parameter get javascript error in console t.map is not a function
    `      /**
          *     @SWG\Parameter(
         *         name="room",
         *         in="query",
         *         type="array",
         *         @SWG\Items(
          *             type="string",
          *             enum="['dining','living','nursery']"
         *         )
         */
`

**Comment by wraycode** [comment]
inn logs 

[2017-06-22 08:54:55] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/nelmioapidoc/swagger-ui/swagger-ui-standalone-preset.js.map""

**Comment by wraycode** [comment]
got the errors to go away by adding 

`     *         @SWG\Items(
     *             type="string",
     *             enum={"dining","living","nursery","sidechair"}
     *         ),
`
but ti makes a select box not a drop down

**Comment by GuilhemN** [comment]
Should be fixed in https://github.com/nelmio/NelmioApiDocBundle/commit/0bd45e648641caf029a7f629ee1a021354de9958, thanks!
