### ISSUE TITLE
Add ability to get JSON only to use swagger-codegen

### ISSUE THREAD

**Issue by Alex-D** [nelmio/NelmioApiDocBundle#1025]
Get a Swagger doc is cool, but generate SDK with Swagger is better!

So if we can have an URL to get the Swagger as JSON, it could be perfect :)

Also, it could be convenient to reimplements commands which was present in v2: https://github.com/nelmio/NelmioApiDocBundle/tree/2.x/Command

**Comment by GuilhemN** [comment]
See https://github.com/nelmio/NelmioApiDocBundle/pull/1026

> Also, it could be convenient to reimplements commands which was present in v2: https://github.com/nelmio/NelmioApiDocBundle/tree/2.x/Command

Why not, it shouldn't be complicated.
