### ISSUE TITLE
The PropertyInfo component was not able to guess the type of DateTime::$timezone

### ISSUE THREAD

**Issue by tiagokalinke** [nelmio/NelmioApiDocBundle#1027]
Hi,
i have problems with fields with type DateTime.

The PropertyInfo component was not able to guess the type of DateTime::$timezone

**Comment by GuilhemN** [comment]
See https://github.com/nelmio/NelmioApiDocBundle/pull/1028

**Comment by GuilhemN** [comment]
https://github.com/nelmio/NelmioApiDocBundle/pull/1028 is merged.
