### ISSUE TITLE
[3.0] app_dev.php is ignored

### ISSUE THREAD

**Issue by coolmic** [nelmio/NelmioApiDocBundle#1032]
Hi,

I just migrated from 2.x to 3.0 , and I have an issue when I used app_dev.php in the url.

My api doc url is 
`http://domain.dev/app_dev.php/api/doc/`

When I do a request, it target

`http://domain.dev/auth/login`

instead of

`http://domain.dev/api_dev.php/auth/login` .

Did I miss something? It worked well in 2.x .

**Comment by GuilhemN** [comment]
see https://github.com/nelmio/NelmioApiDocBundle/pull/1035
