### ISSUE TITLE
migration doc incomplete

### ISSUE THREAD

**Issue by bitgandtter** [nelmio/NelmioApiDocBundle#1039]
Im migrating my existing doc from v2 to new v3 using the provided doc [under](https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-3.0.md) on which the command use a service call `nelmio_api_doc.extractor.api_doc_extractor` which is not on the bundle.

Is this code obsolete?
There is a any new migration guide?
The service must be created or was not included on the doc?

Help thanks

**Comment by GuilhemN** [comment]
This command must be run with the v2, it is indicated when you have to upgrade to the V3 😉
I think we should add a warning, you're not the first to do the mistake...

**Comment by bitgandtter** [comment]
Sure thing, that will help a lot, thanks for the clarification
