### ISSUE TITLE
[Migration Error] Schema::mergeDescription() must be of the type array

### ISSUE THREAD

**Issue by davidbonachera** [nelmio/NelmioApiDocBundle#1044]
Hi,

After migrating I went through different errors,
First, I had the `@SWG\Parameter` wrongly configured after the migration command. The annotations were like this :

```
    /**
     *     @SWG\Parameter(
     *         name="connection",
     *         in="formData",
     *         description="",
     *         required=false,
     *         type="object (ConnectionType)"
     *     ),
     */
```

The first error was that "in" can't be "formData", so I changed it to body. Then I added a @S

Just after that I added a `@SWG\Schema` with a `@Model` to the SWG/parameter and now I'm getting this error :

```
Type error: Argument 1 passed to EXSyst\Component\Swagger\Schema::mergeDescription() must be of the type array, string given, called in /var/www/symfony/vendor/exsyst/swagger/src/Schema.php on line 86
```
I don't understand which parameter should be an array, it's related to a description field I can easily guess but I can't see which one.

**Comment by davidbonachera** [comment]
After digging a bit (sorry that I wrote this issue to fast) i saw that also an patchAction was updated via the migration command with a wrong line, this issue can be closed.

**Comment by Soullivaneuh** [comment]
@davidbonachera Could you please elaborate what you fixed? I ran into the same issue.

**Comment by davidbonachera** [comment]
@Soullivaneuh It's been a while, but I remember it happened when I used the migration commands. It had wrongly convert annotation on a patch function in my controller.
