### ISSUE TITLE
[3.0] FileType not supported

### ISSUE THREAD

**Issue by Alex-D** [nelmio/NelmioApiDocBundle#1055]
Seems simple to implement with something like that:

```php
<?php
                if ('file' === $blockPrefix) {
                    $property->setType('file');
                    break;
                }
```

https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/FormModelDescriber.php#L63

**Comment by Alex-D** [comment]
Seems not working with just that block of code.

Swagger PHP version here:

https://github.com/zircote/swagger-php/blob/d191b5fca4f08786605316895f0542938bacb4a8/Examples/petstore.swagger.io/controllers/PetController.php#L282

**Comment by 7thcubic** [comment]
http://docs.swagger.io/spec.html

4.3.5 actually file type is not recommended

**Comment by chrisguitarguy** [comment]
Closing due to age and inactivity. Also looks like OpenAPI 3.X no longer has a `file` type but instead recommends multi part request definitions.

- https://swagger.io/docs/specification/data-models/data-types/#file
- https://swagger.io/docs/specification/describing-request-body/file-upload/
