### ISSUE TITLE
[3.0] CollectionType not supported

### ISSUE THREAD

**Issue by Alex-D** [nelmio/NelmioApiDocBundle#1056]
As said here: https://github.com/nelmio/NelmioApiDocBundle/pull/1022#issue-238325388

CollectionType are not implemented yet.

Seems to be just an array type:

https://github.com/zircote/swagger-php/issues/328#issuecomment-231652774

**Comment by iBasit** [comment]
+2

**Comment by GuilhemN** [comment]
Fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1126 :)
