### ISSUE TITLE
[3.0] Use JSON schema file for swagger declaration

### ISSUE THREAD

**Issue by ryall** [nelmio/NelmioApiDocBundle#1057]
Wondering how to use an external JSON schema file when declaring the annotations on a controller action.

**Comment by GuilhemN** [comment]
I'm not sure what you mean. If you use an external JSON schema file, then you don't need annotations, right?

**Comment by ryall** [comment]
I have an external schema file, I just don't know how to link it to the expected input/output.

**Comment by GuilhemN** [comment]
I guess you can reference an other file using `$ref`: `$ref: ./schema.json#/définitions/Foo`.

**Comment by GuilhemN** [comment]
Closing as I guess it's fixed :)

**Comment by ryall** [comment]
Yes, thanks!
