### ISSUE TITLE
adding description for url param

### ISSUE THREAD

**Issue by iBasit** [nelmio/NelmioApiDocBundle#1063]
How to add description for `user` for following route tag

     * @Route("/api/{user}/rewards", methods={"GET"})

I have tried putting the following, it worked, but it throws javascript error and fails to trigger action. 

     *     @SWG\Parameter(
     *         name="user",
     *         in="query",
     *         description="username or ....",
     *         required=true,
     *         type="string"
     *     ),

**Comment by GuilhemN** [comment]
Using `@SVG\Parameter` is the way to go. What error do you have ?

**Comment by GuilhemN** [comment]
Closing as I guess it's fixed :)
