### ISSUE TITLE
3.0 migration script errors:  Unrecognized options "name, swagger" under "nelmio_api_doc"

### ISSUE THREAD

**Issue by plimpton** [nelmio/NelmioApiDocBundle#1064]
I updated my composer reference to 3.0@beta and copy/pasted the example command for upgrading the annotations following directions from https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-3.0.md but I'm getting a strange error with little to no stack trace

{code}
./bin/console api:doc:convert

Fatal error: Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized options "name, swagger" under "nelmio_api_doc" in /var/www/html/phpapp/Symfony/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 317

Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized options "name, swagger" under "nelmio_api_doc" in /var/www/html/phpapp/Symfony/vendor/symfony/symfony/src/Symfony/Component/Config/Definition/ArrayNode.php on line 317

Call Stack:
    3.9970    6494512   1. Symfony\Component\Debug\ErrorHandler->handleException() /var/www/html/phpapp/Symfony/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:0
{code}

Any ideas what I'm missing?

Also the command references Nelmio\ApiDocBundle\Annotation\ApiDoc but that class is not part of the 3.0 package for some reason

**Comment by GuilhemN** [comment]
You have to stick on 2.0 to run the command. Only then you have to upgrade to 3.0.

**Comment by plimpton** [comment]
Yeah, I thought I'd save time by upgrading earlier, but nope
