### ISSUE TITLE
Bundle requires TwigBundle to be active even when outputting to JSON format

### ISSUE THREAD

**Issue by dnna** [nelmio/NelmioApiDocBundle#1072]
NelmioApiDocBundle declares "twig" as an argument for the service "nelmio_api_doc.controller.swagger_ui", which makes the container build break if TwigBundle is not enabled.

In my use case I have a stripped-down Symfony setup without twig and I simply want to output the spec in JSON. I have worked around the issue by overriding "nelmio_api_doc.controller.swagger_ui" in my app, but it would be nice if TwigBundle could be made optional upstream.

**Comment by GuilhemN** [comment]
Thanks for the report!
See https://github.com/nelmio/NelmioApiDocBundle/pull/1074
