### ISSUE TITLE
Inline schema allOf not working

### ISSUE THREAD

**Issue by choonge** [nelmio/NelmioApiDocBundle#1083]
We have a Symfony 3.3 application which has a `Project` model. To improve DRY, we use JMS Serializer annotations on the Model to define which fields to expose using the API. But the response is not always exactly the model - sometimes we add more information to the JSON output. For example, an `url`. To this end, we use the `allOf` property as follows in this controller method annotation:

```
    /**
     * @SWG\Get(
     *     summary="Retrieves the collection of Project resources",
     *     operationId="cget",
     *     tags={"project"},
     *     @SWG\Response(
     *         response=200,
     *         description="Give it to me baby",
     *         @SWG\Schema(
     *             allOf={
     *                 @SWG\Schema(ref="#/definitions/Project"),
     *                 @SWG\Schema(
     *                     @SWG\Property(property="url", type="string")
     *                 )
     *             }
     *         )
     *     )
     * )
     * @FOS\RestBundle\Controller\Annotations\View()
     */
    public function cgetAction()
    {
        return $this->getProjectRepository()->findAll();
    }
```

This leads to the following error:

```
Type error: Argument 1 passed to EXSyst\Component\Swagger\Schema::__construct() must be of the type array, object given, called in /var/www/app/vendor/exsyst/swagger/src/Schema.php on line 75
```

When looking into `exsyst/swagger`, on this line: https://github.com/GuilhemN/swagger/blob/v0.3.0/src/Schema.php#L58

Indeed we see that the constructor argument must be an `array`. Interestingly:

* Annotations are read into stdObject classes, so this cannot work
* There is an old commit `Allow non array values (such as stdClass)` which seems to take care of exactly this problem for everything except `Schema.php`: https://github.com/GuilhemN/swagger/commit/5913ee99a9b1a5d8db6ac20afe388689756810d9#diff-d93665ebda8161366b1bb721f8df7092
* If I manually remove that `array` type hint from the constructor, everything works as I would expect: I get the fields from the definition, plus any extra fields which I define in the annotation

So the question is: shall I send a PR to remove that type hint?

PS Apologies if this is not the correct place for this question. The `exsyst/swagger` project has its Issues turned off, and since they are so closely related, I hope it is OK if I ask this here.

**Comment by GuilhemN** [comment]
I think that's a mistake indeed, please send a PR if you can :)

**Comment by choonge** [comment]
@GuilhemN Thank you, PR sent :)

**Comment by choonge** [comment]
PR was merged, thanks @GuilhemN :)

Could I request a release of `exsyst/swagger`, so it becomes active in my project? The `~0.3` in composer.json should pull in `0.3.1` automatically.

**Comment by GuilhemN** [comment]
Sure, done ;)
