### ISSUE TITLE
Could not resolve reference when $ref relative path files. "basePath" undefined. 

### ISSUE THREAD

**Issue by padlavoine** [nelmio/NelmioApiDocBundle#1085]
I've actually a problem with $ref when displaying the swagger ui:

Resolver error at paths./private/api/v1/users.get.responses.200.schema.$ref
Could not resolve reference: ../../Entity/User.php#/definitions/User

/Controller/PrivateApi/UserController.php

```
/**
 * @Route("/v1/users")
 *
 */
class UserController extends BaseController
{    
     /**
     * List users.
     *
     * @Route("", methods={"GET"})
     * @SWG\Response(
     *     response=200,
     *     description="Returns the list of users",
     *     @SWG\Schema(ref="../../Entity/User.php#/definitions/User")
     * )
     * @SWG\Parameter(
     *     name="order",
     *     in="query",
     *     type="string",
     *     description="The field used to order users"
     * )
     * @SWG\Tag(name="Users")
     */
    public function getAction(Request $request, ParamFetcherInterface $paramFetcher)
    {
     .......
    } 
}
```
/Entity/User.php

```
/**
 *
 * @SWG\Definition(definition="User", type="object")
 *
 */
class User
{
    /**
     * @var string
     *
     * @ORM\Column()
     *
     * @Serializer\Expose
     * @Serializer\Groups({"UPDATE", "CREATE", "SHOW", "LIST"})
     *
     * @SWG\Property()
     *
     */
    private $name;
     
     .....
}

/**
 *  @SWG\Definition(
 *   definition="UserFull",
 *   type="object",
 *   allOf={
 *       @SWG\Schema(ref="#/definitions/User"),
 *       @SWG\Schema(
 *           required={"name"},
 *           @SWG\Property(property="uuid", format="int64", type="integer")
 *       )
 *   }
 * )
 */
```

config.yml:

```
# Nelmio API Doc (swagger)
nelmio_api_doc:
    models:
      use_jms: true
    routes:
        path_patterns: # an array of regexps
            - ^/api
            - ^/public
            - ^/private
    documentation:
        basePath: /
        info:
            title: ''
            description: '',
            version: 1.0
```
Thanks

**Comment by GuilhemN** [comment]
`@SWG\Definition` is not supported by this bundle, that's why we provide `@Model`.

**Comment by padlavoine** [comment]
Ok, so it's not possible to add custom model ? not an entity linked with database.
Sometimes, the controller get data from many entities and make new data model object with new datas.

   ```
  * @SWG\Response(
     *     response=200,
     *     description="Returns the rewards of an user",
     *     @SWG\Schema(
     *         type="array",
     *         @Model(type=UserConcat::class, groups={"LIST"})
     *     )
     * )
```

But I can not expose the model to swagger. The model on the swagger-ui is empty.

**Comment by GuilhemN** [comment]
We could provide a config option to configure parameters using `@Definition` (by looking only in some folders) or you could just define your models in `swagger.documentation`.

> The model on the swagger-ui is empty.

If you're using the JMS serializer check that you correctly configured your model parameters exposition.

**Comment by gijsstegehuis** [comment]
Is it possible to combine definitions using the `@Model` annotation?
see example here: https://github.com/zircote/swagger-php/issues/243#issuecomment-141102541

If not, we really need `@SWG\Definition` support in this bundle.

**Comment by zhanghuanchong** [comment]
My solution:

Define the definition in config.yml:
![image](https://user-images.githubusercontent.com/3062319/31886121-a7a58e16-b7b8-11e7-81d5-0b315ea626cf.png)

Define the schema:
![image](https://user-images.githubusercontent.com/3062319/31886108-96923570-b7b8-11e7-9bab-f83b574f71a8.png)

Output doc:
![image](https://user-images.githubusercontent.com/3062319/31886078-6cec5660-b7b8-11e7-9aac-de1c8ee917f2.png)

Output json:
![image](https://user-images.githubusercontent.com/3062319/31886172-d446fff4-b7b8-11e7-867a-1eb6892cc951.png)

**Comment by gijsstegehuis** [comment]
Thanks @zhanghuanchong.
I came up with the same solution :)

Still, `@SWG\Definition` would be a much neater solution.

**Comment by GuilhemN** [comment]
A partial `@Definition` support will be there soon (https://github.com/nelmio/NelmioApiDocBundle/pull/1151), awaiting PRs to have a more complete support :)

**Comment by devrck** [comment]
@zhanghuanchong (or @gijsstegehuis)  I've tried to use your solution but without any success :cry: .

This is what i have in config.yml:
![image](https://user-images.githubusercontent.com/16414298/34382383-0dec56d2-eb17-11e7-942c-b27ee7120073.png)
And this is what i have in my controller:
![image](https://user-images.githubusercontent.com/16414298/34382395-328fc12c-eb17-11e7-9dfb-755570c45892.png)

 Could you please provide more info?

**Comment by gijsstegehuis** [comment]
@devrck looks like there's a typo in your code:
Replacing `$/definitions` with `#definitions` should make it work.

**Comment by devrck** [comment]
@gijsstegehuis yes it was a typo but that was not the solution. The problem was with the version of zircote/swagger-php and I downgraded it to 2.0.10 for this to work.

**Comment by GuilhemN** [comment]
@devrck https://github.com/nelmio/NelmioApiDocBundle/pull/1232 should fix your issue (and the related bc break in zircote/swagger-php).

**Comment by GuilhemN** [comment]
Closing as #1232 is merged.
