### ISSUE TITLE
How to add constraint into JSON Schema 

### ISSUE THREAD

**Issue by eldad87** [nelmio/NelmioApiDocBundle#1090]
Hi,
Branch: `dev-master`.

Is there a way to display what are the limitations on a given field?
```
/**
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @ORM\Table(name="user")
 *
 * @JMS\ExclusionPolicy("all")
 */
class User implements UserInterface
{
    /**
	 * @JMS\Expose()
	 * @JMS\Groups("register")
	 * @JMS\Type(name="string")
	 *
         * @ORM\Column(type="string", length=25, nullable=false)
	 *
	 * @Assert\Length(min="2", max="25")
     */
    private $firstName;
```

In this example, if I'll use:
```
	 *     @SWG\Parameter(
	 *       	name="user",
	 *       	in="body",
	 *       	description="JSON User object",
	 *       	type="json",
	 *       	required=true,
	 *      	@Model(type=User::class, groups={"register"})
	 *     )
```
I would expect the documentation to notify that there is a `min: 2` and `max: 25` length limit, something like [this](http://json-schema.org/examples.html).
Same thing goes with `@Assert\Range` etc.

Is there a way to do that?
Thanks!

**Comment by GuilhemN** [comment]
The bundle does not support validation metadata, that'd be a great addition though.

**Comment by eldad87** [comment]
> The bundle does not support validation metadata yet, that'd be a great addition though.
Cool.
Is there any "Developer" guide? 
I would like to evaluate the complexity before I commit to do a PR.

**Comment by GuilhemN** [comment]
You mean [this](https://github.com/nelmio/NelmioApiDocBundle/blob/master/CONTRIBUTING.md)?

**Comment by MichaelHindley** [comment]
I think he means more of a outline of the architecture, the moving parts and how to extend or replace functionality.

I'm in the same boat and trying to figure out the best approach. Sadly so far I've figured out that the popular FOSRestBundle that is often used together with Nelmio/SF2 Validator does not generate validator metadata when using body converters, which are typically used together with the Model annotation, so the scope of this task for our use case had sadly grown out of what we are willing to do in a contributory manner :(

**Comment by MichaelHindley** [comment]
We have some basic functionality for this, by having our own model Describer that is based on the JMSSerializer one

![image](https://user-images.githubusercontent.com/1016639/31885297-57db879a-b7f0-11e7-9698-f9694f779a42.png)

**Comment by GuilhemN** [comment]
Fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1202 :)
