### ISSUE TITLE
What is the best practice for using this Bundle along with FOSRestBundle?

### ISSUE THREAD

**Issue by eldad87** [nelmio/NelmioApiDocBundle#1091]
Hi,
Branch: `dev-master`.

I'm trying to embed this new bundle, so far, it ain't smooth as I expected it to be.
Anyway, the options are limitless, but there is no documentation on how to use them.

I'm looking for an advice on how to use this Bundle along with FOSRestBundle (a NEW project, no migrations are needed).
From what I've read so far, in order to build consistence documentation and constraints, I can go with 2 approaches:

1. @model with FormType, FormType is also used for validation
2. @model with Entity, `@Validator` service  (Entity must be annotated with Constraints) - which is the preferred one.

What do you think?

**Comment by Siprah** [comment]
:+1: I have same question. I wouldn't define same thing in two cases.

**Comment by GuilhemN** [comment]
Well this is a matter of taste, both forms and entities are supported by the `@Model` annotation. Note though that constraints aren't supported yet. (PR welcome)

**Comment by martijnvankempen** [comment]
Constraints might be supported soon ;)

[https://github.com/nelmio/NelmioApiDocBundle/pull/1202](url)
