### ISSUE TITLE
JMSModelDescriber is being used for describing all objects, not just those using JMS annotations

### ISSUE THREAD

**Issue by angrygreenfrogs** [nelmio/NelmioApiDocBundle#1095]
My response has a Login object, which has an embedded User object. The Login model works fine, but I can't get the properties of the embedded User model to come through.

Example cut-down controller:
```
namespace AppBundle\Controller\Api;
...
class UserController
{
...
     *     @SWG\Response(
     *         response="200",
     *         description="Success",
     *         @SWG\Schema(
     *              @Model(type="AppBundle\ApiOutputModels\User\Login")
     *         )
     *     ),
```
Login object:
```
namespace AppBundle\ApiOutputModels\User;
use JMS\Serializer\Annotation\Type;
...
/**
 * @Model()
 */
class Login
{
    /**
     * User information object
     *
     * @Type("AppBundle\Document\User")
     * @SWG\Property(
     *     @SWG\Schema(
     *         @Model(type="AppBundle\Document\User")
     *     )
     * )
     */
    protected $user;
....
```
User object:
```
namespace AppBundle\Document;
use Swagger\Annotations as SWG;
...
/**
 * @Model()
 */
class User
{    
    /**
     * Username
     * 
     * @var string
     * @SWG\Property()
     */
    public $username;

    /**
     * E-mail address
     *
     * @var string
     * @SWG\Property()
     */
    public $email;
...
```
The resulting definition json looks like this:
```
"definitions":{  
      "Login":{  
         "properties":{  
            "token":{  
               "type":"string"
            },
            "user":{  
               "$ref":"#\/definitions\/User"
            }
         },
         "type":"object"
      },
     "User":{"type":"object"}}
```

You can see the Login object is showing up with its properties, but no matter what I do, I can't get my User object to pull in its properties.

**Comment by angrygreenfrogs** [comment]
I think I've finally figured out the root problem.

It seems the JMSModelDescriber is being used for getting the properties of both of the model classes (Login/User), even though only the Login class is using JMS annotations.

In JMSModelDescriber.php in the function supports(), there's this line of code:
```
 if ($this->factory->getMetadataForClass($className)) {
```

This is returning true for both of these classes, even though User is only a normal object.

I'm not really sure of the fix, however, and would need further advice. A work-around at least is just to use JMS annotations everywhere, and that actually works fine.

**Comment by GuilhemN** [comment]
Well yes we can't do much about this, you must either use the jms serializer or the property info component (see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#if-you-re-using-the-jms-serializer).
Closing there is no right fix.
