### ISSUE TITLE
SwaggerUiController overrides `basePath` configured in the API specification 

### ISSUE THREAD

**Issue by Devristo** [nelmio/NelmioApiDocBundle#1096]
Currently the `SwaggerUiController` overrides the `basePath` if configured.

```php
$spec = $this->apiDocGenerator->generate()->toArray();
        if ('' !== $request->getBaseUrl()) {
            $spec['basePath'] = $request->getBaseUrl();
        }
```
This breaks our application as we already have  `$spec['basePath']` set. 

Perhaps the value should only be set if it hasn't been set in the `$spec` before?

**Comment by GuilhemN** [comment]
The problem is that this bundle doesn't support a manually-defined basePath, so isn't all your doc wrong by forcing this setting?

**Comment by GuilhemN** [comment]
Closing as the author seems inactive, please reopen if you still encounter this issue.
