### ISSUE TITLE
Swagger UI OAuth2 not working due to missing oauth2-redirect.html

### ISSUE THREAD

**Issue by Devristo** [nelmio/NelmioApiDocBundle#1097]
![image](https://user-images.githubusercontent.com/1564257/31138534-21ece894-a86f-11e7-9211-bd46a7bf5236.png)

In the  Swagger UI its possible to authorize the client using OAuth2. Currently in the NelmioApiDocBundle this is not working due to two issues:

* Parameter `oauth2RedirectUrl` can not be configured (this defaults to `http://localhost:3000/oauth2-redirect.html`).
* The `oauth2-redirect.html` itself is missing. This file is responsible for retrieving the OAuth token and setting the Bearer token in subsequent requests from the Swagger UI.

As a simple test I copied the `https://github.com/swagger-api/swagger-ui/blob/master/dist/oauth2-redirect.html` in my web root and exposed it on `http://localhost:3000/oauth2-redirect.html` and then it seems to be working.

However it would be much easier if NelmioApiDocBundle included this file and set the `oauth2RedirectUrl` to a absolute URL generated by for example a route to this view.

**Comment by aklakl** [comment]
how to fix that？

**Comment by Lopton** [comment]
I'm having this same problem and am not sure what to do, or why "oauth2-redirect.html" is hardcoded to localhost....

**Comment by Lopton** [comment]
I finally figured out the solution to this for me: https://stackoverflow.com/questions/49518868/oauth2-authorization-in-nelmioapidocbundle/49519134#49519134

**Comment by chrisguitarguy** [comment]
> could we make this configurable? that would mean that we need to make this js file a twig template and render it through a controller...

For context, the [linked stackoverflow solution](https://stackoverflow.com/questions/49518868/oauth2-authorization-in-nelmioapidocbundle/49519134#49519134) is to change the options passed to `SwaggerUIBundle` to include `oauth2RedirectUrl`:

```js
const ui = SwaggerUIBundle({
      oauth2RedirectUrl: 'URLhere',
    // ...
});
```

There's already _some_ configurabily in place now vis `userOptions` here:

https://github.com/nelmio/NelmioApiDocBundle/blob/9cd417efb4cac669ba517f66e9dfd484a4d93001/Resources/public/init-swagger-ui.js#L8

Which are passed in via the twig template:

https://github.com/nelmio/NelmioApiDocBundle/blob/9cd417efb4cac669ba517f66e9dfd484a4d93001/Resources/views/SwaggerUi/index.html.twig#L79-L80

https://github.com/nelmio/NelmioApiDocBundle/blob/9cd417efb4cac669ba517f66e9dfd484a4d93001/Render/Html/HtmlOpenApiRenderer.php#L44-L58

I'm 50/50 here, this is probably a good idea to make configurable, but it's also pretty easy to do in twig by overriding the template now:

```
{# in templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig #}
{% extends '@!NelmioApiDoc/SwaggerUi/index.html.twig' %}

{% block swagger_initialization %}
        <script type="text/javascript">
            (function () {
                var swaggerUI = {{ swagger_ui_config|json_encode(65)|raw }};
                swaggerUI.oauth2RedirectUrl = 'changeme';
                window.onload = loadSwaggerUI(swaggerUI);
            })();
        </script>
{% endblock swagger_initialization %}
```

Open to feedback. I honeslty do not use the auth bits of swagger UI.

**Comment by chrisguitarguy** [comment]
Going to close this one in favor of #1330
