### ISSUE TITLE
PropertyInfoExtractor seems to break the doc

### ISSUE THREAD

**Issue by kix** [nelmio/NelmioApiDocBundle#1100]
I have a model that uses `@Groups` annotation from Symfony serializer. However no properties are returned by `PropertyInfoExtractor`: the first extractor it delegates to is `SerializerExtractor` which returns an empty array, which in turn gets returned as the field list. The models are annotated with `@Groups`, and my controller is annotated as follows:
```php
    /**
     * @Swagger\Response(
     *     response=200,
     *     description="Returns all available sports",
     *     @Swagger\Schema(
     *          type="array",
     *          @Model(type=Sport::class, groups={"list"})
     *     )
     * )
     * @Swagger\Tag(name="Sports")
     *
     * @Rest\Route(methods={"GET"}, path="/sports.{_format}")
     */
    public function indexAction()
    {
        $repo = $this->getDoctrine()->getRepository(Sport::class);

        return $this->handleView(View::create($repo->findAll()));
    }
```

As a result, I get empty model definitions:
```
"Goal": {
"type": "object"
},
"Sport": {
"type": "object"
}
```

**Comment by tamcy** [comment]
Please try the followings and see if they solve your problem:

1. Make sure `enable_annotations` is `true` in `config.yml`:
```
framework:
    serializer: { enable_annotations: true }
```

2. Make sure you have installed `phpdocumentor/reflection-docblock`. 
```
composer require phpdocumentor/reflection-docblock
```

**Comment by GuilhemN** [comment]
Closing as you got an answer. Thank you @tamcy :)
