### ISSUE TITLE
How to show a example json output

### ISSUE THREAD

**Issue by alejgarciarodriguez** [nelmio/NelmioApiDocBundle#1109]
Can I use "output" ApiDoc annotation to show a response output sample?  Something like this:
```/**
     * @ApiDoc(
     *     resource=true,
     *     section="myResource",
     *     description="Some Description",
     *     output="{
     *           "hello": "world"
     *    }"
     * )
     */
    public function sampleAction(Request $request){ ... }```

**Comment by cosminroman** [comment]
You can show a response example like this: 

* @Operation(
*     tags={"myResource"},
*     summary="Some Description",
*     @SWG\Response(
*         response="200",
*         description="Returned when successful",
*         @SWG\Schema(
*              type="array",
*              example={
*                   "hello": "world" 
*              }
*         )
*     )
* )
*/

**Comment by GuilhemN** [comment]
Closing as 2.0 is no longer maintained and @cosminroman answered you in case you update to 3.0 :)
