### ISSUE TITLE
[3.0] Parse form with CollectionType

### ISSUE THREAD

**Issue by matrix818181** [nelmio/NelmioApiDocBundle#1110]
Is it normal that FormModelDescriber doesn't work with CollectionModelDescriber ?

I have a collection within a form but I'm not able to transform it in a : 

```
"items": {
	"$ref": "#/definitions/{SubFormType}"
},
"type": "array"
```

Is this a bug or do I have to do something else ?

Update...
From what I understand, it seems like we do nothing with a collection.
```
if ('collection' === $blockPrefix) {
    $subType = $config->getOption('entry_type');
}
```
The `$subType` variable is not used anywhere.

**Comment by kopaygorodsky** [comment]
fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1126
