### ISSUE TITLE
[3.0] Remember api key

### ISSUE THREAD

**Issue by juntereiner** [nelmio/NelmioApiDocBundle#1115]
If you set the api key then refresh the api doc, the api key is gone. That's a bit frustrating,and the version 2.* could remember it.

Is there an option to remember the api key?

**Comment by GuilhemN** [comment]
Is this about 3.0 or 2.0?

**Comment by MrBanjo** [comment]
I'm using the 3.0. I just would like to know if it possible to remember the api key on reload like it was possible with the 2.0.

**Comment by GuilhemN** [comment]
Well that's up to swagger-ui, and it seems they do not allow this currently, though [they are workarounds](https://github.com/swagger-api/swagger-ui/issues/3079).
