### ISSUE TITLE
Host/hosts parameter

### ISSUE THREAD

**Issue by presscot** [nelmio/NelmioApiDocBundle#1121]
I propose to add the host/hosts parameter to config. 

`
    private function match(Route $route): bool
    {
        if(  !in_array( $route->getHost(), $this->hosts ) ){
            return false;
        }
        foreach ($this->pathPatterns as $pathPattern) {
            if (  preg_match('{'.$pathPattern.'}', $route->getPath())) {
                return true;
            }
        }

        return false;
    }
`

**Comment by notFloran** [comment]
I have the same needs, to work around the problem we defined our own FilteredRouteCollectionBuilder with a CompilerPass.

A possible solution would be to implement a system like the zone of FOSRestBundle (http://symfony.com/doc/master/bundles/FOSRestBundle/3-listener-support.html#zone-listener).

Ex: 
```
nelmio_api_doc:
    routes:
        - { path: ^/api, host: myapp.example.com }
```

**Comment by GuilhemN** [comment]
Please submit a PR to add hosts support, or use areas https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html.
