### ISSUE TITLE
Array to string conversion error with default={} in queryparam

### ISSUE THREAD

**Issue by AizeLeOuf** [nelmio/NelmioApiDocBundle#1124]
Hi guys,

I think there is an issue with param default for QueryParam : 

` * @Rest\QueryParam(name="plugins", nullable=true, default={}, description="plugins enabled")`

Return 

An exception has been thrown during the rendering of a template ("Notice: Array to string conversion").

Thanks

PS: version 2.13.2

**Comment by GuilhemN** [comment]
Closing as 2.0 is not maintained anymore. Please submit a PR or upgrade to 3.0.
