### ISSUE TITLE
[3.0] BasePath doubled

### ISSUE THREAD

**Issue by MJBGO** [nelmio/NelmioApiDocBundle#1128]
Hi,

I've been searching for a solution but could not find one ...

I've set the basePath parameter to "/api/v1/" and my routing.yml looks like this : 

![image](https://user-images.githubusercontent.com/8344487/32705844-a00e843a-c818-11e7-8ff2-7bb5ecd6d384.png)

But all my paths still have the "/api/v1" prefix and when I execute them, the path is doubled "/api/v1/api/v1" ...

![image](https://user-images.githubusercontent.com/8344487/32705892-09579346-c819-11e7-817f-194e5d932220.png)

Is it a bug or am I doing something wrong ?

Thanks

**Comment by GuilhemN** [comment]
You did set it manually ? If so this bundle does not take it into account.

**Comment by 7thcubic** [comment]
can you post the annotation on the controller actions?

**Comment by GuilhemN** [comment]
Should be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1172

**Comment by Bcow7** [comment]
Hi,
I have the exact same issue with commit `279d20b`.

Here is my configuration in /nelmio_api_doc.yaml
```
nelmio_api_doc:
    documentation:
        host: my-api.example.org
        basePath: /api/v2/
        schemes: [https]
        info:
            title: API Doc test
            description: This is an awesome app!
            version: 1.0.0
    areas: # to filter documented areas
        default:
            path_patterns:
                - ^/api/v2(?!/doc*) # Accepts routes under /api except /api/doc

```

and Controller
![image](https://user-images.githubusercontent.com/2751121/55243120-de261b00-523e-11e9-83d2-3ea0a1615bad.png)

![image](https://user-images.githubusercontent.com/2751121/55242932-8d162700-523e-11e9-80d7-ff4e46c63177.png)

Am I doing something wrong?

Thank you very much!

**Comment by 7thcubic** [comment]
pretty sure it is settings error, because u are setting the base path to be

my-api.example.org/api/v2

and using a controller that has a base route of 

/api/v2

which means the current swagger generated is correct.

Try setting your base path to be: my-api.example.org

**Comment by GuilhemN** [comment]
@Bcow7 the basePath you configured manually isn't changing how routes are registered, so you get the path doubled.
Following @7thcubic instruction should solve your issue.
