### ISSUE TITLE
Unnecessary backslashes in curl headers

### ISSUE THREAD

**Issue by vladkras** [nelmio/NelmioApiDocBundle#1135]
My request works fine in sandbox, but when I copy-paste "Curl Command Line" request
```
curl -X "POST" -d "{\"key\":\"value\"}" -H "Accept:\ application/json" -H "Content-type:\ application/json" /api/endpoint
```
it fails because of backslashes in headers:
```
* ALPN, server accepted to use http/1.1
> POST / HTTP/1.1
> Host: example.com
> User-Agent: curl/7.47.0
> Accept:\ application/json
> Content-type:\ application/json
> Content-Length: 15
```
If I remove them - everything works as expexted. Not a big deal but annoying.

I'm usign "nelmio/api-doc-bundle":"2.13.2" and update to "~3.0@beta" is undesirable.

**Comment by GuilhemN** [comment]
Well 2.0 is no longer maintained so we can't truly help here. Please submit a PR or upgrade to a higher version.
