### ISSUE TITLE
The service "nelmio_api_doc.formatter.html_formatter" has a dependency on a non-existent service "templating".

### ISSUE THREAD

**Issue by dkorsak** [nelmio/NelmioApiDocBundle#1137]
Version 2.13

**Comment by phptuts** [comment]
I running into this issue as well.

**Comment by phptuts** [comment]
For me it's using symfony 4 it works with symfony 3.4.

**Comment by MatthewBooth** [comment]
Not working for me on symfony 3.4

**Comment by dbu** [comment]
symfony 4 drops the templating abstraction and uses twig directly. please do a pull request to make this bundle depend on twig directly.

**Comment by GuilhemN** [comment]
Closing as 2.0 is not maintained anymore. Please submit a PR or upgrade to 3.0.
