### ISSUE TITLE
Mention Twig and Asset requirements for use with Symfony Flex

### ISSUE THREAD

**Issue by slootjes** [nelmio/NelmioApiDocBundle#1141]
To make this bundle work with Symfony Flex it's required to manually install "twig-bundle" and "asset". It would be helpful if this was mentioned in the documentation. When installing this without those you will get an exception about the router which can not handle the "nelmio_api_doc.controller.swagger_ui" controller as this is removed since the TwigBundle isn't loaded.

**Comment by GuilhemN** [comment]
See https://github.com/symfony/recipes-contrib/pull/207/files#r157362744
