### ISSUE TITLE
Need Symfony Recipe for 3.0

### ISSUE THREAD

**Issue by jhkchan** [nelmio/NelmioApiDocBundle#1143]
I have reported at https://github.com/symfony/recipes-contrib/issues/197 and they suggested to report here instead.

**Comment by unglud** [comment]
https://github.com/symfony/recipes-contrib/pull/207

**Comment by GuilhemN** [comment]
See https://github.com/symfony/recipes-contrib/pull/226

**Comment by GuilhemN** [comment]
PR merged.
