### ISSUE TITLE
error when symfony form component is not activated

### ISSUE THREAD

**Issue by dbu** [nelmio/NelmioApiDocBundle#1149]
if the form component is not activated in the symfony framework bundle, but the code is available, we get an error `The service "nelmio_api_doc.generator" has a dependency on a non-existent service "form.factory".`

the correct thing would be to do a compiler pass that checks the container for form.factory and only adds the form model describer if forms is enabled.

**Comment by dbu** [comment]
i can do a pull request for this if you agree that this is the correct approach.

**Comment by GuilhemN** [comment]
That's indeed a problem... See https://github.com/nelmio/NelmioApiDocBundle/pull/1154 :)

**Comment by dbu** [comment]
will be fixed by #1154
