### ISSUE TITLE
SWG\Schema describes the model as an array...always. How to describe as an object?

### ISSUE THREAD

**Issue by wbrframe** [nelmio/NelmioApiDocBundle#1157]
Is it possible to describe a (`@API\Model(type=..class..`) as an object? Because now I always get an array.

--------------

Case:

1. Controller action for the upload file.
```
    use Swagger\Annotations as SWG;
    use Nelmio\ApiDocBundle\Annotation as API;

    /**
     * @Rest\Post("/storage")
     * @Rest\View
     *
     * @SWG\Tag(name="storage")
     * @SWG\Response(
     *   response="200",
     *   description="Returns file information",
     *   @SWG\Schema(
     *     @API\Model(type=File::class)
     *   )
     * )
     *
     * @param Request $request
     * @return File
     */
    public function uploadAction(Request $request)
    {
        // upload file
    }
```

2. File entity
```
/**
 * File
 *
 * @Vich\Uploadable()
 * @ORM\Table(name="file")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\FileRepository")
 */
class File
{
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=100)
     */
    private $name;

    ....etc...
}
```

--------------

After render docs I see

![img1](https://user-images.githubusercontent.com/4079553/34267017-fc5c295c-e683-11e7-8bf9-a39d5e37142d.png)

But I expected to see:

![img2](https://user-images.githubusercontent.com/4079553/34267115-5d710136-e684-11e7-854a-e00fb7a9a852.png)

--------------

Checked whether the swagger supports this format:

![img3](https://user-images.githubusercontent.com/4079553/34267463-97230202-e685-11e7-99f5-3aea925ec07a.png)

--------------

I also tried to debug this situation and came across a line of code:

![img4](https://user-images.githubusercontent.com/4079553/34267704-8252df68-e686-11e7-91cc-7990c95a183e.png)

--------------

Tell me please, this is a bug or requirement zircote/swagger-php ?

I use:
"nelmio/api-doc-bundle": "3.0.0"
"zircote/swagger-php": "^2.0.9"

**Comment by wbrframe** [comment]
The same question and without an answer.
[https://stackoverflow.com/questions/35208033/nelmio-api-doc-documentation-says-my-json-objects-are-arrays-how-to-fix](url)

Perhaps I do not understand something fundamentally and there is no need to use arrays.

**Comment by 7thcubic** [comment]
please change your annotation to

```
     *     @API\Model(type=File::class)
```

basically remove the schema part. the model annotation automatically handles the declaration of schema thus when you declare a schema > model the bundle is treating it as an array of object

**Comment by wbrframe** [comment]
Thanks, it worked!

**Comment by dbu** [comment]
great!
