### ISSUE TITLE
Symfony 4 don't load services.xml

### ISSUE THREAD

**Issue by za4me** [nelmio/NelmioApiDocBundle#1158]
Hi i'm install this bundle and in `example.com/api/` url get `LogicException` with message `Controller not found: service "nelmio_api_doc.controller.swagger_ui" does not exist.`

I think symfony cannot load services.xml inside bundle, but why? Or i make something wrong?

**Comment by scaytrase** [comment]
services are private by default now, so this controller should be explicitly marked as `public`

**Comment by GuilhemN** [comment]
@scaytrase not sure what you mean, it is already explicitely made public.

**Comment by scaytrase** [comment]
@GuilhemN hm, indeed

@za4me did you enabled bundle in kernel?

**Comment by dbu** [comment]
duplicate of #1143 - there is no recipe for flex yet.

**Comment by Gemorroj** [comment]
any workaround?

**Comment by scaytrase** [comment]
@Gemorroj not to use flex for this bundle?

**Comment by za4me** [comment]
Hi guys. Sorry i'm later, but i remove all packages and install this and it working fine. I forgot the exact solution, but like last time, I did not add the code in `routing.yml`.

**Comment by dbu** [comment]
will be fixed with https://github.com/symfony/recipes-contrib/pull/226

**Comment by za4me** [comment]
@dbu Thank a lot, now i need fix my another bundle for using new nelmio :D

**Comment by kochen** [comment]
The `swagger_ui` controller requires both `twig` & `symfony/asset` which are not mentioned in the doc and are not added by the flex recipe.

If those are missing, the service `nelmio_api_doc.controller.swagger_ui` will not be autowired and therefor won't be found (regardless of it being public).

**Comment by GuilhemN** [comment]
> are not added by the flex recipe

This is not possible afaik. We mention it in the routing of the recipe though.

> which are not mentioned in the doc

Please submit a PR if you think it's lacking.
