### ISSUE TITLE
Attempted to load class "DocBlockFactory" from namespace "phpDocumentor\Reflection"

### ISSUE THREAD

**Issue by anboo** [nelmio/NelmioApiDocBundle#1160]
https://github.com/nelmio/NelmioApiDocBundle/commit/fe3629cdeb11fc81b7500ba8ea8588c0f03c26e7

You forgot add "phpdocumentor/reflection-docblock" to you requirements in composer.json!

**Comment by dbu** [comment]
dang. i think the other places we use this, the docblock handling is optional depending on whether phpdocumentor is available. i will do a fix to only activate this if its available.
