### ISSUE TITLE
Show needed roles

### ISSUE THREAD

**Issue by jhkchan** [nelmio/NelmioApiDocBundle#1165]
In 2.x, there is a lock icon and it would show "Needs ROLE_API" for example to know what roles are needed to call the APIs. This feature seems missing in 3.0, or did I miss anything? Thanks!

**Comment by GuilhemN** [comment]
It's indeed missing, it would be a great adding though. PRs are welcome :)

**Comment by kopaygorodsky** [comment]
I'll be able to it next weekend.

**Comment by phansys** [comment]
@konradpodgorski, do you plan to work on this feature?

**Comment by LordWeedlle** [comment]
Up !

I'm actually moving from symfony `2.8` to `3.4`.
I thought it was a good time to rework my ApiDoc annotation as I went from `2.x` to `3.3.0`.

But after running the given migration command I couldn't figure out how to specify the roles needed by the user to be able to call the API as the old annotation `authenticationRoles={"MYROLE"}` did.

Now I know why :P

I would really appreciate this option to come back as it is a downgrade for the project :/

But still, gj for the work you already did, the new `3.x` UI seems quiet promising!

**Comment by chrisguitarguy** [comment]
I'm going to close this for now. To re-open, please provide some more context about how this worked in 2.X (what did the annotations look like? what was the generated swagger document?)

The little lock icon does still appear, but OpenAPI seems more heavy on the authentication side of things. You can narrow security things per operation, however. And OAuth2 authentication does provide some support for narrowing scopes: https://swagger.io/docs/specification/authentication/oauth2/

```php
/**
 * @OA\Get(security={"oauth2": ["scopeHere"]})
 */
```

Where the `oauth2` above is the name of in `securityDefinitions`: https://swagger.io/docs/specification/authentication/
