### ISSUE TITLE
Model annotation groups don't work

### ISSUE THREAD

**Issue by kubaceg** [nelmio/NelmioApiDocBundle#1167]
My custom serialize group don't work in nelmio api bundle v3.0

My Swagger definition:
```
     * @SWG\Get(
     *     tags={"User"},
     *     @SWG\Response(
     *      response="200",
     *      description="Get current user info (by token)",
     *      @SWG\Schema(@Model(type=User::class, groups={"private"}))
     *     )
     * )
```

My Entity:
```
class User implements UserInterface, \Serializable
{
    /**
     * @var int
     * @Serializer\Groups("public")
     */
    private $id;

    /**
     * @var string
     * @Serializer\Groups("private")
     */
    private $username;

    /**
     * @var string
     */
    private $password;

    /**
     * @var bool
     * @Serializer\Groups("private")
     */
    private $isActive;

    /**
     * @var int
     * @Serializer\Groups("public")
     * @Serializer\Accessor(getter="getUserType")
     * @Serializer\Type("string")
     */
    private $userType;
```

my fos_rest.yaml configuration:
```
    serializer:
        groups: ['public']
```

Endpoint response
```
{
	"id": 1,
	"user_type": "private"
}
```

An You see endpoint response only with public group fields. When I remove serializer settings from fos_rest.yaml each entity property is serialized into response.

**Comment by davidpv** [comment]
@kubaceg why did you close the issue?. I'm having the same problem.

**Comment by davidpv** [comment]
Did you find any sollution?,

**Comment by kubaceg** [comment]
Directly no. I've created value object classes with responses and there I have Public and Private User response object, than I return those objects from controller action (depending on my needs public or private). So generally I use only one serialize group.
This approach give me more flexible and easier to maintain control on response formats/data, because I can merge data from different entities or add some custom logic to response easily,.
It's little bit more code but such VO classes are eaasy to read and modify so for me it's worth it.

I hope it helps :)

**Comment by davidpv** [comment]
Ok thanks for the response and explanation. I'll give it a try!

**Comment by vihuarar** [comment]
I'm having the same problem...

When you publish an error in internet, should be nice if you discover the solution that you publish some examples to help other people.

I think that this is an error of the Nelmio Api Doc Bundle because I'm having the same problem

**Comment by marcin-jozwikowski** [comment]
OK, I got it working!
The answer is as old as it gets: clear the cache. At least that's what it was in my case.
There's also a requirement in [Serializer manual](https://symfony.com/doc/current/serializer.html#using-serialization-groups-annotations) to install sensio/framework-extra-bundle but it work for me without it.
