### ISSUE TITLE
Assets returning 404 

### ISSUE THREAD

**Issue by iaejean** [nelmio/NelmioApiDocBundle#1173]
I'm using SF4  with Flex, I've updated this bundle (^3.0), but when run api/doc endpoint in the browser I getting:

![screen shot 2018-01-07 at 11 37 39 pm](https://user-images.githubusercontent.com/4458783/34659927-d05bfe3a-f403-11e7-88c2-b4ccb7807ee6.png)

**Comment by JonathanLafey** [comment]
I don't know if this is an acceptable solution, but I solved this issue by copying the assets with the following command
`php bin/console assets:install --symlink`

**Comment by dbu** [comment]
normally, this should happen in a composer task to install the assets. is our recipe missing something to tell flex that it should set up that hook?

**Comment by iaejean** [comment]
I get this when reinstall the bundle and still getting 404 with the bundle resources

![screen shot 2018-01-08 at 6 38 25 pm](https://user-images.githubusercontent.com/4458783/34699531-7e24f432-f4a3-11e7-9b69-5301ebe6f344.png)

**Comment by dbu** [comment]
but when you run the assets:install command on its own, it works?

**Comment by iaejean** [comment]
is not working

**Comment by dbu** [comment]
@JonathanLafey are you using symfony 4 and flex? did you migrate from a symfony 3 application or start with SF 4 from scratch? @iaejean did you start from scratch? i'd like to find the difference if it works for one of you but not the other. either the assets do not work with just the SF4 skeleton, or @iaejean somehow broke his setup - so either we need to fix something or not ;-)

**Comment by JonathanLafey** [comment]
@dbu I'm still using symfony 3.3 without flex. Migration will happen sometime next month, when I will report back on whether the manual installation will be still needed.
I'm also working using [MicroKernelTrait](http://symfony.com/doc/3.4/configuration/micro_kernel_trait.html), in case this somehow causes the said issue.

**Comment by iaejean** [comment]
Actually I start my project recently  with Flex and SF4

**Comment by GuilhemN** [comment]
> i'd like to find the difference if it works for one of you but not the other. either the assets do not work with just the SF4 skeleton, or @iaejean somehow broke his setup - so either we need to fix something or not ;-)

I just tried installing nelmioapidocbundle on a new project using Flex and it worked fine. Did you run `composer require asset`?

**Comment by iaejean** [comment]
I've reinstalled nelmioapidocbundle and symfony/asset too and still not working, I tried to comment all my services, listeners etc looking for a dependency conflict behaviour but without any good news!

**Comment by iaejean** [comment]
I'm running my web server with: 

```
php -S localhost:8000 public/index.php
```

Do I have to check this with an nginx or apache configuration?

**Comment by dbu** [comment]
is this really specific to this bundle, or a general problem with flex? i don't think the api doc bundle does anything unusual with regards to assets... what is the doc root when you start the php server like this? ./public or ./ ? the old symfony doc used the -t parameter to set the docroot. current doc [says to use the server:run command](https://symfony.com/doc/current/quick_tour/the_big_picture.html)

**Comment by iaejean** [comment]
Thanks a lot, this work with nginx as I said before and with web server bundle!
