### ISSUE TITLE
V3 documentation ?

### ISSUE THREAD

**Issue by TheKassaK** [nelmio/NelmioApiDocBundle#1175]
Hello,

Where is the documentation for the V3 ?

https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html is for V2...

Thanks !

**Comment by GuilhemN** [comment]
They're [here](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.rst) until symfony.com is synced with the repo. I guess we should change the URL in the readme until then...

**Comment by dbu** [comment]
who is in charge of that syncing? this should happen automatically every day or at least week imho - otherwise we risk having very outdated documentation...

**Comment by GuilhemN** [comment]
This will be fixed soon, this is a configuration problem here, the master branch was no longer synced as we did put the docs in the README.

**Comment by GuilhemN** [comment]
Fixed :)
