### ISSUE TITLE
Unrecognized option "areas"

### ISSUE THREAD

**Issue by Fordiag** [nelmio/NelmioApiDocBundle#1179]
Hello,
I get this error when following the doc in the README 
-> Unrecognized option "areas" under "nelmio_api_doc"?

Is there a problem with the stable 3.0 version?

**Comment by Fordiag** [comment]
Ok, found ... I had to use "routes" instead of "areas", can be closed.

**Comment by dbu** [comment]
this is a new feature for 3.1 that is not released yet. @GuilhemN symfony itself uses the versionadded thingy. that won't be rendered on github .rst though. but we should probably add such blocks to avoid confusion like this one.
