### ISSUE TITLE
Support for input Form/Type with DataTransformer

### ISSUE THREAD

**Issue by kornel-kedzierski** [nelmio/NelmioApiDocBundle#118]
Simple FormType works great, but when I add DataTransformers, docs for input becomes empty.

**Comment by nazar256** [comment]
Hi guys, I've faced the same problem. But looking at how ApiDoc bundle works for few minutes I've found a solution for my case! Here it is:
1. First, define your form as service, it is [pretty easy](http://symfony.com/doc/current/book/forms.html#defining-your-forms-as-services), suppose it is "form_alias_you_defined"
2. Inject needed services to form (ex. EntityManager)
3. Use your form name in ApiDoc like 
```php
/**
* ...
* input = form_alias_you_defined
*/
```

Profit!
Also don't forget to read official documentation with usefull tips, like passing method (GET, POST, etc).

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
