### ISSUE TITLE
How to set multiple views in v3?

### ISSUE THREAD

**Issue by qweluke** [nelmio/NelmioApiDocBundle#1181]
Hi

In V2 i was able to create some endpoint and set them some views like `/premium` , `/basic` etc...
Is it possible in V3? If so, how to do that?
  
Or meybe I can hide endpoints somehow...?

**Comment by GuilhemN** [comment]
Take a look at areas https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html, it will be available in 3.1.
