### ISSUE TITLE
v3.0 Form Describer/Annotations

### ISSUE THREAD

**Issue by AlexandreKilian** [nelmio/NelmioApiDocBundle#1183]
I couldn't find the documentation for that, so O think there might be missing documentation for that.

In the previous version, there was documentation for the annotation to describe the form type of a post endpoint, in 3.0 there seems to be only documentation about "Parameter" to describe a single field rather than using the Symfony FormType... 

There is a FormModelDescriber but I could not find that described anywhere in the docs and it isn't an annotation either.

**Comment by GuilhemN** [comment]
A FormType is a model, see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#use-models. It's indeed not very clear, PR welcome to make it clearer :)

**Comment by AlexandreKilian** [comment]
Thank's for the reply... but it seems, @Model is not allowed as a Root annotation

```

/**
     * @Post("/search")
     * @SWG\Response(
     *     response=200,
     *     description="Returns a list of articles",
     *     @SWG\Schema(
     *         type="array",
     *         @Model(type=Article::class, groups={"search"})
     *     )
     * )
     * @Model(type=SearchType::class)
     */

```

Can't put it in the Response Annotation since it would be added in the wrong place and I can't find the right annotation to define post params

**Comment by GuilhemN** [comment]
You should use `@SWG\Parameter(in="body", @Model(...))`

**Comment by AlexandreKilian** [comment]
is there a way to put it as in="formData"? in="body" works, but I was trying to keep all forms as `application/x-www-form-urlencoded` since there is not really a clean way of submitting forms via JSON... if not, I might have to just send my forms in the body

**Comment by GuilhemN** [comment]
No that's not possible, but I guess you can specify what your method consumes to make swagger-ui understand to send your request body as a form.

**Comment by dbu** [comment]
if that works, please do a pull request to the documentation (in Resources/doc/) to add an example for that, @AlexandreKilian

**Comment by GuilhemN** [comment]
Can this be closed?
