### ISSUE TITLE
Modeling Form Collections should convert entry_type

### ISSUE THREAD

**Issue by aequasi** [nelmio/NelmioApiDocBundle#1184]
https://symfony.com/doc/current/reference/forms/types/collection.html#entry-type

When the spec gets generated, it ends up looking like:

    "categories": "[{Symfony\\Component\\Form\\Extension\\Core\\Type\\TextType}]",

when it should be:

    "categories": "[string]",

Even doing `['entry_type' => "string"]` makes the spec look like:

    "categories": "[{string}]",

Also, is it possible to set examples in a form type?

**Comment by GuilhemN** [comment]
The default example we set for form collections most likely is wrong indeed (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/FormModelDescriber.php#L122), please submit a PR if you can think of an improvement.

> Also, is it possible to set examples in a form type?

Not for now but it could be, we just need to port https://github.com/nelmio/NelmioApiDocBundle/blob/2.x/Form/Extension/DescriptionFormTypeExtension.php.
