### ISSUE TITLE
Pull descriptions from Entity instead of Form

### ISSUE THREAD

**Issue by woofiewilly** [nelmio/NelmioApiDocBundle#1189]
When specifying an expected schema for a submission endpoint, we can use a FormType in the ApiDoc annotation like so:
```
    /**
     * @ApiDoc(
     *     section="System",
     *     description="Create a new system.",
     *     routes={"new_system"},
     *     method="POST",
     *     input={"class"="AppBundle\Form\SystemType"},    <-------
     *     output={"class"="AppBundle\Entity\System"}
     * )
     */
```

And inside the FormType we can specify the additional `description` key in the options array for each input, which will be used in the generated documentation.

However, not only does this seem out of place to me, but it means that you will repeat a lot of descriptions if you also put a short description on each field in the Entity object.

Is there any way to pull these descriptions from the Entity annotations instead? Not only do I think it makes more sense structurally, but it would prevent unnecessary repetition if you want all those descriptions in the documentation as well as on the Entity fields. If for a specific form the description on an input should be slightly different for some reason, you should be able to override it with the `description` key in the options array like the current setup.

**Comment by GuilhemN** [comment]
Well 2.0 is no longer maintained so this likely won't be solved. I guess you can extend the FormTypeExtension directly in your app to make it aware of your entities description.

**Comment by woofiewilly** [comment]
I haven't yet learned the differences in 3.0. Is this situation different with the new annotations?

**Comment by woofiewilly** [comment]
All right, thanks! I probably won't be messing with 3.0 for a while since I've got other things to worry about.
