### ISSUE TITLE
Relative symbolic link error upon installation

### ISSUE THREAD

**Issue by gibsonneke** [nelmio/NelmioApiDocBundle#1194]
While installing the latest version (2.13), I do get an error through composer while trying to install assets as relative symbolic links of the NelmioApicDocBundle.

Version of Composer is 1.6.2

Anyone who has an idea how to fix this?

**Comment by GuilhemN** [comment]
What's the error you get exactly?

**Comment by gibsonneke** [comment]
As copied after running composer install:

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- -------------------- ------------------
      Bundle               Method / Error
 --- -------------------- ------------------
  ✔   NelmioApiDocBundle   relative symlink
 --- -------------------- ------------------

However, the installation completes and everything including the documentation runs... So I guess that it's not really a significant problem.
