### ISSUE TITLE
Link for documentation 2.x is broken

### ISSUE THREAD

**Issue by pmoubed** [nelmio/NelmioApiDocBundle#1195]
Documentation link for 2.x is broken

https://symfony.com/doc/2.8/bundles/NelmioApiDocBundle/index.html

**Comment by Sydney-o9** [comment]
In the meantime - https://github.com/nelmio/NelmioApiDocBundle/blob/2.x/Resources/doc/index.rst

**Comment by dbu** [comment]
please report this in the https://github.com/symfony/symfony-docs/ repository, there is nothing we can do on this side.
