### ISSUE TITLE
Assets returning 404 

### ISSUE THREAD

**Issue by abdallahmaali** [nelmio/NelmioApiDocBundle#1199]
i installed  the  bundle and every things working fine but the css files and js not loaded 
i reinstall it and try this command 
` php bin/console assets:install --symlink
` 
Relative symbolic link  in bundle directory doesn't contain the nelmio directory as the following screen shoot , 

<img width="1440" alt="screen shot 2018-01-22 at 4 39 34 pm" src="https://user-images.githubusercontent.com/5798651/35226282-7fb08e4c-ff93-11e7-8b0f-a5e592dfba9c.png">
 -----------------------------------------------------------------------------------------
<img width="1440" alt="screen shot 2018-01-22 at 4 45 05 pm" src="https://user-images.githubusercontent.com/5798651/35226331-a1a4f178-ff93-11e7-81bf-efa261e69389.png">

**Comment by GuilhemN** [comment]
Does it work better with `server:run`? (See @dbu's comment https://github.com/nelmio/NelmioApiDocBundle/issues/1173#issuecomment-358574530).

**Comment by abdallahmaali** [comment]
same problem

**Comment by abdallahmaali** [comment]
yes i found the  assets  installed under public/uploads ,,,i copy the files under /bundles and it's working fine but  why   the assets path under  `bundles`
 `http://localhost/daman/bundles/nelmioapidoc/swagger-ui/swagger-ui-bundle.js`
and it's should be   under `public/bundles `  ,  i don't find any configuration related for **symlink path**

**Comment by simonbertonsugasti** [comment]
I have the same problem. the assets:install --symlink shows that I don't have access to that folder, so might be a permission issue and not nelmio.

**Comment by dbu** [comment]
this is a general symfony setup problem and not specific to this bundle. it only uses the general way how web assets work for symfony bundles.

if you are on windows or some other strange file system, symlink might not work - did you try without the `--symlink`? if that does not help, i'd recommend to check stackoverflow for symfony assets:install problems and if you don't find the solution, post a question there.

**Comment by simonbertonsugasti** [comment]
In my case I solved without the --symlink. I believe this is an apache misconfiguration on my part. Thanks !!!
