### ISSUE TITLE
[Question] How to send JSON object based on params via sandbox

### ISSUE THREAD

**Issue by kmaci** [nelmio/NelmioApiDocBundle#1211]
Hi,

I have following annotations in my post action. 

![vyber_339](https://user-images.githubusercontent.com/3668203/35439120-a3f6f454-0299-11e8-96ac-d2b8ab6f6cb9.png)

Documentation is created correctly, but when I try to send data via sandbox, only last parameter is send, like:

`curl -X POST "http://localhost:8000/api/subscribed-users" -H "accept: application/json" -H "content-type: application/json" -d "\"string\""`

How can I send request in format like below via sandbox?

`
curl -X POST \
  http://localhost:8000/api/subscribed-users \
  -H 'content-type: application/json' \
  -d '{
	"name": "test",
	"surname": "test",
	"email": "test",
	"source": "test",
	"url": "test"
}'
`

**Comment by antonisin** [comment]
```
...
* @SWG\Patch(
*      @SWG\Parameter(
*          in="body",
*          required=true,
*          name="request",
*          description="JSON Request body",
*          @SWG\Schema(
*              type="object",
*              @SWG\Property(property="..."),
*              @SWG\Property(property="..."),
*              @SWG\Property(property="..."),
*              @SWG\Property(property="..."),
*              @SWG\Property(property="..."),
*              @SWG\Property(property="..."),
*              @SWG\Property(property="..."),
*          )
*      ),
* )
...
```
