### ISSUE TITLE
input documents with symfony validation Constraints

### ISSUE THREAD

**Issue by alcoig** [nelmio/NelmioApiDocBundle#1214]
Hi, How could I define a document with validation constraints for a controller? I use to do it with the input key of the @ApiDoc tag. thanks in advance

**Comment by GuilhemN** [comment]
You can use model : https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#use-models. Validation constraints are supported since version 3.1.

**Comment by alcoig** [comment]
Hi! thanks for your fast response, I had seen this post before but the example is to define a  response, I'm looking for a way to specify the input param for a request with a model.

**Comment by GuilhemN** [comment]
Just use `@SWG\Parameter(name="body", on="body", @Model(...)` then

**Comment by alcoig** [comment]
Very thanks, I'm going to try it! it may be a good idea to document it on official repos

**Comment by GuilhemN** [comment]
Indeed, the documentation needs to be improved but we don't have much time to take care of it unfortunately... Please submit a PR if you can :)

**Comment by alcoig** [comment]
oks, thanks

**Comment by GuilhemN** [comment]
Closing as your issue is fixed :)
