### ISSUE TITLE
Optional parameters gets sent using empty values

### ISSUE THREAD

**Issue by sweoggy** [nelmio/NelmioApiDocBundle#1215]
Using version 3.1.0 and Symfony 3.4.3 optional query parameters gets send using empty values. In 2.X optional query parameters would not be sent at all. This causes FosRest to set the parameters to empty strings instead of `null`, which in my causes a, possibly unintended, BC-break from 2.X.

My query param annotations:
```
     * @QueryParam(name="product", requirements=".+")
     * @QueryParam(name="version", requirements=".*", nullable=true)
```

My OpenAPI annotations:
```
     * @SWG\Parameter(
     *         name="product",
     *         in="query",
     *         description="Product/software name, required",
     *         required=true,
     *         type="string"
     *     ),
     * @SWG\Parameter(
     *         name="version",
     *         in="query",
     *         description="The version of the product",
     *         required=true,
     *         type="string"
     *     ),
```

**Comment by GuilhemN** [comment]
Just remove the required field if you don't want them to be sent if empty.
