### ISSUE TITLE
documentation + full config nelmio 3.1 / swagger

### ISSUE THREAD

**Issue by imajim** [nelmio/NelmioApiDocBundle#1216]
Hello,

is anybody have a complete configuration for Symfony nelmio/swagger 3.1 ?

```
nelmio_api_doc:
    sandbox:
        enabled:  false
    documentation:

        info:
            title: 'Documentation API'
            description: This is an awesome app!
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)

```
I would like disable sandbox but i've got this error : 
```
 InvalidConfigurationException

Unrecognized option "sandbox" under "nelmio_api_doc"
```

**Comment by dbu** [comment]
you can see the full configuration with `bin/console config:dump-reference NelmioApiDocBundle`. does that help?
if the doc about how to enable the sandbox is currently incorrect, it would be great if you can do a pull request to fix it.

**Comment by GuilhemN** [comment]
Why would you need to disable the Sandbox ? Not enabling the route has the same effect.

**Comment by imajim** [comment]
in fact i write a new project symfony 3.4 with the new nelmio 3.1 with swagger (i follow this post : https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html) but Swagger is not working.

I post my configuration as soon as possible, I'm doing more testing

thank for yours responses.

**Comment by GuilhemN** [comment]
Maybe you need to install assets and twig ?

**Comment by imajim** [comment]
yop !
@GuilhemN  nop assets it's working ans my API run fine.
After few test to show the doc, I had forgotten a "*" in the comment !!! tsssss it's working  fine now with "/**" ^^

**Comment by sergiodebcn** [comment]
You forgot because documentation at
https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html

only shows one *, please fix documentation, thanks

**Comment by GuilhemN** [comment]
Indeed, good catch @sergiodebcn :) It's fixed.

**Comment by samarshahzad** [comment]
how to remove the list of models from the documentation page?

**Comment by mtaylor678** [comment]
It's possible to do it via the dump option
`php bin/console nelmio:apidoc:dump --format=html --html-config '{"assets_mode":"offline","server_url":"https://example.com","swagger_ui_config":{"supportedSubmitMethods":[]}}' > api.html`

is it also possible to include all the [swagger options](
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration) in the config?

i.e 

nelmio_api_doc:
    swaggerUI:
         supportedSubmitMethods: []
