### ISSUE TITLE
[Help] Hide endpoints that are guarded by authentication

### ISSUE THREAD

**Issue by c00p3r** [nelmio/NelmioApiDocBundle#1217]
In my API some routes can be accessed anonymously but most of them require authentication to use.
But in swagger UI all of them are visible all the time.
And what I want is that if I haven't authenticated yet (copy-pasted auth token) all guarded routes should not be visible.
Can someone give me some clues if that is possible and how to achieve that?

**Comment by GuilhemN** [comment]
Areas may be the solution https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html. But if you're looking for a frontend solution, the best would be to ask your question on swagger-ui repository or on Reddit.

**Comment by c00p3r** [comment]
@GuilhemN thnx, but that won't help.
Probably I was not clear enough
With areas, I can just hide/show whole routes area (not depending on whether they need authentication or not).
But what I ask is to hide routes that require authenticated user to use till I insert api token here:
![image](https://user-images.githubusercontent.com/5259532/35804065-d536370e-0a7e-11e8-9a58-e8913c221cd6.png)
And only after that they should be revealed.
I saw this implementation on other similar swagger-based plugins
Also, imho, the "lock" icon should indicate whether route requires authentication
![image](https://user-images.githubusercontent.com/5259532/35805596-2a21e71c-0a85-11e8-8830-282955f82293.png)
Unlocked for routes accessible anonymously, Locked for routes guarded by authentication

**Comment by GuilhemN** [comment]
> But what I ask is to hide routes that require authenticated user to use till I insert api token here:

I guess this requires adding a custom script on top of swagger-ui, since it's a very specific will, I think you should just extend this bundle's templates and add it.

> Also, imho, the "lock" icon should indicate whether route requires authentication

Well this is up to [``swagger-ui``](https://github.com/swagger-api/swagger-ui) which we depend on.

**Comment by c00p3r** [comment]
@GuilhemN Ok I see
But doesn't it sounds logical about the 'lock' icon? 
We can call it a 'feature request'

**Comment by GuilhemN** [comment]
Sure but you should ask it on swagger-ui repository :) We try to avoid as much as possible customizing swagger-ui since it's already nice by default imo and would require a lot of maintenance.

**Comment by Lycsona** [comment]
You could delete the locker icon for public endpoints by setting `"security"={}`. For protested endpoints, a global setting for security should be used, it is set in nelmio_api_doc.yaml, like:
```
        security:
            - JWT: []
```
As an output for public endpoints, there is no locker with Available authorizations window, for protested endpoints there are still lockers as before.
