### ISSUE TITLE
FosRestDescriber duplicates body definitions from FosRest RequestParam annotations

### ISSUE THREAD

**Issue by jlekowski** [nelmio/NelmioApiDocBundle#1219]
`FosRestDescriber` filters annotations, and for all `RequestParam` sets `"in": "formData"` (while all my request params would be `body`). This doesn't work well when I want to define body parameters by my own annotations:

```
    /**
     * @Operation(
     *     tags={"Group"},
     *     summary="Create group",
     *     @SWG\Parameter(
     *         name="body",
     *         in="body",
     *         required=true,
     *         @SWG\Schema(
     *             @SWG\Property(
     *                 property="name",
     *                 type="string"
     *             ),
     *             @SWG\Property(
     *                 property="accountId",
     *                 type="integer"
     *             )
     *         )
     *     ),
     *     @SWG\Response(
     *         response="201",
     *         description="Group created"
     *     )
     * )
     * @Rest\RequestParam(name="name", requirements=".*\S.*", allowBlank=false)
     * @Rest\RequestParam(name="accountId", requirements="\d+", allowBlank=false)
     *
     * @param ParamFetcherInterface $paramFetcher
     * @return Response
     */
```

And I get both in swagger and Api-Platform 3 parameters: body, name, and accountId.
```
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "properties": {
                "name": {
                  "type": "string"
                },
                "accountId": {
                  "type": "integer"
                }
              }
            }
          },
          {
            "name": "name",
            "in": "formData",
            "allowEmptyValue": false,
            "required": true,
            "type": "string",
            "format": ".*\\S.*"
          },
          {
            "name": "accountId",
            "in": "formData",
            "allowEmptyValue": false,
            "required": true,
            "type": "string",
            "format": "\\d+"
          }
        ],
```
I find `FosRestDescriber` very useful for creating default definitions - even as `formData` they do the job. But I would expect my parameter definition to override `RequestParam` definitions.

Also, it would be helpful to define that `RequestParam` are sent in `body`, not `formData`.

Thanks

**Comment by MarcelMC** [comment]
I agree with @jlekowski 
Have same problem with FOSRest RequestParam, I have to redefine body definitions at @SWG, to use JSON request. It is very annoying.

**Comment by jlekowski** [comment]
@MarcelMC, my workaround for this is to add my own normalizers which remove `formData` if `body` is present, and move `formData` into `body` https://gist.github.com/jlekowski/ff8c06391c2f409a1faf19c3008780b3

**Comment by GuilhemN** [comment]
Please have a look at #1328

**Comment by Lory1990** [comment]
I have the same issue, how did you solve?

**Comment by GuilhemN** [comment]
The solution is not yet released, it is in master only for now.

**Comment by Lory1990** [comment]
thanks, when would you release the new version?
