### ISSUE TITLE
Getting an Exception with 406 status for js, css and images files

### ISSUE THREAD

**Issue by lngphp** [nelmio/NelmioApiDocBundle#1222]
No js, css nor images loaded. Getting Exception instead:

> Uncaught PHP Exception 
> Symfony\Component\HttpKernel\Exception\NotAcceptableHttpException:
> "No matching accepted Response format could be determined" at 
> /.../vendor/friendsofsymfony/rest-bundle/EventListener/FormatListener.php line 71

The issue is described here:
https://stackoverflow.com/questions/48707204/getting-exception-with-406-status-on-nelmioapidocbundle

**Comment by lngphp** [comment]
Fixed with 
`$ bin/console assets:install --symlink`

**Comment by GuilhemN** [comment]
I'm closing this as there is already https://github.com/nelmio/NelmioApiDocBundle/pull/1223.
