### ISSUE TITLE
Custom Types (enum)

### ISSUE THREAD

**Issue by phpPhil** [nelmio/NelmioApiDocBundle#1226]
Hi,
The following property of my model doesn't show up in the api docs model section:
```php
    /**
     * Status
     *
     * @var string
     *
     * @ORM\Column(name="status", type="entitystatustype", nullable=false)
     * @DoctrineAssert\Enum(entity="MyVendor\ServicesBundle\DoctrineExtensions\DBAL\Types\EntityStatusType")
     * @Assert\NotBlank()
     *
     * @JMS\Groups({"MyGroup"})
     */
    private $status = EntityStatusType::ACTIVE;
```
I guess it is ignored because it has a custom type (enum).
How can I make this field show up?

**Comment by GuilhemN** [comment]
Is your model referenced somewhere?

> I guess it is ignored because it has a custom type (enum).

I don't think that's the case, but you can check by hooking in the `ObjectDescriber`.

**Comment by Bukashk0zzz** [comment]
Have same issue. Any Idea how to show it?

**Comment by GuilhemN** [comment]
Please share your model here and explain what doesn't work exactly.

**Comment by Bukashk0zzz** [comment]
```php
    /**
     * @ORM\Column(type="MemberStopStatusType", nullable=false)
     * @DoctrineAssert\Enum(entity="App\DBAL\Types\MemberStopStatusType")
     *
     * @var string
     */
    protected $status = MemberStopStatusType::UPCOMING;
```

In doc this field not shown.

**Comment by GuilhemN** [comment]
If you're using the jms serializer, the problem likely is that it cannot what type this is. Does it work better if you add `@SWG\Parameter(type="string")`?

**Comment by Bukashk0zzz** [comment]
Adding  `@JMS\Type("string")` helps. Thanks.

Full example:
```php
    /**
     * @ORM\Column(type="MemberStopStatusType", nullable=false)
     * @DoctrineAssert\Enum(entity="App\DBAL\Types\MemberStopStatusType")
     * @JMS\Type("string")
     *
     * @var string
     */
    protected $status = MemberStopStatusType::UPCOMING;
```

**Comment by Bukashk0zzz** [comment]
I think this issue can be closed.

**Comment by GuilhemN** [comment]
Indeed :)
