### ISSUE TITLE
Definition not found

### ISSUE THREAD

**Issue by amarox** [nelmio/NelmioApiDocBundle#1227]
```php
/**
 * @SWG\Definition(type="object", @SWG\Xml(name="domainUser"))
 * @package App\Domain\Model\User
 */
class User implements UserInterface
{
    /**
     * @SWG\Property(format="uuid")
     * @var Identity
     */
    private $id;
    /**
     * @SWG\Property(format="string")
     * @Assert\Email()
     * @Assert\NotBlank()
     * @var string
     */
    private $email;
    /**
     * @SWG\Property(format="string")
     * @var string
     */
    private $name;
    //...
}
```

Controller

```php
/**
     * @Route("/{id}", methods={"PUT"})
     * @SWG\Tag(name="Users")
     * @SWG\Parameter(
     *     name="id",
     *     in="path",
     *     type="string",
     *     required=true,
     *     description="..."
     * )
     * @SWG\Response(
     *     response="200",
     *     description="...",
     *     @SWG\Schema(ref="#/definitions/domainUser")
     * )
     *
     * @param $id
     * @param Request $request
     * @return JsonResponse
     */
    public function update($id, Request $request)
    {
         //....
    }
```

Error:

`{"message":"User Notice: $ref \u0022#\/definitions\/domainUser\u0022 not found for @SWG\\Schema() in \\UserController-\u003Eupdate() in \/var\/www\/html\/src\/Controller\/UserController.php","file":"\/var\/www\/html\/vendor\/zircote\/swagger-php\/src\/Logger.php","line":38,"code":0}`

**Comment by GuilhemN** [comment]
`@SWG\Definition` is not supported by this bundle, it provides `@Model` instead (see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#use-models).

**Comment by amarox** [comment]
I also tried `@Model`

```php
/**
     *
     * @Route("/{id}", methods={"PUT"})
     * @SWG\Tag(name="Users")
     * @SWG\Parameter(
     *     name="id",
     *     in="path",
     *     type="string",
     *     required=true,
     *     description="..."
     * )
     * @SWG\Response(
     *     response="200",
     *     description="...",
     *     @Model(type=User::class)
     * )
     *
     * @param $id
     * @param Request $request
     * @return JsonResponse
     */
    public function update($id, Request $request)
    {
        //....
    }
```

I had error
`{"message":"Warning: count(): Parameter must be an array or an object that implements Countable","file":"\/var\/www\/html\/vendor\/nelmio\/api-doc-bundle\/ModelDescriber\/ObjectModelDescriber.php","line":74,"code":0}
`

**Comment by amarox** [comment]
This error for php 7.2 only

**Comment by GuilhemN** [comment]
Could you provide us the entire stack trace please? (You can find it in the profiler)

**Comment by amarox** [comment]
`
ErrorException:
Warning: count(): Parameter must be an array or an object that implements Countable

  at vendor/nelmio/api-doc-bundle/ModelDescriber/ObjectModelDescriber.php:74
  at Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber->describe(object(Model), object(Schema))
     (vendor/nelmio/api-doc-bundle/Model/ModelRegistry.php:80)
  at Nelmio\ApiDocBundle\Model\ModelRegistry->registerDefinitions()
     (vendor/nelmio/api-doc-bundle/ApiDocGenerator.php:65)
  at Nelmio\ApiDocBundle\ApiDocGenerator->generate()
     (vendor/nelmio/api-doc-bundle/Controller/SwaggerUiController.php:53)
  at Nelmio\ApiDocBundle\Controller\SwaggerUiController->__invoke(object(Request), 'default')
     (vendor/symfony/http-kernel/HttpKernel.php:149)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:66)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:190)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:37)
`

**Comment by amarox** [comment]
Object

`
/var/www/html/vendor/nelmio/api-doc-bundle/ModelDescriber/ObjectModelDescriber.php:76:
array (size=1)
  0 => 
    object(Symfony\Component\PropertyInfo\Type)[2869]
      private 'builtinType' => string 'string' (length=6)
      private 'nullable' => boolean false
      private 'class' => null
      private 'collection' => boolean false
      private 'collectionKeyType' => null
      private 'collectionValueType' => null
`

**Comment by GuilhemN** [comment]
Could you check if https://github.com/nelmio/NelmioApiDocBundle/pull/1228 fixes your issue please ? :)

**Comment by amarox** [comment]
Yes, works!
