### ISSUE TITLE
Many sections (areas ?) on the same page

### ISSUE THREAD

**Issue by alterphp** [nelmio/NelmioApiDocBundle#1230]
Hi,

Since version 3 and the use of Swagger, I don't know how to render many sections on the same page. Areas seems to act this role, but  I can only browse on different pages.

I'd like to render multiple sections, like `pet`, `store` and `user` on this doc http://petstore.swagger.io/#/.

Thanks for explanations

**Comment by GuilhemN** [comment]
This is done using tags :)

**Comment by alterphp** [comment]
@GuilhemN thanks for the hint !

So I guess one operation could be present in many tags ?

I tried that one :
```
    /**
     * @Rest\Post(name="createUser", path="/create-user")
     * @Rest\RequestParam(name="username")
     * @Rest\RequestParam(name="password")
     * @SWG\Post(tags={"registration"})
     * @SWG\Response(description="Some infos")
     */
    public function createUser(ParamFetcher $paramFetcher)
    {
        $params = $paramFetcher->all();

        $view = [];

        return $this->handleView($view);
    }
```

But I got this error :
> User Notice: Unable to merge @SWG\Post() in \RegistrationController->moveboxCode() in /var/www/symfony/src/Controller/Api/RegistrationController.php

**Comment by GuilhemN** [comment]
What if you use `@SWG\Tag` instead of `@Post`? Or use `@Operation` instead of `@SWG\Post`?

**Comment by alterphp** [comment]
@Tag works well, @Operation is abstract (Cannot instantiate abstract class Swagger\Annotations\Operation).

Thanks !
