### ISSUE TITLE
Definitions is found from entities, but not found from controller

### ISSUE THREAD

**Issue by petr-buchin** [nelmio/NelmioApiDocBundle#1231]
In my entities I use definitions, as I was advised in https://github.com/nelmio/NelmioApiDocBundle/issues/1229#issuecomment-365691390 - by defining them in config.

This solution works well for entities, but somehow this does not work for controllers: the same ref to the same definition, that works in entity, does not work in controller.
My annotation that does not work:

```php
    /**
     * @Route("/example", methods={"GET"})
     *
     * @SWG\Response(
     *     response=400,
     *     description="Returned when parameter 'mediaSize' is absent or invalid.",
     *     @SWG\Schema(
     *         type="array",
     *         @SWG\Items(ref="#/definitions/Media")
     *     )
     * )
     */
```

And the error:
![Error](https://i.imgur.com/wCSubtJ.png)

P.S. `Media` definition is used for this response only as an example, since I have exactly the same ref to this definition in entity, and it works.

**Comment by GuilhemN** [comment]
Indeed sorry, I forgot this issue due to a BC break in zircote/swagger-php... (see https://github.com/nelmio/NelmioApiDocBundle/issues/1085) I'll submit a patch asap.

**Comment by petr-buchin** [comment]
@GuilhemN  thank you very much for the quick reply and for your work :)

**Comment by GuilhemN** [comment]
Should be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1232
