### ISSUE TITLE
Sort tags by alphabetical order

### ISSUE THREAD

**Issue by ganchito55** [nelmio/NelmioApiDocBundle#1238]
It seems that **now the tags appear in the same order that they appear in the routing file** (this is the behavior that I detect in Symfony 4).

To improve the usability, I think that **it would be good to sort the tags by alphabetical order** instead of use the appearance order.

Thanks for your time.

**Comment by ganchito55** [comment]
I have found that the Swagger UI JavaScript code allows this behavior adding:
  tagsSorter: 'alpha'

So the init-swagger-ui.js should be:

```
window.onload = () => {
  const data = JSON.parse(document.getElementById('swagger-data').innerText);
  const ui = SwaggerUIBundle({
    spec: data.spec,
    dom_id: '#swagger-ui',
    validatorUrl: null,
    presets: [
      SwaggerUIBundle.presets.apis,
      SwaggerUIStandalonePreset
    ],
    plugins: [
      SwaggerUIBundle.plugins.DownloadUrl
    ],
    layout: 'StandaloneLayout',
      tagsSorter: 'alpha'
  });

  window.ui = ui;
};
```

However I cannot achieve to pass this parameter from nelmio configuration file (something similar to nelmio_api_doc.tagsSorter: 'alpha').

**Comment by GuilhemN** [comment]
That's not supported right now. Imo https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/public/init-swagger-ui.js could be inlined in https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/SwaggerUi/index.html.twig and then adding a ``nelmio_api_doc.ui.config`` config option would easily solve your issue :)

**Comment by ganchito55** [comment]
Thanks for your answer, I'm going to try to implement it.

**Comment by SHND** [comment]
Are there any news on this feature?

**Comment by ndench** [comment]
I achieved this easily by overriding the template as specified in [the docs](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/customization.html):

```
{# templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig #}

{% extends '@!NelmioApiDoc/SwaggerUi/index.html.twig' %}

{% block swagger_initialization %}
    <script  type="text/javascript">
        window.onload = loadSwaggerUI({tagsSorter: 'alpha'});
    </script>
{% endblock swagger_initialization %}
```

**Comment by chrisguitarguy** [comment]
Related to https://github.com/nelmio/NelmioApiDocBundle/issues/1097#issuecomment-1079558547
