### ISSUE TITLE
FOSRestBundle's `AbstractScalarParam#requirements` should be used for `SWG\Parameter#pattern`

### ISSUE THREAD

**Issue by ManInTheBox** [nelmio/NelmioApiDocBundle#1239]
Hello,

I think that by accident [`Parameter#format`](https://github.com/nelmio/NelmioApiDocBundle/blob/v3.1.0/RouteDescriber/FosRestDescriber.php#L57) is set instead of the `pattern` property. I might be wrong but to me, _format_ should be used for different purposes, and FOSRestBundle's `QueryParam#requirements` and `RequestParam#requirements` should be used to configure `Parameter::setPattern()` property.

Right now input validation is completely ignored. With suggestion above it works fine. However, I can't still see in the UI regex pattern for allowed input.

For example, the following FOSRestBundle `QueryParam` annotation would produce input field like shown in the screenshot, but allowed regex is not mentioned, therefore the clients can't really know what is allowed.

```
@QueryParam(name="itemsPerPage", default="20", requirements="\d{1,2}", description="Items per page. Default is `20`.")
```

![missing regex pattern](https://content.screencast.com/users/zarkostankovic/folders/Jing/media/cf05a4ad-d884-4091-8682-1354296ddd79/00000561.png)

Thanks!

**Comment by GuilhemN** [comment]
Indeed, I agree this should be done if ``$requirements`` is a string/an array/or an instance of Regex.
Would you like to submit a PR for this?

**Comment by ManInTheBox** [comment]
Sure, will do! Thanks.

**Comment by ManInTheBox** [comment]
Thanks, @GuilhemN for the help. #1243 should properly configure `pattern` property, however, I believe we still don't display this requirement regex pattern to the consumers. Given my example annotation above this is what we get. Please notice that now validation works fine, although there's no single notion that valid input can only be `\d{1,2}`:

![input w/o regex pattern](https://content.screencast.com/users/zarkostankovic/folders/Jing/media/cf221d89-eea8-4589-9d3e-a03a7f30c5d7/00000562.png)

I'd be glad to fix that as well but your guidance would be appreciated. I'm having a hard time trying to adjust the UI (I believe that's a separate swagger-ui thing, but please correct me).

Thanks!

**Comment by GuilhemN** [comment]
Apparently it's supposed to be shown in a popup on hover (see https://github.com/swagger-api/swagger-ui/issues/1217).
