### ISSUE TITLE
PhoneNumberType shows not correctly

### ISSUE THREAD

**Issue by Bukashk0zzz** [nelmio/NelmioApiDocBundle#1240]
I use https://github.com/misd-service-development/phone-number-bundle in my Form Types.

PhoneNumberType has:
```php
    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'tel';
    }
```

So I expect that in doc it look like string. But PhoneNumberType shown. How can I fix this?

Shown:
<img width="527" alt="screen shot 2018-02-25 at 19 44 33" src="https://user-images.githubusercontent.com/1908342/36644521-5918baac-1a64-11e8-927d-75a042d1e8ce.png">

Expected:
<img width="340" alt="screen shot 2018-02-25 at 19 45 32" src="https://user-images.githubusercontent.com/1908342/36644536-789a25a0-1a64-11e8-8533-c3063f22d9b5.png">

Any idea how to fix this?

**Comment by GuilhemN** [comment]
In 3.2, you'll be able to do :
```php
$builder->add('phone', PhoneNumberType::class, ['documentation' => ['type' => 'string']]);

**Comment by Bukashk0zzz** [comment]
@GuilhemN Ok. Awesome! Can I get some how dev version now? What brunch you use for development? 

Thank you.

**Comment by Bukashk0zzz** [comment]
I see in master you have Form Extension. Thanks for help.
