### ISSUE TITLE
Question: How to add endpoint description

### ISSUE THREAD

**Issue by bahatron** [nelmio/NelmioApiDocBundle#1245]
I'm using Symonfy 4 with built-in Router annotation. I've installed NelmioApiDocBundle for my REST API documentation. I have:

```
    /**
     * @Route("/api/keywords", name="get_keywords", methods={"GET"})
     * @SWG\Response(
     *      response=200,
     *      description="Returns an array of keywords",
     *      @SWG\Schema(
     *          type="array",
     *          @Model(type=Keyword::class)
     *      )
     * )
     *
     * @SWG\Tag(name="Keyword")
     */
```

Which outputs:

![keyword_result](https://user-images.githubusercontent.com/19673942/36792303-24e26cda-1c92-11e8-854a-b148d0bcc054.jpg)

I want to add route level definitions as shown in: (screenshot taken from https://demo.api-platform.com/)

![route_description](https://user-images.githubusercontent.com/19673942/36791866-cea11cf0-1c90-11e8-8379-2c6979385956.jpg)

I can't find anything on internet on how to do this when using Symfony's basic route annotations

**Comment by GuilhemN** [comment]
Just add a description in the doc block of your method and it will be shown :)

In you example:
```php
    /**
     * Returns an array of keyword.
     *
     * @Route("/api/keywords", name="get_keywords", methods={"GET"})
     * @SWG\Response(
     *      response=200,
     *      description="Returns an array of keywords",
     *      @SWG\Schema(
     *          type="array",
     *          @Model(type=Keyword::class)
     *      )
     * )
     *
     * @SWG\Tag(name="Keyword")
     */

**Comment by bahatron** [comment]
Yeah it works! thanks!

**Comment by GuilhemN** [comment]
Ok, closing then ;)
