### ISSUE TITLE
Add an annotation to specify the area(s) of a route

### ISSUE THREAD

**Issue by babaorum** [nelmio/NelmioApiDocBundle#1246]
I would like to use the areas to specify multiple pages.
The problem with the **path_patterns** is I would need some complicated regular expressions.
Plus, if possible, I would like to abstract from the path to determine where a route should be displayed/described.

I think the easiest way would be to have an `@Area()` or `@Areas()` annotation?
I'm interested in contributing if you approve this feature, but I would love some guidance on the subject.

**Comment by GuilhemN** [comment]
We discussed this in https://github.com/nelmio/NelmioApiDocBundle/pull/1207 and I'm personally in favor of this new annotation, I'm not sure what name it should take though.

I'd say the only thing to do is to add a check in https://github.com/nelmio/NelmioApiDocBundle/blob/master/Routing/FilteredRouteCollectionBuilder.php#L40-L45 ensuring that annotated routes only get matched when presenting the correct annotation.

**Comment by kadryjanek** [comment]
I'm also for adding `@Area` annotation as the functionality is called: `Areas`.

**Comment by dbu** [comment]
just stumbled over needing this as well ;-)

as routes can be in several areas, the annotation should probably allow to specify a whole list of areas and thus be called `@Areas`, right? anybody up for writing a pull request with this feature?

**Comment by kadryjanek** [comment]
I think, I can implement it :)

**Comment by babaorum** [comment]
I started working on it this weekend.
It takes, a little more time than I thought... Right now, FilteredRouteCollectionBuilder only concern is the path matching. So the context is changing a bit.

**Comment by todoricMDPI** [comment]
I also need this feature. @babaorum, any news? :+1:
