### ISSUE TITLE
SWG\Property with JMS\VirtualProperty

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1247]
I tried adding the `@SWG\Property` annotation to a `@JMS\VirtualProperty` method but don't see the corresponding data in the output.  Is there a way to add description, example, etc. for a VirtualProperty?

**Comment by fanch317** [comment]
Work on v3.1.0.
- You must **exclude the attribute** if exists
- You must also **define the type** with @JMS\Type("string")

```
/**
 * Volatile var for thumbUrl, must filled before rendering
 * @serializer\Exclude
 */
private $thumbUrl;

/**
 * Url thumbnail for user image
 * @serializer\VirtualProperty
 * @serializer\Groups({"user","viewer","PortfolioContact", "v4_user"})
 * @Serializer\Type("string")
 */
public function getThumbUrl()
{
    return $this->thumbUrl;
}
```

**Comment by pdugas** [comment]
Using v3.1.0 according to my `composer.lock` file.

My entity class has the following:
```
    /**
     * @var Foo|null
     * @ORM\ManyToOne(targetEntity="Foo")
     * @Gedmo\Versioned
     * @JMS\Exclude
     */
    private $foo;

    /**
     * ID of the Foo
     * @JMS\Type("integer")
     * @JMS\VirtualProperty
     */
    public function getFooId() : ?int
    {
        return $this->foo ? $this->foo->getId() : null;
    }
```
The resulting JSON API spec includes:
```
    "Foo": {
      "properties": {
        ...
        "foo_id": {
          "type": "integer"
        },
```
Also tried adding `@SWG\Property(description="...")` to the getFooId() method to no avail.

I only seem to be able to get the type into the resulting output.  Do you get more with your example?

**Comment by GuilhemN** [comment]
``@Model`` is not supported on methods.
https://github.com/nelmio/NelmioApiDocBundle/pull/1263 will provide an alternative solution:
```php
/**
 * @SWG\Definition(
 *     @SWG\Property(property="foo_id", ref=@Model(MyModel::class))
 * )
 */
class Foo {
    // ...
}

**Comment by GuilhemN** [comment]
Closing since #1263 was merged
