### ISSUE TITLE
Disable the default group

### ISSUE THREAD

**Issue by sanchobouillant** [nelmio/NelmioApiDocBundle#1249]
Hi,

How can I disable the auto generate default group ?

![image](https://user-images.githubusercontent.com/5731199/36940087-879f5836-1f0a-11e8-9b65-04458bd97cae.png)

**Comment by GuilhemN** [comment]
That's not possible, all untagged operations go to default, see https://github.com/swagger-api/swagger-ui/issues/1311.

**Comment by huqiaoparis** [comment]
In some cases (when `$ref` is used), the "default" group still shows up, even when all my operations are tagged though.

**Comment by GuilhemN** [comment]
@huqiaoparis I have no explanation for this unfortunately. Have you tried asking this on Reddit or on https://github.com/swagger-api/swagger-ui?
