### ISSUE TITLE
Read @Assert annotations to determine required fields

### ISSUE THREAD

**Issue by duanegran** [nelmio/NelmioApiDocBundle#125]
Suppose you use an entity for your input class, it would be nice if the "required" flag on the documentation would read from the @ORM annotation.  For example, I have a property like the following:

```
    /**
     * @var string $recordType
     *
     * @ORM\Column(name="record_type", type="integer", nullable=false)
     * @JMS\Type("integer");
     * @JMS\SerializedName("record_type");
     * @Assert\NotBlank()
     * @Assert\Choice(choices = {"distributions", "diversifications", "dividends", "oia_dividends", "restricted_stock"}, message = "Choose a valid record type")
     */
    private $recordType;
```

It would be really nice if the "nullable" attribute was read.  I could also see the "Assert\NotBlank()" doing this.  If we had a way to utilize the "Assert\Choice" list that would be especially nice.

I didn't see a way to set the description for input parameters using an entity with JMS.

**Comment by magnetik** [comment]
Looks like it's working now ?

**Comment by catchamonkey** [comment]
Confirmed, We use @Assert at entity level, and the docs are pulling that through.

The only problem I can see is that it doesn't support validation groups.

**Comment by sromano88** [comment]
The Nelmio\ApiDocBundle\Parser\ValidationParser is taking care of the @Assert annotations, but does not consider the groups defined in it.

The problem of not supporting validation groups is that validations that are only part of a specific group, are handled as if they are in the Default group. Excluding them would be a better (not final) solution.

The Nelmio\ApiDocBundle\Parser\JmsMetadataParser consider the @JMS\Serializer\Annotation\JMS\Groups annotation.
The Nelmio\ApiDocBundle\Parser\ValidationParser does not consider Symfony asserts groups (@Symfony\Component\Validator\Constraints\Assert\<Name>) nor JMS groups (@JMS\Serializer\Annotation\JMS\Groups).

Does anyone knows how to solve it?

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
