### ISSUE TITLE
Schema validation errors after dependency upgrade

### ISSUE THREAD

**Issue by winterstefan** [nelmio/NelmioApiDocBundle#1250]
Hi there,

_TL;DR_
Whilst using your bundle, after upgrading the dependency`exsyst/swagger` to `v.0.4.0`, I'm receiving schema validation errors (without changing anything schema-related).

### The setup
- I'm using the `NelmioApiDocBundle` for generating Swagger docs. The schema is defined by using PHP annotations.
- Furthermore, I'm checking the validity of the schema by a PHPUnit test that posts the generated JSON to `swagger-api/validator-badge` [online validator](https://online.swagger.io/validator/debug).

Dependency | Version 
------------ | -------------
NelmioApiDocBundle | v3.1.0
zircote/swagger-php | v2.0.13
exsyst/swagger | was v.0.3.2, upgraded to v0.4.0
swagger-api/validator-badge | Online validator ([click](https://online.swagger.io/validator/debug))

### The problem
The problem has occurred after upgrading `exsyst/swagger` from `v0.3.2` to `v0.4.0` (see [Nelmio commit](https://github.com/nelmio/NelmioApiDocBundle/commit/3799dc13380b572bb6c35c48a71f3c715f7deb64)). Before the upgrade, the online validator returned zero errors.
Right after the upgrade, the online validator returns multiple errors with the same underlying pattern. 

To be honest, with four packages taking part in this problem, I wasn't finally able to track it down to a certain package. I would be deeply grateful if you could take a look at this and comment.

- Example test output:
```json 
{
    "schemaValidationMessages": [
        {
            "level": "error",
            "domain": "validation",
            "keyword": "oneOf",
            "message": "instance failed to match exactly one schema (matched 0 out of 2)",
            "schema": {
                "loadingURI": "http:\/\/swagger.io\/v2\/schema.json#",
                "pointer": "\/definitions\/parametersList\/items"
            },
            "instance": {
                "pointer": "\/paths\/~1api~1v1~1example~1endpoint~1{number}~1doit\/post\/parameters\/1"
            }
        }
    ]
}
```
- Swagger annotation, **that produces the violation** (list of scalar values!):
```php 
     * @SWG\Parameter(
     *     name="myParameter",
     *     in="formData",
     *     type="array",
     *     description="List of some INT values,
     *     @SWG\Items(
     *         type="integer",
     *         description="One single INT value",
     *         example="104",
     *     )
     * )
```
- Swagger annotation, **that is valid** (removed `description` & `exception` from the `Items()` annotation)
```php 
     * @SWG\Parameter(
     *     name="myParameter",
     *     in="formData",
     *     type="array",
     *     description="List of some INT values,
     *     @SWG\Items(
     *         type="integer",
     *         description="One single INT value",
     *         example="104",
     *     )
     * )
```
- The API docs UI seem to be error-free (at least, the `myParameter` looks well described).

### A deep dive
- Debugging lead me to this modification: [Made Items extend Schema](https://github.com/GuilhemN/swagger/commit/70adeaeeb0d97431e994015b3a1d86c96f184b12). Only **with** that change, the mentioned validation error occurs.
- When removing `description` & `example`, no violations are shown at all.
- Adding a PHPUnit test case *with* `description` & `example` (as JSON) to `exsyst/swagger` doesn't show any error.
- Adding a PHPUnit test case *with* `description` & `example` (as Annotation) to `zircote/swagger-php` doesn't show any error.

### Conclusion
As far as I understand, the environment is using the OpenAPI v2 specification.
IMHO, the mentioned code change should not affect the Swagger version / schema at all.

Could you give me a hint / point me out if there are any problems like that after upgrading the dependencies?

**Comment by GuilhemN** [comment]
The problem likely is that `@Items` doesn't support description and example in the specification so the validator complains but they are in practice (you had no error before because these fields were silently removed).

**Comment by winterstefan** [comment]
Oh well, that's very true...

I just didn't understand, why a code change that changes the `Item` hierarchy, could lead to validation errors. But yep, that does make sense.

**Thank you very much for the fast reply!**
