### ISSUE TITLE
Multiple templates for multiple views

### ISSUE THREAD

**Issue by dmitrovskiy** [nelmio/NelmioApiDocBundle#1252]
Hi,

My app has two APIs. 
The first one is private and requires auth. I created a documentation for the first one, did override of a template to add `Getting Started` section.
The second one is public and could be accessed by anyone and there should be no introduction like for the fist one. So I guess I need other template here.

Those two apis I split by multiple views feature.

And my question is, whether it's possible to use multipl templates at this point somehow? I use v2.13.3 version. Thanks!

**Comment by GuilhemN** [comment]
2.x is no longer supported, please consider upgrading to 3.x which provides a way to define areas suiting your needs :)
