### ISSUE TITLE
The option "documentation" does not exist.

### ISSUE THREAD

**Issue by Nadrshin** [nelmio/NelmioApiDocBundle#1253]
The [documentation](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#symfony-form-types) says:

> You can customize the documentation of a form field using the documentation option.

But I get the error:

> The option "documentation" does not exist.

**Comment by GuilhemN** [comment]
Indeed, this is not released yet. This is only available in the `master` branch.
