### ISSUE TITLE
Example of a self referencing field in an entity is always null

### ISSUE THREAD

**Issue by pbmyloc** [nelmio/NelmioApiDocBundle#1256]
We have a problem with an example of a self referencing entity field which is always displayed as null. It seems that the JmsSerializer\Type Annotation is ignored and converted to null.

We use the latest version of NelmioApiDocBundle "v3.1.0"

TestController Annotation:
```
    /**
     * @REST\Get(path="/test")
     *
     * @SWG\Response(
     *     response=200,
     *     description="",
     *     @Nelmio\Model(type=Test::class)
     * )
     *
     * @return View
     */
    public function getAction() {
        // ...
    }
```

Test Entity:
```
namespace TestNamespace\Entity;

use JMS\Serializer\Annotation as JmsSerializer;

class Test
{
    /**
     * @var Test
     *
     * @JmsSerializer\Type("ArrayCollection<TestNamespace\Entity\Test>")
     * @JmsSerializer\MaxDepth(2)
     */
    protected $subTest;
}
```

Current Example:
```
{
  "sub_test": [
    null
  ]
}
```

What we expect (or similar):
```
{
  "sub_test": [
    {
      "sub_test": [
        null
      ]
    }
  ]
}
```

Is there a simple workaround or fix for this problem?

**Comment by GuilhemN** [comment]
What if you use an array instead of `ArrayCollection`? I don't think we support this class.

**Comment by pbmyloc** [comment]
I changed it to `array`, but the example the same as with `ArrayCollection`:
```
{
  "sub_test": [
    null
  ]
}
```

Side note: ArrayCollection (and array) works as expected with other Entities:
```
class Test
{
    /**
     * @var Contract[]
     *
     * @JmsSerializer\Type("ArrayCollection< TestNamespace\Entity\OtherEntity>")
     * @JmsSerializer\MaxDepth(2)
     */
    protected $otherEntity;
}
```

This will produce the following example:
```
{
  "other_entity": [
    {
      "field_1": 1,
      "field_2": 1
    }
  ]
}
```

**Comment by GuilhemN** [comment]
I think I misunderstood the issue in the first place. 
You're talking about the generated examples shown in the documentation ui, right ? If so, we have no control over it unfortunately, they are managed by https://github.com/swagger-api/swagger-ui.

**Comment by pbmyloc** [comment]
Yeah I meant the example shown in the documentation.
Ok then I need to contact the devs from the swagger-ui. Thanks for guiding me to the solution/responsible repo of this problem 🙂

**Comment by GuilhemN** [comment]
Since we can't help more here, I'm closing :)
