### ISSUE TITLE
Parameters ref not found

### ISSUE THREAD

**Issue by hmonglee** [nelmio/NelmioApiDocBundle#1258]
Hello,

I define global parameters :
`nelmio_api_doc:
    documentation:
        info:
            title: My project
            description: API documentation for my project
            version: 0.0.0
        parameters:
          authorization:
            name: Authorization
            in: header
            description: Access token (must be prefixed by Bearer)
            required: true
            type: string`

and when I try to use it in controller annotation, it give me a User Notice: $ref "#/parameters/authorization" not found for @SWG\Parameter()
Here 's my annotation :
`/**
     * Get list.
     *
     * @Rest\View(serializerGroups={"Default"})
     * @SWG\Parameter(ref="#/parameters/authorization")
     */`

Thanks for your help.

**Comment by GuilhemN** [comment]
This was fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1232 but it isn't released yet.

**Comment by hmonglee** [comment]
@GuilhemN Only definitions are added but not parameters.

**Comment by GuilhemN** [comment]
Indeed, you're right. 
Would you like to submit a PR  fixing their support as well ?

**Comment by hmonglee** [comment]
Yes I will look at this week.

**Comment by n0str3ss** [comment]
@GuilhemN i see that this fix was merged, but was it released already?https://github.com/nelmio/NelmioApiDocBundle/pull/1322

thanks for your help
