### ISSUE TITLE
Docs Issue

### ISSUE THREAD

**Issue by kunicmarko20** [nelmio/NelmioApiDocBundle#1271]
[Here](https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html#general-php-objects) we can see an explanation about JMS serializer and it says that JMS is enabled by default and that we should disable it if we are not using it, but:

https://github.com/nelmio/NelmioApiDocBundle/blob/f9e28db38b2673f7ed9ba63b472d53064203fee0/DependencyInjection/Configuration.php#L83-L89

We see that it is false by default? So should I make a PR to fix the docs or configuration? 😄

**Comment by GuilhemN** [comment]
It's working fine, see https://github.com/nelmio/NelmioApiDocBundle/blob/master/DependencyInjection/NelmioApiDocExtension.php#L42

**Comment by kunicmarko20** [comment]
My bad, a little confusing but it works 😄

**Comment by GuilhemN** [comment]
Indeed, `prepend` is not well known and intuitive but it works well :) thanks for the report still :smile:
