### ISSUE TITLE
Symfony Serializer Groups cause Exception while parsing

### ISSUE THREAD

**Issue by MaksSlesarenko** [nelmio/NelmioApiDocBundle#1276]
api/doc page results in error after defining Groups annotation in Entity:
`{"error":{"code":500,"message":"Internal Server Error","exception":[{"message":"Warning: Illegal offset type in isset or empty","class":"ErrorException","trace"`

There is something suspicious going on this line:
https://github.com/nelmio/NelmioApiDocBundle/blob/a356221c6769988712295a16bc5896b8265e8029/ModelDescriber/ObjectModelDescriber.php#L66

**$groups** - this is actually a numerical-key array of groups from SWG annotation in controller
**$property** - while this is an instance of object(EXSyst\Component\Swagger\Schema)

PS Unfortunately have no time for further investigation. Will switch to JMS

**Comment by GuilhemN** [comment]
You're right, I don't know how we ended up using $property, it should be `$propertyName`. Will try to submit a fix.

**Comment by kamil-nawrotkiewicz** [comment]
Hello, when the problem will be corrected?

**Comment by dbu** [comment]
when somebody has time to do it, i guess. you are welcome to send a pull request. this is open source and people work on it in their free time...

**Comment by MaksSlesarenko** [comment]
I do not think it is a fix, because groups variable are number ordered array that is contsructed from controller's annotation group.

I believe that fix should contain fetching groups from target property and performing array_intersect between groups defined in controller and model

**Comment by tarlepp** [comment]
Seems like this exists on latest stable `3.2.0` when is the next release coming?

**Comment by GuilhemN** [comment]
I released v3.2.1 containing this fix https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v3.2.1.

**Comment by tarlepp** [comment]
@GuilhemN thanks!

**Comment by jameswhitehead2** [comment]
Thanks @GuilhemN (and all others involved)
