### ISSUE TITLE
With 300 api methods Google Chrome crashed

### ISSUE THREAD

**Issue by mydoctool** [nelmio/NelmioApiDocBundle#1281]
I have a project with more than 300 api methods.
I updated NelmioApiDocBundle from 2.13.3 to 3.2.0

Browser tab freezing and crashing on page /api/doc after first click to route link.

**Comment by shockey** [comment]
Any update here? Curious to know if Swagger-UI 3.x solved this.

**Comment by GuilhemN** [comment]
Updated in https://github.com/nelmio/NelmioApiDocBundle/pull/1411 ;) But https://github.com/swagger-api/swagger-ui/issues/1919 has not been updated.

**Comment by chrisguitarguy** [comment]
Going to close this one as the best we can do here is keep Swagger UI up to date
