### ISSUE TITLE
Invalid swagger.json generation - definition for entities with both Assert\NotBlank|Assert\NotNull and Assert\Length

### ISSUE THREAD

**Issue by jlekowski** [nelmio/NelmioApiDocBundle#1283]
Having an entity with both `@Assert\NotBlank` and `@Assert\Length` generates `swagger.json` from array like `[0 => "name", 2 => "accountId"]`, so we get:
```json
"definitions":{"User":{"required":{"0":"name","2":"accountId"}
```
This is due to the way `array_unique()` function works - it preserves keys (also the numeric ones).

FIX
https://github.com/nelmio/NelmioApiDocBundle/blob/ff590b013c59a37cf624c38c2ae4e1799d518209/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php#L100 could be replaced with (additional `array_values()` function):
```php
$this->schema->setRequired(array_values(array_unique($existingRequiredFields)));
```

**Comment by dbu** [comment]
good find, thanks for the report and analysis. can you create a pull request with this change?

**Comment by jlekowski** [comment]
PR created https://github.com/nelmio/NelmioApiDocBundle/pull/1285
