### ISSUE TITLE
Required form options when using form type

### ISSUE THREAD

**Issue by Laniax** [nelmio/NelmioApiDocBundle#1286]
I currently use the following annotation.
  

     * @SWG\Parameter(
     *        ....
     *  )
     * @SWG\Parameter(
     *         name="body",
     *         in="body",
     *         required=true,
     *         @SWG\Schema(
     *           type="array",
     *           @SWG\Items(
     *              ref=@Model(type=BatchEntityType::class),
     *          )
     *         )
     *  )
     * @SWG\Response(
     *    ...
     * )

As you can see, the `BatchEntityType` is a form type, but it has a custom required option 

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'csrf_protection'    => false,
            'cascade_validation' => true,
        ));

        $resolver->setRequired([
            "collection_type"
        ]);
    }

This results in a `MissingOptionsException: The required option "collection_type" is missing.` when rendering the docs. Is there any way i can define the `collection_type` option inside the annotation?

**Comment by GuilhemN** [comment]
It's not supported right now unfortunately but we could add an `options` field to `@Model`, are you willing to submit a PR?

**Comment by daum** [comment]
Agreed this would be helpful to just pass any options one may want to the form for configuration purposes too so that the docs for example could remove a captca field if it is being called via the API.

**Comment by magnetik** [comment]
The fix has been landed to dev but never to master. 

Do you need some user testing ?

Thanks

**Comment by GuilhemN** [comment]
I think we should backport this commit to master since dev won't be merged in master as it is about 4.x and Swagger 3 support.

I'll try to do it in a few weeks if there is no PR as I am currently passing exams :)

**Comment by GuilhemN** [comment]
Closing as this was backported in https://github.com/nelmio/NelmioApiDocBundle/pull/1522. Thanks!
