### ISSUE TITLE
Endpoints description is not rendered on production version

### ISSUE THREAD

**Issue by astronati** [nelmio/NelmioApiDocBundle#1287]
Settings:
```
Symfony: 3.3.*
NelmioApiDocBundle: 3.0
```
Is there a reason why on production any endpoint description is not rendered?
Is there a particular setting or env that could cause this difference?

I would like to mention that using the same code, the same description is visible in the development environment.

![screen shot 2018-04-11 at 13 59 06](https://user-images.githubusercontent.com/2708431/38615324-897fe45a-3d90-11e8-9a27-59e3c14ac585.png)

LOCAL
![screen shot 2018-04-12 at 12 22 53](https://user-images.githubusercontent.com/2708431/38671650-41cc500a-3e4c-11e8-94de-c1b3b9d8f142.png)

PRODUCTION
![screen shot 2018-04-12 at 12 22 34](https://user-images.githubusercontent.com/2708431/38671662-478e6f8c-3e4c-11e8-92e5-28ccf3b660aa.png)

**Comment by notFloran** [comment]
Hi !

The bundle need `phpdocumentor/reflection-docblock` for description : you needs to install it manually for version before 3.2.

See https://github.com/nelmio/NelmioApiDocBundle/pull/1186

**Comment by astronati** [comment]
@notFloran Thanks. It works!!!

**Comment by GuilhemN** [comment]
Closing as your issue is fixed :)
