### ISSUE TITLE
Groups parameter in annotation @Model thrown exception

### ISSUE THREAD

**Issue by rebangm** [nelmio/NelmioApiDocBundle#1289]
Hi,

I have an issue concerning groups annotations. I have two entity with doctrine annotations.
User and Feedback, an user can have one or multiple feedback.

My API retrieve the list of feedback (without any criteria), here the swagger documentation:
```PHP
    /**
     * @Route("/api/v1/feedback", name="list")
     * @Method({"GET"})
     * @ApiGroups({"feedback_list"})
     *
     * @SWG\Get(
     *     summary="get feedback list",
     *     @SWG\Parameter(
     *          name="limit",
     *          in="query",
     *          description="number of feedback",
     *          required=false,
     *          type="integer"
     *     ),
     *     @SWG\Parameter(
     *          name="offset",
     *          in="query",
     *          description="position of cursor",
     *          required=false,
     *          type="integer"
     *     ),
     *     @SWG\Response(
     *          response=200,
     *          description="success",
     *          @SWG\Schema(
     *              type="array",
     *              @SWG\Items(ref=@Model(type=Feedback::class, groups={"feedback_list"}))
     *        )
     *      )
     *
     * )
     *
     * @param Request $request
     * @return array
     */
```

 In Feedback entity, I have a reference to user:
```php

    /**
     * @var User user
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     * @ORM\JoinColumn(nullable=false)
     * @Assert\NotBlank()
     * @Groups({ "feedback_list" })
     * @SWG\Property(ref=@Model(type=User::class}))
     */
    private $user;
```

I create groups to exclude some fields in API output, but when I had groups in following line,
```php
 @SWG\Items(ref=@Model(type=Feedback::class), groups={"feedback_list"})
```
I had this error: 
![image](https://user-images.githubusercontent.com/1638136/38562410-c912808e-3cda-11e8-97eb-71dbff0a9fbd.png)

But when I removed groups params in @ Model annotations, it works but all my user fields are displayed in swagger.

Am I missing something about how to use groups in this bundle ?

Regards.

**Comment by GuilhemN** [comment]
This was fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1282, it is not released yet however, it probably will be in the next minor, or maybe we could just submit a patch.
