### ISSUE TITLE
Link & Unlink verbs run a ContextErrorException

### ISSUE THREAD

**Issue by burgesQ** [nelmio/NelmioApiDocBundle#1290]
Hi, 

I'm running a sf 3.4 application. 
Since I migrate nelmio to 3.x if I try to doc a method that use the verbs `link` or `unlink`  (`@FOS\RestBundle\Controller\Annotations\Unlink`) the web page conclude in a "Notice : undefined index: [link|unlink]".
Is that normal ? Should I stop using those verbs if I want to doc my route ?

**Comment by notFloran** [comment]
Hi,

It seems that OpenAPI doesn't supports the LINK and UNLINK methods. See https://github.com/OAI/OpenAPI-Specification/issues/480

I made a PR to fix that, see #1294
