### ISSUE TITLE
@Model Naming

### ISSUE THREAD

**Issue by thhan** [nelmio/NelmioApiDocBundle#1292]
I'm trying to name a Model specificate.

An exmaple:

```php
/**
* @SWG\Response(
*     description="Successfully created",
*     response="201",
*     @Model(type=Folder::class, groups={"folder_detail"}, definition="Folder_Detail")
* )
*/
```

So in ApiDoc the response Model is named "Folder_Detail" and not "Folder3". Is something like this included in the project?

**Comment by valiknet18** [comment]
I think it's will be a good feature.
I have many entities with same name (ex. User, User2, User3), i want to have ability to rename this models to Login, Registration, Profile.
