### ISSUE TITLE
Using `date-time` pattern 

### ISSUE THREAD

**Issue by kadryjanek** [nelmio/NelmioApiDocBundle#1298]
I'm trying to receive proper exmaple for `\DateTime` property: `2018-04-16 11:11:11` but I have: `2018-04-16T11:11:11.632Z`. I know that `SymfonyConstraintAnnotationReader` is adding `pattern` for property but this does change nothing. I think better solution would be to set example for that property with given format instead of pattern. I've tested it and this working fine.

What is also important (see: https://github.com/swagger-api/swagger-editor/issues/1225#issuecomment-288286561) combaining `format` and `pattern` is not recommended and will not work.

**Comment by darius-v** [comment]
With attributes it does not work,

#[OA\Property(type: 'string', format: 'date-time', example: '2020-01-01T00:00:00Z')]

still shows 2024-09-17T06:18:28.983Z" 
unless I make property public. What does it have to do with visibility at all?
