### ISSUE TITLE
Access to optional query parameter from controller

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1299]
This seems to be a trivial thing but I didn't find a way or any documentation to explain how to retrieve the value of my controller's query parameters (path params are working)

The error: 
`Controller \"App\\Controller\\SeasonController::showAction()\" requires that you provide a value for the \"$discr\" argument. Either the argument is nullable and no null value has been provided, no default value has been provided or because there is a non optional argument after this one.`

Below my controller's code:

```
    /**
     * Show a season
     *
     * Show season details by id or slug.
     *
     * @Route("/{id}", methods={"GET"}, name="season_show")
     *
     * @SWG\Tag(name="seasons")
     *
     * @SWG\Parameter(
     *     name="id",
     *     in="path",
     *     required=true,
     *     type="string",
     *     description="Slug of the season"
     * )
     * @SWG\Parameter(
     *     name="discr",
     *     in="query",
     *     required=false,
     *     enum={"id","slug"},
     *     default="id",
     *     type="string",
     *     description="Document discriminator property (id or slug)"
     * )
     *
     * @SWG\Response(
     *     response=200,
     *     description="Returns the season record",
     *     @Model(type=Season::class)
     * )
     * @SWG\Response(
     *     response=404,
     *     description="Season not found"
     * )
     *
     * @param string $id
     * @param string $discr
     * @return JsonResponse
     */
    public function showAction($id, $discr)
    {
        var_export($id); //OK
        var_export($discr); //NOT OK
    }
```

if I set a default value to $discr php parameter it's always getting this value.

On the documentation https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#using-the-bundle the query parameter is not even used in the function..

Any help would be appreciated

**Comment by dbu** [comment]
symfony does not pass query parameters as parameters to actions. you need to add `Request $request` to your action method and then do `$request->query->getAlpha('discr', 'id')` in your code. (there is `query->get()` but with the getAlpha and such, you can have some validation). see https://symfony.com/doc/current/controller.html#the-request-object-as-a-controller-argument for further reading.

closing this as the question has nothing to do with the api doc bundle.
