### ISSUE TITLE
Cannot use custom form type that have a parent

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#1303]
Hi,

To centralize the input value I'l like to define a FormType that have a ChoiceType as parent

Let's say you define ([as done in the symfony doc](http://symfony.com/doc/current/form/create_custom_field_type.html))

```
<?php

namespace Nelmio\ApiDocBundle\Tests\Functional\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RoleType extends AbstractType
{
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'choices' => [
                'User' => 'user',
                'Admin' => 'admin',
            ],
        ]);
    }

    public function getParent()
    {
        return ChoiceType::class;
    }
}

```

It should be fairly easy to use this `RoleType` as a field in another form, and be automagically detected as a `string[]` value, but currently it's detected as an object type.

Indeed in the `FormModelDescriber` the "catch-all" check with `$this->isBuiltinType` catches it and define it as a simple object.

Not sure on how to fix it.

**Comment by GuilhemN** [comment]
Fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1320
