### ISSUE TITLE
Optional path parameters?

### ISSUE THREAD

**Issue by dbu** [nelmio/NelmioApiDocBundle#1305]
I try to define a path parameter as optional. I double checked that the symfony routing sees that the path segement is optional. But in the generated swagger doc, the parameter is reported as required. Even when i define the parameter explicitly and set required=false, its still shown as required in the swagger doc. Is this a bug of nelmio or a shortcoming of swagger?

**Comment by GuilhemN** [comment]
Unfortunately swagger doesn't support optional path parameters, the only thing we could do is duplicating the path with/without the optional parameter.

**Comment by dbu** [comment]
we created separate controllers - that also allows us to better document what is happening. i will see if i can add a FAQ entry for this, as its somewhat specific to symfony vs swagger.
