### ISSUE TITLE
Dynamic references

### ISSUE THREAD

**Issue by alistairking** [nelmio/NelmioApiDocBundle#1327]
First of all, thanks a lot for this great project!
I'm relatively new to Swagger in general and this bundle in particular, so apologies if I've missed something.

I'm trying to use the dynamic reference feature of Swagger-PHP (https://github.com/zircote/swagger-php/tree/master/Examples/dynamic-reference) to have a base schema that i can extend dynamically in my various controllers, but based on the errors that I get, it feels like api-doc-bundle is not registering the definition with Swagger-PHP before the controller annotations are parsed.

So, ideally I'd like to do something like this in my controller:

```
    /**
     * @Route("/api/path/", methods={"GET"}, name="my_route")
     * @SWG\Response(
     *     response=200,
     *     description="Returns a list of things",
     *     @SWG\Schema(
     *         ref=@Model(type=BaseResponse::class),
     *         @SWG\Property(
     *             property="data",
     *             type="array",
     *             @SWG\Items(ref=@Model(type=MyDataType::class))
     *         )
     *     )
     * )
     */
    public function myAction()
    {
```

And have the `data` property explicitly defined here override the `data` property defined in the `BaseResponse` class. Unfortunately the `@Model` annotation always resolves to something like `#/definitions/BaseResponse`, where the `#` reference doesn't allow the parameters to be overridden.

To try and get around this, I manually created a BaseResponse definition in my config file like this:
```
        definitions:
            BaseResponse:
                properties:
                    type:
                        type: "string"
                    data:
                        description: "This field will be overridden."
```
and changed my controller annotation to something like this:
```
    /**
     * @Route("/api/path/", methods={"GET"}, name="my_route")
     * @SWG\Response(
     *     response=200,
     *     description="Returns a list of things",
     *     @SWG\Schema(
     *         ref="$/definitions/BaseResponse",
     *         @SWG\Property(
     *             property="data",
     *             type="array",
     *             @SWG\Items(ref=@Model(type=MyDataType::class))
     *         )
     *     )
     * )
     */
    public function myAction()
    {
```
but this is where I get an error like `Unable to find the definitions reference "BaseResponse" in ...`, while if i change the `ref="$/definitions/BaseResponse",` line to `ref="#/definitions/BaseResponse",` I get no error, but as with the `@Model` annotation, the extended parameter information is ignored.
In this case it seems like Swagger-PHP doesn't yet know about the definition at the point where it is parsing the controller annotations.

Any help would be appreciated. Thanks!

**Comment by GuilhemN** [comment]
Meanwhile you can use `@Schema::$allOf`. To support this feature I think we need to register config definitions in Swagger-php (and fix https://github.com/zircote/swagger-php/blob/master/src/Processors/HandleReferences.php for our models).

**Comment by alistairking** [comment]
`@Schema::$allOf` seems to work perfectly.
Thanks!
