### ISSUE TITLE
[Question] Dealing with Tags

### ISSUE THREAD

**Issue by jpegram2** [nelmio/NelmioApiDocBundle#1329]
A couple of questions dealing with tags that I don't find in the documentation... 
When viewing: http://petstore.swagger.io/

It looks like "pet" is the tag used by that collection of routes.

1. How do you get the summary/description next to the tag name?
2. How to make all of the tags default to closed?

Example of what I'm trying to do.

     * @SWG\Post(
     *     consumes={"application/json"},
     *     produces={"application/json"},
     *     tags={"MyTag"},
     *     path="/api/v1/getSomething",
     *     summary="This gets something",
     *     description="Retrieve list of something."
     *     @SWG\Parameter(
     *         in="body",
     *         name="",
     *         description="",
     *         @SWG\Schema(
     *              type="object",
     *              @SWG\Property(type="string",property="thing",type="string",example="books)
     *         ),
     *     ),
     *     @SWG\Response(
     *         response=200,
     *         description="Return a book",
     *     )
     * )
     * @SWG\Tag(
     *   name="MyTag",
     *   description="Operations about stuff",
     *   @SWG\ExternalDocumentation(
     *     description="Find out more about our stuff",
     *     url="http://google.com"
     *   )
     * )

This is the error I'm getting:

> "message": "[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_CLOSE_PARENTHESIS, got '@' at position 1208 in method

I've tried adding 
`use Doctrine\Common\Annotations\DocLexer;`
but that didn't do anything...

**Comment by jpegram2** [comment]
Figure it out.. For anyone else looking for how to set this up.

@SWG\Tag() did nothing for me, when it would sort of work it only display the tag name. To get the tags with descriptions as true accordion headers, I had to add them to the config/packages/nelmio_api_doc.yaml

```
nelmio_api_doc:
    documentation:
        info:
            title: Name of my App
            description:
            version: 1.0.0
        host: myapps.domain.com
        basePath: /api/v1
        tags:
        - name: "Tag1"
          description: "Everything about Tag1"
        - name: "Tag2"
          description: "Everything about Tag2"
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
```

then in my annotations all I had to add was
*     tags={"Tag1"},

I don't know if this is how it's meant to work, but it's how it is working.. To me it wasn't abundantly clear from any of the documentation.

**Comment by aguidis** [comment]
@jpegram2 how did you manage to remove the **default** section ? I'm struggling with this since few days ?

I used your `areas` config example but this is the result:

![image](https://user-images.githubusercontent.com/1856652/50589472-07751c00-0e87-11e9-9107-d8cf2e9857dc.png)

**Comment by cliffbroadbent** [comment]
> @jpegram2 how did you manage to remove the **default** section ? I'm struggling with this since few days ?
> 
> I used your `areas` config example but this is the result:
> 
> ![image](https://user-images.githubusercontent.com/1856652/50589472-07751c00-0e87-11e9-9107-d8cf2e9857dc.png)

'default' only appears when a Route has not been assigned a Tag.

In your particular case, assign a ' * @SWG\Tag(name="Internal")' annotation to your api/internal/delivery-notes and parcel Routes.

**Comment by aguidis** [comment]
@cliffbroadbent I already had the tag set:

```
     * @SWG\Post(
     *     path="/authenticate",
     *     tags={"Authentication"},
```

if I put the suggested annotation inside `@SWG\Post`, this is the result:

![image](https://user-images.githubusercontent.com/1856652/52228728-688f7580-28b3-11e9-8c04-b0d3b062eb9a.png)

and if I put it outside like:

```
     * @SWG\Tag(name="Authentication")
     * @Rest\Post(
     *     path="/authenticate",
     *     name="api_authentication_authenticate",
     * )
```

![image](https://user-images.githubusercontent.com/1856652/52228778-907ed900-28b3-11e9-86b7-9ab74b2878e2.png)

**Comment by 4nakata** [comment]
Any update ? 
I have the same issue :(
