### ISSUE TITLE
ERR_EMPTY_RESPONSE generating doc with Xdebug

### ISSUE THREAD

**Issue by PGLongo** [nelmio/NelmioApiDocBundle#1338]
Generating the documentation using Chrome I receive _ERR_EMPTY_RESPONSE_ but the same configuration works in production environment. 

The main difference between production and development environment was Xdebug. I've disable the module and now it works.

**Comment by GuilhemN** [comment]
Closing as it most likely isn't related to this bundle, it seems there are many occurences of [this bug in various contexts](https://www.google.fr/search?q=ERR_EMPTY_RESPONSE+xdebug+symfony&oq=ERR_EMPTY_RESPONSE+&aqs=chrome.0.69i59j69i61j69i57j0l3.1154j0j4&sourceid=chrome&ie=UTF-8).
