### ISSUE TITLE
Add Custom Parameters

### ISSUE THREAD

**Issue by charliefancelli** [nelmio/NelmioApiDocBundle#1345]
Hi,

I spend few hours to find, without success, how add a custom header in all requests.
We need to add the apiVersion in the sandbox but no mention in swagger documentation and neither in the this bundle.

It could be interesting to test our api with the `X-Accept-Version` header. Do you have an idea to add this headers in all requests (more than 80 route so adding in each is not the good idea).

With the old NelmioApiDoc version it was simple...

Regards,

**Comment by GuilhemN** [comment]
See https://stackoverflow.com/q/19590197/6140843, this will be easier with OpenApi 3 but we need to complete https://github.com/GuilhemN/swagger/pull/9.
