### ISSUE TITLE
PropertyInfo unable to check type of Collection

### ISSUE THREAD

**Issue by nataliaAznar** [nelmio/NelmioApiDocBundle#1346]
When declaring a Doctrine collection, I get this error:
_The PropertyInfo component was not able to guess the type of Doctrine\\Common\\Collections\\Collection::$element_

I have disabled de JMS like this:
```yml
nelmio_api_doc:
    models: { use_jms: false }
```

I think this error is the same that happened here:
https://github.com/nelmio/NelmioApiDocBundle/issues/1021

**Comment by nataliaAznar** [comment]
I think that it broke in the commit
https://github.com/nelmio/NelmioApiDocBundle/commit/01f691c4568de54063f580110247646e300f7dd6#diff-1c64574ff1f633f0df3aac6fa7a25c7b

**Comment by sebastiaanviaene** [comment]
I can confirm this. I threw away JMS serializer a while ago and have been using the Symfony Serializer. But to properly output the models to Nelmio I have to add this to config : 
``
nelmio_api_doc:
    models: { use_jms: false }
``

But this breaks my docs and I get the error as described above when using collections.
