### ISSUE TITLE
Allow deprecations via routing configuration

### ISSUE THREAD

**Issue by scaytrase** [nelmio/NelmioApiDocBundle#1354]
Currently deprecation is only possible via
* Manual swagger schema manipulations (aka hard-coding)
* `@SWG\Operation` with deprecated set to true
* `@deprecated` tag on a controller

In my use case I have renamed operation path, and now I have one legacy operation and one canonical operation, pointing on the same controller. The difference is only with route declarations

In order to mark legacy one as deprecated I should have the possibility to mark single route (or better - also entire resource import) as deprecated.

**Comment by GuilhemN** [comment]
This is possible already:
```yml
nelmio_api_doc:
    documentation:
        paths:
            /foo:
                get: {deprecated: true}

**Comment by scaytrase** [comment]
Wow, cool. Documentation indeed lacks all these new cool features, thank you!
