### ISSUE TITLE
How to use Alternative Names feature

### ISSUE THREAD

**Issue by carlosgoro** [nelmio/NelmioApiDocBundle#1355]
Hi.

I'm trying to use the alternative names feature ( https://symfony.com/doc/master/bundles/NelmioApiDocBundle/alternative_names.html ) added in #1312 , but I can't find the correct way to use this feature.

How can I reference the alias in the annotation instead of: `@Model(type=EntityName::class, groups={"groupName"}) ?`

Thanks in advance.

**Comment by GuilhemN** [comment]
I think the feature is incomplete, see https://github.com/nelmio/NelmioApiDocBundle/pull/1312#issuecomment-402664198.

**Comment by GuilhemN** [comment]
See https://github.com/nelmio/NelmioApiDocBundle/pull/1384
