### ISSUE TITLE
Error code 400, request not valid

### ISSUE THREAD

**Issue by AhsanNissar** [nelmio/NelmioApiDocBundle#1356]
I am sending data to an input property in service. I have initialized all members of DTO with valid data but in the service my input property is not getting initialized with the data. I am calling the service method properly from my component and passing all the data as the function parameter but the property do not get initialized and just move forward and call the api. I can show code too if you guys need it

**Comment by chrisguitarguy** [comment]
Need to see some example code here, but closing for new due to age.
