### ISSUE TITLE
Missing dependencies in composer.json

### ISSUE THREAD

**Issue by MaksSlesarenko** [nelmio/NelmioApiDocBundle#1361]
After bundle installation in sf4 and nelmio 3.2 I get following error:

> 
Did you forget to run \"composer require symfony/asset\"? Unknown function \"asset\" in \"@NelmioApiDoc/SwaggerUi/index.html.twig\".

Which means that I have to require additional package symfony/asset
It appears that template packages added to nelmio composer in require-dev section only, not in require

**Comment by GuilhemN** [comment]
Yes if you want to use the ui, you need to additionaly install the assets component, as specified in our recipe https://github.com/symfony/recipes-contrib/blob/master/nelmio/api-doc-bundle/3.0/config/routes/nelmio_api_doc.yaml#L8.
