### ISSUE TITLE
List parameter options

### ISSUE THREAD

**Issue by StefanNiederkofler** [nelmio/NelmioApiDocBundle#1372]
Hello,

is it possible to show the parameter options in the doc?
For example:

    products:
        path:     /products/{sort}
        controller: AppBundle\Controller\ProductController::indexAction
        methods:  ["GET"]
        defaults:
            sort: "default"
        requirements:
            sort: "default|alpha|newest|popular"

Now i want that the possible options "default|alpha|newest|popular" are listed in the doc, but they aren't.
The same goes for the global _locale parameter, with possible options "de|en|it"

![Image](https://i.imgur.com/UprMRbO.png)

**Comment by GuilhemN** [comment]
Isn't it shown on hover? See https://github.com/swagger-api/swagger-ui/issues/1217
