### ISSUE TITLE
Sending requests from page doesn't allow use of request->request

### ISSUE THREAD

**Issue by devinmatte** [nelmio/NelmioApiDocBundle#1381]
I have an API that uses `$request->request->getInt()` in a lot of places. In 2.0 of the API docs we were able to make requests just fine this way.

It appears that in v3 however we can only make requests pass params to `$request->query`. `in="request"` isn't an available option, and the documentation doesn't appear to explain how to pass in post request params in this fashion.

We can't change the way we receive params due to the API being in use. Is there a way to send params to the `$request->request` attribute?

**Comment by GuilhemN** [comment]
It's just not called `request`, you have to use either ``formData`` or ``body`` depending on your needs, see https://swagger.io/specification/v2/#parameterObject.
