### ISSUE TITLE
v2.13.* jQuery init error

### ISSUE THREAD

**Issue by jgauthi** [nelmio/NelmioApiDocBundle#1385]
Hi,
On html api doc, the jquery is undefined. The "all.js" file is introducted in HTML documentation without use external JS file, BUT javascript error appear. My relative symbolic links is OK.

> Uncaught SyntaxError: missing ) after argument list
> Uncaught ReferenceError: $ is not defined at doc:1365

If i change "vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/views/layout.html.twig":

```
<script type="text/javascript">
	{{ js|raw }}
</script>
```
by `<script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>`, this code fix the problem.

Can you fix this issue by use "all.js" with external call ?

**Comment by GuilhemN** [comment]
2.x is no longer maintained. Please upgrade to 3.x or submit a PR if you think this is an issue really important to fix and you can't upgrade (that's strange you're the first to report it though).
