### ISSUE TITLE
RepeatedType is rendering wrong in Nelmio

### ISSUE THREAD

**Issue by eaunitrust** [nelmio/NelmioApiDocBundle#1386]
Hello,

We're using a RepeatedType in the form to check if both passwords match.
The code itself is working, but in NelmioApiDocBundle, the fields are not recognized as a "plainPassword: string" option.

This is the form:
![schermafbeelding 2018-08-27 om 09 47 22](https://user-images.githubusercontent.com/15194074/44647396-3d3c5c80-a9de-11e8-8fd4-ab35cb4c8d33.png)

This is the annotation of the controller function:
![schermafbeelding 2018-08-27 om 09 49 29](https://user-images.githubusercontent.com/15194074/44647511-87bdd900-a9de-11e8-89e7-dfcd110c704f.png)

This is how it's rendered in the Models-section of NelmioApiDoc:
![schermafbeelding 2018-08-27 om 09 47 50](https://user-images.githubusercontent.com/15194074/44647415-4b8a7880-a9de-11e8-8a74-702f76f9acc7.png)

This is what I can enter as parameters (the "plainPassword"-option is missing in here!!!):
![schermafbeelding 2018-08-27 om 09 48 20](https://user-images.githubusercontent.com/15194074/44647444-5f35df00-a9de-11e8-9c3f-dc031a831267.png)

Am I doing something wrong? Please help me get all the required fields rendered in the API docs...

**Comment by GuilhemN** [comment]
The bundle does not support the `RepeatedType` yet, it shouldn't too hard to add though.
Would you be willing to submit a PR?
