### ISSUE TITLE
Assert\Length and required property semantics

### ISSUE THREAD

**Issue by lushc** [nelmio/NelmioApiDocBundle#1388]
Hello, I've noticed that a field is marked as required if the `Assert\Length` annotation is used with a minimum length greater than 0:

https://github.com/nelmio/NelmioApiDocBundle/blob/df9893428ec5ee6e60e8666c7001bcd54a384953/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php#L46-L53

However, because null and empty strings are not handled by the annotation ([docs](http://symfony.com/doc/current/reference/constraints/Length.html)), it's possible (and expected) to assert a minimum length on optional fields. In this case, my schema is marking fields as required when it's acceptable for them to not have a value according to the Symfony constraint validator.

What would be the best way to address this without a BC break for those relying on the current (and incorrect, in my opinion) behaviour?

**Comment by GuilhemN** [comment]
In this case I'd say this is a bug and the lines you're referring to should be removed :) (I wouldn't consider this change a BC break)
Would you like to submit a PR?

**Comment by GuilhemN** [comment]
See https://github.com/nelmio/NelmioApiDocBundle/pull/1389, thanks!

**Comment by lushc** [comment]
That's excellent, thank you very much!
