### ISSUE TITLE
Update Swagger UI to latest stable release

### ISSUE THREAD

**Issue by GMTA** [nelmio/NelmioApiDocBundle#1393]
The last update to the bundled Swagger UI in NelmioApiDocBundle was 8 months ago and since then, many improvements (such as [support for enum parameters](https://github.com/swagger-api/swagger-ui/issues/3873)) were made. It could use a little update :-)

**Comment by GuilhemN** [comment]
Done in https://github.com/nelmio/NelmioApiDocBundle/issues/1411 :)
