### ISSUE TITLE
Enum values parameter validation

### ISSUE THREAD

**Issue by InternalServerError** [nelmio/NelmioApiDocBundle#1398]
Hi there,

I'm implementing nelmioApiDoc with my Sf4.1.
I have some routes with allowable values, so I've set an enum values on my parameter.
However, if I give another value on my route, no exception or error is thrown.

Here my annotations routes : 
```
/**
 * @Rest\Route("/api/controller/")
 */
class FooController extends Controller
{
       /**
	 * @Rest\Get("/{parameter}", name="get__my_route", defaults={"parameter": "Foo"})
	 *
	 * @SWG\Parameter(
	 *     name="WaveVersionCode",
	 *     in="header",
	 *     type="integer",
	 *     required=true,
	 *     description="Version de WAVE"
	 * )
	 * @SWG\Parameter(
	 *     name="parameter",
	 *     in="path",
	 *     type="string",
	 *     enum={"Foo", "Bar"},
	 *     required=true,
	 *     description="My Parameter"
	 * )
	 * @SWG\Response(
	 *     response=JsonResponse::HTTP_OK,
	 *     description="Description",
	 *     @SWG\Schema(
	 *         type="array",
	 *         @SWG\Items(
	 *             ref=@Model(type=MyEntity::class)
	 *         )
	 *     )
	 * )
	 * @SWG\Tag(name="Entities")
	 *
	 * @param Request $request
	 * @param string $parameter
	 *
	 * @return JsonResponse
	 */
       public function getMyRoute(Request $request, string $parameter): Response
       {
           ....
       }
}
```

Thanks by advance,

Regards,

**Comment by adrenalinkin** [comment]
@InternalServerError Hello! If I right understand, you want to validate request data according to the Swagger API documentation.

Unfortunately `NelmioApiDocBundle` (also [swagger-php](https://github.com/zircote/swagger-php)) do not provide any manipulation with real data. This is just a userfull tool for generate API documentation in the [Open API 2.0](https://swagger.io/docs/specification/2-0/basic-structure/) standard.

But you can try this bundle **[swagger-resolver-bundle](https://github.com/adrenalinkin/swagger-resolver-bundle)**

Bundle provides possibility for validate data according to the Swagger 2 documentation. You describe your API documentation by Swagger and provides verification of data for compliance with the described requirements. When documentation has been updated then verification will be updated too, all in one place!

**Comment by chrisguitarguy** [comment]
Closing as this bundle and OpenAPI are just about documentation, not validation.

the `Choice` constraint annotation/attribute from the Symfony Validator is a good option for Enum validation.
