### ISSUE TITLE
deprecated and author annotations

### ISSUE THREAD

**Issue by hatemBBN** [nelmio/NelmioApiDocBundle#1399]
how to add deprecated tag 
and set author or contact or any info about the author per API not for whole documentation

**Comment by eaunitrust** [comment]
You can deprecate a route by using "\@deprecate" annotation. The route will be grayed out in Nelmio. The "\@author" annotation doesn't seem to work, so I don't know if that's being supported.

**Comment by hatemBBN** [comment]
It does not work for me @eaunitrust  could you please provide an example

**Comment by GuilhemN** [comment]
@eaunitrust gave you a correct answer about ``@deprecated`` :) About ``@author`` we don't support it per operation (OpenApi doesn't in fact, see https://swagger.io/specification/v2/), the best available is the Contact field that is related to the whole API (https://swagger.io/specification/v2/#contactObject) or you may also use the description field.

**Comment by hatemBBN** [comment]
@deprecated annotation does not work for me with 
Symfony : 3.4
Nelmio/api-doc-bundle: 3.2
