### ISSUE TITLE
jwt auth

### ISSUE THREAD

**Issue by gulaandrij** [nelmio/NelmioApiDocBundle#1401]
Hi
Is there a way to make api request to get jwt token. Like to make a request to login endpoint with some credentials and get token?

My config file:
```
nelmio_api_doc:
  documentation:
    info:
      title: G
      description: This is an awesome app!
      version: 1.0.0
    securityDefinitions:
      Bearer:
        type: apiKey
        description: 'X-Token: Bearer {jwt}'
        name: X-Token
        in: header
#        tokenUrl: /api/auth/login_check
#        authorizationUrl: /api/auth/login_check
    security:
      - Bearer: []
  areas: # to filter documented areas
    path_patterns:
    - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
```

**Comment by GuilhemN** [comment]
Please priviledge symfony support endpoints (see https://symfony.com/support) for this kind of questions ;)
And it only seems possible for OAuth2 authentication unfortunately (because Bearer are not truly standardized?).
