### ISSUE TITLE
Super slow on Docker

### ISSUE THREAD

**Issue by tobiassjosten** [nelmio/NelmioApiDocBundle#1410]
I just tried using this bundle in our brand new app (Symfony 4.1.4), running on Docker (Docker for Mac). Not sure if that's the problem but it's incredibly slow – takes 1.7 minute to load /api/doc.

Not really sure where to start looking, so I wanted to check in and see if anyone else has experienced these problems before? And perhaps has solved them? :)

**Comment by goetas** [comment]
Issues with Docker on Mac are not related to this Bundle and neither to symfony or PHP.
Is about how docker shares the filesystem between the host system and the container, and it affects mainly Mac and even more Windows.

https://docs.docker.com/docker-for-mac/osxfs-caching/ has some tips on how to mitigate the problem.

**Comment by tobiassjosten** [comment]
Right. I wasn't sure that was the problem so I wanted to reach out to verify with others' experience. Turns out it was a misconfiguration – works perfectly now.
