### ISSUE TITLE
Showing route name in api doc?

### ISSUE THREAD

**Issue by runawaycoin** [nelmio/NelmioApiDocBundle#1413]
Hi,

Is it possible to show the route's name in the api doc output at all?

I'm on symfony 4.1.6 and using Symfony\Component\Routing\Annotation\Route annotations within my Controller, eg:

``` 
/**
@Route("/path/", name="route_name")
*/
```

The path is picked up but not the name.

Thanks.

**Comment by LBlibiao** [comment]
I think so too

**Comment by mormanski** [comment]
This would be very helpful, especially when importing into POSTMAN.

**Comment by GuilhemN** [comment]
Would you like to import it as `operation_name`?

**Comment by mormanski** [comment]
Sorry, maybe it's not as simple as I thought. I'm not using SWG annotations.

I'm not sure how this bundle generated the `name` value in the case where I'm only using @route annotations. 

It seems like it takes the first comment line from PHP Comment block and sets that to `name`. Perhaps if there was a flag where we could set such as `use_route_name: true` in the yaml config. If this value is true, then the `name` value could be set to the route name and not the first comment.

**Comment by GuilhemN** [comment]
Swagger doesn't have a `name` field actually. We parse php docs to fill operations description (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/RouteDescriber/PhpDocDescriber.php), maybe is this what you're seing?

Could you try to set `operationId` manually on one of your routes to check if this would suit you?

**Comment by pdugas** [comment]
Is there a way for the automatically generated route name from FOSRest be used as the operationId?

**Comment by GuilhemN** [comment]
The name of the route should be used as operation id from https://github.com/nelmio/NelmioApiDocBundle/pull/1907.
Closing as this is now fixed.
