### ISSUE TITLE
[3.0] FormType input as separate formData or query parameters

### ISSUE THREAD

**Issue by zloyboldin** [nelmio/NelmioApiDocBundle#1422]
Hello, everyone!
Looking for a recipe, how can i pass some formtype into `@SWG\Parameter` and get separate formData inputs?
```
     * @Operation(
     *     @SWG\Parameter(
     *         name="form",
     *         in="body",
     *         description="Bla Bla Bla",
     *         @Model(type=AccountType::class)
     *     ),
     * )
```

```
class AccountType 
{
    public function buildForm(FormBuilderInterface $builder, array $options)
        {
            $builder
                ->add('name', TextType::class)
                ->add('account_type', TextType::class, ['property_path' => 'accountType'])
                ->add('salesforce_account_id', TextType::class, ['property_path' => 'salesforceAccountId']);
        }
```
When i do this - a get 
![ce24264ec8](https://user-images.githubusercontent.com/23660416/47716303-e1f44800-dc74-11e8-9dc6-9563cdeb5292.jpg)

But i want to see something like this
![ea627cc237](https://user-images.githubusercontent.com/23660416/47716327-fa646280-dc74-11e8-852e-000286d14928.jpg)

Is there any method to convert all fields from `AccountType` class into separate `formData` fields?
In previous version of Nelmio i saw something like `parsers` in `input` annotation, but I don't remember how it works. What can I do now?

**Comment by lukepass** [comment]
I have the same problem and unfortunately I converted them by hand.

**Comment by GuilhemN** [comment]
According to the specification (https://swagger.io/docs/specification/2-0/describing-request-body/), the name of the body is ignored and is just here for documentation purposes, not sure we can easily work around that unfortunately.

However this should be easier with OpenApi 3 and the support of `requestBody` (see https://swagger.io/docs/specification/describing-request-body/). It is supported by NelmioApiDocBundle v4 which is currently in beta.
