### ISSUE TITLE
Doctrine array type can't be overriden

### ISSUE THREAD

**Issue by fmarchalemisys** [nelmio/NelmioApiDocBundle#1431]
My entity contains a property like this:

~~~~~~
/**
 * @ORM\Column(type="array", name="spoken_languages", nullable=true)
 * @var string[]
 */
private $spokenLanguages;
~~~~~~

When /api/doc is visited, it ends with error "Property \"\\App\\Entity\\User:spokenLanguages\" is an array, but no indication of the array elements are made. Use e.g. string[] for an array of string."

The `@var` attribute is ignored. Changing the column type to `@ORM\Column(type="string[]",…)` solves the problem but, then, it is not a valid doctrine type.

Is it possible to override the type declared in the column type of that property?

**Comment by GuilhemN** [comment]
Indeed, this is related to https://github.com/nelmio/NelmioApiDocBundle/issues/1348. Meanwhile, you can use `@SWG\Property(type="array", @Items(type="string"))`, see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#general-php-objects.

**Comment by fmarchalemisys** [comment]
Thanks! It works!

For the record, I had to define it like this:

    @SWG\Property(type="array", @SWG\Items(type="string"))

with an additional `@SWG\Items`. The use statement is:

    use Swagger\Annotations as SWG;
