### ISSUE TITLE
Multiple versions with multiple views (v3)

### ISSUE THREAD

**Issue by TomCawthorn** [nelmio/NelmioApiDocBundle#1442]
Hi there,

Referencing https://github.com/nelmio/NelmioApiDocBundle/issues/754

We're looking to have a swagger document per version of the api. E.g.
* /api/v1/doc.json will document all /api/v1* endpoints
* /api/v2/doc.json will document all /api/v2* endpoints
* /api/v3/doc.json will document all /api/v3* endpoints
etc...

Is this possible with version 3.0? Any other suggestions?

Thanks

**Comment by GuilhemN** [comment]
Sure, have a look at https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html
