### ISSUE TITLE
Symfony 4.2 and new Routing support

### ISSUE THREAD

**Issue by DemigodCode** [nelmio/NelmioApiDocBundle#1444]
We're struggling with a Problem in the Utils\ControllerReflector.

Symfony stores the controllers as services as default.
Services are stored like all other controllers in the router now (with controllername::method).
This causes problems when the ControllerReflector tries to read the api methods with reflection.

ControllerReflector->getClassAndMethod() has to be changed in the first if (preg_match('#(.+)::([\w]+)#', $controller, $matches)). First this method has to check if an service with the matched controller name exists.

**Comment by DemigodCode** [comment]
Forget what i've written. Another problem.

**Comment by 6ecuk** [comment]
There's still a problem when you have a controller as a service with the name of service differed from FQCN. 
And another question - why there is check on not exist class in bundle ?
https://github.com/nelmio/NelmioApiDocBundle/blob/0bca7f377dc65a955cad719131bdc45219aec6f9/Util/ControllerReflector.php#L99
