### ISSUE TITLE
Symfony serializer property names

### ISSUE THREAD

**Issue by tbmatuka** [nelmio/NelmioApiDocBundle#1445]
From what I can see in the current master, getPropertyName only checks for the SWG property annotation. There are at least 2 other factors with Symfony serializer:

1. Name converter which applies to all property names. The most common is the 'serializer.name_converter.camel_case_to_snake_case' service which comes with the serializer and is in the docs.
2.  Annotation Symfony\Component\Serializer\Annotation\SerializedName which overrides the property name for serialization.

Getting names from the serializer component instead of manually should cover both of these cases and should future proof it for when other stuff gets added to the serializer.

The only current workaround is to manually specify all property names which are affected, but that's a hassle and is something that developers need to be aware of.

**Comment by sotsky** [comment]
Any plans to have this implmented?

That will save a lot of time for getting correct properties for models.

**Comment by GuilhemN** [comment]
:+1:, that would be a great addition if someone is willing to implement it.
It would mostly be about adding their support in https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/ObjectModelDescriber.php.

**Comment by GuilhemN** [comment]
Will be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1636 so I'm closing here.
