### ISSUE TITLE
Only display tags and hide the default section

### ISSUE THREAD

**Issue by aguidis** [nelmio/NelmioApiDocBundle#1458]
I really tried many things before creating this issue but I can't figure it out.

I just want to remove the **default** section :

![image](https://user-images.githubusercontent.com/1856652/50606113-ca2f7f00-0ec4-11e9-977e-21904c72e3ce.png)

Here is the nelmio configuration:

```
nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        host: delivery.app/api/internal
        schemes: [https]
        info:
            title: Internal API
            version: 1.0.0
        tags:
            - name: "Authentication"
              description: "Authentication related endpoints"
            - name: "Delivery Note"
              description: "Delivery notes related endpoints"
            - name: "Parcel"
              description: "Parcel related endpoints"
            - name: "User"
              description: "User related endpoints"
    areas: # to filter documented areas
        path_patterns:
             - ^/api(?!/doc/$) # Accepts routes under /api except /api/doc

```

**Comment by GuilhemN** [comment]
Have you tried excluding your internal routes by updating the path patterns?

**Comment by Bizinovic** [comment]
How can you do that ?

**Comment by GuilhemN** [comment]
Check out the last part of the `If you're not using Flex` paragraph of [the docs](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html#installation).

To summarize, you have to update `nelmio_api_doc.areas.path_patterns`.

**Comment by rendler-denis** [comment]
@GuilhemN 
I would like to filter the default path /api/doc to only have my sections without the default section. I've tried with Areas, but then I would have to go to /api/doc/subscriber . Is there any possibility to use the /api/doc to show only my sections? Thanks.

**Comment by chrisguitarguy** [comment]
Related: https://github.com/nelmio/NelmioApiDocBundle/issues/1425

seems like this issue has been resolved via the PR above, though, so closing.

**Comment by tomazartack** [comment]
For me this worked:

nelmio_api_doc:
    documentation:
        info:
            title: Title
            version: 1.0.0
    areas:
        default:
            disable_default_routes: true
