### ISSUE TITLE
Schema for FormData parameter is ignored

### ISSUE THREAD

**Issue by HooK81** [nelmio/NelmioApiDocBundle#1459]
Hello everyone,

I have a form-data service with 2 parameters:
- file: a binary file
- metadata: a string wich contains a JSON object with the description of the photo

I'm trying to set the schema of the JSON object but the @Schema annotation is ignored...
It seems to be caused by using in=formData 

Here is the description of my service:

    /**
     * Upload a photo
     * @Rest\View()
     * @SWG\Post(
     *     consumes={"multipart/form-data"}
     * )
     * @SWG\Parameter(name="version", in="path", type="string", description="version of service", default="v1")
     * @SWG\Parameter(
     *     name="metadata",
     *     in="formData",
     *     type="string",
     *     description="Photo properties",
     *     required=true,
     *     @SWG\Schema(
     *         type="object",
     *         @Model(type=AppBundle\Entity\Photo::class)
     *     )
     * )
     * @SWG\Parameter(name="file", in="formData", type="file", description="The photo file", required=true)
     * @SWG\Response(response=204, description="Photo uploaded")
     * @SWG\Response(response=500, description="Internal error")
     */

![doc](https://user-images.githubusercontent.com/8122575/50685392-4d61e980-1019-11e9-8dec-14b56f29a37a.PNG)

Is it possible to do that ? 
The only solution I've found for the moment is to put the schema manually into the description.

Thanks

**Comment by GuilhemN** [comment]
According to the specification, using schema is only allowed when using `in: body` (see https://swagger.io/specification/v2/#parameterObject).

Maybe as a solution we could inline models in non body parameters at the very end of the processing.
