### ISSUE TITLE
"Could not render this component, see the console" error for QueryParam with map=true

### ISSUE THREAD

**Issue by spolischook** [nelmio/NelmioApiDocBundle#1465]
The `@SWG\Parameter` works ok, but QueryParam produce an error in api doc
![selection_283](https://user-images.githubusercontent.com/1978331/51243135-64de9200-198a-11e9-9138-92b566aca95e.png)
Here is code for produce this result:
```php
class ApiController
{
    /**
     * @SWG\Response(
     *     response=200,
     *     description="List of products"
     * )
     * @SWG\Parameter(
     *     name="cat",
     *     in="query",
     *     type="array",
     *     collectionFormat="multi",
     *     @SWG\Items(
     *         type="string"
     *     ),
     *     description="The field used to order rewards"
     * )
     * @QueryParam(map=true, name="categories", requirements="\d+", description="Id of categories to filter.")
     */
    public function getProductsAction()
    {
        return [];
    }
}
```
for the code example see https://github.com/spolischook/api-doc-test

**Comment by spolischook** [comment]
@GuilhemN can you reproduce this issue?

**Comment by GuilhemN** [comment]
Yes, sorry for the delay I missed the notification...

Thank you for the precise report, I opened https://github.com/nelmio/NelmioApiDocBundle/pull/1506/files which should solve your issue.
Could you give it a try?
