### ISSUE TITLE
Error in "php bin/console debug:autowiring"

### ISSUE THREAD

**Issue by peterprochaska** [nelmio/NelmioApiDocBundle#1470]
When i execute `php bin/console debug:autowiring` i get the following error:

```
Fatal error: Class 'Symfony\Component\Form\AbstractTypeExtension' not found in C:\www\comeback\vendor\nelmio\api-doc-bundle\Form\Extensio
n\DocumentationExtension.php on line 22
```
Am I doing something wrong?
I'am using Symfony 4.2.3 and nelmio api doc bundle 3.3.1

**Comment by GuilhemN** [comment]
See https://github.com/nelmio/NelmioApiDocBundle/pull/1472, the issue is that we autowire a possibly broken service (when forms are not installed).

**Comment by peterprochaska** [comment]
Thank you very much for the fix
