### ISSUE TITLE
Generated JSON escapes route requirements wrong

### ISSUE THREAD

**Issue by markusgillmeister** [nelmio/NelmioApiDocBundle#1479]
We discovered an issue that the generated JSON API documentation escapes the route requirements wrong:

Given the following route:
```
 * @Route("/products/{id}/cis", methods={"GET"}, requirements={"id"="\d+"})
```
(according to symfony documentation its the way to tell symfony that id has to be numeric).
and Swagger-Annotation
```
...
    *     @SWG\Parameter(
     *         name="id",
     *         in="path",
     *         description="ID des Produkts",
     *         required=true,
     *         type="integer"
     *     ),
...
```

will generate the following json output
```
...
"/products/{id}/cis": {
   "get": {
      "parameters": [
          {
             "name": "id",
             "in": "path",
             "required": true,
             "description": "ID des Produkts",
             "type": "integer",
             "pattern": "\\d+"
           },
...
```

As you can see the pattern is now **\\\\d+** instead of **\d+**. This causes errors when using code generators when parsing this (we tried this with openapi-generator).

Are we right that this seems to be a bug when generating the json file? 

Best Regards
Markus

**Comment by GuilhemN** [comment]
I think the issue is in openapi-generator, backslashes must be escaped (see https://www.freeformatter.com/json-escape.html) and it's done by PHP itself.
Or maybe they just don't recognize this pattern, which is more expectable since there is no conventions on this field and we simply adopted the value returned by symfony. Could you check the format they expect?

**Comment by markusgillmeister** [comment]
Hi,
you're  absolutely right! JSON rules say that a backslash has to be replaced with \\\ . It is a confirmed (and already fixed) bug in openapi-generator.
Apologize for raising an issue here!

Best Regards
Markus
