### ISSUE TITLE
[Question] How to pass custom (not authorization) headers from sandbox?

### ISSUE THREAD

**Issue by k0d3r1s** [nelmio/NelmioApiDocBundle#1481]
In previous bundle version it was possible to pass extra headers from sandbox mode. How to enable that in new version? All I can find are those security options but that's not really what I need.
I sometimes want to pass optional drop cache header to my endpoints. Is there a way to define this? And preferably globally so I don't need to set this up on every endpoint.

Edit: Ok, I found that headers can be passed by parameters per endpoint. Still looking for global solution, not endpoint based

**Comment by GuilhemN** [comment]
It supported by the spec unfortunately (see https://stackoverflow.com/questions/39791491/how-to-define-global-parameters-that-will-apply-to-all-paths).

A small "hack" to solve this could be to create a route describer automatically adding the header to all your operations:
```php
class HeaderDescriber implements RouteDescriberInterface
{
    use RouteDescriberTrait;

    public function describe(Swagger $api, Route $route, \ReflectionMethod $reflectionMethod)
    {
        foreach ($this->getOperations($api, $route) as $operation) {
            $operation->getParameters()->get('Some-Header', 'header')
                ->setType('string');
        }
    }
}

**Comment by k0d3r1s** [comment]
@GuilhemN Thanks. Your suggestion is working but that's some serious hack for something that was working fine in previous version.
And as I don't need that header on every endpoint, I ended up with something like this:
```php
public function describe(Swagger $api, Route $route, ReflectionMethod $reflectionMethod): void
{
    $controller = explode('::', $route->getDefault('_controller'));
    if (is_array($controller)) {
        if ($method = (new ReflectionClass($controller[0]))->getMethod($controller[1])) {
            if ($this->reader->getMethodAnnotation($method, Cache::class)) {
                foreach ($this->getOperations($api, $route) as $operation) {
                    $operation->getParameters()->get(PhpsedCache::CACHE_HEADER, 'header')->setType('string');
                }
            }
        }
    }
}
```
which is some serious workaround for theoretically simple function

**Comment by GuilhemN** [comment]
Why not using the ``$reflectionMethod`` provided as argument in your code?

Apart from that I agree it's a hack but it's a limitation from Swagger itself... to deal with that we could however provide a config option to add extra headers to all routes more easily (as does the describer I provided earlier), would that help?

**Comment by k0d3r1s** [comment]
well, it wasn't working as I wanted for some reason, now works ok after symfony update.
but configuration will help :)

**Comment by chrisguitarguy** [comment]
I feel like a config option here _is_ the ability to add a custom route describer, tag it, and then do whatever you need to do. A config option to add params globally is one thing, but seems like the ask here to basically support any sort of annotation or conditionally apply params.

I'm going to close for now for the reasons above and due to age. Feel free to re-open or comment if this is still relevant.

**Comment by stloc** [comment]
```
    #[OA\Parameter(
        name: 'token',
        in: 'header',
        description: 'Token d\'authentification',
        schema: new OA\Schema(type: 'string'),
        required: true,
    )]
```
