### ISSUE TITLE
Tag description not show

### ISSUE THREAD

**Issue by pdias** [nelmio/NelmioApiDocBundle#1483]
I use this annotation:

```
@SWG\Tag(
      name="Digitalis - Academic Year",
      description="Operations on digitalis about academic year",
      @SWG\ExternalDocumentation(
             description="Find out more",
             url="http://swagger.io"
      )
 )
```

The **Tag** name is shown but the description is not and the **ExternalDocumentation** is also not shown.

What am I doing wrong?

Thanks.

**Comment by GuilhemN** [comment]
Please git us some more context: are you using this on a controller method?

If so, `@SWG\Tag` is only a syntactic sugar in this context and only `name` is really supported (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/Describer/SwaggerPhpDescriber.php#L178), other fields are not allowed there.

**Comment by pdias** [comment]
You're right @GuilhemN (is on controller). 

Thanks.
