### ISSUE TITLE
Bundle setting all content in swagger-data element

### ISSUE THREAD

**Issue by gbelvedere** [nelmio/NelmioApiDocBundle#1485]
I've configured the bundle according to the instructions, but even when the API is working, I can't see anything in the html, when I see the source code, I see this: 

![image](https://user-images.githubusercontent.com/6868303/54496114-e94a8400-48eb-11e9-8871-757d373e17c8.png)

I've added 
`
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
`
to app/config/routing.yml

I also have FosRestBundle and FOSOAuthServerBundle configured and working. 

any idea?

**Comment by GuilhemN** [comment]
Could you be more precise what's the issue you're dealing with please?

**Comment by gbelvedere** [comment]
The problem was that nothing was visible in the html. I solved it now...the clue was in the two lines for stylesheets. The assets for the bundles were missing from the public directory, once I copied them it worked.
