### ISSUE TITLE
Exclude by name pattern

### ISSUE THREAD

**Issue by Lifeformwp** [nelmio/NelmioApiDocBundle#1486]
Hello, currently this bundle allows (as documentation states) excluding some routes with path_patterns for areas, for example:
```
areas:
  default:
    path_patterns: [ ^/api(?!test) ]
```

But in my project, there is case, when one route exists with two names (for versioning, it's not my fault) and nelmio throws "Unable to merge" because of this. Is there a possible chance to have name_patterns option for config, same as path_patterns, but for name of the route, thanks.

**Comment by GuilhemN** [comment]
We recently merged https://github.com/nelmio/NelmioApiDocBundle/pull/1460 which might suit your needs.
But sure, having a ``name_patterns`` option as well would be great.

**Comment by Lifeformwp** [comment]
Thanks for reply, I've added pull request regarding that option, please check it

**Comment by wikimatze** [comment]
@GuilhemN thanks for letting me know, I'll try that out.
