### ISSUE TITLE
API response wrapper

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1487]
Hello! I am using a wrapper object class called ApiResponse which has a status string property (success or error) and a data object containing the actual response (for example an array of products).
How can I describe this since every controller's action returns an ApiResponse with a different data?

Thanks!

**Comment by GuilhemN** [comment]
Hi,
you'd like a way to add this wrapper to all your routes automatically, right?

This is quite a specific issue so I think the best would be to create a Describer on your side to do just that:
```php
<?php

use EXSyst\Component\Swagger as Swagger;
use Nelmio\ApiDocBundle\RouteDescriber\RouteDescriberInterface;
use Nelmio\ApiDocBundle\RouteDescribe\RouteDescriberTraitr;
use Symfony\Component\Routing\Route;

class ResponseWrapperDescriber implements RouteDescriberInterface
{
    use RouteDescriberTrait;

    public function describe(Swagger\Swagger $api, Route $route, \ReflectionMethod $reflectionMethod)
    {
        foreach ($this->getOperations($api, $route) as $operation) {
            foreach($operation->getResponses() as $response) {
                $fn = function () {
                     $data = $this->schema;
                     $this->schema = new Swagger\Schema();
                     $this->schema->setType('objet');
                     $this->schema->getProperties()
                             ->set('data', $data)
                             ->get('status')->setType('string');
                 };

                $fn->call($response);
            }
        }
    }
}

**Comment by lukepass** [comment]
Thanks for the answer! Is there a place where I can find more info about describers?

**Comment by GuilhemN** [comment]
It is quite low level so it isn't documented right now (we should focus on documenting most used swagger annotations first imo), but normally you won't have to use them much.

**Comment by ghtmh** [comment]
any updates to the describer topic?

**Comment by GuilhemN** [comment]
You may check the ones defined in the repository https://github.com/nelmio/NelmioApiDocBundle/tree/v3.5.0/Describer.
Once created, they must be registered as services with the tag `nelmio_api_doc.describer`.

**Comment by NicolasCharpentier** [comment]
For you people still on those old NelmioApiDoc versions, please not that implementations of `RouteDescriberInterface` (not `DescriberInterface`) must be tagged with `nelmio_api_doc.route_describer` (not `nelmio_api_doc.describer`)

**Comment by gorasu** [comment]
How to create a wrapper for the response in the latest versions of Nelmio?
{"name":"Jon"} -> {"data": {"name":"Jon"}, "status":"ok"}

I tried registering the service using the nelmio_api_doc.describer tag, but the response object it receives does not have the schema populated.
