### ISSUE TITLE
Support for Swagger 3?

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1488]
Hello, does this bundle support Swagger 3?
In the composer.lock it requires `"zircote/swagger-php": "^2.0.9"` and it seems to give errors when using new Swagger 3 properties.

Thanks!

**Comment by GuilhemN** [comment]
https://github.com/nelmio/NelmioApiDocBundle/issues/1443 is about it, it needs some attention but it's definitely doable

**Comment by mantis** [comment]
The work needed for Swagger 3 has been picked up by someine in the following PR : https://github.com/nelmio/NelmioApiDocBundle/pull/1623 - which is a continuation of the previous attempt I believe.

**Comment by GuilhemN** [comment]
#1623 will indeed bring OpenApi 3.0 support :) I'm closing this as it will be solved very soon!
