### ISSUE TITLE
Using @Model in examples field?

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1489]
Hello again!
Sorry for the massive question count but I am still learning this wonderful bundle!
Is it possible to use `@Model` in an example attribute? I tried this but it didn't work:

    /**
     * Returns the children nodes of a specified parent node.
     *
     * @Rest\Get("/{id}/children")
     * @SWG\Response(
     *     response=200,
     *     description="Parent node and list of children nodes",
     *     examples = {
     *         "pluto"={
     *             "status"="success",
     *             "data"={
     *                 "parent"=@Model(type=Node::class),
     *                 "nodes"={}
     *             },
     *             "code"=null,
     *             "message"=null
     *         }
     *     }
     * )
     * @SWG\Response(
     *     response=404,
     *     description="Parent node not found",
     * )
     * @SWG\Parameter(
     *     name="id",
     *     in="path",
     *     type="integer",
     *     description="Parent node ID"
     * )
     */
    public function childrenAction(Request $request, Node $node)
    {
    }

**Comment by GuilhemN** [comment]
It's not supported, what result would you have expected? The bundle replacing it by an example specific to the model?

**Comment by lukepass** [comment]
Uhm, I I would have expected an object model of the Node class. Actually you are right and it doesn't make a lot of sense! :)
