### ISSUE TITLE
Property collectionFormat multi bug

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1490]
Hello,
I encountered a minor bug using collection format. This is my action:

    /**
     * Creates a new product.
     *
     * @Rest\Post("/create")
     * @SWG\Response(
     *     response=200,
     *     description="Created product"
     * )
     * @SWG\Response(
     *     response=400,
     *     description="901 - Invalid input"
     * )
     * @SWG\Parameter(
     *     name="code",
     *     in="formData",
     *     type="string",
     *     required=true
     * )
     * @SWG\Parameter(
     *     name="image",
     *     in="formData",
     *     type="file"
     * )
     * @SWG\Parameter(
     *     name="machineries[]",
     *     in="formData",
     *     type="array",
     *     @SWG\Items(type="integer"),
     *     collectionFormat="multi",
     * )
     */
    public function createAction(Request $request)
    {
    }

This is the generated call:

`curl -X POST "http://mysite.local/app_dev.php/api/products/create" -H "accept: application/json" -H "Content-Type: multipart/form-data" -F "code=12345" -F "machineries[]="123","321""`

I would have expected the `machineries[]` parameter repeated 2 times instead of a single parameter with multiple values:

https://swagger.io/docs/specification/2-0/describing-parameters/#array-and-multi-value-parameters

Thanks.

**Comment by lukepass** [comment]
Hi @GuilhemN, did you have time to check the submitted bug? Thanks!

**Comment by GuilhemN** [comment]
This part is managed by [swagger-ui](https://github.com/swagger-api/swagger-ui), and I don't know its internals.
Have you tried posting a message on one of symfony's support channels ? (see https://symfony.com/support)

**Comment by GuilhemN** [comment]
Just in case, have you tried using type ``string`` instead of `int`?

**Comment by chrisguitarguy** [comment]
Closing this due to age and OpenAPI 2.X use.

For those that land here: https://swagger.io/docs/specification/describing-parameters/#query-parameters

The `explode` keyword is probably what you want in the parameter definition:

```php
use OpenApi\Annotations as OA;

/**
 * @OA\Parameter(
 *     in="query",
 *     name="example",
 *     schema=@OA\Schema(type="array", items=@OA\Items(type="integer")),
 *     explode=true,
 * )
 */
```
