### ISSUE TITLE
When I try @SWB\get, all method get displayed + Areas utilisation trouble

### ISSUE THREAD

**Issue by WMystral** [nelmio/NelmioApiDocBundle#1494]
Hello,

I'm getting an issue by trying to define an API with GET method like this : 
```
 /**
     * @SWG\Get(
     *     path="/liste_bioagresseurs_cultures_fixes_v1",
     *     @SWG\Parameter(
     *          name="body",
     *          in="body",
     *          required=true,
     *          @SWG\Schema(
     *              @SWG\Property(
     *                  property="name",
     *                  type="string",
     *                  maximum=64
     *              ),
     *              @SWG\Property(
     *                  property="description",
     *                  type="string"
     *              )
     *          )
     *     ), 
     *  
     *     @SWG\Response(
     *         response=200,
     *         description="OK"
     *     )
     * )
    */

```
But I'm getting a display like this  : 
![cc](https://user-images.githubusercontent.com/44498811/55709393-7dd66c80-59e8-11e9-91f7-d3be0e764707.PNG)

I tried to delete the xml file from api platform and nothing changed (saw it on this [issue ](https://github.com/nelmio/NelmioApiDocBundle/issues/1484))

Also I'mgetting troubles with using AREAS:
Here is the setting file.
```
`
#config/packages/nelmio_api_doc.yaml
nelmio_api_doc: 
    documentation:
        info:
        title: Vigicultures
        description: Outil de collecte d'observations agronomiques
        version: 1.0.0   
    areas: # to filter documented areas
        default:
            path_patterns:
             - ^/liste_api_v1 # Accepts routes under /api except /api/doc
        apiget:    
            path_patterns: 
                

                - ^/liste_bioagresseurs_cultures_fixes_v1
                - ^/liste_bioagresseurs_cultures_flottantes_v1
                - ^/liste_droits_v1
                - ^/liste_interventions_v1
                - ^/liste_parcelles_v1
                - ^/liste_sols_v1
                - ^/liste_stades_v1
                - ^/liste_types_interventions_v1
                - ^/liste_types_interventions_v2
                - ^/liste_variables_parcelles_cultures_v1
                - ^/liste_variables_reseaux_v2
                - ^/liste_varietes_v1
                - ^/liste_communes_v1
                - ^/liste_unites_v1
            
        apipost:
             path_patterns: 
                 - ^/ajout_obs_fixe_v1 # Accepts routes under / except /doc
                 - ^/ajout_obs_flot_v1
                 - ^/ajout_parcelles_v1
                 - ^/ajout_actions_v1
                 - ^/ajout_intrants_v1`
```
Got two URLs, apiget and apipost
When I'm getting to "http://....public/doc/apiget"
If I'm not setting manually in routes.yaml like this,  i'll also get the content of apiget in apipost... 
```
app.swagger_ui:
    path: /doc/{areas}
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui, area: apiget}

app.swagger:
    path: /doc/{areas}.json
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger, area: apiget}
```

If I put "default" I'll see it either way in the url "http://....public/doc/apiget" or "http://....public/doc/apipost" and going to "http://....public/doc/" will get me an error (Twig loader error like this :
![cc1](https://user-images.githubusercontent.com/44498811/55710119-2e913b80-59ea-11e9-8854-2acc0ffe3c17.PNG)

Hope I'll get some help, and that it's the right forum for this !

Thanks a lot in advance

**Comment by WMystral** [comment]
Tried this #1460, doesn't work...

**Comment by Alex-D** [comment]
Hey!

You just make a typo: `path: /doc/{areas}`=> `path: /doc/{area}` without the s.

**Comment by WMystral** [comment]
> Hey!
> 
> You just make a typo: `path: /doc/{areas}`=> `path: /doc/{area}` without the s.

Omg thans a lot !

**Comment by Alex-D** [comment]
I think it's better to add the tag for every method instead of moving this in config since it's not a single regex to catch all GET or POST.

**Comment by WMystral** [comment]
Can you show me an example I'm not sur about what you are trying to say, sorry

**Comment by Alex-D** [comment]
On each controller action, add:

```php
use Nelmio\ApiDocBundle\Annotation as ApiDoc;

/**
 * @ApiDoc\Areas({"apiget"})
 *
 * OR
 *
 * @ApiDoc\Areas({"apipost"})
 */
public function blah()
```

**Comment by WMystral** [comment]
ok i'll try this

**Comment by WMystral** [comment]
I tried with @Apidoc, and it says I didn't import the packages, and if I use SWG because I wrote this :+1: 

```
use Swagger\Annotations as SWG;
use Symfony\Component\Routing\Annotation\Route;
```

I got this error:

> annotation "@Swagger\Annotations\Areas" in method App\Controller\ApiGetController::liste_bioagresseurs_cultures_fixes_v1() does not exist

**Comment by Alex-D** [comment]
Please, read my code sample, the use is in it...

**Comment by WMystral** [comment]
Woops sorry ! but it kind of made the whole thing disappear actually, (I tried for one) so even the GET one I had on the tag disappered too.

**Comment by WMystral** [comment]
@Alex-D 
Actually it worked for one, and then i put the area for every get api, and it returned to its original state...

**Comment by Alex-D** [comment]
Be sure to make `operationId` value unique for each endpoint.

**Comment by WMystral** [comment]
@Alex-D something else worked in my route.yaml I add "methods; get" for every route ! Thanks a lot !
