### ISSUE TITLE
how to remove default request url

### ISSUE THREAD

**Issue by WMystral** [nelmio/NelmioApiDocBundle#1497]
Hello,

I'm getting trouble with request api url:

So here is my api url : 

https://api.vigicultures.fr/

And here an access to some datas:

https://api.vigicultures.fr/observations_fixes

I set up my nelmio_api_doc.yaml like this:

```
nelmio_api_doc:
    documentation:
        host:  api.vigicultures.fr
        basePath: /doc/
        schemes: [https,http]
        info:
            title: Documentation Vigicultures
            description: Outil de collecte d'observations agronomiques
            version: 1.0.0
        securityDefinitions:
            bearer:
                type: apiKey
                name: Authorization
                in: header
```
And I get this additional path to my request url

![cc3](https://user-images.githubusercontent.com/44498811/55863807-91fea300-5b7b-11e9-93a7-fd06d6d8fce7.PNG)

Which is the current path to my symfony application  (and will be removed for production mode) and for example with login_check from lexik I get this request url:

![cc4](https://user-images.githubusercontent.com/44498811/55864033-f91c5780-5b7b-11e9-9176-a8bae794269e.PNG)

Is there any settings I can add to remove this unwanted path on my api request ?

**Comment by GuilhemN** [comment]
Hi, you can use `path_patterns` to remove unwanted routes (see https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html).

By the way you probably don't want to use `basePath` in your config, this field is managed by the bundle and defining it in config may break things (I think I'll add a warning sometime soon)

**Comment by WMystral** [comment]
Ok so I should use the host_pattern right ? Shoud I settle it for every I areas I created ?

**Comment by GuilhemN** [comment]
Ok in fact I think I misunderstood your issue.
We don't provide a setting directly to do that but you may create your own describer to do that (and register it with a low priority):
```php
<?php

use Nelmio\ApiDocBundle\Describer\DescriberInterface;
use EXSyst\Component\Swagger\Swagger;

class RoutePrefixDescriber implements DescriberInterface
{
    public function describe(Swagger $api)
    {
        $paths = $api->getPaths();
        foreach ($paths as $path => $model) {
            $paths->remove($path);
            $paths->set(substr($path, 0, 30), $model);
        }
    }
}

**Comment by WMystral** [comment]
@GuilhemN I'm not sure how to use this, will I be able to test my api by using this ?

And where should I register this ? I'm sorry I'm kinda used to Laravel, so it's not the same structur nor the same syntax with .yaml and sutff
