### ISSUE TITLE
{areas}.json not working

### ISSUE THREAD

**Issue by WMystral** [nelmio/NelmioApiDocBundle#1500]
I'd like to have both possibility for urls for example:

api/doc/area AND api/doc/area.json

which worked fine whitout any areas declared.

So here is my routes.yml which I declared as the [symfony docs](https://symfony.com/doc/master/bundles/NelmioApiDocBundle/areas.html) did (except that my access to the documentation require /doc and not /api/doc

![cearea](https://user-images.githubusercontent.com/44498811/55953892-9bf8d280-5c5d-11e9-961c-8ac15d8cbb21.PNG)

And here is my nelmio_api_doc:

```
nelmio_api_doc:
    documentation:
        # host: api.example.fr
        schemes: [https,http]
        info:
            title: Documentation 
            description: awesome app
            version: 1.0.0
        securityDefinitions:
            bearer:
                type: apiKey
                name: Authorization
                in: header
        paths:
          /login_check:...
         
    areas: # to filter documented areas
        default:
            path_patterns:
             - ^/liste_api_v1 
            
        apiget:
            documentation:
                description: "Requêtes get"
            path_patterns: 
                
                - ^/liste_bioagresseurs_cultures_fixes_v1
                - ^/liste_bioagresseurs_cultures_flottantes_v1
          ......
            
        apipost:
             path_patterns: 
                 - ^/ajout_obs_fixe_v1 # Accepts routes under / except /doc
                .....
              
```

The regular path doc/apipost or any areas work fines but when I try to access to the {area}.json I get this error:

![cc10](https://user-images.githubusercontent.com/44498811/55954231-77e9c100-5c5e-11e9-93b4-ef00bcd04fe4.PNG)

**Comment by GuilhemN** [comment]
I think you should reverse the order of definition of your route, since the first one is checked first, it is always the one used

**Comment by WMystral** [comment]
I reversed like this
![cc9](https://user-images.githubusercontent.com/44498811/55957715-47f2eb80-5c67-11e9-97a4-c995f47ed666.PNG)

And another error occured:

![cc11](https://user-images.githubusercontent.com/44498811/55957742-5c36e880-5c67-11e9-8267-4953fe57f9d0.PNG)
