### ISSUE TITLE
Support anyOf, oneOf for entity mappings

### ISSUE THREAD

**Issue by genetus** [nelmio/NelmioApiDocBundle#1503]
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

I build sync of thwo servers. They commnucate with packets, that describe service information and content of entities. Packet's headers are the same, but field "field" has different content for all entities.
How can I add description of two or more different object to one field of heder? In swagger documentation it solve with tags anyOf & oneOf, but bundle support only allOf (that we use to describe pagination).

**Comment by GuilhemN** [comment]
The link you refer to is about Swagger 3.0. This bundle is currently based on Swagger 2.0 (see https://github.com/nelmio/NelmioApiDocBundle/issues/1443). I don't think we can support these fields before we upgrade unfortunately.

**Comment by olix21** [comment]
@GuilhemN As the bundle now supports OpenApi, can we reopen this issue?

**Comment by GuilhemN** [comment]
Well they are now supported so why reopening this issue?
https://github.com/zircote/swagger-php/blob/320ae56fa49f7a305c31e6e75786ce264711073e/src/Annotations/Schema.php#L263-L284

**Comment by MarcelMC** [comment]
Case not working. Api doc bundle does not generate schemas.

* @OA\RequestBody(
     *
     *          @OA\JsonContent(oneOf={
     *              @ApiDoc\Model(type=TypeOne::class, groups={"create"}),
     *              @ApiDoc\Model(type=TypeTwo::class, groups={"create"})
     *          })
     *
     * )

**Comment by cprn** [comment]
Schemas are generated okay but examples for these keywords aren't (at least for `anyOf`, I'll check `oneOf` in few hours when I start work). My proposal for `anyOf` example is to generate one with all params from all children of `anyOf` combined. Alternatively an example for the first child of `anyOf` could be generated (although it seems more suitable to `oneOf`). If we're feeling fancy there could be several possible strategies in config.
