### ISSUE TITLE
Documentation lacks

### ISSUE THREAD

**Issue by archi-tektur** [nelmio/NelmioApiDocBundle#1507]
Hey, I don't want to be silly, but actual documentation sucks a lot. It DOES NOT provides any details, only few most basic examples. Please, update it to make it more detailed (all options shown and described, etc.). It took me about 15 minutes to search how to group endpoints, no documentation mentions @SWG\Tag(name="foo") option for example. It should take at most 2 minutes. Even docs for FOSUserBundle cooperation does not exist. It's miracle package: as much as you will find by trial-and-error method, as much you can use. Fix it, because this bundle can be one of the best API doc soft over PHP world, but with this docs it cannot exist.

**Comment by GuilhemN** [comment]
The annotations come from zircote/swagger-php this is where most of the information about them is.

Anyway this is open source so please submit a PR if it bothers you, there are lacks in the docs because people complain but do nothing about it.

**Comment by archi-tektur** [comment]
Not agreed. For example - the section about configuring your bundle (`nelmio_api_doc.yaml` in` config/`) - it's totally left for nothing. Only most basic examples are described (NO, SYMFONY FLEX WILL NOT CONFIG IT PERFECTLY). 

It's silly that you ask people to documentate code you write. Seriously - a lots of people needs solid docs for configuring your bundle. If documentation is on Swagger page, redirect users to them! Come on, get responsibility for code you write and publish, and documentate it well or don't publish it.

Swagger page mostly shows only YAML configuration, not the annotation way (better for maintenance).

**Comment by GuilhemN** [comment]
The point of this bundle is collaboration, not me offering free work.
If some part of it doesn't please you, submit a PR or pay me for the time I'll spend on it, I've got more urgent occupations.

**Comment by dbu** [comment]
@archi-tektur please check your tone. you are talking to the person who invests a lot of his free time into this bundle. if you NEED something, then pay something - as @GuilhemN says he would be open for payed work to improve specific things of the bundle. open source does not mean you get everything for free.
if you are not willing to do that and don't want to invest the time yourself, then by all means use a better option if you have one.
