### ISSUE TITLE
How to hide big blank white bar in the header?

### ISSUE THREAD

**Issue by tinayihe** [nelmio/NelmioApiDocBundle#1508]
We are using NelmioApiDocBundle for generating API Documentation of a symfony 4.2 application.

It works but there is always a big blank white bar (scheme-container) in the header.

I have tried to use different versions, 3.3.0, 3.3.1, 3.4.0. But it doesn't work.

I'd like to know how to hide this blank bar. Thanks in advance :smiley: 

![screenshot-api-v2 offer-api aa test-2019 04 23-11-31-34](https://user-images.githubusercontent.com/12396052/56570617-91bec880-65bb-11e9-8926-c1bf628295c2.png)

**Comment by betd-jfranclin** [comment]
Hello, what have you tried to do so far ? Override yml template etc ?

**Comment by chrisguitarguy** [comment]
Pretty sure that white bar usually contains a dropdown of servers as well as an `Authorize` button. So probably putting `servers` and `security` under the `documentation` as well as `securitySchemes` under `documentation.components` would be a start.

As far as hiding it entirely, override the template and use CSS to hide it. https://symfony.com/bundles/NelmioApiDocBundle/current/customization.html
