### ISSUE TITLE
Call with choice type value

### ISSUE THREAD

**Issue by Chrysweel** [nelmio/NelmioApiDocBundle#1511]
I have a form with a property with choice type

```
public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('types', ChoiceType::class, [
                'multiple' => true,
                'choices' => [
                    'option1' => 'option1',
                    'option2' => 'option2'
                ],
                'required' => false
            ])
    }
```

Now I want to be able send and include from Nelmio`s Dashboard the values, so I have:

```/**
     * Register user as trainer
     *
     * @Route("/trainers", name="trainers_register_as_trainers")
     * @Method({"POST"})
     * @Operation(
     *     tags={"Trainers"},
     *     summary="Register user as trainer",
     *     @SWG\Parameter(
     *         name="types[0]",
     *         in="formData",
     *         description="Admitted values: option1 or option2",
     *         required=false,
     *         type="string"
     *     ),
     *     @SWG\Parameter(
     *         name="types[1]",
     *         in="formData",
     *         description="Admitted values: option1 or option2",
     *         required=false,
     *         type="string"
     *     ),
``` 

But If I tomorrow include a new field in my formType with option3, I need update the annotation swg\parameter and include option3 to can send option3 from dashboard

Are there other solution to can include new fields from dashboard nelmio ?

**Comment by chrisguitarguy** [comment]
I want to say that choice types [already pull out their choices](https://github.com/nelmio/NelmioApiDocBundle/blob/2295f68b89138e04c8b9685d6161c0a976c8288d/ModelDescriber/FormModelDescriber.php#L181-L196) and set up `enum` values in OpenAPI.

Maybe that wasn't supported at the time, though.
