### ISSUE TITLE
Calling var_dump or similar anywhere in code cause "failed to fetch error"

### ISSUE THREAD

**Issue by florianajir** [nelmio/NelmioApiDocBundle#1516]
tried with:
+ `var_dump`
+ `var_export`
+ `print_r`
+ `echo`

Note: This is happening only from the browser api doc sandbox, not with rest clients

**Comment by GuilhemN** [comment]
What version of the bundle are you using?

**Comment by florianajir** [comment]
currently installed v3.4.0

**Comment by GuilhemN** [comment]
Swagger-ui is a third-party library so it's harder for me to debug it.

Does https://github.com/nelmio/NelmioApiDocBundle/pull/1518 fix your issue by any luck?
In case not, folks on symfony's slack would likely know swagger-ui better than I do, sending a message there might help.
Or if you could provide a reproducer but i'm not sure i'll have enough time to investigate soon unfortunately

**Comment by chrisguitarguy** [comment]
Closing due to age, but I'd expect any extra output to break JSON stuff.
