### ISSUE TITLE
Internet Explorer 11 fails to load apidocs due to arrow functions

### ISSUE THREAD

**Issue by chewett** [nelmio/NelmioApiDocBundle#1517]
We have upgraded from version 2 to version 3.4.0 and while it brings a lot of useful features it doesn't appear to work in Internet Explorer 11.

When loading the page we get the error:
`
SCRIPT1002: Syntax error
init-swagger-ui.js (8,20)
`

Looking into it, this is because the named file is using arrow functions which IE11 doesn't support.

It looks like it was changed in this commit to add the arrow functions: https://github.com/nelmio/NelmioApiDocBundle/commit/39eda091c1e73d8a64c33695395f11ff633db598#diff-a90704cf30b79383ba0635aff756b26f

Is this library expected to run in IE11?

Thanks
Chris

**Comment by chewett** [comment]
Digging into it, it appears that that function is the only thing stopping IE11 working. I can create a PR if you wish?

**Comment by GuilhemN** [comment]
This files are imported from [swagger-ui](https://github.com/swagger-api/swagger-ui), any manual change will be overidden during the next update.
Apparently this was fixed in their lib and released in April (see https://github.com/swagger-api/swagger-ui/pull/3264/commits/ab960e8c4571ea67dc1ae0cfd1006e821d7cb162) so updating the files here should be enough :)

**Comment by GuilhemN** [comment]
Could you check if https://github.com/nelmio/NelmioApiDocBundle/pull/1518 fixes your issue please?

**Comment by chewett** [comment]
Doesnt look like it does.

The problematic file is init-swagger-ui.js which doesn't appear to be included in your commit.

**Comment by chewett** [comment]
Also it doesnt look like the commit your referenced has anything to do with this file `init-swagger-ui.js`

**Comment by chewett** [comment]
Are you able to help with this?

**Comment by GuilhemN** [comment]
Indeed I misunderstood what was your issue, arrow functions are used in Api-Platform (see https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/public/init-swagger-ui.js) but it's totally acceptable for me to move back to the usual syntax.

Would you like to submit a PR?

**Comment by chewett** [comment]
Can you re-open this please as #1518 doesnt resolve this.

I will look at making a PR to api-platform/core later this week.

**Comment by GuilhemN** [comment]
Sure, sorry I didn't close it on purpose

**Comment by chewett** [comment]
Sorry for the delay, PR has been created: https://github.com/api-platform/core/pull/2899

**Comment by chewett** [comment]
That has now been merged in, does this library now need to pull in the latest changes?

**Comment by kverfaille** [comment]
Any updates/schedule on this?

**Comment by GuilhemN** [comment]
Sorry I forgot this issue for a while... This is now in the v3 branch of the NelmioApiDocBundle (https://github.com/nelmio/NelmioApiDocBundle/commit/5e8f7290e86ef83e4ebee94fa33f57ab120b6168) and will be bundled with the next release.
