### ISSUE TITLE
The "nelmio_api_doc.form.documentation_extension" service is private, checking for its existence is deprecated since Symfony 3.2 and will fail in 4.0

### ISSUE THREAD

**Issue by seyfer** [nelmio/NelmioApiDocBundle#1526]
> [2019-06-13 17:32:30] php.INFO: User Deprecated: The "nelmio_api_doc.form.documentation_extension" service is private, checking for its existence is deprecated since Symfony 3.2 and will fail in 4.0. {"exception":"[object] (ErrorException(code: 0): User Deprecated: The \"nelmio_api_doc.form.documentation_extension\" service is private, checking for its existence is deprecated since Symfony 3.2 and will fail in 4.0. at vendor/symfony/dependency-injection/Container.php:224)

could this issue be fixed, please?
seen in Symfony v3.4

**Comment by GuilhemN** [comment]
Could you provide the rest of the stacktrace please?

The issue is likely an outdated library in your dependencies, we don't check for the existence of this service, symfony may do though.
Could you try to update your dependencies please?
