### ISSUE TITLE
Doctrine2 datetime_immutable not appending to model

### ISSUE THREAD

**Issue by Sonny812** [nelmio/NelmioApiDocBundle#1527]
Properties that having annotation `@ORM\Column(type="datetime_immutable")` are not appending to model.  Properties with `@ORM\Column(type="datetime")` are working fine.

**Comment by GuilhemN** [comment]
Are you using the symfony serializer (and version 3.x of the bundle)?

If so could you check whether [this line](https://github.com/symfony/doctrine-bridge/blob/master/PropertyInfo/DoctrineExtractor.php#L140) is executed? And [this one](https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/ObjectModelDescriber.php#L109)?

It should be supported through the DoctrineBridge but we have no tests here ensuring its support as its managed by the DoctrineBridge.

**Comment by Sonny812** [comment]
> Are you using the symfony serializer (and version 3.x of the bundle)?

I am using jms/serializer-bundle 3.3 and nelmio/api-doc-bundle 3.4.

> If so could you check whether [this line](https://github.com/symfony/doctrine-bridge/blob/master/PropertyInfo/DoctrineExtractor.php#L140) is executed? And [this one](https://github.com/nelmio/NelmioApiDocBundle/blob/master/ModelDescriber/ObjectModelDescriber.php#L109)?

No, this lines never was executed during request handling.

I tried to debug and found that the field was removed from the model at [this](https://github.com/nelmio/NelmioApiDocBundle/blob/v3.4.0/ModelDescriber/JMSModelDescriber.php#L118) line.

**Comment by GuilhemN** [comment]
Ok, so in face the issue is that https://github.com/schmittjoh/serializer lacks support of this field type.
I think you should open an issue on their repository to see if they're willing to add it.
