### ISSUE TITLE
Endpoint not relative to base url

### ISSUE THREAD

**Issue by jasonetwork** [nelmio/NelmioApiDocBundle#1529]
![api_ss](https://user-images.githubusercontent.com/12465679/60401329-d8411e00-9b3c-11e9-8740-9246d7d49077.png)

So, here's an issue I am encountering. I'm in the process of developing an API, but I'm having issues with the base url and endpoint "path". The endpoint is not relative to the base url. In my example above, since the base url contains _/v1/partner_, then the endpoint should simply be _/contacts_ and not _/v1/partner/contacts_. I'm fully aware that I could simply remove _/v1/partner_ from the base url and it would be technically correct, but frankly, this is ugly and not visually appealing for end users. I don't want each of my endpoints to display this prefix when it's already included in the base url. It's absolutely unnecessary for each endpoint to be prefixed with /v1/partner when it could simply be stated in the base url. 

I've tried messing with the configuration, but have had no luck. It appears to me that the "host"  and "basePath" settings in nelmio_api_doc.yaml are just for display purposes and serves no other purpose than to display the base url in the documentation. Wouldn't it make sense to be able to define a "basePath" which would then allow your endpoints to be relative to this path?

So, what am I missing? Is there actually any way to allow my base url to include _/v1/partner_ and my endpoint to simply be _/contacts_?

**Comment by GuilhemN** [comment]
`basePath` is an option the bundle uses when symfony's root is not `/` but it doesn't support setting it manually for now.

Allowing that would require a post processing describer removing the base path from all URLs imo, PR welcome if you're willing to implement that :)
