### ISSUE TITLE
Question regarding custom JMS types

### ISSUE THREAD

**Issue by KDederichs** [nelmio/NelmioApiDocBundle#1531]
Hey I have a question regarding custom JMS Serializer types.
I'm using the serialiser for my requests and have a custom type that takes the ID of an object managed by doctrine and fetches the corresponding entity from the database.
The problem now is that it won't show up in the examples and without type in the model of the swagger UI.

Is there a way to register custom types somehow with the Api Doc Bundle so it treats it as  "string" for example when it comes across a certain custom type?

**Comment by GuilhemN** [comment]
https://github.com/nelmio/NelmioApiDocBundle/pull/1495 allowed that by creating your own model describers, it hasn't been released yet though.

**Comment by KDederichs** [comment]
Ok, thanks for letting me know, I'll keep an eye out for that release then!
