### ISSUE TITLE
SwaggerDocblockConvertCommand: Cannot allocate memory

### ISSUE THREAD

**Issue by PhilippSchreiber** [nelmio/NelmioApiDocBundle#1535]
I try to migrate from 2.x to 3 and when running the command it cannot allocate memory. My vm has 8G of memory and memory limit of PHP is -1. Is it possible to pass only a few directories instead of the whole project?

```$ php bin/console api:doc:convert

mmap() failed: [12] Cannot allocate memory

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 7908364288) (tried to allocate 12288 bytes) in /var/www/vendor/symfony/symfony/src/Symfony/Component/Intl/Data/Bundle/Reader/BundleEntryReader.php on line 112

mmap() failed: [12] Cannot allocate memory
PHP Fatal error:  Out of memory (allocated 7908364288) (tried to allocate 32768 bytes) in /var/www/vendor/symfony/symfony/src/Symfony/Component/Debug/Exception/OutOfMemoryException.php on line 1```

**Comment by malc0mn** [comment]
Is there any more info concerning this issue: a specific version that does or does not have this problem? Or a workaround perhaps?
Running into this with a _fairly_ old project with a _fairly_ old `nelmio/api-doc-bundle` of `2.12.0`, even wen attempting to dump a separate section.
There **are** a lot of API calls in this project...

**Comment by chrisguitarguy** [comment]
I'm not sure that this bundle can do anything about this. Large projects with many API endpoints and components are going to eat a lot of memory generating docs.
