### ISSUE TITLE
Schema not respecting SubscribingHandlerInterface

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1536]
Hello, I have the following annotation:

```
    /**
     * Returns the list of news filtered by type.
     *
     * @SWG\Response(
     *     response=200,
     *     description="The news list",
     *     @SWG\Schema(
     *         type="object", @SWG\Property(property="news", type="array", @SWG\Items(ref=@Model(type=News::class)))
     *     )
     * )
     */
```

My `News` class contains a property of type `Media` (it's the Sonata Media entity but that's not important). My `Media` class has a custom Subscriber:

```
<?php

namespace AppBundle\Serializer;

use AppBundle\Entity\Media;
use JMS\Serializer\Context;
use JMS\Serializer\GraphNavigator;
use JMS\Serializer\Handler\SubscribingHandlerInterface;
use JMS\Serializer\JsonSerializationVisitor;
use Sonata\MediaBundle\Provider\FileProvider;
use Sonata\MediaBundle\Provider\ImageProvider;
use Sonata\MediaBundle\Provider\MediaProviderInterface;
use Sonata\MediaBundle\Provider\Pool;

class MediaHandler implements SubscribingHandlerInterface
{
    /**
     * @var Pool
     */
    private $mediaPool;

    public function __construct(Pool $mediaPool)
    {
        $this->mediaPool = $mediaPool;
    }

    public static function getSubscribingMethods()
    {
        return array(
            array(
                'direction' => GraphNavigator::DIRECTION_SERIALIZATION,
                'format'    => 'json',
                'type'      => Media::class,
                'method'    => 'serializeMediaToJson',
            ),
        );
    }

    public function serializeMediaToJson(JsonSerializationVisitor $visitor, Media $media, array $type, Context $context)
    {
        // custom logic, it simply returns an array with strings
    }
}
```

The serializer is working fine (the response contains the custom serialization of Media when executing the call) but the preview in the API dashboard it's not respecting it, why?

Thanks.

**Comment by GuilhemN** [comment]
The bundle is not able to detect what custom subscribers do so it ignores them.

I think the best solution would be that you document `Media` manually in config and then link to this definition in `News` (using a `ref`).

**Comment by lukepass** [comment]
Hello, the problem is that my Media class inherits from another Media class which is in another bundle. Is it still doable? Thanks!

**Comment by GuilhemN** [comment]
My suggestion was documenting your Media class manually so its parent would have no impact.
Have a look at https://symfony.com/doc/current/bundles/NelmioApiDocBundle/faq.html#sharing-parameter-configuration.

**Comment by chrisguitarguy** [comment]
Closing as @GuilhemN's solution is the right one here.
