### ISSUE TITLE
Command line availability

### ISSUE THREAD

**Issue by mantis** [nelmio/NelmioApiDocBundle#1537]
Hello,

Are there any plans to have a command line option to dump out a swagger.json documentation file ?

This would basically be similar to DocumentationController, with $spec, passed through json_encode( JSON_PRETTY_PRINT ); 

(or is it preferred to download the file from the webui via a different method?)

Thanks

**Comment by GuilhemN** [comment]
This hasn't be considered but it would be definitely be great to have.

Would you like to submit a PR?

**Comment by mantis** [comment]
I've had a stab at a sample command with #1540

**Comment by GuilhemN** [comment]
Fixed in #1540 :)
