### ISSUE TITLE
Problem with setting up areas

### ISSUE THREAD

**Issue by gregorstuber** [nelmio/NelmioApiDocBundle#1538]
I'm trying to create different docs using areas. I did the config like it is described here https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html and it worked, I can see the new routes. But I can't find any documentation how I can add functions/routes to an area. Do I need to specify this in annotations above the functions?

**Comment by GuilhemN** [comment]
We have an annotation that is not documented yet, see https://github.com/nelmio/NelmioApiDocBundle/pull/1460.

PR welcome by the way if you'd like to complete our docs :)
