### ISSUE TITLE
@QueryParam annotations not inherited

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1550]
I'm trying to avoid repeating the FOSRest `@QueryParam` annotations that are identical for the `searchAction()` methods across many of my controllers. I tried inheriting from an abstract baseclass. The parameters I expected from annotations on the baseclass method failed to appear in the inherited controller action's API documentation. 

i.e. a baseclass like so:

    abstract class SearchableController 
        extends AbstractFOSRestController 
        implements ClassResourceInterface
    {
        /**
         * @QueryParam(name="start", ...)
         */
        abstract public function searchAction(ParamFetcherInterface $params);
    }

i.e. a controller like so:

    class FooController extends SearchableControler 
    {
        /**
         * Search Foos.
         * @REST\Get("/api/foos")
         * {@inheritDoc}
         */
        public function searchAction(ParamFetcherInterface $params)
        {
            // ...
        }
    }

The resulting documentation for GET /api/foos shows no parameters. I expected to see the details for the `start` query parameter. Am I wrong to expect this?

**Comment by pdugas** [comment]
I did some more digging and it appears Doctrine's AnnotationReader doesn't deal with {@inheritDoc} at all so my expectation appears to be incorrect. I wonder if this project would be open to extending AnnotationReader to add supported for it.

**Comment by pdugas** [comment]
Something like so in RouteDescriber/FosRestDescriber.php

    private function _getMethodAnnotations(\ReflectionMethod $reflectionMethod): array
    {
        $annotations = $this->annotationReader->getMethodAnnotations($reflectionMethod);

        $parent = $reflectionMethod->getDeclaringClass()->getParentClass();
        if (FALSE !== $parent && $parent->hasMethod($reflectionMethod->name)) {
            $annotations = array_merge(
                $annotations, 
                $this->_getMethodAnnotations($parent->getMethod($reflectionMethod->name))
            );
        }

        return $annotations;
    }

    public function describe(Swagger $api, Route $route, \ReflectionMethod $reflectionMethod)
    {
        //$annotations = $this->annotationReader->getMethodAnnotations($reflectionMethod);
        $annotations = $this->_getMethodAnnotations($reflectionMethod);
        ...

**Comment by GuilhemN** [comment]
I compared our code to FOS rest's and it seems we're using the same logic (see https://github.com/FriendsOfSymfony/FOSRestBundle/blob/master/Request/ParamReader.php#L58 and https://github.com/nelmio/NelmioApiDocBundle/blob/master/RouteDescriber/FosRestDescriber.php#L35).
Are you sure your `@QueryParam` is actually inherited ? According to [this](https://stackoverflow.com/questions/30425978/symfony2-annotation-inheritance) it shouldn't be.

If you really want to inherit annotations, I think you should decorate the annotation reader in your repository. I don't think this should be included in this repository, we're just depending on doctrine/annotations and this kind of support should be in it if they were willing to support it.

**Comment by pdugas** [comment]
You are correct. The annotations are not inherited. I expected they would be before I delved deeper into the code and found my expectation to be wrong. Sorry I didn't phrase that very clearly.

I've no argument against your position. Thanks for the consideration.

**Comment by nelson6e65** [comment]
`@OA\Tag` is also not inherited from base controller.
