### ISSUE TITLE
SwaggerUiController error on constructor

### ISSUE THREAD

**Issue by timotheemoulin** [nelmio/NelmioApiDocBundle#1554]
Dear all,

I'm facing an issue when trying to install NelmioApiDocBundle v3 on my Symfony4 application (with FOSRestBundle).

Here is what I get right after the install with composer.

> Argument 2 passed to Nelmio\ApiDocBundle\Controller\SwaggerUiController::__construct() must be an instance of Twig_Environment

Here is the full list of installed packages.
[composer-show.txt](https://github.com/nelmio/NelmioApiDocBundle/files/3848425/composer-show.txt)

Any thought about what's going on?

Cheers,
Timothée

**Comment by GasparMDQ** [comment]
I've the same problem and it seems that on symfony/twig-bundle 4.4.x, they allow for twig 3.x to be installed.
To prevent this, you should restrict your twig version to:
        "twig/twig": "^1.41|^2.10"
I'm not sure is this should be added to the current 3.x branch on NelmioApiDocBundle, or they should just update the type on the constructor of Nelmio\ApiDocBundle\Controller\SwaggerUiController
