### ISSUE TITLE
Upgrade to Symfony 4.4 causes - The "controller_name_converter" service is deprecated

### ISSUE THREAD

**Issue by treadmillian** [nelmio/NelmioApiDocBundle#1561]
`1x: The "controller_name_converter" service is deprecated since Symfony 4.3. It is being referenced by the "nelmio_api_doc.controller_reflector" service.
        1x in JsonControllerTest::setUp from App\Tests\Controller\Api\V1`

**Comment by fabianoroberto** [comment]
There is already a PR #1557

**Comment by cobyl** [comment]
After fix that symfony 5 will be possible?

**Comment by maxhelias** [comment]
@cobyl The owners will do the necessary when their free time will allow them. In the meantime be patient.
You can also make contributions 😉

**Comment by GuilhemN** [comment]
Fixed in #1557 :)
