### ISSUE TITLE
Will there be support Symfony 5.0?

### ISSUE THREAD

**Issue by akaddev** [nelmio/NelmioApiDocBundle#1563]
```
"require": {
        "php": "^7.0",
        "symfony/framework-bundle": "^3.4|^4.0",
        "symfony/options-resolver": "^3.4.4|^4.0",
        "symfony/property-info": "^3.4|^4.0",
        "exsyst/swagger": "^0.4.1",
        "zircote/swagger-php": "^2.0.9",
        "phpdocumentor/reflection-docblock": "^3.1|^4.0"
    }

**Comment by maxhelias** [comment]
See #1564 
There is still work todo, some help would be welcome :)

**Comment by fma-technologies** [comment]
> See #1564
> There is still work todo, some help would be welcome :)

What can we do to help? :)

**Comment by maxhelias** [comment]
@fma-technologies On the bundle itself nothing, bug FOSRestBundle is not compatible Sf5 yet

**Comment by ssaki** [comment]
@maxhelias would you then merge (and tag) the Sf 5 compatibility fixes? FOSRest is not a hard dependency as the bundle can be used without it. Oris there anything left that you need help with?

**Comment by maxhelias** [comment]
@ssaki I am not allowed to do if you look at my status, I am only a "Contributor"

**Comment by maxhelias** [comment]
Please see #1564 I added information

**Comment by gustawdaniel** [comment]
Now there is error

```
$ composer require nelmio/api-doc-bundle
Using version ^3.5 for nelmio/api-doc-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "5.0.*"
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for nelmio/api-doc-bundle ^3.5 -> satisfiable by nelmio/api-doc-bundle[v3.5.0].
    - nelmio/api-doc-bundle v3.5.0 requires symfony/framework-bundle ^3.4|^4.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

On page

https://packagist.org/packages/nelmio/api-doc-bundle

We can see that version `v3.5.0` was released `2019-11-21` - one day before this issue.

Pull request https://github.com/nelmio/NelmioApiDocBundle/pull/1564 was merged `2019-12-04`
so to fix anyone need to install from master branch from github, no from `packagist` 

You need to add keys

```
    "minimum-stability": "dev",
    "prefer-stable": true
```

And execute

```
composer require nelmio/api-doc-bundle:dev-master
```

Sources

https://stackoverflow.com/questions/19916183/how-do-i-get-composer-to-download-the-latest-commit-in-the-master-branch-from-gi
https://github.com/phingofficial/phing/issues/799
https://igor.io/2013/02/07/composer-stability-flags.html
https://symfonycasts.com/screencast/symfony2-ep1/composer

**Comment by maxhelias** [comment]
So there's no error. 3.5 isn't compatible with Symfony 5.0. You just need patience until the next release.

BTW, be carefull with the `"minimum-stability": "dev"`, because he's going to get all the dev-masters from all your dependencies. Juste the composer require on dev-master for your dependency is enough

**Comment by ThibaultVlacich** [comment]
When will a new version be released?

**Comment by AnthonyGWeb** [comment]
I hope soon :)

**Comment by lzomedia** [comment]
me to :))

**Comment by cyanid** [comment]
Any updates? I really want to upgrade my project to Symfony5 but is a showstopper for it.

**Comment by lzomedia** [comment]
@ cyanid I'm using the dev-master and it's working for now for me

**Comment by isrenato** [comment]
When will a new (stable) version be released for Symfony 5.0?

**Comment by rvanlaak** [comment]
> So there's no error. 3.5 isn't compatible with Symfony 5.0. You just need patience until the next release.
> BTW, be carefull with the "minimum-stability": "dev", because he's going to get all the dev-masters from all your dependencies. Juste the composer require on dev-master for your dependency is enough

@maxhelias this is not the case, [as `minimum-stability` is a root-only property](https://getcomposer.org/doc/04-schema.md#minimum-stability). This means it only applies to your own composer.json.

We also are running `dev-master` on Sf 5.0.4 without any problems.

**Comment by gnutix** [comment]
Release `^3.6` works for me! Thanks a lot.

**Comment by qanastek** [comment]
Downgrade to `3.6` works for me too. I used `composer require nelmio/api-doc-bundle:3.6` to doing it.

**Comment by isaac410** [comment]
don't work to me with on versión 3.6, when it will be compatible with symfony 5?
