### ISSUE TITLE
Call to a member function push() on null

### ISSUE THREAD

**Issue by smuralidharan** [nelmio/NelmioApiDocBundle#1567]
While Using Model, I am getting "Call to a member function push() on null" issue.,

My Code :
@SWG\Items(ref=@Model(type=Account::class))

**Comment by MrMitch** [comment]
@smuralidharan did you find the cause of your problem ? how did you solve this issue ?

**Comment by iskyd** [comment]
Same problem here.

**Comment by iskyd** [comment]
For me the problem was the version of jms serializer. I have jms serializer < 2.0 so I had to downgrade also nelmio/api-doc-bundle to 2.13.4.

**Comment by rafaelpires815** [comment]
I had the same issue, but I still wanted to use nelmio _^3.0_, so I fixed by upgrading _jms/serializer_ and _jms/serializer-bundle_ to _^2.0_
