### ISSUE TITLE
SWG annotation in model public methods 

### ISSUE THREAD

**Issue by versh23** [nelmio/NelmioApiDocBundle#1568]
i have a code

```
     * @return File[]|Collection
     * @SWG\Property(
     *         type="array",
     *         @SWG\Items(ref=@Model(type=File::class, groups={"main", "documents"}))
     *     )
     * @Groups({"main"})
     */
    public function getActualFiles(): Collection
    {
        return $this->getFilesByStatus(File::STATUS_ACTIVE);
    }
```

get an error 

`Property App\Entity\Document\Document::$actualFiles defines more than one type. You can specify the one that should be documented using `@SWG\Property(type="")`.`

Can i use SWG\Property without real property in class ?

**Comment by GuilhemN** [comment]
Sorry for the late answer...
Unfortunately no, `@SWG\Property` is only supported on properties.

This may not be ideal but you may however use a `@Schema` at the class level:
```
/**
 * @SWG\Schema(
 *   @SWG\Property(
 *         name="actual_files",
 *         type="array",
 *         @SWG\Items(ref=@Model(type=File::class, groups={"main", "documents"}))
 *     )
 * )
 */
class Entity {
    // ...
}
