### ISSUE TITLE
Set version dynamically

### ISSUE THREAD

**Issue by smuralidharan** [nelmio/NelmioApiDocBundle#1569]
I like to set the version of nelmio dynamically like below

nelmio_api_doc:
    documentation:
        info:
            title: API
            description: API Documentation
            version: "@=container.hasParameter('some_param') ? parameter('some_param') : 'default_value'"

But it doesn't output the version , instead prints it as a string. Please help

**Comment by GuilhemN** [comment]
You could do that by creating a describer ans setting the version field in it (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/Describer/DefaultDescriber.php for an example)

**Comment by demroos** [comment]
> You could do that by creating a describer and setting the version field in it (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/Describer/DefaultDescriber.php for an example)

Thanks GuilhemN)))
It helped me)

**Comment by GuilhemN** [comment]
I'm closing this then :)
