### ISSUE TITLE
Describe entity to use as @Model

### ISSUE THREAD

**Issue by timotheemoulin** [nelmio/NelmioApiDocBundle#1572]
Hello there,

I would like to use the same model for a few endpoints. I thought I could "simply" define the my Doctrine entity as a model, but it doesn't work that way.

Can someone point me in the right direction?

Here is my Swagger route documentation.
```
     * @SWG\Response(
     *     response=200,
     *     description="Returns a single group.",
     *     @SWG\Schema(
     *         @SWG\Property(property="id", type="string"),
     *         @SWG\Property(property="name", type="string"),
     *         @SWG\Property(property="points", type="array", @SWG\Items(ref=@Model(type="PointOfSale::class"))),
     *     )
     * )
```

Here, my endpoint returns an array of **PointOfSale** in the property **points** so instead of redefining every field, I would like to reuse the same model on multiple endpoints.

**Comment by MichaelKubovic** [comment]
Nothing prevents you from using the `ref=@Model(...)` for multiple endpoints.

**Comment by timotheemoulin** [comment]
Hello @MichaelKubovic, sorry if I wasn't clear enough, but that was not my question.

Can you point me to the doc where it's explained how to describe an entity (or any other class) to use it as a `@Model` ?

**Comment by MichaelKubovic** [comment]
I think that `@Model` is not meant to be used on entities, but rather used inside of Swagger annotations when you need to reference some entity. Together with other options, like serialization groups, you then get resulting models described in docs.

**Comment by MichaelKubovic** [comment]
Anyway, the annotation you gave above looks good to me. Can you check what model describers do you have available? They are tagged as `nelmio_api_doc.model_describer`.  I believe that the built-in `ObjectModelDescriber` should be able to describe your class.

**Comment by timotheemoulin** [comment]
I do have 2 describers.
```
>symfony console debug:container --tag=nelmio_api_doc.model_describer

Symfony Container Services Tagged with "nelmio_api_doc.model_describer" Tag
===========================================================================

 ---------------------------------------- ---------- ---------------------------------------------------------
  Service ID                               priority   Class name                                              
 ---------------------------------------- ---------- ---------------------------------------------------------
  nelmio_api_doc.model_describers.form     100        Nelmio\ApiDocBundle\ModelDescriber\FormModelDescriber
  nelmio_api_doc.model_describers.object              Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber
 ---------------------------------------- ---------- ---------------------------------------------------------
```

How can I tell Nelmio that my entity should use this describer?

**Comment by GuilhemN** [comment]
You should not use quotes around `PointOfSale::class` so that it is resolved to an actual fully qualified class name.
Something like `@Model(type=PointOfSale::class)`

**Comment by SchabrechtsK** [comment]
Sorry to hi-jack this thread but I have the same issue

> Schema of type "Country" can't be generated, no describer supports it.

But I don't have quotes around the response part:
```
@SWG\Response(
     *     response=200,
     *     description="Returns an array of country objects",
     *     @SWG\Schema(
     *         type="array",
     *         @SWG\Items(type="object", ref=@Model(type=Country::class, groups={"detail"}))
     *     )
     * )
```

If I do the command I get nothing:

>symfony console debug:container --tag=nelmio_api_doc.model_describer

```
Symfony Container Public Services Tagged with "nelmio_api_doc.model_describers" Tag
===================================================================================

 ------------ ------------
  Service ID   Class name
 ------------ ------------

kenneth@devtng:~/vhosts/Kenneth$
```

Any idea?

**Comment by fabianoroberto** [comment]
Doc should be

```
@SWG\Response(
    response=200
    description="Returns an array of country objects",
    @SWG\Schema(
        type="array",
        @SWG\Items(
            ref=@Model(type= Country::class, groups={"detail"})
        )
    )
)
```

**Comment by SchabrechtsK** [comment]
I fixed it. Was not using the Class Country.

**Comment by GuilhemN** [comment]
I'm closing this issue as it seems to be fixed.
