### ISSUE TITLE
Possible to export documentation?

### ISSUE THREAD

**Issue by fma-technologies** [nelmio/NelmioApiDocBundle#1580]
I notice in previous versions it was possible through a command: https://symfony.com/doc/2.x/bundles/NelmioApiDocBundle/commands.html

I'd like to be able to export to an HTML file without the sandbox now. 

Is there a mechanism for doing this in the newer versions?

**Comment by pana1990** [comment]
@GuilhemN is it possible migrate commands from 2.* to 3.*?

**Comment by GuilhemN** [comment]
We could add an option to disable the sandbox in our template first (using `supportedSubmitMethods`, see https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/), exporting the documentation would then just be about putting in a zip a computed version of the swagger ui template along with its assets.

There is no such thing available in 3.x for now but if you're willing to implement it, it would be a nice addition :)
