### ISSUE TITLE
"message":"The PropertyInfo component was not able to guess the type of Exception::$message"

### ISSUE THREAD

**Issue by Hugmungus** [nelmio/NelmioApiDocBundle#1581]
Issue: Using the Exception Object in core PHP when documenting an exception response for a Controller action is throwing the following error:
`"message":"The PropertyInfo component was not able to guess the type of Exception::$message"` 

Example:  
```  
     * @Response(
     *     response=500,
     *     description="Thrown when attempting to update a non-existent record.",  
     *     @Schema(  
     *        type="array",  
     *        @Items(ref=@Model(type=Exception::class))  
     *     )  
     * )
```

Desired Solution: Ability to use Exception class object in response annotations and/or documentation on how to properly annotate an exception response in Symfony (as I could be setting up the incorrect notation :))

**Comment by GuilhemN** [comment]
You could use a manually defined model, see the docs https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/faq.rst#sharing-parameter-configuration.
Or, you could use a custom `ModelDescriber`, I don't think that would be worth it though.

However, I don't think we should support the `Exception` class directly in this bundle as there are plenty of ways to serialize it and we can't determine which one you use.
