### ISSUE TITLE
How to use NelmioApiDocBundle with DTO

### ISSUE THREAD

**Issue by bettinz** [nelmio/NelmioApiDocBundle#1582]
Hello, I have this situation:
Entity\User
Entity\Account

DTO\Person

I use Person DTO to validate mandatory fields (some from User and some from Account).
Now, with the rout /api/person I want to create a person, so I send a body with

```
"name" : "John",
"lastname": "Smith" ,
"email" : "john@smith.com"
```
Name and Lastname are field of Account, email is a field of User.

I've tried with:

```
 * @SWG\Parameter(
     *     name="CreatePersonDTO",
     *     in="body",
     *     description="CreatePerson in json format",
     *     required=true,
     *     @SWG\Schema(
     *      type="array",
     *      @Model(type=CreatePerson::class)
     *    )
     * )
```

but it doesn't work.

I've also tried to add in PersonDTO
```
* @SWG\Definition(
 *     type="object",
 *     @SWG\Xml(name="CreatePersonDTO")
 * )
```

but it doesn't load fields from DTO. Can you help me? 😄

**Comment by GuilhemN** [comment]
What was the issue in your api doc exactly ? What contraints are added to your request body?

**Comment by bettinz** [comment]
Hello, it was a typo. Thank your for your time 😉
