### ISSUE TITLE
QueryParam key property not used

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1585]
Hello, in the `QueryParam` annotation for FOSRestBundle the `key` param is used to change a parameter's name (in query string):

```
* @Rest\QueryParam(name="itemsPerPage", key="items_per_page", requirements="\d+", default=PaginatedResult::DEFAULT_ITEMS_PER_PAGE, description="Number of items per page")
```

Unfortunately Nelmio is not "using" it and in the documentation it shows `itemsPerPage` as parameter name, which is not correct (and it leads to the default being used).

Any way to fix this (even manually in annotations)?

Thanks.

**Comment by GuilhemN** [comment]
Could you review https://github.com/nelmio/NelmioApiDocBundle/pull/1589 please?

**Comment by lukepass** [comment]
It's now working fine. Thanks!
