### ISSUE TITLE
Use @SWG\Get

### ISSUE THREAD

**Issue by guenneguezt** [nelmio/NelmioApiDocBundle#1590]
I have seen in a blog the possibility to use the annotate like :
@SWG\Get(
     *     path="/agent/patrol/{ip<[\.\d]*>}/{port<\d*>}/config",
     *     summary="Get config",
     *     description="Get config Agent",
     *     operationId="getConfigPatrol",
     *     produces={"text/cfg"},
     *     @SWG\Parameter(
     *         name="ip",
     *         in="path",
...
The blog is : https://dev.to/mathieuks/use-swagger-to-document-a-symfony-api-790

I try to use the syntaxe, but the route (mark as path) are not detected by symfony router.
I use symfony 4.4.
I don't find doc for NelmioApiDocBundle with symfony 4.

Thanks for help
Thomas

**Comment by maxhelias** [comment]
I don't understand what you're trying to do, but in this article it doesn't use about NelmioApiDocBundle.
First of all, the article is quite old and it uses https://github.com/zircote/swagger-php v2 directly without NelmioApiDocBunle.
Second, swagger only describes the action of the route and does not communicate with the Symfony router. You need to configure your route in Symfony in addition.

**Comment by guenneguezt** [comment]
Thanks a lot for reply
thomas
