### ISSUE TITLE
Best way for custom annotation extension?

### ISSUE THREAD

**Issue by daum** [nelmio/NelmioApiDocBundle#1593]
We  have a number of endpoints which support a list of common parameters and a specific response format.  I wanted to add a custom annotation like @Custom\Listing(model=MyModel:class).  From there I'd want to pick it up in my own class to add the actual response/parameter swagger annotations.  I am able to get basically what I'm looking by looking for Get annotation on https://github.com/nelmio/NelmioApiDocBundle/blob/master/SwaggerPhp/ModelRegister.php#L66 .  

What would be the best way to hook into this bundle to be able to read those annotations/detect my own custom one and add it to the entire API output?  I'd be looking to add the Response and Parameter annotations.

Thanks for any pointers on where/how I could hook into that.

**Comment by GuilhemN** [comment]
If I understand correctly your annotations are not nested with swagger annotations, right?
If so I think you should create a route describer like the one we use for fosrest annotations (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/RouteDescriber/FosRestDescriber.php).

The ModelRegister is quite low level and has no hooks while the RouteDescribers are meant to be easily extended.

**Comment by daum** [comment]
Thanks, I think that should work, will take a crack at that this week and come back if it doesn't seem to be doing it.  Thanks so much.

**Comment by daum** [comment]
@GuilhemN  thanks for the direction on that I think for the most part everything is pretty close to working.  My last question is for the response formatting/hooking into the model definitions.  For example the response:
```
     * @SWG\Response(
     *     response=200,
     *     description="Returns list of items to the user",
     *     @SWG\Schema(type="object",
     *                           @SWG\Property(property="page",type="integer",example={"1"}
     *                                        ),
     *                           @SWG\Property(property="limit",type="integer",example={"100"}
     *                                        ),
     *                           @SWG\Property(property="total",type="integer",example={"1500"}
     *                                       ),
     *                          @SWG\Property(property="data",type="array", @SWG\Items(ref=@Model(type=MyClass::class,groups={"list"}))),
     *                                       ),
     *                  )
     *     )
```

I'm trying to replace all that with my custom annotation, ie `@APIListing(model=MyClass::class)`.  The tricky part is how to know what "ref" I want to use for the "items" on the swagger side since it looks like the ModelRegistry isn't a public service that I can inject/call to call a register on.  I didn't want to try to recreate all that code either so wasn't sure if you knew a better way on it to do it.

Thanks!

**Comment by GuilhemN** [comment]
If your describer implements https://github.com/nelmio/NelmioApiDocBundle/blob/master/Describer/ModelRegistryAwareInterface.php, the ModelRegistry will be automatically injected in it :)

**Comment by daum** [comment]
@GuilhemN  Thanks!  I've got it fully working minus one annoyance, not sure if I can get around it.  So my action looks something like this:
```
/**
 * @MyAnnotationListAPIAnnotation
 * @Route("/list",methods={"GET"})
 */

The problem is that with just that I get the following notice/error:
`User Notice: @SWG\Get() requires at least one @SWG\Response() in \MyController->listAction() `

Any ideas on how to get around that without adding the Response annotation?  My describer generates and adds the response and schema, it just doesn't get called before that error occurs.    

And again thank you so much for your help with all this!

**Comment by daum** [comment]
Nevermind figured it out it was the routes which have additional @SWG\Params declared need to have at least one valid response also defined.  Thanks again for the help.
