### ISSUE TITLE
Property description error since 3.6

### ISSUE THREAD

**Issue by thomaspicquet** [nelmio/NelmioApiDocBundle#1594]
Hello,

I've been describing my properties like that for ArrayCollection, since Psalm allows this format:
```
@var ArrayCollection<array-key, PageImage>
```
but since the new version, I can't generate the docs anymore due to this error:
```
^ phpDocumentor\Reflection\DocBlock\Tags\InvalidTag^ {#43065
  -name: "var"
  -body: "ArrayCollection<array-key, PageImage>"
  -throwable: InvalidArgumentException {#43061
    #message: ""\array-key" is not a valid Fqsen."
```

reverting to Nelmio ApiDocBundle 3.5 fixes the issue

I've seen suggestions online to change it to 
```
@var ArrayCollection|PageImage[]
```
but in this case Psalm thinks this can be an array

Any help would be appreciated

**Comment by GuilhemN** [comment]
I guess phpDocumentor added checks, isn't it sufficient to downgrade phpDocumentor ? And have you tried replacing `array-key` with a correct type like `string` or `mixed`?
