### ISSUE TITLE
Support for "hasX" methods break on "function hash()"

### ISSUE THREAD

**Issue by gnutix** [nelmio/NelmioApiDocBundle#1595]
I recently upgraded NelmioApiDocBundle from ^2.x to ^3.6 (supporting Symfony 5) and had the following error on our API doc page : 

```
The PropertyInfo component was not able to guess the type of SomeNamespace\SomeClass::$h. You may need to add a `@var` annotation or use `@SWG\Property(type="")` to make its type explicit.
```

It took me quite a bit of digging to understand the issue, because the class SomeNamespace\SomeClass had no property `$h`... It does, however, have a method `public function hash(string $algorithm): string`, which is interpreted has "hasH".

So there's probably 2 issues with the current implementation : 
1. The "hasser" methods support should check for "has" followed by an upper case letter (and therefore not match "hash")
2. (maybe?) the "hasser" methods support should check for the method return type to be a boolean (here a string)

I managed to get rid of the error for now by adding a `@return string Some comments` annotation, which is a total hack.

**Comment by GuilhemN** [comment]
This is how the property info component works unfortunately, a solution could be the annotation proposed in https://github.com/symfony/symfony/pull/28744.

**Comment by gnutix** [comment]
Should I open an issue on Symfony's repository then? I don't think it's a good idea for this component to match `hash` = `h` property.

**Comment by gnutix** [comment]
The annotation you mention was released in 5.1 : https://symfony.com/blog/new-in-symfony-5-1-serializer-improvements#added-ignore-annotation

I'll let you know once our project will have been upgraded to this version if it works or not.

**Comment by gnutix** [comment]
Same error, even with Symfony 5.1 and the Ignore annotation. :(

**Comment by GuilhemN** [comment]
If you're not using serializer groups, both https://github.com/nelmio/NelmioApiDocBundle/pull/1665 and https://github.com/symfony/symfony/pull/37040 need to be released before we can detect `@Ignore` annotations.

**Comment by dav1d8** [comment]
@Ignore annotation is working well for me using Symfony 5.2.1 and nelmio 3.8.0.

There was a bug in Symfony PropertyInfo component but this PR fixed it:
https://github.com/symfony/symfony/pull/39299

**Comment by gnutix** [comment]
I'm looking at this problem again as I keep stumbling upon it, now on a class having a method with signature `public function isEqualTo(self $other): bool;`. And I think the real problem lies in `\Symfony\Component\PropertyInfo\Extractor\SerializerExtractor`, which (AFAIK) should not take into account isser/getter/setter/hasser methods that have required arguments.

At least that's what `\Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor::getReadInfo` is doing with `!$reflClass->getMethod($methodName)->getNumberOfRequiredParameters()`,  see snippet here : 

```php
        foreach ($this->accessorPrefixes as $prefix) {
            $methodName = $prefix.$camelProp;

            if ($reflClass->hasMethod($methodName) && $reflClass->getMethod($methodName)->getModifiers() & $this->methodReflectionFlags && !$reflClass->getMethod($methodName)->getNumberOfRequiredParameters()) {
                $method = $reflClass->getMethod($methodName);

                return new PropertyReadInfo(PropertyReadInfo::TYPE_METHOD, $methodName, $this->getReadVisiblityForMethod($method), $method->isStatic(), false);
            }
        }
```

What do you think ?

**Comment by gnutix** [comment]
I think I found my own response : create implementations of `Nelmio\ApiDocBundle\ModelDescriber\ModelDescriberInterface` for each of these classes.
