### ISSUE TITLE
Error after upgrade to 3.6.0

### ISSUE THREAD

**Issue by versh23** [nelmio/NelmioApiDocBundle#1597]
Hello

```
    /**
     * @ORM\Column(type="json")
     * @Groups("main")
     *
     * @var string[]
     */
    private $roles = [];
```

Now its broken. Threre is error on throwing Exception here https://github.com/nelmio/NelmioApiDocBundle/blob/master/PropertyDescriber/ArrayPropertyDescriber.php#L35

$class, $propertyName - no variables

**Comment by sci3ma** [comment]
Confirm. And now we need to provide more information about array property:
```
    /**
     * @ORM\Column(type="json")
     * @Groups("main")
     *
     * @var string[]
     *
     * @SWG\Property(property="roles", type="array", @SWG\Items(type="string"))
     */
    private $roles = [];
```

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1617, thanks!
