### ISSUE TITLE
Incorrect type in example, when using enum

### ISSUE THREAD

**Issue by volarname** [nelmio/NelmioApiDocBundle#1599]
Hello
**version**: 
> dev-master

Using annotation:
`@SWG\Property(enum={ArticleStatus::AVAILABLE_VALUES}, type="string")`

will generate incorrect example:
`"status": [
      "draft",
      "ready",
      "published"
    ],`

Instead of string with enum values, its now array.

**Comment by chrisguitarguy** [comment]
assuming `ArticleStatus::AVAILABLE_VALUES` is an array?

`enum=ArticleStatus::AVAILABLE_VALUES` is probably the thing that would make it work?

Going to close this for now due to age.
