### ISSUE TITLE
ArrayPropertyDescriber breaks with cryptic message if array annotation is malformed

### ISSUE THREAD

**Issue by msphn** [nelmio/NelmioApiDocBundle#1604]
```
<?php
class Test {
    /**
     * Works fine
     *
     * @var string[]
     */
    private $goodArray;

    /**
     * Works not
     *
     * @var array
     */
    private $badArray;
}
?>
```

The first definition works well, the second is causing:

```
Notice: Undefined variable: class
```

Which is a bit confusing but simply caused by Nelmio\ApiDocBundle\PropertyDescriber\ArrayPropertyDescriber:35:

```
if (null === $type) {
    throw new \LogicException(sprintf('Property "%s:%s" is an array, but its items type isn\'t specified. You can specify that by using the type `string[]` for instance or `@SWG\Property(type="array", @SWG\Items(type="string"))`.', $class, $propertyName));
}
```

Neither $class nor $propertyName existing causing this very cryptic message instead of the proper error message indicating that an array annotation is malformed.

Any ideas how to get the current $propertyName and $class there? Didn't really dig into it .. :-)

**Comment by sci3ma** [comment]
@msphn this comment might help you: https://github.com/nelmio/NelmioApiDocBundle/issues/1597#issuecomment-599212021

**Comment by msphn** [comment]
Didn't see this one @sci3ma sorry!  I leave mine open since it contains the error users might find it easier. If it disturbs you feel free to close :).

**Comment by psociety** [comment]
+1 i'm getting the same error and it's 100% useless, makes it look like nelmio has an internal error.

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1617, thanks!
