### ISSUE TITLE
Cannot pick area for config based paths

### ISSUE THREAD

**Issue by hubertnnn** [nelmio/NelmioApiDocBundle#1606]
In configuration under `nelmio_api_doc.documentation.paths` you are able to specify custom paths.
Those paths not only ignore `path_patterns` from areas, but also there is no way to apply them to only one area.
It seem like those paths are simply merged to the final result regardless of what it is.

**Comment by GuilhemN** [comment]
Indeed, the documentation field is merged directly in the final result as it is a way to manually customize specific fields.

I thought this was documented but apparently it's not, you can add manual documentation fields per area using `nelmio_api_doc.areas.your_area_name.documentation` (see https://github.com/nelmio/NelmioApiDocBundle/blob/v3.6.1/DependencyInjection/Configuration.php#L106).

**Comment by GuilhemN** [comment]
I suppose this is fixed.
Feel free to submit a PR if you'd like to improve our docs :)
