### ISSUE TITLE
[Question] How to change property name as getter method

### ISSUE THREAD

**Issue by tung-huynh** [nelmio/NelmioApiDocBundle#1607]
Hi, 

I have a getter method which i mapped as a property for serialize. I would like to ask how i do the same for NelmioApiDocBundle? I did try as below but the propery name is still `nameObject`
```php
/**
     * @return Embedded\LanguageObject|null
     *
     * @Serializer\Groups(Tender::NORMALIZER_GROUP)
     * @Serializer\SerializedName("name")
     *
     * @SWG\Property(property="name", description="Test name")
     */
    public function getNameObject(): ?Embedded\LanguageObject
    {
        return $this->name[0];
    }
```

**Comment by GuilhemN** [comment]
`@SerializedName` support was added in https://github.com/nelmio/NelmioApiDocBundle/pull/1636, and `@SWG` annotations on methods support was added in https://github.com/nelmio/NelmioApiDocBundle/pull/1678.
These changes will be available when 3.7 is released :)
