### ISSUE TITLE
Support of Inheritance and Polymorphism

### ISSUE THREAD

**Issue by charliefancelli** [nelmio/NelmioApiDocBundle#1610]
Hi,

Is there a roadmap to support great OAS3 features with Inheritance and Polymorphism ?
[](https://swagger.io/docs/specification/data-models/inheritance-and-polymorphism/)

Actually when we describe a Response with AbstractObject, the model stay on the Abstract and note in the child.

With JMS Serializer we already have the discriminator.
```
/**
 * @Discriminator(field = "type", disabled = false, map = {"car": "Car", "moped": "Moped"}, groups={"foo", "bar"})
 */
abstract class Vehicle { }
class Car extends Vehicle { }
class Moped extends Vehicle { }
```

I can help to add this feature but i think OAS3 support is a requirements.

**Comment by GuilhemN** [comment]
Hi!
OA3 support was added to the bundle, see https://github.com/nelmio/NelmioApiDocBundle/pull/1623 :)

It is still in beta but it'd be great indeed to leverage its new features.

**Comment by Koc** [comment]
Symfony also supports de-/serialization of the abstract classes and interfaces since [version 4.1](https://symfony.com/blog/new-in-symfony-4-1-serialize-and-deserialize-from-abstract-classes). Would be nice support parsing corresponsing metadata.
