### ISSUE TITLE
Problem with use Model in Property annotation. Should be model not array

### ISSUE THREAD

**Issue by shubaivan** [nelmio/NelmioApiDocBundle#1611]
`"nelmio/api-doc-bundle": "^3.6@dev"`
I need response with model with property product which eque one model `Product` and property count, but when I use Mode annotation I faced with probem, response model generated like array `Product`. What I'm doing wrong ?   

```
     * @SWG\Response(
     *     response=200,
     *     description="Json collection object Products",
     *     @SWG\Schema(
     *         type="object",
     *         properties={
     *             @SWG\Property(property="product",
     *                  @Model(type=Product::class, groups={Product::SERIALIZED_GROUP_LIST})),
     *                  @SWG\Property(property="count", type="integer")
     *         }
     *     )
     * )


{
  "product": [
    {
      "id": 0
    }
  ],
  "count": 0
}
```

I expected result like this:

```
{
  "product":
    {
      "id": 0
    },
  "count": 0
}
```

**Comment by GuilhemN** [comment]
A deprecation was most likely thrown when using this code.
The issue is that the bundle doesn't know whether you want to use `@Model` as a sub `@Schema` or as a sub `@Items`.

As it was not ideal, this was deprecated in favor of the more explicit:
```
     * @SWG\Property(property="product",
     *                  @SWG\Schema(ref=@Model(type=Product::class, groups={Product::SERIALIZED_GROUP_LIST}))),
```
