### ISSUE TITLE
Notice: Undefined variable: class

### ISSUE THREAD

**Issue by 3rm4k0ff** [nelmio/NelmioApiDocBundle#1612]
https://github.com/nelmio/NelmioApiDocBundle/blob/ab014fe032beb1a7875939ff4162e8d05ad778ab/PropertyDescriber/ArrayPropertyDescriber.php#L35

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1617
