### ISSUE TITLE
JMSModelDescriber doesn't support AdvancedNamingStrategyInterface

### ISSUE THREAD

**Issue by aguidis** [nelmio/NelmioApiDocBundle#1615]
Hello,

I had to implement a custom naming strategy that required the `JMS\Serializer\Context`. So I implemented the interface `JMS\Serializer\Naming\AdvancedNamingStrategyInterface`.

Then I had this error when I refreshed my doc page:

> Argument 2 passed to Nelmio\ApiDocBundle\ModelDescriber\JMSModelDescriber::__construct() must implement interface JMS\Serializer\Naming\PropertyNamingStrategyInterface or be null, instance of App\JMS\CustomNameAnnotationStrategy given

So I simply implemented the interface `PropertyNamingStrategyInterface` to avoid the issue but I was wondering if you think it would be worth to rework the signature of the `JMSModelDescriber`'s contructor ?

Cheers

**Comment by GuilhemN** [comment]
Hi!
I think the issue is that `AdvancedNamingStrategyInterface` no longer exists in JMSSerializer 2.x.
Moreover the fix seems to be quite simple, so I'm not sure we should change the signature here :)
