### ISSUE TITLE
v3.6.1 where this commit `2ae2e008feb98c6ce0c2fc1f72a2e0d2a08b2fd8` ?

### ISSUE THREAD

**Issue by atlance** [nelmio/NelmioApiDocBundle#1621]
https://github.com/nelmio/NelmioApiDocBundle/blob/v3.6.1/PropertyDescriber/ArrayPropertyDescriber.php#L35

**Comment by GuilhemN** [comment]
This was fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1617 which is not included in v3.6.1.
