### ISSUE TITLE
how to exclude field from form type SF ?

### ISSUE THREAD

**Issue by imajim** [nelmio/NelmioApiDocBundle#1624]
Hello,

i should be remove a hidden field from my form type on Symfony.

```
 ->add('token', HiddenType::class,[
                'documentation' => [
                    'hidden' => true,
                ],
            ])
```
but the field is exported into generated doc :

<img width="244" alt="image" src="https://user-images.githubusercontent.com/13310096/82012207-88e1de80-9677-11ea-8768-9218906c84ad.png">

any ideas ?

thx ^^

**Comment by Apipa169** [comment]
I'd like to have this option as well!

**Comment by GuilhemN** [comment]
Closing as I'm missing information. Feel free to reopen if needed.
