### ISSUE TITLE
Preview HTML instead of source code

### ISSUE THREAD

**Issue by hkaraoglu** [nelmio/NelmioApiDocBundle#1626]
Is there an option preview HTML in response tab?

<img width="1347" alt="Screen Shot 2020-05-23 at 17 20 06" src="https://user-images.githubusercontent.com/7407515/82733033-bedb2e80-9d19-11ea-9ed3-6feecd1d4970.png">

**Comment by GuilhemN** [comment]
Unfortunately this is decided by swagger-ui and HTML support was rejected in the past, see https://github.com/swagger-api/swagger-ui/pull/4682.
Though you may check whether there is a swagger-ui plugin providing support for this. I haven't found any with my small search but maybe I missed it.
