### ISSUE TITLE
Swagger base path

### ISSUE THREAD

**Issue by ferriol** [nelmio/NelmioApiDocBundle#1627]
Hi,

I'm using swagger and the path to the symfony app is http://myhost.com/symfonyapp/ and the swagger is http://myhost.com/symfonyapp/api/doc but swagger doesn't works because is looking its assets, for example, at: http://myhost.com/bundles/nelmioapidoc/init-swagger-ui.js
I set 
host: apidev.motogp.com/payments 
in nelmio_api_doc.yaml
What I have to set to make it work ?

**Comment by GuilhemN** [comment]
Hi, have you tried running the command described here : https://symfony.com/doc/current/bundles/NelmioApiDocBundle/faq.html#asset-files-not-loaded ?

**Comment by ferriol** [comment]
Hi, I tried your propose but doesn't work, problem still exists
![Screenshot from 2020-08-26 15-47-36](https://user-images.githubusercontent.com/25852693/91311778-bfb9ab80-e7b3-11ea-9436-9de717093908.png)
![Screenshot from 2020-08-26 15-43-34](https://user-images.githubusercontent.com/25852693/91311782-c1836f00-e7b3-11ea-8fbe-095fbc9002a3.png)

**Comment by GuilhemN** [comment]
@ferriol did you also run `composer require asset`?

**Comment by ferriol** [comment]
Is already installed:
`composer require symfony/asset
Restricting packages listed in "symfony/symfony" to "4.4.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Restricting packages listed in "symfony/symfony" to "4.4.*"
Nothing to install or update
`

**Comment by ferriol** [comment]
We solved adding the path in the asset bundle config
framework:
  assets:
    base_path: 'base_path/to/the/application'

**Comment by GuilhemN** [comment]
@ferriol thanks for the feedback.

This would probably be suited in [our FAQ](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/faq.html#asset-files-not-loaded) :)
