### ISSUE TITLE
@Model swagger ui model side is empty but example side work fine

### ISSUE THREAD

**Issue by kevin-schmitt** [nelmio/NelmioApiDocBundle#1642]
Hello everyone,

Can you help me please?
I use api doc bundle 3.6.
With this annotation work fine it's just array with properties and ref object
```
`    *         @OA\Property(property="appreciations", minItems=2, maxItems=2,
    *             @OA\Items(type="object",
    *                 @OA\Property(property="type", type="string", example="software or request", description="software or  request"),
    *                 @OA\Property(property="canModify", type="bool", description="if current user can modify this appreciation value"),
    *                 @OA\Property(property="value", type="integer", example="1", description="0 = no evaluated, 1 = validated, 2 = refused"),
    *                 @OA\Property(property="user", ref=@Model(type=User::class, groups={"solution_request"})),
    *             ),
    *         ),`
```

 In swagger ui for example side nice
![image](https://user-images.githubusercontent.com/10809414/83395443-937fd000-a3fa-11ea-838a-90bf091a7dac.png)
But in section Model is empty
![image](https://user-images.githubusercontent.com/10809414/83395498-b4482580-a3fa-11ea-9c13-7711408d34e3.png)
`
I forbid something? Thanks

**Comment by GuilhemN** [comment]
Could you check if it's not related to the fact that `bool` should be `boolean`?

**Comment by kevin-schmitt** [comment]
Thanks for reply :)
Yes problem typo with boolean and appreciations have not type i just add array and work fine :)
Thanks.
