### ISSUE TITLE
Add Redoc ui support

### ISSUE THREAD

**Issue by GuilhemN** [nelmio/NelmioApiDocBundle#1644]
Opening an issue to keep track of the suggestion of @BafS (https://github.com/nelmio/NelmioApiDocBundle/pull/1634#issuecomment-636103491).

It would be nice to add support of the Redoc ui alongside swagger-ui.
It is already supported by ApiPlatform (https://github.com/api-platform/core/pull/2384) and their implementation may be a starting point to integrate it to NelmioApiDocBundle.

PR welcome :)

**Comment by BafS** [comment]
I think it can be closed right?

**Comment by DjordyKoert** [comment]
Correct! Thank you for the heads up @BafS :)
