### ISSUE TITLE
[Question] Multiple sections for same path

### ISSUE THREAD

**Issue by kptLucek** [nelmio/NelmioApiDocBundle#1645]
Hi there, and thanks for awesome package!

Let me describe my use-cases so maybe you gonna get better view on that.

I have app, where's toon of configuration, and based on that configuration **routes are generated**, yes they are totally configurable. They all point to same controller (action), most of logic is called before request "trully" reach action.

This is kinda important - Because of that strange usecase, sometimes i do have multiple routes with **exactly the same** path.

Because of different routes point to same action (sometimes under same path) the request should contain various data, sometimes there's parameter "a" which is required, sometimes it's optional or even non-existent, everything depends on body context. That's the reason i would like to have every of those separated.

What i would like to achieve:
- I would like to describe every (even duplicated) path's with their requirements programmatically, on route loading phase, or configuration phase (because at this point i have every parameter, requirement, and their description)
- See every of those describer under /api/doc & /api/doc.json

Right now, every path that's duplicated is being overridden by next one on same path, which is wrong for that usecase.

Thanks for any guides / assistance.

**Comment by GuilhemN** [comment]
Sorry I'm not sure I fully understand your issue.

OpenApi does only support having one action per path/method, in case you have several, this bundle will try to merge the metadata provided but it won't be able to separate them since this is not supported by the OpenApi specification.

**Comment by kptLucek** [comment]
Well, yeah i know.

The point is, that my endpoint expects few parameters as requirements, and "others" are dependent on data provided in required ones.

Like if you provide:
```json
{
    "a": true
}
```

then it would expect additional fields, and i'm kinda lost how to describe them properly

**Comment by GuilhemN** [comment]
OpenApi 3 provides the new field `oneOf` (see https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/), this is not a perfect fit to your needs but I don't think it's possible to directly link constraints on your input to the response unfortunately...

(Note that OpenApi v3 support is added in NelmioApiDocBundle v4 which is not released yet)
