### ISSUE TITLE
[Question] @Model in Yaml

### ISSUE THREAD

**Issue by vertisan** [nelmio/NelmioApiDocBundle#1646]
Hi,  
Is it possible to use someway `@Model` in Yaml format to create definition? Or it is only available as annotation?  
I want to easily create definition based on class and groups.

**Comment by GuilhemN** [comment]
Unfortunately it is only available as an annotation for now. We may add support for a syntax such as `!model {type: App\Entity\MyClass }` though.

**Comment by MetalArend** [comment]
@GuilhemN Does that mean that there is no way to force the bundle to load in some Models that then can be used by ref(erence) in yaml? Do you have a project with any examples on how that might be possible?
