### ISSUE TITLE
[4.0.0-BETA1] Schemas combine in Yaml support

### ISSUE THREAD

**Issue by vertisan** [nelmio/NelmioApiDocBundle#1650]
Hi,  
Yesterday I was posted the issue #1646 about problem with inheritance. I have already tested some solutions and problem is with support for combining schemas by keywords: `oneOf`, `anyOf`, `allOf`, `not`.  
When we try to use it, e.g.  
```yaml
components:
  schemas:
    Pet:
      type: object
      required:
      - petType
      properties:
        petType:
          type: string
      discriminator:
        propertyName: petType
        mapping:
          dog: Dog
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
```
we will get an error:  
```
ErrorException: Array to string conversion
```
Is support planned?

**Comment by GuilhemN** [comment]
Thanks for the report!
This should be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1653 (though when testing in a real app I still had the issue https://github.com/nelmio/NelmioApiDocBundle/issues/1648).

**Comment by GuilhemN** [comment]
#1653 is merged :)
