### ISSUE TITLE
Documentation for 3.x version is not correct

### ISSUE THREAD

**Issue by raresserban** [nelmio/NelmioApiDocBundle#1661]
Hello, if you currently visit the Symfony Doc page for the bundle:
https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html

It has in the examples using `use OpenApi\Annotations as OA;` namespace. However, that is only in `zircote/swagger-php: ^3.0`, which is used by Nelmio Api Doc version v4.0.0-BETA1, version 3.x still uses `zircote/swagger-php: ^2.0.9`, which has the namespace `use Swagger\Annotations as SWG;`

I find it really hard to integrate this bundle with a new project if the documentation does not show correctly what I can do with 3.x version...

**Comment by GuilhemN** [comment]
Thanks for the report :) This should be fixed in a few days when symfony documentation is regenerated ;)

**Comment by GuilhemN** [comment]
done ;)
