### ISSUE TITLE
How to hide (or collapse) Models section?

### ISSUE THREAD

**Issue by lukepass** [nelmio/NelmioApiDocBundle#1662]
Hello! I read that it should be possible to hide or collapse the Models section. How can I do it using NelmioApiDocBundle?

I found this small guide here: https://idratherbewriting.com/learnapidoc/pubapis_swagger.html

```
const ui = SwaggerUIBundle({
  url: "openapi_openweathermap.yml",
  dom_id: '#swagger-ui',
  defaultModelsExpandDepth: -1,
  deepLinking: true,
  presets: [
    SwaggerUIBundle.presets.apis,
    SwaggerUIStandalonePreset
  ],
  plugins: [
    SwaggerUIBundle.plugins.DownloadUrl
  ],
  layout: "StandaloneLayout"
})
```

And I read that this feature should now be possible: https://github.com/nelmio/NelmioApiDocBundle/pull/1358 and https://github.com/nelmio/NelmioApiDocBundle/pull/1357

Where I should I put the code or the options? I am just interested in the `defaultModelsExpandDepth: -1` option.

Thanks!

**Comment by GuilhemN** [comment]
Unfortunately we don't have a simple mechanism to extend `init-swagger-ui.js`.

What you can do is overwrite our template (see https://symfony.com/doc/current/bundles/override.html#templates):
```
{# templates/bundles/NelmioApiDocBundle/SwaggerUi/index.html.twig #}
{# the special '!' prefix avoids errors when extending from an overridden template #}
{% extends "@!NelmioApiDoc/SwaggerUi/index.html.twig" %}

{% block swagger_initialization %}
   <script src="{{ asset('path to your own init-swagger-ui.js') }}"></script>
{% endblock %}
```

And copy `init-swagger-ui.js` in your project and update as you wish.

**Comment by jonmnoj** [comment]
I have been trying to use this new configuration option as shown in the docs [here](https://symfony.com/doc/4.x/bundles/NelmioApiDocBundle/customization.html#overwrite-twig-template), however it throws a ReferenceError "loadSwaggerUI is not defined" had something changed with the release of 4.x that means this needs to be done in a different way?

**Comment by GuilhemN** [comment]
Actually https://github.com/nelmio/NelmioApiDocBundle/pull/1737 (which implements `loadSwaggerUI`) is not released yet.
I'll do a release very soon.

**Comment by jonmnoj** [comment]
Ah yes, this was only merged in shortly after what was the most recent release, silly me.
Thanks for the update and your great work on this.

**Comment by chrisguitarguy** [comment]
Closing in favor of https://github.com/nelmio/NelmioApiDocBundle/issues/1330
