### ISSUE TITLE
Notice: Undefined variable: class

### ISSUE THREAD

**Issue by Cypaubr** [nelmio/NelmioApiDocBundle#1663]
I have an issue with a simple API endpoint configured as it follows:

```php
/**
     * Returns the user's profile.
     * @param SerializerInterface $serializer
     * @return JsonResponse
     * @SWG\Response(
     *     response=200,
     *     description="Returns the user's profile.",
     *     @Model(type=User::class, groups={"apiExposed"})
     * )
     * @SWG\Tag(name="User")
     */
    public function meAction(SerializerInterface $serializer): JsonResponse
    {
        // Some stuff here
    }
```
I also tried with `"App\Entity\User"` as `type` but it changes nothing.

For information:
PHP Version: 7.4.5
Symfony Version: 4.4.10
NelmioAPIDocBundle Version: 3.6.1

**Comment by GuilhemN** [comment]
This was fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1617, however it is not released yet.
