### ISSUE TITLE
UI/Bug After installing master branch

### ISSUE THREAD

**Issue by xpresas** [nelmio/NelmioApiDocBundle#1676]
On master branch there is a bug where clicking on one API endpoint in the UI it opens up all of them.
In HTML all classes become ```opblock opblock-post is-open``` instead of only the one I just clicked.

**Comment by GuilhemN** [comment]
Indeed, I was able to reproduce your issue.
Upgrading swagger ui doesn't fix this issue so I'm not sure whether this is a bug on their side or on ours...
The only solution I see is reverting the last commit bumping swagger-ui.

**Comment by charliefancelli** [comment]
If we look on the html, the `id` is the same for all endpoint in the same "Category" (tag)

![Capture d’écran 2020-07-20 à 16 57 47](https://user-images.githubusercontent.com/800399/87962380-62955080-cab7-11ea-9937-cc42596cca29.png)

**Comment by GuilhemN** [comment]
@charliefancelli thank you for debugging this!

I don't know why but swagger-php enabled a new processor by default in version 3.x (which automatically operation ids on every operation). I don't like it, and it's not working well with the custom contexts we use in this bundle so I submitted https://github.com/nelmio/NelmioApiDocBundle/pull/1685 to disable it.
Would this fix be acceptable to you?

**Comment by charliefancelli** [comment]
@GuilhemN of course it's ok for me. I also don't understand why swagger-php did that.
