### ISSUE TITLE
Empty object with with @Model

### ISSUE THREAD

**Issue by gonsandia** [nelmio/NelmioApiDocBundle#1677]
I followed the documentation on https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html

library versions
```
        "php": "^7.2.5",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "jms/serializer": "^3.8",
        "lcobucci/jwt": "^3.3",
        "nelmio/api-doc-bundle": "^3.6",
        "symfony/asset": "5.1.*",
        "symfony/console": "5.1.*",
        "symfony/dotenv": "5.1.*",
        "symfony/flex": "^1.3.1",
        "symfony/framework-bundle": "5.1.*",
        "symfony/orm-pack": "^1.0",
        "symfony/security-bundle": "5.1.*",
        "symfony/serializer": "5.1.*",
        "symfony/twig-pack": "^1.0",
        "symfony/yaml": "5.1.*",
        "willdurand/hateoas-bundle": "^2.1"
```

My controller action annotation

    /**
     * @Route("/api/login", name="token_authentication", methods="POST")
     *
     * @SWG\Response(
     *     response="201",
     *     description="Operation automatically detected"
     * )
     *
     * @SWG\Parameter(
     *        name="JSON update body",
     *        in="body",
     *        description="json login request object",
     *        required=true,
     *        @SWG\Schema(
     *            type="object",
     *            ref=@Model(type=App\Model\LoginModel::class)
     *        )
     *      )
     * @SWG\Tag(name="auth")
     *
     */
    public function login(Request $request): JsonResponse

My Model class

```
<?php

namespace App\Model;

use JMS\Serializer\Annotation as Serializer;
use Swagger\Annotations as SWG;
use Symfony\Component\Validator\Constraints as Assert;

class LoginModel
{
    /**
     * @var string

     * @Serializer\Type("string")
     *
     * @Assert\NotBlank()
     * @Assert\Type("string")
     *
     * @SWG\Property(description="The unique identifier of the user.")
     */
    private $username;

    /**
     * @var string
     * @Serializer\Type("string")
     *
     * @Assert\NotBlank()
     * @Assert\Type("string")
     *
     * @SWG\Property(description="The login password.")
     */
    private $password;
}
```

melmio:api_doc.yaml
I tried use_jms true and false with the same result
```
nelmio_api_doc:
    documentation:
        info:
            title: My App
            description: This is an awesome app!
            version: 1.0.0
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Value: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
        models:
            use_jms: true
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
```

But when i try it on swagger it's empty
![image](https://user-images.githubusercontent.com/8087716/87230846-a5b63c00-c3b2-11ea-90bc-de8d3f1ccd6b.png)

![image](https://user-images.githubusercontent.com/8087716/87230911-37be4480-c3b3-11ea-9bfb-c464cffc3abd.png)

I tried all I get on google and nothing works

**Comment by GuilhemN** [comment]
I'm sorry I am not able to reproduce your issue.
Could you create a small app with this problem and share it here?

**Comment by gonsandia** [comment]
I reinstalled JMS and updated loginModel imports and now it is working fine.
Thx @GuilhemN 

![image](https://user-images.githubusercontent.com/8087716/87387405-e83e6b00-c5a2-11ea-9187-474d5efe0ca4.png)
![image](https://user-images.githubusercontent.com/8087716/87387423-f68c8700-c5a2-11ea-842e-decd7e0effb1.png)

**Comment by GM-Alex** [comment]
@gonsandia Hey could you describe a little more what you did to solve this? Because I facing the same issue.

**Comment by Pchol** [comment]
I catch this case. If property is not public, model is empty
