### ISSUE TITLE
Notice: Undefined variable: class

### ISSUE THREAD

**Issue by aminvoly** [nelmio/NelmioApiDocBundle#1687]
I have a Customer class extended UserInterface in Symfony 5.
Here is the response part for my index action in the customer controller:
`     * @SWG\Response(
     *     response=200,
     *     description="Return list of customers",
     *     @SWG\Schema(
     *         type="array",
     *         @SWG\Items(ref=@Model(type=Customer::class, groups={"default"}))
     *     )
     * )`
Every time I add * @Groups({"default"}) to roles variable, I get an error Notice: Undefined variable: class, and when I remove it everything works ok, by the way, the type for roles is JSON.
Thanks in advance.

**Comment by GuilhemN** [comment]
This issue is related to https://github.com/nelmio/NelmioApiDocBundle/pull/1617. It is fixed by not released yet.
It means you have an array property and its inner type can't be resolved.
