### ISSUE TITLE
Is there a plan to create a documentation?

### ISSUE THREAD

**Issue by dobryy** [nelmio/NelmioApiDocBundle#1688]
Hi there, 

The library looks great but the lack of documentation makes the usage of the library painful, especially when it comes to the most recent version of the master branch and 4.0-BETA.

Thus, I'd like to ask whether there is a plan to create some documentation? 

Also, I'll be more than happy if you'll share some tips and tricks on how to figure out all the features there're at the moment and how to use them.

**Comment by GuilhemN** [comment]
Hi!

Do you see specific issues with the documentation? The swagger annotations usage is described in zircote/swagger-php (see https://github.com/zircote/swagger-php/tree/master/Examples), maybe we should make this clearer.

I personally can't dedicate much time to the docs but I'm be happy to explain unclear points in issues and I'd definitively appreciate documentation PRs :)

**Comment by GuilhemN** [comment]
Closing as there is no specific tracker here.
Feel free to reopen if you have specific questions.
