### ISSUE TITLE
[4.0][Documentation] Issue in documentation to Alternative name

### ISSUE THREAD

**Issue by charliefancelli** [nelmio/NelmioApiDocBundle#1689]
Hi, 

There is a mistake in the documentation https://symfony.com/doc/master/bundles/NelmioApiDocBundle/alternative_names.html

```
class HomeController
{
    /**
     * @OA\Response(response=200, @OA\JsonContent(@OA\Schema(ref="#/components/schemas/MyModel")))
     */
    public function indexAction()
    {
    }
}
```
must be
```
class HomeController
{
    /**
     * @OA\Response(response=200, @OA\JsonContent(ref="#/components/schemas/MyModel"))
     */
    public function indexAction()
    {
    }
}
```

With the current example, model and example are empty

![Capture d’écran 2020-07-24 à 14 31 33](https://user-images.githubusercontent.com/800399/88391542-ae4b4100-cdba-11ea-9b3e-fe0b0fbdb7df.png)

**Comment by GuilhemN** [comment]
Hi,
Thanks for the report! I thought it was all good... I fixed it in https://github.com/nelmio/NelmioApiDocBundle/commit/35b84d12980db654ae17252a3e668b48fc6a3e46 :) 

If you wish, you can submit a PR directly in order to update the documentation ;)
