### ISSUE TITLE
[4.0] Documentation about OA\Parameter outdated?

### ISSUE THREAD

**Issue by NicoHaase** [nelmio/NelmioApiDocBundle#1704]
I've just started to use your bundle, and I'm already using v4 such that I don't have to upgrade my code when that gets final in the next time.

The documentation at https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html states that `@OA\Parameter` might contain a type information, but I could not find such information in their documentation. Also, this throws an exception

     * @OA\Parameter(
     *     name="order",
     *     in="query",
     *     type="string",
     *     description="The field used to order rewards"
     * )

![Bildschirmfoto von 2020-08-21 15-05-07](https://user-images.githubusercontent.com/1069028/90893697-bd281200-e3bf-11ea-9c29-1d49a3a0dab7.png)

**Comment by NicoHaase** [comment]
I'm not sure whether both lines do the same and have no experience with the former configuration, but as this does not throw an error, but show the string information in the GUI instead, this looks fine :)

As far as I see, it could also be good to highlight this change in the upgrade notes?

After all, thanks for your great work!

**Comment by GuilhemN** [comment]
> I'm not sure whether both lines do the same and have no experience with the former configuration, but as this does not throw an error, but show the string information in the GUI instead, this looks fine :)

**Comment by GuilhemN** [comment]
> I'm not sure whether both lines do the same and have no experience with the former configuration, but as this does not throw an error, but show the string information in the GUI instead, this looks fine :)

I checked the official specification to produce this sample, it was just to have a second review :)

> As far as I see, it could also be good to highlight this change in the upgrade notes?

We haven't much documented the migration from Swagger to Open Api 3 annotations, I believe this would more suited in the zircote/swagger-php repository.
They provided a guide to help people migrate (https://github.com/zircote/swagger-php/blob/master/docs/Migrating-to-v3.md) but it's quite simple and I agree some additions would be appreciated :) I suppose they would appreciate contributions on this topic.

**Comment by chrisguitarguy** [comment]
Gonna close this one for now as it's a bit stale (v3 migration stuff) and it was closed before.
