### ISSUE TITLE
[4.0] Warning after upgrading: Undefined index host

### ISSUE THREAD

**Issue by MKHSKY** [nelmio/NelmioApiDocBundle#1707]
I just upgrade from 3.x to 4.x in order to use the OpenApi 3.0 Specs.
I was wondering why nobody else has this problem.

## Problem description:
PHP Warning: "Notice: Undefined index: host"
![image](https://user-images.githubusercontent.com/42220355/91277233-d693da00-e782-11ea-9376-e30b26296749.png)

## Workaround (for me)
I created a workaround in the Util.php file like so
![image](https://user-images.githubusercontent.com/42220355/91277293-ec090400-e782-11ea-84ed-332f9a5fe9d7.png)
But i guess this is not a good way (but this issue keeps blocking me)

## Environment
- PHP 7.4.9
- Symfony 5
- Composer .json for apidoc `"nelmio/api-doc-bundle": "4.*@dev",`
- Package Version
   ```"name": "nelmio/api-doc-bundle",
            "version": "dev-master",
            "source": {
                "type": "git",
                "url": "git@github.com:nelmio/NelmioApiDocBundle.git",
                "reference": "5dce5fe1bcb9be7e6cf3a6c4bc7cf84ee22ac0e4"
            },```
- Swagger PHP
  ```` "name": "zircote/swagger-php",
            "version": "3.0.4",
            "source": {
                "type": "git",
                "url": "https://github.com/zircote/swagger-php.git",
                "reference": "fa47d62c22c95272625624fbf8109fa46ffac43b"
            },```

Am i doing something wrong or why is this warning coming up?

**Comment by GuilhemN** [comment]
Did you upgrade your nelmio api doc documentation to respect open api 3? Here it seems you're using a `host` field somewhere which is no longer available in open api 3.

**Comment by MKHSKY** [comment]
Thank you for taking a look.

Yep in my nelmio_api_doc.yaml was something like this from the prior version, not sure why i didn´t see that.

So its done :) Thanks!
