### ISSUE TITLE
Magic methods no longer supported by JMSModelDescriber

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1708]
I have `__call()` defined for some of my API DTO input classes that are referenced in `@Parameter(in="body",...)` annotations on controller actions in a Symfony app. I use `@JMS\Accessor(getter="getFoo", setter="setFoo")` annotations on the properties in these DTO classes. This used to work fine but is busted in the new 3.7 release. I'm getting `ReflectionException` when [JMSModelDescriber](https://github.com/nelmio/NelmioApiDocBundle/blob/v3.7.0/ModelDescriber/JMSModelDescriber.php#L97) tries to create a corresponding `ReflectionMethod` object when the getter is defined in the `__call()` instead of directly.

**Comment by GuilhemN** [comment]
Thanks for the report! 

I believe we will need additional logic to catch `ReflectionException`s when using `getter` and `setter`... I'll try to submit a fix in the next days, in case you'd like to work on a fix a PR would also be appreciated :)

**Comment by pdugas** [comment]
What's the approach you're suggesting?  Catch the exception and do what?  I likely don't have time to work on it but asking just in case I do.

**Comment by GuilhemN** [comment]
I was thinking simply ignoring the getter or setter when we can't create a `ReflectionMethod` for it.

**Comment by pdugas** [comment]
Warning....   Untested.

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1715 :)
