### ISSUE TITLE
Providing configuration operation to disable UI + JSON docs

### ISSUE THREAD

**Issue by deanc** [nelmio/NelmioApiDocBundle#1717]
I've not had much success with trying to disable the API Docs UI + JSON in prod environment (or even dev for that matter). I've had a look through this but it doesn't seem to work for me with the latest Symfony 5:
https://stackoverflow.com/questions/40495097/how-to-disable-nelmio-ui-in-production

But it seems to me that a very sensible default would be to only allow the UI docs + JSON generation in dev environment by default.

Things I have tried:
- Changing the routes in `config/routes/nelmi_api_doc.yaml` does nothing. 
- Changing the `config/bundles.php` from `all => true` to `dev => true` does nothing

**Comment by GuilhemN** [comment]
Have you tried moving `config/routes/nelmio_api_doc.yaml` to `config/routes/dev/nelmio_api_doc.yaml`?

**Comment by deanc** [comment]
Thanks @GuilhemN - this solved the issue, and I think I was having some cache issues which prevented it from working locally.
