### ISSUE TITLE
Take into account symfony's Ignore annotation

### ISSUE THREAD

**Issue by mahkali** [nelmio/NelmioApiDocBundle#1724]
Symfony 5.1 introduced the Ignore annotation. 
https://symfony.com/blog/new-in-symfony-5-1-serializer-improvements#added-ignore-annotation

It would be helpful if the attributes that are annotated with Ignore are not included in the ApiDocs as a property of that schema.

**Comment by GuilhemN** [comment]
Please see https://github.com/nelmio/NelmioApiDocBundle/issues/1595#issuecomment-652628318.
