### ISSUE TITLE
Error messages regarding inheritDoc aren't helpful at all

### ISSUE THREAD

**Issue by ondrowan** [nelmio/NelmioApiDocBundle#1728]
> "Property \"{@inheritdoc}\" is an array, but its items type isn't specified. You can specify that by using the type `string[]` for instance or `@SWG\\Property(type=\"array\", @SWG\\Items(type=\"string\"))`."

I'm working on a fairly large codebase and this error (along with the stack trace) don't mention where this error could be coming from and it's really hard to debug/fix. Would it be possible to improve this error message? At least resolving the `@inheritdoc` reference would help a ton. Displaying the name of the property would be even better.

I'm using version 3.7.X of this bundle along with Symfony serializer.

**Comment by GuilhemN** [comment]
Closing as this as since been fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1747
