### ISSUE TITLE
Is it possible to specify input form as `application/x-www-form-urlencoded` in version 4?

### ISSUE THREAD

**Issue by VBelozyorov** [nelmio/NelmioApiDocBundle#1729]
With following controller's method annotation:
```
     * @OA\Parameter(name="form", in="query",     
     *          @OA\Schema(
     *              ref=@AD\Model(type="<from FQCN>")
     *          )
     * )
```
I'm getting docs for this method looking like there is JSON input:
![изображение](https://user-images.githubusercontent.com/860208/95562650-19ed9380-0a25-11eb-9923-094e2f2daf49.png)

And yes, [docs also says about default `application/json`](https://symfony.com/doc/master/bundles/NelmioApiDocBundle/index.html#use-models)

Can I somehow specify that method consumes `application/x-www-form-urlencoded` input? I've tried different combinations `@OA\MediaType`, `@OA\Schema` and `@OA\Parameter` but no luck.

Also I hope this would allow me to add more info about particular form fields:
![изображение](https://user-images.githubusercontent.com/860208/95562570-ffb3b580-0a24-11eb-8453-5a53d4dde118.png)

For now I managed to do this only by specifing `@OA\Parameter` annotations for each form field by hand, and what worse those annotations only take effect being specified on the API method, not inside Form class.

**Comment by VBelozyorov** [comment]
Ref #891 #956 #1127

**Comment by GuilhemN** [comment]
I'm not sure I understand the issue, is it that you want to use a `application/x-www-form-urlencoded` body, or do you want to describe `query` parameters using a dto object?

If you want the first you should do the following:
```php
/**
 * @OA\MediaType(mediaType="application/x-www-form-urlencoded", @OA\Schema(ref=@Model(...)))
*/
```

For the second, please have a look at https://swagger.io/docs/specification/serialization/

**Comment by GuilhemN** [comment]
Closing as I suppose your issue is fixed.
Please reopen if needed.
