### ISSUE TITLE
Documentation about the Request and Request Body

### ISSUE THREAD

**Issue by alexander-schranz** [nelmio/NelmioApiDocBundle#1732]
After some time I wanted to give NelmioApiDoc a try again. I have really struggle to find example how to define the RequestBody. For me the Docs currently is to focus on the Response and to focused that you have a PHP Model behind it which does match exactly your API.

Are there any good resources or examples without using Model References or things like that. Just how to define the Request, Request Body Schema and Response Schema with different Http Status Codes.

**Comment by GuilhemN** [comment]
I suppose you could have a look at `zircote/swagger-php` [examples](https://github.com/zircote/swagger-php/blob/master/Examples/petstore-3.0/controllers/Pet.php).
Is this what you are looking for?

**Comment by alexander-schranz** [comment]
@GuilhemN Thank you for that! The following example was what I was searching for need to check if it works in combination with FOSRestBundle but at least it represents how I need to nest the annotations.

https://github.com/zircote/swagger-php/blob/160bdab6e8f927221db18b9c2cb819bba16b7cd5/Examples/petstore-3.0/controllers/Pet.php#L226-L244

**Comment by GuilhemN** [comment]
Great!
I'm still unsure whether we should document the usage of zircote annotations in NelmioApiDocBundle as we don't support them exactly the same as `zircote/swagger-php` does but I'm afraid it would be tough to maintain.

**Comment by GuilhemN** [comment]
Closing as it seems you found the examples you needed.
Feel free to reopen if you have the need.

**Comment by alexander-schranz** [comment]
Yeah, Thank you for your support 👍

**Comment by ViniciusLCredendio** [comment]
> @GuilhemN Thank you for that! The following example was what I was searching for need to check if it works in combination with FOSRestBundle but at least it represents how I need to nest the annotations.
> 
> https://github.com/zircote/swagger-php/blob/160bdab6e8f927221db18b9c2cb819bba16b7cd5/Examples/petstore-3.0/controllers/Pet.php#L226-L244

Thanks, it helped me today!
