### ISSUE TITLE
getting the api route from a yml file

### ISSUE THREAD

**Issue by emrbzkr** [nelmio/NelmioApiDocBundle#1733]
Hi,
I just upgrade the bundle to 3.0 but I can not see my APIs in the Doc. Then I saw that, if I add the routes to the annotation of the API, then I can see it.But, I do not write the routes asannotations, I have yml files for them?
So, is there any way to get the routes from the api specific yml file?

Example (how I can not see the api in the apiDoc):
AABundle->Controller->AAController.php

```
<?php
namespace AABundle\Controller;
use Nelmio\ApiDocBundle\Annotation\Operation;
use Nelmio\ApiDocBundle\Annotation\Model;
use Swagger\Annotations as SWG;

class AAController extends AbstractFOSRestController implements ClassResourceInterface
{
  /**
     * @param Request $request
     * @return ArrayCollection
     *  @Operation(
     *     tags={"AAA"},
     *     summary="aaaaaaa aaaa aaa",
     *     @SWG\Parameter(
     *         name="hizmet_id",
     *         in="body",
     *         description="",
     *         required=false,
     *         @SWG\Schema(type="integer")
     *     ),
     *     @SWG\Parameter(
     *         name="user_id",
     *         in="body",
     *         description="",
     *         required=false,
     *         @SWG\Schema(type="custom handler result for (int)")
     *     ),
     *     @SWG\Parameter(
     *         name="user_departman_id",
     *         in="body",
     *         description="",
     *         required=false,
     *         @SWG\Schema(type="custom handler result for (int)")
     *     ),
     *     @SWG\Response(
     *         response="200",
     *         description="Returned when successful"
     *     )
     * )
     *
     */
public function aaTestAction($request){ }
```

AABundle->Resources->config->routing.yml
```
aaa_test_api:
    type:     rest
    path:     /v1/aaa/test
    defaults: { _controller: AABundle:AA:AATest}
```

Only way that I can see it in apiDoc, fi I add * @Route("/api/{user}/rewards", name="get_academic_year", methods={"GET"}) to the annotation. (Note: I test the api so the routing is valid in yml. Note 2: It was working properly in apiDoc v2.0)

thx :)

**Comment by emrbzkr** [comment]
by the way I found this:  @route("/api/{user}/rewards", name="get_academic_year", methods={"GET"})
from here: https://github.com/nelmio/NelmioApiDocBundle/issues/1255

and add it to my code, just for testing

**Comment by GuilhemN** [comment]
I suppose this is due to your configuration, please check `path_patterns` under `config/nelmio_api_doc.yaml` and make sure you document the URLs you want.

**Comment by chrisguitarguy** [comment]
closing for now due to lack of feedback and @GuilhemN's response. This is probably due to configuration issues (`path_patterns`, etc).
