### ISSUE TITLE
OpenApi3 -> path and nelmio areas not working

### ISSUE THREAD

**Issue by aidenko** [nelmio/NelmioApiDocBundle#1734]
I expect the following configiration splits the doc at 2 sections: public and wholesale.
But I see all the methods at both pages /api/doc/public and /api/doc/wholesale.

Is this possible to separate public and wholesale methods with areas (no annotations, all doc is in the .yml files)?

`nelmio_api_doc:
    documentation:
        info:
            title: Title
        servers:
            -   url: https://localhost
        paths:
            /api/public/dealer/{id}:
                $ref: '%base_url%/api/doc/paths/public.yml#/dealer'

            /api/public/client/{id}:
                $ref: '%base_url%/api/doc/paths/public.yml#/client'

            /api/wholesale/auth:
                $ref: '%base_url%/api/doc/paths/wholesale.yml#/auth'

            /api/wholesale/settings:
                $ref: '%base_url%/api/doc/paths/wholesale.yml#/settings'

        components:
            securitySchemes:
                ApiKey:
                    type: apiKey
                    in: query
                    name: key

    areas:
        public:
            path_patterns: [ ^/api/public ]
        wholesale:
            path_patterns: [ ^/api/wholesale ]
        default:
            path_patterns: [ ^/api(?!/doc) ]
`

**Comment by GuilhemN** [comment]
If I understood correctly what you're looking for is the field `nelmio_api_doc.areas.your_area.documentation`.

You should move the documentation of your paths under the documentation field of its corresponding area

**Comment by aidenko** [comment]
really appreciate. 
it works as expected
