### ISSUE TITLE
operationId should be string

### ISSUE THREAD

**Issue by Gemorroj** [nelmio/NelmioApiDocBundle#1743]
#1685

<img width="1444" src="https://user-images.githubusercontent.com/885731/98005619-4fa65200-1e02-11eb-9743-72b31160b9df.png" />

**Comment by GuilhemN** [comment]
Thanks for the report, it seems support for the null value was removed in `zircote/swagger-php` (see https://github.com/zircote/swagger-php/commit/70316e3411a203b73dab270f180b0f25e25f22fe#diff-95de59e4b4f717f2f8872b2209151efd4cfe46c688762478b229d88a10aaea22L166-L168)... I'll try to come up with another solution

**Comment by aario-k24** [comment]
Any updates?

**Comment by andreas5232** [comment]
Same problem here. :( 
Would be cool if there were any generic solution without having to update all annotations manually. So using the name attribute of the Route annotation would be probably the most convenient fix.

**Comment by giannign1** [comment]
Any updates?

**Comment by andreas5232** [comment]
As a quick workaround I'm currently deleting all occurrences of the operationId by using search and replace. Most Swagger/OpenApi tools seem to accept it then. But I'd love to have a better solution for this issue.

**Comment by maraerben** [comment]
My workaround:

```
<?php

/**
 * @Rest\Get("/items", name="getItems")
 * @OA\Get(operationId="getItems")
 */
public function getItems() { ... }
```

It would be the best to generate `operationId` based on route name, but this works fine as well for me.

**Comment by GuilhemN** [comment]
Should finally be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1907!
