### ISSUE TITLE
use @Model for a property

### ISSUE THREAD

**Issue by caminin** [nelmio/NelmioApiDocBundle#1744]
I have an issue using the bundle with annotations.

For example here is an entity, with a schema and a property with a description inside.
When I want to use this property as a returned value somewhere else, I don't know to repeat the description (see below).

I manage to do it by editing the yaml file, but that would mean putting every descriptions of every entities inside the yaml file (more than a hundred of properties...)

Is there a way to reference this property without putting it in the yaml file (with @Model for example)? 
(I REALLY want to use annotations instead)

For example, oyu can reference a class by 
@Model( MyClass::class)

Is there a @Model (MyClass::property) ?

Entity where the description is
```
/**
     * @ORM\Column( type = "string", length = 255 )
     *
     * @OA\Schema(
     *    schema = "harware_privateKey",
     *    @OA\Property(
     *      property = "private_key",
     *      type = "string",
     *      description = "Private key of the hardware",
     *      example = "bHLuKQR1dZrxSA5N8gzPG19a",
     *      maxLength = 255
     *    )
     * )
     *
     * @Groups( { "hardware_read" } )
     * @OA\Property(
     *    ref =  **@Model (type = harware_privateKey** 
     * )
     *
     * @var string $private_key
     */
    public $private_key;
```

Route where the property is returned, but no description because I didn't find a way to reference it as @Model
```
@Route( "/hardware/{hardwareKey}", name = "get_hardware", methods = { "GET" } )
   *
   * @OA\Get(
   *    path = "/hardware/{hardwareKey}",
   *    summary = "Get a hardware according the 'hardwareKey' parameter",
   *    tags = { "Hardware" },
   *    @OA\Parameter(
   *      name = "hardwareKey",
   *      in = "path",
   *      required = true,
   ========>      @OA\Schema( ref = **@Model (type =harware_privateKey** )
   *    ),
   *    @OA\Response(
   *      response = "200",
   *      description = "OK",
   *      @OA\JsonContent(
   *        @OA\Property( type = "string", property = "status", example = "ok" ),
   *        @OA\Property( type = "object", property = "hardware", ref = @Model( type = Hardware::class, groups = { "hardware_read" } ) )
   *      )
   *
   * @param string $hardwareKey
   * @param HardwareRepository $hardwareRepository
   * @return JsonResponse
   */
  public function getHardware ( $hardwareKey = null, HardwareRepository $hardwareRepository ) : JsonResponse
```

My Yaml where I don't want to put descriptions if possible
```
nelmio_api_doc:
    models: { use_jms: false }
    documentation:
        info:
            title: A2Api
            description: Description à mettre ici
            version: 1.0.0
            contact:
                email: contact@a2display.fr
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
```

**Comment by GuilhemN** [comment]
You may try to fix the names of your models using https://symfony.com/doc/current/bundles/NelmioApiDocBundle/alternative_names.html.
And then if the name of your model is `MyModel` for instance, you could reference one of its properties using:
```
@OA\Schema(ref="#/components/schemas/MyModel/properties/thepropertytoreferto")
```

This is working for me, however I'm not sure whether this is a syntax that is actually supported (https://swagger.io/docs/specification/using-ref/ is not very clear on that)

**Comment by caminin** [comment]
Hum, for this to work, we need to put something in the schema inside the yaml configuration file.

To be clear, we would like to use @Model with a property and not a class so that we don't have to edit the yaml file (sometimes, only a value is returned and not an object).

Is there a way to do that with @Model ? 

From my perspective, if I want to use ref="#/xxx/yyy" I need to put it inside the yaml file.

**Comment by GuilhemN** [comment]
> From my perspective, if I want to use ref="#/xxx/yyy" I need to put it inside the yaml file.

Actually no, using `@Model` enforces that the bundle creates a schema corresponding to your object in your documentation and the `@Model` annotation is then replaced with a reference to the generated schema.
But you can also enforce the creation of such a schema using your configuration:
```yaml
nelmio_api_doc:
    models:
        names:
            - { alias: MyClass, type: App\Entity\MyClass} # enforces that App\Entity\MyClass will be documented under #/components/schemas/MyClass
```

Then you can use references to properties of this class in your annotations using
```php
/**
 * @OA\Schema(ref="#/components/schemas/MyClass/properties/yourproperty")
 */
```
for instance.


To ease this, we could also add a field to `@Model` such as `subpath` (or `property`? but that would be less flexible) which could be used like this:
```php
/**
 * @OA\Schema(ref=@Model(MyClass::class, subpath="properties/yourproperty")
 */
```
PR welcome for this second option :)

**Comment by chrisguitarguy** [comment]
Going to close this for now (due to age), but also because the subpath thing isn't the move, IMO.

Instead, I'd recommend defining and referencing your own custom schemas and referencing them. Which would be inside the yaml file to define them:

```yaml
nelmio_api_doc:
  components:
    schemas:
      PrivateKey:
        type: string
        # etc ...
```

Then reference via `ref="#/components/schemas/PrivateKey"`, you'll be able to share the config you want.

**Comment by chrisguitarguy** [comment]
Or, alternatively, use a value object and put the annotation on top of it, which should work after https://github.com/nelmio/NelmioApiDocBundle/pull/1978

```
/**
  * @OA\Schema(...)
  */
final class PrivateKey
{

}
```
