### ISSUE TITLE
Unable to hide/exclude field

### ISSUE THREAD

**Issue by phazei** [nelmio/NelmioApiDocBundle#1746]
I'm using the annotations to build the docs and I've spent hours googling, but am unable to find any way to hide a parameter so it remains undocumented.

This is my Type:

```
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'secret_field',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => [
                        'description' => "no one should ever see this, exclude me"
                        'hidden' => true,
                        'display' => 'none'
                    ]
                ]
            )
```

And here's the "data_class" for it:

```
    /**
     * @var string
     * @SWG\Parameter(hidden=true)
     * Flamingo only returns a boolean indicating that the value is set, so it is safe to pass along
     */
    protected $secret_field;
```

The Parameter annotation just throws errors and doesn't show hidden as an available option.  The hidden in documentation does nothing.

How can I exclude this from appearing in the docs anywhere?

Is this possible?  

Using v3.4

**Comment by GuilhemN** [comment]
I don't really understand why you would want to have a parameter in your form and not document it. Could you explain what your use case is please?

This is not possible at the time but could easily be added to the [`FormModelDescriber`](https://github.com/nelmio/NelmioApiDocBundle/blob/3.x/ModelDescriber/FormModelDescriber.php) (see this [issue](https://github.com/nelmio/NelmioApiDocBundle/issues/1624#issuecomment-636013818) where I already answered this).

**Comment by phazei** [comment]
Sometimes there are dev only params.   Sometimes it might be deprecated and don't want anyone to know it's there.  Sometimes it's part of the form model for validation but is filled in with other methods.  There are many reasons.  Would be really nice to have since it's all generated so can't just be removed from the json.  
If it's marked as "hidden" or maybe "excluded" it should be ignored by the generator and not exist in the swagger json.

Our system has many micro-services ranging from Symfony 2.8 to 5, each being documented via multiple versions of this bundle.

How could I go about extending the FormModelDescriber to support this?  Or would it require a fork?  Would be lovely if it could be added as a feature.

**Comment by GuilhemN** [comment]
I submitted https://github.com/nelmio/NelmioApiDocBundle/pull/1752, it could be used like this:
```php
class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'secret_field',
                TextType::class,
                [
                    'required' => false,
                    'documentation' => false
                ]
            )
```
to hide fields.

Would it be acceptable for you?

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1752

**Comment by phazei** [comment]
Nice, thank you!
