### ISSUE TITLE
Add a description to FormType model?

### ISSUE THREAD

**Issue by phazei** [nelmio/NelmioApiDocBundle#1748]
Attempting to add a description to a form type, but it seems to be ignored.  For fields I add `documentation => [description=>"here"]` and that seems to work, but not for non basic types.

It's supported in swagger when I manually add it:
<img width="1572" alt="Screen Shot 2020-11-23 at 2 04 04 PM" src="https://user-images.githubusercontent.com/431395/100022402-f3e33f00-2d97-11eb-804d-280690881dbf.png">

But I've tried a few things and it doesn't show up:
```php
/**
 * Class UserDetailType
 * @package AppBundle\Form\Type\Signup
 * @SWG\Info(description="THIS IS SPARTA2")
 * @SWG\Parameter(description="THIS IS SPARTA3")
 * @SWG\Schema(description="THIS IS SPARTA4")
 * @SWG\Tag(description="THIS IS SPARTA5")
 * @SWG\Definition(description="THIS IS SPARTA6")
 * @ApiDoc(description="THIS IS SPARTA7")
 *
 */
class UserDetailType extends BaseType
{
```
and in the parent Type:
```php
class SignupDataType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'detail',
                UserDetailType::class,
                [
                    'constraints' => array(new Valid()),
                    'documentation' => [
                        'description' => 'THIS IS SPARTA',
                    ]
                ]
            )
```

Is this supported?  Am I using improper syntax?  I just want to add a description to the existing generated doc.

**Comment by GuilhemN** [comment]
Thanks for the report!

Actually I don't think I thought about that when I added form types support and no one complained about this so far.
We can easily add support of `@SWG\Definition` at the class level of the form type now though (see https://github.com/nelmio/NelmioApiDocBundle/pull/1751):
```php
/**
 * Add your description here.
 *
 * @SWG\Definition(description="Or you can also add it here")
 */
class YourFormType extends ... { ... }
```

would that suit your needs?

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1751

**Comment by phazei** [comment]
Thanks!
