### ISSUE TITLE
Route doesn't seem to be secured despite security config

### ISSUE THREAD

**Issue by marrahi8** [nelmio/NelmioApiDocBundle#1753]
Hello,

I just started using NelmioApiDoc and followed the documentation for the first time.
nelmio/api-doc-bundle: "v4.0.1"

I have not yet introduced the Bearer <JWT> token, I click the "Execute" button, the controller runs and prints "Hi there!". Shouldn't the annotation "@Security(name="Bearer")" along with the nelmio security config have prevented the execution of the Controller action due to authorization jwt not being provided ? I thought It wouldn't run until I passed the bearer token...

Following is the config and test controller code:

<img width="1123" alt="Captura de pantalla 2020-11-30 a las 19 41 22" src="https://user-images.githubusercontent.com/75272938/100650406-2b2b9000-3344-11eb-8f12-9f06b1a4567b.png">

<img width="547" alt="Captura de pantalla 2020-11-30 a las 19 37 18" src="https://user-images.githubusercontent.com/75272938/100650020-96c12d80-3343-11eb-9832-0cca9de9caf9.png">
<img width="442" alt="Captura de pantalla 2020-11-30 a las 19 37 55" src="https://user-images.githubusercontent.com/75272938/100650040-9e80d200-3343-11eb-9818-97608ccdd0be.png">

Thank you very much

**Comment by GuilhemN** [comment]
Hello,

This bundle is only about documentation, it does not secure your routes in any way.

To actually secure your routes with JWT, you may have a look at https://github.com/lexik/LexikJWTAuthenticationBundle for instance.

**Comment by marrahi8** [comment]
Ok thanks.
