### ISSUE TITLE
[v4.0] Schema's ref=@Model does not work anymore

### ISSUE THREAD

**Issue by zerkms** [nelmio/NelmioApiDocBundle#1758]
It looks like the documentation example

```
 * @SWG\Response(
 *     @SWG\Schema(ref=@Model(type=User::class))
 * )
```
does not work anymore. It generates no `content` whatsoever

```json
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
```

The example without `@Schema` works fine though

```
 * @SWG\Response(
 *     response=200,
 *     @Model(type=User::class)
 * )
```
generates
```json
                "responses": {
                    "200": {
                        "description": "",
                        "content": {
                            "application\/json": {
                                "schema": {
                                    "$ref": "#\/components\/schemas\/User"
                                }
                            }
                        }
                    }
                }
```

From debugging the `ModelRegister` it looks like because the `@Model` version goes through `$this->createContentForMediaType($mediaType, $properties, $annotation, $analysis);` which creates content for the `$annotation` (which is a `Response`) and the `@Schema ref` version does not reach there and does not create content at all.

UPD: implemented a quick-and-dirty fix, in `ModelRegister` after `annotation->ref = $this->modelRegistry->register(new Model($this->createType($model->type), $this->getGroups($model, $parentGroups), $model->options));` in the first condition add

```php
                $parent = $annotation->_context->nested;

                if ($parent instanceof OA\Response) {
                    $properties = [
                        '_context' => Util::createContext(['nested' => $parent], $parent->_context),
                        'ref' => $annotation->ref,
                    ];

                    foreach ($this->mediaTypes as $mediaType) {
                        $this->createContentForMediaType($mediaType, $properties, $annotation, $analysis);
                    }
                }
```

UPD2:

the
```
     *     @SWG\Schema(
     *         type="array",
     *         @SWG\Items(ref=@Model(type=Reward::class, groups={"full"}))
     *     )
```

annotation is broken as well

**Comment by GuilhemN** [comment]
Are you using OpenApi 3 and NelmioApiDocBundle v4? (I'm not completely sure as you use `@SWG`).

If you are using v4, this is actually a point mentioned in the upgrading guide: https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-4.0.md.

It doesn't make much sense in my opinion to support 
``` 
 * @SWG\Response(
 *     @SWG\Schema(ref=@Model(type=User::class))
 * )
```
as a `@Schema` is not allowed directly under a response in the spec and you have to specify the mime types.

We offer `@Response(..., @Model(...))` as syntactic sugar.

But honestly if you really want this feature I can merge a PR implementing it, I wouldn't have implemented it myself but it won't hurt me much if we support it.

**Comment by zerkms** [comment]
> Are you using OpenApi 3 and NelmioApiDocBundle v4? (I'm not completely sure as you use @SWG)

I just copied it from the example, in my code namespaces are correct.

> as a @Schema is not allowed directly under a response in the spec and you have to specify the mime types.

How would you implement an "array of @model" then?

**Comment by jacekpl** [comment]
@zerkms 
That will work for array of models:

```
* @OA\Response(response="200", description="Success",
*     @OA\JsonContent(type="array", @OA\Items(ref=@Model(type=Team::class)))
* )
```

**Comment by chrisguitarguy** [comment]
Closing as this BC break was intentional.
