### ISSUE TITLE
[v4.0] OpenAPI Extension inside response annotations

### ISSUE THREAD

**Issue by Johnson66666** [nelmio/NelmioApiDocBundle#1759]
### Description:
Hi.

According to [swagger.io](https://swagger.io/docs/specification/openapi-extensions/), OAS3 supports OpenAPI Extensions inside responses.

I try to use an Open API Extension to define a specific TTL for each different path Response. My goal is to add a [x-wso2-response-cache](https://apim.docs.wso2.com/en/latest/learn/api-gateway/response-caching/) extension like this, a different number of seconds for each route :
```
x-wso2-response-cache: 
    enabled: true
    cacheTimeoutInSeconds: 400
```

I can't find any way to achieve this using nelmio/api-doc-bundle 4.0 annotations...

### Steps to reproduce:
For example, I tried : 

```
    /**
     * @Route("client/v2//person/{person}", name="client_v2_person", methods={"GET"})
     *
     * @param Request $request
     * @param int $person
     * @return Response
     *
     * @OA\Tag(name="Person Collection"),
     * @OA\Get(
     *     description="Get Person",
     *     operationId="getPersonById",
     *     @OA\Response(
     *         response=200,
     *         description="Return person information by person Id",
     *         x={
     *             wso2-response-cache={
     *                 enabled=true,
     *                 cacheTimeoutInSeconds=400,
     *             }
     *         },
     *         @OA\JsonContent(
     *             @OA\Property(property="id", type="integer"),
     *             @OA\Property(property="name", type="array", @OA\Items()),
     *             @OA\Property(property="nationality", type="string"),
     *             @OA\Property(property="birth_date", type="string"),
     *             @OA\Property(property="birth_place", type="string"),
     *             @OA\Property(property="height", type="string")
     *         )
     *     ),
     *     @OA\Response(
     *         response=400,
     *         description="Resource not found",
     *         @OA\JsonContent(type="array", @OA\Items())
     *     ),
     *     @OA\Parameter(name="coach", in="path", @OA\Schema(type="string"), required=true, description="Person id")
     * )
     */
    public function GetPerson(Request $request, int $person): Response
    {
        // method code
    }
```

But all I get is an AnnotationException when I visit my OAS json page in http://mydomain.example.com/doc/client_v2.json

> Doctrine\Common\Annotations\
> AnnotationException
> [Semantical Error] Couldn't find constant wso2, method App\Controller\Client\V2\PersonController::GetPerson().

### Affected Product Version:
- Symfony v4.4.17
- nelmio/api-doc-bundle v4.0.1

### Environment details (with versions):
- OS: Debian 9.13

### My questions are : 
- Can I do it, and if so, how?
- If Nelmio doesn't support it yet, could you please work on it?

Thanks.

**Comment by Johnson66666** [comment]
Nobody? I think a pull request to support OpenAPI extensions is open here : https://github.com/nelmio/NelmioApiDocBundle/pull/1714

But continuous integration tests failed...

**Comment by GuilhemN** [comment]
I don't have any time to dedicate this right now unfortunately.
https://github.com/nelmio/NelmioApiDocBundle/pull/1714 needs some polish, mainly rebasing it on master and adding some tests (I don't think the tests failure was related).

If you'd like to submit a PR it would more than  welcome :)

**Comment by Johnson66666** [comment]
Hi, and thanks for your answer.

I see. I'm not sure if I understand why this pull request failed the Travis CI build, but I'll take a look.
