### ISSUE TITLE
MediaType object, file uploads question

### ISSUE THREAD

**Issue by jacekpl** [nelmio/NelmioApiDocBundle#1772]
Hello,

I have a REST api with PUT endpoint for file uploads as binary data. Is there a way to define is like in one of the examples in https://swagger.io/specification/#media-type-object? 
I mean that part:

```
# multiple, specific media types may be specified:
requestBody:
  content:
      # a binary file of type png or jpeg
    'image/jpeg':
      schema:
        type: string
        format: binary
    'image/png':
      schema:
        type: string
        format: binary        
```

I would like to achieve: requestBody with binary content with possible two types for upload: image/jpeg and image/png.
Any help appreciated :-)

**Comment by GuilhemN** [comment]
Hi,

Have you tried:
```
/**
 * @OA\Request(
 *      @OA\MediaType(
 *           mediaType="image/jpg",
 *           @OA\Schema(
 *               type="string",
 *               format="binary"
 *           ),
 *      ),
 *      @OA\MediaType(
 *           mediaType="image/png",
 *           @OA\Schema(
 *               type="string",
 *               format="binary"
 *           ),
 *      )
 *   )
 */
```
?

**Comment by jacekpl** [comment]
I've tried several, with n luck. But different thank yours.
That one works (with RequestBody instead of Request). 

Thank you!
