### ISSUE TITLE
Ignore parts of model docblock comments

### ISSUE THREAD

**Issue by pdugas** [nelmio/NelmioApiDocBundle#1779]
Is there a way to ignore parts of docblock comments so they don't appear in the api docs? I have developer details and notes in comments for entity and model properties and don't want these to appear in the output.  For example:

```php
/**
 * Entity Title
 *
 * This is the entity description.
 * 
 * These are internal details that I don't want in the API docs.
 * 
 * @ORM\Entity
 */
class Eg
{
    /**
     * Property Title
     *
     * This is the property description.
     * 
     * These are internal details that I don't want in the API docs.
     * 
     * @ORM\Column(type="string")
     */
    private ?string $eg = null;
}
```

Or, is the solution to put these comments in separate blocks? (yuck)

**Comment by pdugas** [comment]
Oh, I should note that I tried using the `{@internal ...internal details here...}` as suggested [by phpDoc]( https://docs.phpdoc.org/latest/guide/references/phpdoc/tags/internal.html) but it was included verbatim in the output.

**Comment by pdugas** [comment]
I just discovered comments after the first `@annotation` in the docblock are not included. SO, I can adjust the example above as below to achieve what I'm looking for.

```php
/**
 * Entity Title
 *
 * This is the entity description.
 * 
 * @ORM\Entity
 * 
 * These are internal details that I don't want in the API docs.
 */
class Eg
{
    /**
     * Property Title
     *
     * This is the property description.
     * 
     * @ORM\Column(type="string")
     * 
     * These are internal details that I don't want in the API docs.
     */
    private ?string $eg = null;
}
```

**Comment by GuilhemN** [comment]
You could also use `@SWG\Property(description="")` to explicit that you want an empty description in the documentation
