### ISSUE TITLE
Allow for injection of DocumentationController into another controller as a service

### ISSUE THREAD

**Issue by m-graham** [nelmio/NelmioApiDocBundle#1782]
Hi,

I want to serve the api.json as part of a twig template when a request is made to a certain page in my app. Is there any easy way that this could be done? I couldn't find any documentation on this and most of the services are private. 

If there's no easy way to do this, and you think this feature could also be useful I could add it a helper function to the Documentation Controller (I think that would be the best place for it, but I may be wrong). The Documentation Controller could be injected as a service to any controller then and the spec could be served from any controller.

Thanks!

Edit: To give a better example, I was thinking something like this could be done in the documentation controller:

```php
public function __invoke(Request $request, $area = 'default')
{
    $this->generate($request, $area);
    return new JsonResponse($spec);
}

public function generate(Request $request, $area = 'default') {
    if (!$this->generatorLocator->has($area)) {
        throw new BadRequestHttpException(sprintf('Area "%s" is not supported as it isn\'t defined in config.', $area));
    }

    /** @var OpenApi $spec */
    $spec = $this->generatorLocator->get($area)->generate();

    if ('' !== $request->getBaseUrl()) {
        $spec->servers = [new Server(['url' => $request->getSchemeAndHttpHost().$request->getBaseUrl()])];
    }

    return $spec;
}
```

**Comment by GuilhemN** [comment]
Have you tried using render in your twig template? https://stackoverflow.com/questions/49571747/calling-controller-from-twig#49574536
