### ISSUE TITLE
How to add example array values in a model

### ISSUE THREAD

**Issue by TerjeBr** [nelmio/NelmioApiDocBundle#1786]
I have a model class like this
```
class Contact
{
    /**
     * @Assert\NotNull
     * @Assert\Type("array")
     * @var string[]
     */
    public $roles;

    /**
     * @Assert\NotBlank
     * @var string
     */
    public $email;
}
```

How can I add examples of roles to my model?

I tried something like this:
```
class Contact
{
    /**
     * @Assert\NotNull
     * @Assert\Type("array")
     * @var string[]
     * @OA\Property(example="[""sales"", ""legal""]")
     */
    public $roles;

    /**
     * @Assert\NotBlank
     * @var string
     */
    public $email;
}
```
But it does not look right in the documentation, it shows as a string inside quotes instead of a real array. How should it be done?

**Comment by GuilhemN** [comment]
Maybe the following would do?
```
@OA\Property(OA\Items(examples=["sales", "legal"]))
```

**Comment by TerjeBr** [comment]
[Semantical Error] Couldn't find constant OA\Items, property App\Model\Contact::$roles

**Comment by TerjeBr** [comment]
Changed it to 
```
@OA\Property(@OA\Items(examples=["sales", "legal"]))
```

Then I got:
```
[Syntax Error] Expected PlainValue, got '[' at position 105 in property App\Model\Contact::$roles.
```

**Comment by TerjeBr** [comment]
Thank you GuilhemN for trying to help. I am still stuck on this.
Any more help from anyone will be greatly appreciated.

**Comment by GuilhemN** [comment]
I guess it should be:
```
@OA\Property(@OA\Items(examples={"sales", "legal"}))
``` (I did a typo)

**Comment by TerjeBr** [comment]
Now I get this error:
,,,
User Notice: Unexpected field "examples" for @OA\Items(), expecting "ref", "schema", "title", "description", "maxProperties", "minProperties", "required", "properties", "type", "format", "items", "collectionFormat", "default", "maximum", "exclusiveMaximum", "minimum", "exclusiveMinimum", "maxLength", "minLength", "pattern", "maxItems", "minItems", "uniqueItems", "enum", "multipleOf", "discriminator", "readOnly", "writeOnly", "xml", "externalDocs", "example", "nullable", "deprecated", "allOf", "anyOf", "oneOf", "not", "additionalProperties", "additionalItems", "contains", "patternProperties", "dependencies", "propertyNames", "const", "x"
,,,

**Comment by TerjeBr** [comment]
Ok, this did it:
```
     @OA\Property(example={"sales", "legal"})
```

Thank you so much for your help.
