### ISSUE TITLE
Nullable refs

### ISSUE THREAD

**Issue by raziel057** [nelmio/NelmioApiDocBundle#1802]
Hello,

I would like to add a nullable property in a DTO like that, but currently the nullable is not reflected in the resulting json.

```php
    /**
     * @var Status|null
     *
     * @OA\Property(ref=@Model(type=PTC\ApiBundle\TOEntity\Status::class), nullable=true)
     */
    private $status;
```

As result I got:

```json
"status":{
    "$ref":"#\/components\/schemas\/Status"
}
```

I'm not sure that we just need to add a nullable property or if we should create the fragment in a different way as here: 
https://github.com/zircote/swagger-php/commit/615941e42d31dda89add9508c9321daac938846a

When using Rest API Generator from .net if it works correctly as soon as we add the nullable true like bellow.

```json
"status":{
    "$ref":"#\/components\/schemas\/Status",
    "nullable": true
}
```

After it's not clear what should be done in OA spec: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md#referenceObject

**Comment by raziel057** [comment]
The problem is in fact related to https://github.com/zircote/swagger-php/issues/918

**Comment by GuilhemN** [comment]
Well this is not supported by the RFC.

I think you can however use something like:
```
@OA\Schema(allOf = { @OA\Schema( ref=@Model (...)) },nullable =true)
```
Would that be acceptable?

**Comment by raziel057** [comment]
I tried using oneOf and anyOf but it’s not working. The rest client generator create a Collection on object.

**Comment by chrisguitarguy** [comment]
Seems like this is a `wontfix` since it's not supported by the spec itself. OpenAPI 3.1 has a `null` type, so this would be the recommended way it seems: https://github.com/zircote/swagger-php/issues/918#issuecomment-1047304070
