### ISSUE TITLE
Install on SF5.2

### ISSUE THREAD

**Issue by yannickgranger** [nelmio/NelmioApiDocBundle#1805]
On a fresh project with SF5.2, composer req package. Then, i got the error :

The controller for URI "/api/doc" is not callable: Controller "nelmio_api_doc.controller.swagger_ui" does neither exist as service nor as class.

The bundle is registered by flex

**Comment by javierJarupkin** [comment]
hello, how did you solve it?

**Comment by livevasiliy** [comment]
> hello, how did you solve it?

You need install `twig` and `assert` bundle

```sh
composer require twig assert
```
