### ISSUE TITLE
Change exclusiveMaximum\exclusiveMinimum from bool to numeric

### ISSUE THREAD

**Issue by beerline** [nelmio/NelmioApiDocBundle#1813]
Hi and thank you for this great library!

According Changelog `draft-wright-json-schema-validation-01` of [JSON Schema Validation specs](http://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.2.3) `exclusiveMaximum` and `exclusiveMinimum`, needs to changed from bool to numeric

**Comment by GuilhemN** [comment]
Not sure what to do here, if we do this change, we might break older systems relying on this.
And it's still annotated as bool in zircote/swagger-php (see https://github.com/zircote/swagger-php/blob/master/src/Annotations/Schema.php#L115-L120).

Maybe we should ask there what they think about this first?

**Comment by beerline** [comment]
@GuilhemN i think we can apply changes from `draft-wright-json-schema-validation-01` and increase major version of library, because this changes will broke compatible

**Comment by GuilhemN** [comment]
Wait it's still a draft? Then I'd say let's wait and see if it's adopted and promoted.

But bumping to a major version just for this seems like a no go. It's quite complicated to get people to migrate and it doesn't seem worth it.

**Comment by beerline** [comment]
@GuilhemN i agree with you, it is seems weird that it is in `draft` sections, but the current version officially is ` 2020-12`, and  link `Json Schema validation` leads to `draft-wright-json-schema-validation-01`. So we can assume that `draft-wright-json-schema-validation-01` is current version/ 

![Снимок экрана 2021-05-15 в 15 32 29](https://user-images.githubusercontent.com/7195911/118363087-c4bdc580-b5a3-11eb-8369-56cd9ea8150d.png)

about bumping version.
I think old version will be fine for those who not ready to migrate.
And for new ones better to follow last version of specification.
