### ISSUE TITLE
Feature request: support for compound validation rule

### ISSUE THREAD

**Issue by melihovv** [nelmio/NelmioApiDocBundle#1817]
For this snippet open api is successfully generated
```php
final class SomeWebRequest
{
    /**
     * @Assert\Type("numeric")
     * @Assert\NotBlank()
     * @Assert\Positive()
     */
    private $someParam;
}
```
but for this - it doesn't
```php
namespace App\Validator\Constraints;

use Symfony\Component\Validator\Constraints\Compound;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @Annotation
 */
class SomeValidationRule extends Compound
{
    protected function getConstraints(array $options): array
    {
        return [
            new Assert\Type('numeric'),
            new Assert\NotBlank(),
            new Assert\Positive(),
        ];
    }
}

namespace App\Controller;

use App\Validator\Constraints as AcmeAssert;

final class SomeWebRequest
{
    /**
     * @AcmeAssert\SomeValidationRule
     */
    private $someParam;
}
```

Is it possible to make support for compound validation rules? https://symfony.com/doc/current/reference/constraints/Compound.html

**Comment by GuilhemN** [comment]
Sure, it probably wouldn't be too complicated, it's just about parsing browsing the constraint in `Compound::$constraints` (which is a public field) in https://github.com/nelmio/NelmioApiDocBundle/blob/1899a9e7ba87ae9e27004af14413793a016479b7/ModelDescriber/Annotations/SymfonyConstraintAnnotationReader.php#L94.

Would you like to submit a pull request?

**Comment by melihovv** [comment]
I would like, thank you :)

**Comment by kirya-dev** [comment]
Great feature! We waiting for it
