### ISSUE TITLE
[BUG] /api/doc.json is enabled by default, though documentation says otherwise

### ISSUE THREAD

**Issue by yyaremenko** [nelmio/NelmioApiDocBundle#1824]
The [documentation](https://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html) says to enable **/api/doc.json** route, you have to register a corresponding route in routes.yml. This is not true. This route is enabled by default.

Either corresponding section in documentation must be updated, or corresponding code must not enable the route by default.

**Comment by chrisguitarguy** [comment]
Seems like the route is added if using Symfony flex, and the docs seem to note this by saying [if not using flex](https://symfony.com/bundles/NelmioApiDocBundle/current/index.html).

<img width="805" alt="Screen Shot 2022-05-16 at 10 04 54" src="https://user-images.githubusercontent.com/1010392/168624086-23348b24-3f4c-425b-b397-bc28c0c1d82c.png">

**Comment by yyaremenko** [comment]
Well, looks like they updated the doc formatting - the issue was submitted almost a year ago, and the original doc looked like

https://github.com/nelmio/NelmioApiDocBundle/blob/730feba2d9d55089f18526416b58c185d2accd8b/Resources/doc/index.rst

From the formatting of back then, it was unclear that 
> To browse your documentation with Swagger UI, register the following route:
relates to the case of not using Flex

Anw, thank you.
