### ISSUE TITLE
New version for Symfony 5.3

### ISSUE THREAD

**Issue by tarlepp** [nelmio/NelmioApiDocBundle#1825]
Symfony 5.3 has been released and this bundle needs new version that contains fix #1808 for that.

**Comment by derrabus** [comment]
I was about to ask the same thing. 🙂 

In my project, I'm developing against the master branch of this package at the moment and it appears pretty stable. Now that Symfony 5.3 is out, a compatible stable release of this bundle would be awesome.

**Comment by gnutix** [comment]
It would be great if the fix could be available in the 3.x version of this bundle too, as migrating to 4.x requires to upgrade Swagger from 2.x to 3.x too.

**Comment by derrabus** [comment]
@gnutix The fix has been applied to the 3.x branch, but there's no stable release either yet. But requiring `"nelmio/api-doc-bundle": "^3.8.3@dev"` in your composer.json should give you a dev snapshot that contains the fix.

**Comment by gnutix** [comment]
Works indeed, thanks for the tip! I didn't know you could use a tag that "does not exist yet" suffixed with `@dev`.. and I prefer it to my composer patch idea. ;)

**Comment by GuilhemN** [comment]
Sorry for the delay, this is now fixed: I just released [4.3.0](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.3.0).

The master branch is indeed pretty stable as I do my best to not merge PRs breaking stuff but in case it happens it's always better to depend on a stable release :)

**Comment by derrabus** [comment]
Thank you, @GuilhemN! ❤️

**Comment by gnutix** [comment]
And version `3.9.0` was releases for those on 3.x.
