### ISSUE TITLE
[Question] Unable to exclude a group of paths?

### ISSUE THREAD

**Issue by daniele-andriani-io** [nelmio/NelmioApiDocBundle#1826]
Reading the documentation you should be able to ignore parts of the documentation creating Areas, unfortunately the settings don't seem to take in account excluding a whole chunk.

I'm using API-platform for part of a project and Nelmio for an other. Everything coming from API-platform is prefixed with `/v1` everything coming from Nelmio is either prefixed with `/api` or `/api2`. Based on the documentation I have tried the following:

1. I've tried to create a default area with a `path_patterns` which would only contain `/api` and `/api2`. This doesn't work.
2. I've tried to create a default area with a `path_patterns` which would only contain `/api` and `/api2` and excludes `/v1`. This doesn't work.

It seems that exclusion only works on the second element of a path as `/api(?!/doc$)` does exclude the `/api/doc` path from the documentation. I've seen many posts on this subject on Stackoverflow but never have I found a correct answer. Can anyone help me out here?

**Comment by chrisguitarguy** [comment]
Can you show your example of path pattern regex?

I'm going to close this for now due to age and pending feedback.
