### ISSUE TITLE
Invalid requirement for phpdocumentor/reflection-docblock

### ISSUE THREAD

**Issue by Mairu** [nelmio/NelmioApiDocBundle#1835]
In the current composer.json the version constraint for phpdocumentor/reflection-docblock is ^3.1|^4.4|^5.0

But there is not 4.4 version of that package, the latest 4.x is 4.3.4 -> https://packagist.org/packages/phpdocumentor/reflection-docblock

**Comment by GuilhemN** [comment]
Indeed, thanks for the report!
I believe this was done by mistake.

This is fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1948.
