### ISSUE TITLE
swagger-php updates

### ISSUE THREAD

**Issue by DerManoMann** [nelmio/NelmioApiDocBundle#1847]
Hi there,

This is just a heads up that as of version 3.2.0 swagger-php has deprecated the `\OpenApi\scan()` method as well as a few other things. Braodly speakling we are trying to get rid of managing things via static properties.

Other changes comming soon ™️ include removal of the static `Logger` class in favor of a configurable PSR logger and other things...

See: https://github.com/zircote/swagger-php/releases/tag/3.2.0

Any questions, feel free to ping me.

Cheers, mano

**Comment by GuilhemN** [comment]
https://github.com/nelmio/NelmioApiDocBundle/pull/1916 added support for v4 and fixed some constants usage, hopefully we should be quite good now.
