### ISSUE TITLE
Fix Symfony\Component\PropertyInfo\Type::getCollectionValueType() deprecation notice in symfony 5.3

### ISSUE THREAD

**Issue by kappa1389** [nelmio/NelmioApiDocBundle#1856]
I get this deprecation notice
Since symfony/property-info 5.3: The "Symfony\Component\PropertyInfo\Type::getCollectionValueType()" method is deprecated, use "getCollectionValueTypes()" instead.

The deprecated method is called in these files:
ObjectPropertyDescriber, ModelRegistry, ArrayPropertyDescriber

**Comment by FarhadKh** [comment]
Also we got this deprecation notice:
Since symfony/property-info 5.3: The "Symfony\Component\PropertyInfo\Type::getCollectionKeyType()" method is deprecated, use "getCollectionKeyTypes()" instead.

**Comment by GuilhemN** [comment]
Closing as it was fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/1863.
This will be released soon.
