### ISSUE TITLE
Rename a schemas

### ISSUE THREAD

**Issue by adelinoo** [nelmio/NelmioApiDocBundle#1867]
Hello,
i have multiple Response using a model by diffrent groups
`
@OA\Response(
  response=200,
  @OA\Schema(
...
    @OA\Property(
            property="test",
            type="object",
            ref=@Model(type=Test::class, groups={"read"})
   )
`

`
@OA\Response(
  response=500,
  @OA\Schema(
...
    @OA\Property(
            property="test",
            type="object",
            ref=@Model(type=Test::class, groups={"minimal"})
   )
`

in UI, i have two blocs of schema with name: **test1** and **test2**.

There's a way to give a specific name for each Model, like an alias
`
ref=@Model(type=Test::class, groups={"read"}, alias='TestResponse200')
`

Thanks.

**Comment by GuilhemN** [comment]
Sorry for the delay... You can actually use "Alternative names", this page may help you: https://symfony.com/bundles/NelmioApiDocBundle/current/alternative_names.html.
