### ISSUE TITLE
How to register custom processor?

### ISSUE THREAD

**Issue by DJZT** [nelmio/NelmioApiDocBundle#1871]
I wanna register my custom processor. How and where can I do it? 
For example this:
https://github.com/zircote/swagger-php/tree/master/Examples/processors/schema-query-parameter

**Comment by juliusstoerrle** [comment]
How are you generating your documentation? (See the two options here: https://zircote.github.io/swagger-php/guide/generating-openapi-documents.html)

You should be able to pass your processor to the cli script:
`./vendor/bin/openapi --processor <FQCN\To\Your\CustomProcessor> -o openapi.yaml app`

If you are using PHP directly, [this file from the examples](https://github.com/zircote/swagger-php/blob/7a204730e13e4b60cb9d500d2c9de7ffb9bcc395/Examples/processors/schema-query-parameter/scan.php) shows how you can add processors on your generator instance.

Were you able to solve your issue already or does this resolve your issue?

**Comment by juliusstoerrle** [comment]
It does not seem to be possible with the bundle at the moment, based on what I see [here](https://github.com/nelmio/NelmioApiDocBundle/blob/14383f4ee5cab468ec1549097943cf31f05d4463/ApiDocGenerator.php#L114).

Were you able to solve your issue already? If not you could create a PR where you define a service tag (there seems to be no upstream marker interface) and than [add them](https://github.com/nelmio/NelmioApiDocBundle/blob/5ed0d31294afd1cbc1c38cc33b81c3abcaf16a6a/DependencyInjection/NelmioApiDocExtension.php#L75) to the [ApiDocGenerator](https://github.com/nelmio/NelmioApiDocBundle/blob/14383f4ee5cab468ec1549097943cf31f05d4463/ApiDocGenerator.php) class.

**Comment by Luehrsen** [comment]
This has been resolved in #2149 and has been released in `v4.14.0`. This is roughly how you do it:

1) Generate a custom process as per the [official `swagger-php` examples](https://github.com/zircote/swagger-php/blob/master/Examples/processors/schema-query-parameter/SchemaQueryParameter.php) in your symfony app.
2) Register the processor with the tag `nelmio_api_doc.swagger.processor` [as described here](https://symfony.com/doc/current/service_container/tags.html).
3) The custom processor is now used in the generator.

Note: You can influence WHEN the processor is run by giving the tag a [`before`](https://github.com/zircote/swagger-php/blob/a70a5dc5db26183c86f589ff3d76fb11e141fc58/src/Generator.php#L306) attribute. The attribute takes the FQN of an existing processor and adds your custom processor right before it.
