### ISSUE TITLE
Symfony serializer groups

### ISSUE THREAD

**Issue by pkly** [nelmio/NelmioApiDocBundle#1886]
Hi, we have jms installed because of legacy reasons, but we use the symfony serializer for all our entities, as a lot of things happen real-time.
The issue is recently we started using the symfony serializer groups, and were unable to get them working in nelmio easily.
Is there a way I can actually have fields that have specific groups shown when displaying my models in nelmio? It seems it's only supporting JMS groups.

**Comment by pkly** [comment]
Yes, all it does is make all my models disappear.
Since the symfony serializer is much better in 5.x and even in 4.4 which we're still using it's perfectly fine, we'd rather not use jms simply so we can have 1:1 api stuff.
I could probably look into it more, I'm not quite sure how the JMS groups are found and detected, but if the bundle itself checks the fields then a callback check could be added (possibly hidden behind a config option by default?) for the symfony annotation for groups?
the `@SerializedName` also aren't supported, which is just irritating more than anything, for now we just create separate classes for the api responses so it's clean enough

**Comment by GuilhemN** [comment]
We're trying to replicate the behavior of the serializers, and only properties that would  be deserialized/serialized by the Symfony serializer appear in the Nelmio documentation.

One possibility I see is that your fields are configured with JMS groups annotations but not with the Symfony `@Groups` annotation, are they?
Without further details on how you call `@Model` and the look of your models themselves it will be complicated to help further unfortunately.

**Comment by pkly** [comment]
We do have JMS installed, but don't actually use it (leftovers), instead we use the Symfony groups.

What I wanted to be able to do is to pass an entity class with the groups for symfony serialization, but i'm pretty sure they're just ignored instead.

**Comment by herndlm** [comment]
please check if https://github.com/nelmio/NelmioApiDocBundle/pull/2342 might be useful for this case

**Comment by pkly** [comment]
This is a 3 year old issue and I don't even remember what exactly the issue is. I'm pretty sure we've since removed jms completely and it works fine. The issue was never disabling jms on context, it was that without jms you'd get no results, if I remember correctly.
