### ISSUE TITLE
Any plans to support PHP 8 Attributes for OpenApi annotations? 

### ISSUE THREAD

**Issue by acornforth** [nelmio/NelmioApiDocBundle#1893]

**Comment by GuilhemN** [comment]
Not really up to this repository, you may have a look at https://github.com/zircote/swagger-php/issues/806

**Comment by akalineskou** [comment]
@GuilhemN https://github.com/nelmio/NelmioApiDocBundle/pull/1931 this adds support for the annotation reader to work with those attributes
