### ISSUE TITLE
How to set the operationId?

### ISSUE THREAD

**Issue by IvoPereira** [nelmio/NelmioApiDocBundle#1895]
In the [Bundle documentation](https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#using-the-bundle), it is not specified in any way on how to define the operation id of each REST resource.

The example given where this should be possible is:
```php
@Route("/api/{user}/rewards", methods={"GET"})
```

I assumed eventually passing an `operation="getUserRewards"` or `operationId="getUserRewards"` would work but it does not seem to do the job.

What is the recommended way of setting the operation id using Nelmio?

**Comment by IvoPereira** [comment]
Just found out, but it seems I need to repeat myself (in the method) for it to recognize the operationId.

```php
     * @Route("/api/{user}/rewards", methods={"POST"}, name="get_user_rewards")
     * @OA\Post(
     *     operationId="getUserRewards",
     * )
```

Feel free to comment if you have a better approach.

**Comment by webdevilopers** [comment]
```php
#[Route('/person/add', name: 'personAdd', methods: ['post']
```

In the current version using this example the bundle will automatically generate the following `operationId`:
**post_personAdd**

I'm not sure if prefixing the route name with the HTTP method is the (desired) default behaviour for OpenAPI Doc?
