### ISSUE TITLE
How to define a custom Form Type name ?

### ISSUE THREAD

**Issue by pdoreau** [nelmio/NelmioApiDocBundle#1899]
When adding Model annotation linked to a FormType : 
```
* @OA\RequestBody(
*     @OA\JsonContent(
*         ref=@Model(type=CustomerType::class)
*     )
* )
```
The generated result is
![image](https://user-images.githubusercontent.com/2128594/140499393-67666fe6-1bd3-4543-bc09-9a80b926a5e1.png)

API consumers reading the doc are not supposed to know about Form Types.

Is it possible in that case to display a Customer schema type ?

**Comment by GuilhemN** [comment]
I believe you could use alternative names: https://symfony.com/bundles/NelmioApiDocBundle/current/alternative_names.html
