### ISSUE TITLE
Symfony 4.4 Incoompatibility in 4.5.0 and Later

### ISSUE THREAD

**Issue by chrisguitarguy** [nelmio/NelmioApiDocBundle#1901]
https://github.com/nelmio/NelmioApiDocBundle/blob/v4.5.0/Model/ModelRegistry.php#L147-L148

uses `getCollection{Key,Value}Types` directly, which are not available in Symfony 4.4: https://github.com/symfony/symfony/blob/4.4/src/Symfony/Component/PropertyInfo/Type.php

Somewhat suprised I haven't hit this in production yet, but I do make heavy use of aliases so likely not getting to the point where `modelToArray` is used in a log message.

**Comment by GuilhemN** [comment]
Indeed, thanks for the report! This was apparently not covered by our test cases...
This should be fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/1910
