### ISSUE TITLE
disable_default_routes not present in 4.x

### ISSUE THREAD

**Issue by roger-codina** [nelmio/NelmioApiDocBundle#1915]
Hi,

As I commented on this PR: https://github.com/nelmio/NelmioApiDocBundle/pull/1868 
merged on october 6, the `disable_default_routes` option for default area has been only released on 3.x versions.

However, the FAQs about 4.x: https://symfony.com/bundles/NelmioApiDocBundle/4.x/faq.html#disable-default-section
are refering to this feature, so I assume that this is a feature that should also be present on 4.x versions.

As you can see, there isn't any code about that on version 4.6.2 tree:
https://github.com/nelmio/NelmioApiDocBundle/blob/v4.6.2/DependencyInjection/Configuration.php#L52

Could you please add those changes to a newest 4.X.Y patch version tag?
Thanks.

**Comment by silentgecko** [comment]
Had the same issue, after some trying this worked for me (I'm really not that of a regex pro):

`    areas: # to filter documented areas
        default:
            path_patterns:
                - ^\/[^_|^doc]`

removes every route which starts with /_ (for e.g. /_profiler) and /doc*
My API is living in root folder, so no /api prefix.

**Comment by GuilhemN** [comment]
Indeed this was not released yet (see https://github.com/nelmio/NelmioApiDocBundle/compare/v4.6.2...master).
I'll try to make a release in the next days ;) You can ping me in case I don't.

**Comment by roger-codina** [comment]
Thank you @GuilhemN !
I see that it has been added in the 4.7.0
