### ISSUE TITLE
How to eneable anchor links?

### ISSUE THREAD

**Issue by esbobkov** [nelmio/NelmioApiDocBundle#1917]
Hello!

How to enable anchor links to the specific API method, like this https://petstore.swagger.io/#/pet/addPet

Why anchor links not work in NelmioApiDocBundle?

**Comment by alshenetsky** [comment]
Hi @esbobkov.

Just extend a template as described in this article:
https://symfony.com/bundles/NelmioApiDocBundle/current/customization.html

```
{#
    Change swagger UI configuration
    All parameters are explained on Swagger UI website:
    https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
#}
{% block swagger_initialization %}
    <script type="text/javascript">
        window.onload = loadSwaggerUI({
            defaultModelsExpandDepth: -1,
            deepLinking: true,
        });
    </script>
{% endblock %}
```

All you need is to set custom Swagger UI param **deepLinking** to **true**

**Comment by GuilhemN** [comment]
Closing as this was fixed :)
Thank you @alshenetsky!
