### ISSUE TITLE
Latest version crashes if symfony/serializer is not installed 

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#1937]
`Error: Class "Symfony\Component\Serializer\Annotation\DiscriminatorMap" not found` after updating to 4.8

Because the new `getAnnotation` do not check if a class exists.

https://github.com/nelmio/NelmioApiDocBundle/blob/16608de67f01deee829e6ce50463fc8665ae448b/ModelDescriber/ObjectModelDescriber.php#L192

and it's called with a class of the symfony/serializer package

https://github.com/nelmio/NelmioApiDocBundle/blob/16608de67f01deee829e6ce50463fc8665ae448b/ModelDescriber/ObjectModelDescriber.php#L75

My guess is that the doctrine annotation reader was ignoring unknown class, but not the new one.

Not sure of what the fix should be

**Comment by GuilhemN** [comment]
Thanks for the report!

I investigated a little bit and `$r->getAttributes` throws when looking for an inexistent class AND the flag `\ReflectionAttribute::IS_INSTANCEOF`.

I see two solutions:
- instanciating all attributes like in https://github.com/symfony/symfony/blob/60ce5a3dfbd90fad60cd39fcb3d7bf7888a48659/src/Symfony/Component/Serializer/Mapping/Loader/AnnotationLoader.php#L158-L162 and then checking for `instance of`
- do not retrieve the annotations if the annotation class does not exist.

I guess second option would be safer as instantiating all annotations may break things unexpectedly.

**Comment by magnetik** [comment]
I've tried something in the pull request. It works locally.
