### ISSUE TITLE
Missing #[PathParameter] attribute support

### ISSUE THREAD

**Issue by alshenetsky** [nelmio/NelmioApiDocBundle#1939]
#[PathParameter] attribute, which is very handy feature (https://github.com/zircote/swagger-php/blob/master/docs/Migrating-to-v4.md#the-pathparameter-annotation) is not fully supported right now. As I see it, it could not be parsed when this attribute targets method's parameter, not method itself.

Would be great to support such case.

**Comment by GuilhemN** [comment]
Thank you for the report!
I submitted https://github.com/nelmio/NelmioApiDocBundle/pull/1973 which should fix your issue :)
