### ISSUE TITLE
Conflict with zircote/swagger-php:4.1.0 and new required OpenAPI:3.1.0 version

### ISSUE THREAD

**Issue by michaljusiega** [nelmio/NelmioApiDocBundle#1940]
Related to: https://github.com/zircote/swagger-php/pull/1030
PR for issue in swagger-api: https://github.com/swagger-api/swagger-ui/pull/7719

It's high probability that we need to bump public resources because PR will be merged to **master** branch.
Actual version implemented into bundle now is **3.52.0** (https://github.com/nelmio/NelmioApiDocBundle/pull/1869), currently available version is **4.1.3**. 
See changes in: https://github.com/swagger-api/swagger-ui/compare/v3.52.0...v4.1.3

This is looks like now for UI because is blocked by swagger-api:
![obraz](https://user-images.githubusercontent.com/16488888/147659277-884dbca5-d0c7-4387-8d24-992249d3268c.png)

Maybe we need a bad-looking workaround to fix these situation until PR has been not merged and released ?

**Comment by michaljusiega** [comment]
I forgot about bundle configuration. https://github.com/nelmio/NelmioApiDocBundle/issues/1943#issuecomment-1003715495 see for more details.

**Comment by horlyk** [comment]
I would also at least lock this dependency to a bugfix version update, not a feature. Tired to downgrade it manually 😢

**Comment by GuilhemN** [comment]
This should be fixed by the latest release of zircote/swagger-php https://github.com/zircote/swagger-php/releases!

**Comment by michaljusiega** [comment]
Thanks!
