### ISSUE TITLE
after upgrading to symfony 5.4, got error "Unable to render this definition"

### ISSUE THREAD

**Issue by rifansi** [nelmio/NelmioApiDocBundle#1944]
Hi,
I just upgraded symfony to 5.4 from 5.3.
Then /api/doc is not working properly.
Not really sure where I should put the Swagger or OpenAPI version.
Could someone please help me?

Im using `"nelmio/api-doc-bundle": "^4.8.1"`

![image](https://user-images.githubusercontent.com/16570995/147997233-d4a95bce-e03f-4c5c-bf92-8416f8675dd1.png)

**Comment by magnetik** [comment]
The bundle now generated an openapi 3.1 schema, but swagger-ui do not support it upstream : https://github.com/swagger-api/swagger-ui/issues/5891

Not sure how the openapi schema version can be forced

**Comment by magnetik** [comment]
How you can configure the version : https://github.com/nelmio/NelmioApiDocBundle/issues/1943#issuecomment-1003715495

**Comment by rifansi** [comment]
thanks @magnetik it's working!
