### ISSUE TITLE
Nelmio Doc Page is blank

### ISSUE THREAD

**Issue by SoboLAN** [nelmio/NelmioApiDocBundle#1956]
Hello. I can't get my Nelmio doc page (`/api/doc`) to work, no matter what I try. I'm sure I'm missing something, but I can't figure it out.
I'm using Symfony 5.3 / NelmioApiDocBundle 4.8.2.

Below is what I have:

This is the configuration:

**nelmio_api_doc.yaml**:
```
nelmio_api_doc:
    documentation:
        servers:
            - url: http://localhost:9090
              description: API over HTTP
        info:
            title: My API
            description: API for doing stuff
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
```

The route is defined:

**nelmio_route.yaml**:
```
app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
```

And this is the **documented Controller**:

```
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use OpenApi\Annotations as OA;
use Nelmio\ApiDocBundle\Annotation\Security;
use Nelmio\ApiDocBundle\Annotation\Model;
use App\Domain\Stuff\Entity\Stuff;

final class MyController extends AbstractController
{
    /**
     * List the list of stuff that does a lot of stuff.
     *
     * @Route(
     *     path="/stuff",
     *     name="get_stuff",
     *     methods={"GET"}
     * )
     * @OA\Get(
     *   path="/stuff",
     *     summary="Something",
     *     description="Something more"
     *
     * )
     * @OA\Response(
     *     response=200,
     *     description="Returns the list of Stuff",
     *     @OA\JsonContent(
     *        type="array",
     *        @OA\Items(ref=@Model(type=Stuff::class))
     *     )
     * )
     * @Security(name="Bearer")
     */
    public function getStuff(Request $request): Response
    {
        return new Response();
    }
}
```

Now, when I go to `GET /api/doc` the only thing I get back is an HTTP-200 with a blank page that contains only the GitHub link to this repo:

![nelmio blank](https://user-images.githubusercontent.com/6078542/151963648-5e2e3bc9-8093-48d1-bbc2-2f324db88ed4.png)

There are no errors anywhere (not even in the logs).

Any idea what I'm doing wrong? My suspicion is that it has something to do with Twig, but I don't know where to start looking into that...

PS: Loading time is also incredibly high for some reason...

**Comment by zavitkov** [comment]
Facing with the same issue.
Symfony 6.0.4, NelmioApiBundle 4.8.2

Assets were installed successfully.

**Comment by GuilhemN** [comment]
Were you able to solve your issue?
If not, could you provide a reproducer?

**Comment by SoboLAN** [comment]
@GuilhemN Sort of.

The problem appeared from the default configuration of the webserver (nginx): since the assets were installed in `public/bundles/nelmioapidoc`, nginx was NOT configured to also serve those contents. Hence, a blank page.

I will close this, since it's not really related to this bundle.

**Comment by rcsofttech85** [comment]
may i know your config? i have the same issue as in the image posted above
