### ISSUE TITLE
Defining Schema on class results in "User Warning: Multiple definitions for @OA\Schema()->type"

### ISSUE THREAD

**Issue by gempir** [nelmio/NelmioApiDocBundle#1957]
I have a class like this

```
/**
 * @OA\Schema (
 *     type="array",
 *     @OA\Items(ref=@Model(type=TagData::class))
 * )
 */
class TagDataCollection extends AbstractCollection
```

With the goal of this collection being interpreted as array of TagData Models in NelmioApiDocBundle.
So I don't have to make the @OA\Property type hint every time in the parent object.

This results in a multiple definition error though:

```
User Warning: Multiple definitions for @OA\Schema()->type
Using: \Nelmio\ApiDocBundle\OpenApiPhp\MyNamespace\TagDataCollection::getSchema()
```

Is this a supported usecase?

swagger-php equivalent would be refs https://zircote.github.io/swagger-php/Getting-started.html#reusing-annotations-ref

**Comment by chrisguitarguy** [comment]
> Is this a supported usecase?

It's probably _should_ be, and it seems like it should work.

Looks like this is coming from the open api library itself: https://github.com/zircote/swagger-php/blob/3f3b551db6eb934e8cb8c132ec2430e2e8c2ca0f/src/Annotations/AbstractAnnotation.php#L238

But the reference to `TagDataCollection::getSchema()` has me wondering if that's a method you've got on `TagDataCollection`?

I kinda suspect that the `ObjectModelDescriber` does it's thing on the class: https://github.com/nelmio/NelmioApiDocBundle/blob/9cd417efb4cac669ba517f66e9dfd484a4d93001/ModelDescriber/ObjectModelDescriber.php#L71-L73 and then continues on its way to try to define the properties for the `TagDataCollection` object. When... it shouldn't do that. Unless the `@OA\Schema` annotation explicitly had no type or an `object` type.

Any chance you could provide a minimal project that reproduces your error?

**Comment by gempir** [comment]
Here is a fresh project based on a boilerplate. https://github.com/gempir/nelmio-docs-example

Just run `docker-compose up` and call localhost/api/doc.json

it will result in the same multiple definition error and it trying to do `getSchema` on my example collection.
Relevant Models in here https://github.com/gempir/nelmio-docs-example/tree/main/src/Model

![image](https://user-images.githubusercontent.com/9765622/160234377-b9ec8980-e43f-450b-98e2-656143328468.png)
