### ISSUE TITLE
composer script always fails because of nelmioApiDocBundle

### ISSUE THREAD

**Issue by geoffroyp** [nelmio/NelmioApiDocBundle#1960]
Greetings,

Everytime I install a new bundle, composer automatically execute scripts, and it always fails on "assets:install %PUBLIC_DIR%" because of nelmioApiDocBundle. I don't have any problem with others bundles

The error message is the following:

`
Executing script assets:install public [KO]
 [KO]
Script assets:install %PUBLIC_DIR% returned with error code 1
!!  
!!   Installing assets as hard copies.
!!  
!!   --- -------------------- ---------------------------------------------------------------------------------------------------------------------------------------------- 
!!        Bundle               Method / Error                                                                                                                                
!!   --- -------------------- ---------------------------------------------------------------------------------------------------------------------------------------------- 
!!    ✘   NelmioApiDocBundle   Failed to remove directory "/data/webs/apiroot/api/public/bundles/..o6Z": rmdir(/data/webs/apiroot/api/public/bundles/..o6Z): Text file busy  
!!   --- -------------------- ---------------------------------------------------------------------------------------------------------------------------------------------- 
!!  
!!                                                                                  
!!   [ERROR] Some errors occurred while installing assets.                          
!!                                                                                  
!!  
!!  
Script @auto-scripts was called via post-update-cmd
`

and my `scripts` part of `composer.json`:

`   
 "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },`

Anyone knows how I could solve this (other than executing composer with --no-scripts, which would be a workaround but not a solution)
Thanks!

(ps: sorry for the f*cked up error presentation. I've tried to edit, but there's not much I can do...)

**Comment by GuilhemN** [comment]
This may be a bug with composer or Symfony but I don't have a clue what would cause this inside NelmioApiDocBundle.
Have you tried upgrading your deps in case it was a bug fixed since then?

**Comment by GuilhemN** [comment]
Closing as I don't think this is an issue with this bundle. Feel free to reopen if you're still experimenting this.
