### ISSUE TITLE
OpenAPI Validation

### ISSUE THREAD

**Issue by babaorum** [nelmio/NelmioApiDocBundle#1962]
Hi,

First of all thanks for maintening this project which is truly helpful.

I just encountered a project which was generated an invalid openapi json.
The structure was good, but it failed because the OperationId was not unique within the file.
> related specification on Operation object https://swagger.io/specification/#operation-object
>
> Unique string used to identify the operation. The id MUST be unique among all operations described in the API.

Because of this, I am wondering if you think adding some validation within this bundle could be a good idea ?
Or if it would be easier to handle it with a dedicated library ?

Thank you in advance :)

**Comment by DerManoMann** [comment]
I think validation is part of the swagger-php library used. 

There is now a PR to add operationId validation https://github.com/zircote/swagger-php/pull/1149 - thanks for the suggestion.

**Comment by GuilhemN** [comment]
Closing as this was fixed in https://github.com/zircote/swagger-php (and the issue that appeared in NelmioApiDocBundle following it was fixed in https://github.com/nelmio/NelmioApiDocBundle/issues/1967).
