### ISSUE TITLE
Support PHP 8.1 enums

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#1963]
Hi,

[PHP 8.1 enums](https://www.php.net/manual/en/language.enumerations.php) seems to be "badly" currently supported right now.

In request body, it shows them as an objet that requires a "name" parameter. 
It should be shows as an enum (swagger). 

I've done a basic pull request that works well for me.

**Comment by GuilhemN** [comment]
Closing as https://github.com/nelmio/NelmioApiDocBundle/pull/1965 is merged.
