### ISSUE TITLE
Broken link in docs

### ISSUE THREAD

**Issue by williamdes** [nelmio/NelmioApiDocBundle#1964]
https://github.com/nelmio/NelmioApiDocBundle/blob/5ed0d31294afd1cbc1c38cc33b81c3abcaf16a6a/UPGRADE-4.0.md?plain=1#L16

Needs to be replaced by https://github.com/zircote/swagger-php/blob/3.x/docs/Migrating-to-v3.md

**Comment by GuilhemN** [comment]
Indeed, thank you!
I updated it in https://github.com/nelmio/NelmioApiDocBundle/commit/8fb8d90f246d15315534e85e8213d87adceeaada
