### ISSUE TITLE
PHP 8.1 > Attempting to use non-attribute class [...] as attribute

### ISSUE THREAD

**Issue by bonswouar** [nelmio/NelmioApiDocBundle#1970]
If I try
```php
    #[OA\Response(['response' => 200, 'description' => "Returns something""])]
```
or :
```php
    #[OA\Response(response: 200, description: "Returns something")]
```
I get the error :
> Attempting to use non-attribute class "OpenApi\Annotations\Response" as attribute

Although apparently php 8.1 attributes are already implemented, did I miss something?!

Env: PHP 8.1 / Symfony 6 / NelmioApiDocBundle ^4.8"

**Comment by DerManoMann** [comment]
Attributes are in the `OpenApi\Attributes` namespace so you'll need to change your `use` statement.

**Comment by bonswouar** [comment]
@DerManoMann That makes sense, and works, thanks!
