### ISSUE TITLE
How to use yaml instead of annotations?

### ISSUE THREAD

**Issue by dmitrym-web** [nelmio/NelmioApiDocBundle#1971]
I'm using the latest version of the package, I can't connect the yaml with the description of the routes

**Comment by GuilhemN** [comment]
Doesn't the `nelmio_api_doc.documentation` configuration field fulfills your needs? (see https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#using-the-bundle)

**Comment by dmitrym-web** [comment]
No, I want to use annotations instead
https://github.com/zircote/swagger-php/blob/master/Examples/example-object/OpenApiSpec.php
i want to use yaml
https://github.com/zircote/swagger-php/blob/master/Examples/example-object/example-object.yaml
don't know how to set up

**Comment by GuilhemN** [comment]
Yes, you should use put that yaml code under `nelmio_api_doc.config` in your configuration.

See this https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#using-the-bundle for an example.

I believe this should fix your issue so I'm closing, in case you think of improvements to clarify the docs don't hesitate to create a pull request :)

**Comment by doctorx32** [comment]
@GuilhemN hi, I have faced problem to load form types in refs (it says `User Warning: $ref "#/components/schemas/ExamType" not found for @OA\Schema() in \Nelmio\ApiDocBundle\ApiDocGenerator->generate() in /var/www/project/vendor/nelmio/api-doc-bundle/ApiDocGenerator.php on line 94`), in annotations @Nelmio\Model somehow loads and registers them, to reuse in other endpoints as well. How to register models automatically using YAML as with @Nelmio\Model?

**Comment by GuilhemN** [comment]
@doctorx32 You can define models using alternative names: https://symfony.com/bundles/NelmioApiDocBundle/current/alternative_names.html

Then use these names in references like you did so far `$ref: #/components/schemas/MyModel`
