### ISSUE TITLE
No describer for standard PHP object model 

### ISSUE THREAD

**Issue by MarkBaker** [nelmio/NelmioApiDocBundle#1977]
Return datatype from a successful API request is a json_encoded `Payment` object; a standard PHP object (admittedly some of the properties are also objects).

```php
    #[Route('/create', methods: ['POST'])]
    /**
     * @OA\Response(
     *     description="Creates a new payment",
     *     response=200,
     *     @OA\JsonContent(
     *         ref=@Model(type=Payment::class)
     *     )
     * )
     */
    public function create(Request $request): JsonResponse
    {
        ...
        return new JsonResponse($payment);
    }
```
The model itself is `JsonSerializable`.

but I'm getting an error when I try running `php bin/console nelmio:apidoc:dump`
```
Error thrown while running command "nelmio:apidoc:dump". Message: "Schema of type "Payment" can't be generated, no describer supports it."
```

**Comment by omsi668** [comment]
Just lost an afternoon on the same problem thanks to the shitty doc and error message.

Basically make sure you have a `use Namespace\Payment;` on top of your class because that was my problem (Not using it anywhere else than annotation, IDE don't react as well)

**Comment by MarkBaker** [comment]
Issue resolved, thanks @omsi668. Now on to the next issue, and figuring out why only those properties of Payment with an explicit getter method are being reported, even though the `jsonSerialize()` method serializes all the properties.

This is not an easy package to work with at all: I did the same exercise two weeks ago with a Laravel application using the `darkaonline/l5-swagger` and that worked perfectly first time, with minimal configuration or annotation effort

**Comment by GuilhemN** [comment]
I believe we could indeed improve the error message, I opened https://github.com/nelmio/NelmioApiDocBundle/pull/1979.

@omsi668 note that you're always welcome to help improve the "shitty doc" ;) Just a reminder that what we're doing is all on our free time and we don't owe you time to improve the docs, this is collaborative work and so everyone dedicates it the time they can + want.

> Issue resolved, thanks @omsi668. Now on to the next issue, and figuring out why only those properties of Payment with an explicit getter method are being reported, even though the jsonSerialize() method serializes all the properties.

About your other issue, NelmioApiDocBundle is a bit different from `l5-swagger` in that it hooks into `swagger-php` to integrate it more with the Symfony (or JMS serializer) and conform as much as possible to its behavior.
So the first question I'd have is, are you using JMS or Symfony serializer? If you're using JMS, you probably to expose your properties or set a default exposition privacy. For the Symfony serializer, your properties need to be public to be documented.

We don't have any way to know what computations are done in `jsonSerialize` so we can't really use it to compute the docs.

**Comment by GuilhemN** [comment]
Closing as the original issue is solved.

**Comment by GuilhemN** [comment]
Closing as the original issue is solved, and currently we don't have enough information to help on the potential `jsonSerialize` issue, feel free to reopen if you'd like to add details.
