### ISSUE TITLE
Gettting the error for Unable to find file

### ISSUE THREAD

**Issue by ravendraivy** [nelmio/NelmioApiDocBundle#1995]
I have upgraded nelmio/api-doc-bundle  package from 2.13 to v3.10.1 on my symfony 4.4 by using the steps of https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-3.0.md but still getting the error that is 
`Unable to find file "@NelmioApiDocBundle/Resources/config/routing.yml" in @NelmioApiDocBundle/Resources/config/routing.yml (which is being imported from "/Users/ravendra.payasi/Sites/mppl-cms/config/  
  routes.yaml"). Make sure the "NelmioApiDocBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@NelmioApiDocBundle/Resources/config/routing.yml" is not empty.  `
I have gone through on https://github.com/symfony/recipes-contrib/pull/207 the PR as well but still facing the same error. 

**`config/routes/nelmio_api_doc.yaml`**
`NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc`

**config/packages/nelmio_api_doc.yaml**
`nelmio_api_doc:
     documentation:
        info:
            title: MPPL CMS API
            description: This is an awesome app!
            version: 1.0.0
    routes: # to filter documented routes
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc`

**/manifest.json**
`{
    "bundles": {
        "Nelmio\\ApiDocBundle\\NelmioApiDocBundle": ["all"]
    },
    "copy-from-recipe": {
        "config/": "%CONFIG_DIR%/"
    }
}`

**Comment by FVSoftwareDeveloper** [comment]
same issue

**Comment by GuilhemN** [comment]
As stated in the upgrade guide you need to update the path to your routing file to `@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml`.

Have you done so? If so, have you upgraded NelmioApiDocBundle to 3.x before hand?
Have you installed symfony/asset? (`composer require asset`)

**Comment by ravendraivy** [comment]
> same issue

issue got fixed. I was doing the upgrade steps wrongly. follow the steps properly https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-3.0.md it should work.
