### ISSUE TITLE
Bug bounty program? 

### ISSUE THREAD

**Issue by Sim4n6** [nelmio/NelmioApiDocBundle#2014]
Hi, I was wondering do you run any bug bounty program somewhere? Please

**Comment by GuilhemN** [comment]
Hello,

We're not getting funding to develop this bundle, and so we are unfortunately unable to run a bug bounty program.
If you think you found a vulnerability in our code, please email me at guilhem@gniot.fr, or you can open an issue if this is a regular bug.

Thank you!
