### ISSUE TITLE
Is there way to create model and property updaters?

### ISSUE THREAD

**Issue by misterx** [nelmio/NelmioApiDocBundle#2018]
I have the following use cases:
1. I want to add constructor properties to generated model definition with `writeOnly` flag.
2. I want to set `readOnly` flag when public property does not exist in class. I.e. for getter `getPrompt():string` , bundle wil  generate `prompt` property for read and write, but this property can be used as readonly.

How i can manage this in current implementation?

**Comment by GuilhemN** [comment]
You can use the readOnly/writeOnly properties of the Schema/Property annotations inside your model: https://github.com/zircote/swagger-php/blob/1d08b7ad2914a4baf65cc9dd06b87bbe9fd56e24/src/Annotations/Schema.php#L226-L251

Check the documentation on how to add Property annotations on your models: https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#general-php-objects

**Comment by GuilhemN** [comment]
Ok maybe I answered too fast.
You would like this to be automated right?

I don't think we have an easy way to do that right now, probably was a mistake to not expose the class and property name when calling a PropertyDescriber, maybe we could change that and then you could use https://github.com/symfony/property-info/blob/6.1/Extractor/ReflectionExtractor.php#L204-L228 to determine what information you should add for instance.

We should change this signature: https://github.com/nelmio/NelmioApiDocBundle/blob/master/PropertyDescriber/PropertyDescriberInterface.php#L22
You could then decorate all property describers with your own logic and add information.

Would that be acceptable? Would you like to contribute this change?
