### ISSUE TITLE
Problem with accent in parameters description

### ISSUE THREAD

**Issue by marmotz** [nelmio/NelmioApiDocBundle#202]
I have problems with accented characters.

I use FosRestBundle and @QueryParam annonation like this:

``` php
/**
     * Recherche selon les paramètres spécifiés.
     *
     * @QueryParam(name="page", requirements="\d+", default="1", description="Le numéro de la page demandée")
     * ... SNIP ...
     * @ApiDoc(
     *      resource=true
     * )
     * @param ParamFetcher $paramFetcher
     */
    public function getSearchAction(ParamFetcher $paramFetcher)
    {
        // ... snip ...
    }
```

Here is generated code:

``` html
<!-- snip -->
<p>Recherche les coupons selon les paramètres spécifiés.</p>
<!-- snip -->
<td>Le num\u00e9ro de la page demand\u00e9e</td>
```

Method descriptions has no problem while parameter descriptions contain utf8 sequences instead of a correct accented characters.

If I delete json_encode filter in /Resources/views/method.html.twig (https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/method.html.twig#L93), all is correct.

**Comment by CedCannes** [comment]
+1 same issue

the PR https://github.com/nelmio/NelmioApiDocBundle/pull/775 fix this issue
