### ISSUE TITLE
Upgrading 3.x to 4.x error

### ISSUE THREAD

**Issue by fernandosngular** [nelmio/NelmioApiDocBundle#2020]
I have upgraded and migrated my api/doc, then, when i try access to it:

Nelmio\ApiDocBundle\Render\RenderOpenApi::__construct(): Argument #1 ($generatorLocator) must be of type Psr\Container\ContainerInterface, Nelmio\ApiDocBundle\ApiDocGenerator given, called in /var/www/html/var/cache/dev/ContainerRjzTkZM/App_KernelDevDebugContainer.php on line 8698

**Comment by maxhelias** [comment]
It looks like a cache error that was not clear after the update, have you tried to clear it?

**Comment by fernandosngular** [comment]
Yes, it was, close issue
