### ISSUE TITLE
NelmioApiDoc doesn't group anymore endpoints of entities when using ApiPlatform

### ISSUE THREAD

**Issue by Aerendir** [nelmio/NelmioApiDocBundle#2035]
I've just upgraded to `api-platform/core:^3`.

I don't use the integrated Swagger UI but, instead, I installed NelmioApiDoc.

## What happened BEFORE THE UPGRADE

Before the upgrade (until `api-platform/core:2.6`), the integration was perfect and I was able to see the entities managed by ApiPlatform correctly grouped.

Upgrading first to `api-platform/core:2.7`, the documentation started to become messy: I still had the groups, but the api prefix was wrong and the endpoints were duplicated also in the "default" section:

[![The (WRONG) documentation generated for each entity: **no `api` prefix in the route**][1]][1]
_The (WRONG) documentation generated for each entity: **no `api` prefix in the route**_

As the routes didn't have the prefix, I could not test the endpoints from inside the docs.

In `default` section, instead, the routes was correct (they had the `/api/` prefix) but I could not test them anyway from the documentation as the details of the endpoint was not present.

[![enter image description here][2]][2]
_The endpoints documented in the "default" section (duplicated as they are also in the groups as shown above)_

## What happens AFTER THE UPGRADE

Now I've upgraded to `api-platform/core:3` and the documentation is completely broken:

I don't have the entities grouped anymore and, instead, I only have endpoints described in the "default" section.

There are routes that should not exist (like `/api/.well-known/genid/{id}`) and the correct ones cannot be used as it is impossible to pass payloads:

[![enter image description here][3]][3]
_This is how the endpoint is rendered (wrongly) in NelmioApiDoc_

[![enter image description here][4]][4]
_This is how the endpoint is rendered (correctly) in the integrated Swagger UI of ApiPlatform (and how I like to have it in NelmioApiDoc, too - and like I had it before the upgrade)_

Those are some endpoints that should not be where they are:

[![enter image description here][5]][5]

Any ideas about how to make NelmioApiDoc correctly get the info about endpoints from ApiPlatform?

  [1]: https://i.stack.imgur.com/IIqPb.png
  [2]: https://i.stack.imgur.com/JAaXT.png
  [3]: https://i.stack.imgur.com/txeH3.png
  [4]: https://i.stack.imgur.com/KerUx.png
  [5]: https://i.stack.imgur.com/C3NCd.png

**Comment by GuilhemN** [comment]
Not sure what's happening with api-platform/core:2.x, if you have a reproduced that could help but I can't spend much time on debugging.

About api-platform/core:3, this was not a supported version so far. I'm surprised you still got a documentation still somehow working.
I just merged https://github.com/nelmio/NelmioApiDocBundle/pull/2037 to add its support, could you check if this works better for you?

**Comment by Aerendir** [comment]
> if you have a reproduced that could help

I don't think it is reproducible: as you can see, there are endpoints that point to `.well-known`: I think these are routes pointing to folders in Symfony Server.

> I just merged https://github.com/nelmio/NelmioApiDocBundle/pull/2037 to add its support, could you check the dev-master version of NelmioApiDocBundle to see if this works better for you?

I'm going to try...

**Comment by Aerendir** [comment]
Ok, `dev-master` is working as expected.

At least it renders correctly the routes.

I see those problems:
- In the "default" section remain the endpoints referring to `.well-known`
- In the "default" section there are other routes I'm not sure should be there
- An issue with an endpoint defined in config file (but I think I have to adjust configuration to adapt it to this new version)

![screenshot-202209261049](https://user-images.githubusercontent.com/1968622/192234338-359895b6-038b-4739-bc4e-40bac5b6044c.png)

I'm going to test the decos generated more...

**Comment by Aerendir** [comment]
I have this error:

<img width="1270" alt="Schermata 2022-09-26 alle 10 55 00" src="https://user-images.githubusercontent.com/1968622/192235265-b00a4ee1-9dc2-4fd2-816a-ce53990e7815.png">

> _Resolver error at paths./api/login.$ref
Could not resolve reference: Tried to resolve a relative URL, without having a basePath. path: 'JWT Token' basePath: 'undefined'_

This is a custom route defined in config file:

```yaml
nelmio_api_doc:
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
    documentation:
        info:
            version: 0.0.1
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            -   Bearer: [ ]
        paths:
            /api/login:
                post:
                    tags:
                        - Auth
                    summary: Get JWT Token
                    description: "Use these emails to login _(triple-click to select)_:\n\n- `super_admin@example.com`\n- `merchant@example.com`\n- `employee@example.com`"
                    requestBody:
                        required: true
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        username:
                                            type: string
                                        password:
                                            type: string
                    responses:
                        '200':
                            description: Successful token refresh
                            content:
                                application/json:
                                    schema:
                                        type: object
                                        properties:
                                            token:
                                                type: string
                                            refresh_token:
                                                type: string

```

I checked `Nelmio\ApiDocBundle\DependencyInjection\Configuration` but cannot find anything related to `basePath` so I think it is something inferred from somewhere.

How can I set the `basePath`.

In the documentation I don't remember there is something about a `basePath` and also the new documentation seems not mentioning it.

**PS
If you prefer I open a new issue, please, tell me and I will.**

**Comment by Aerendir** [comment]
Ok, it seems to work with `dev-master`!

**Comment by Aerendir** [comment]
I'm still having this issue: https://github.com/nelmio/NelmioApiDocBundle/issues/1771
