### ISSUE TITLE
Areas don't work with ApiPlatform

### ISSUE THREAD

**Issue by Aerendir** [nelmio/NelmioApiDocBundle#2041]
If setting up areas but paths are generated through ApiPlatform, then the areas don't work as expected.

In fact, the `ApiPlatformDescriber` simply adds all the endpoints generated by ApiPlatform, without filtering them by area.

Am I right or am I missing something? Are areas supported for endpoints generated by ApiPlatform?

**Comment by GuilhemN** [comment]
Areas are not supported for Api-Platform. So far we did not hook much into ApiPlatform internals and we are mostly merging the open api specification they generate into Nelmio's one.

You could eventually create a describer with a low priority filtering paths but supporting areas for ApiPlatform resources would require significant work which I can't commit to. PR very much welcome however if anyone is willing to give it a try!

**Comment by Aerendir** [comment]
Ok, so it is known... I thought was a fault of mine...

In this moment I don't have time to work on a PR, also because I still don't well understand the internals... Maybe in future...

Anyway, thank you for your great job and for your kind reply :)
