### ISSUE TITLE
[feature] Dinamic configure the serializer for model. Really?

### ISSUE THREAD

**Issue by atlance** [nelmio/NelmioApiDocBundle#2056]
When you install JMS serializer, the bundle is automatically configured to use it.
Have you tried adding in your config:
```
nelmio_api_doc:
    models: { use_jms: false }
```
?
(from the documentation: https://symfony.com/bundles/NelmioApiDocBundle/current/index.html#general-php-objects)

_Originally posted by @GuilhemN in https://github.com/nelmio/NelmioApiDocBundle/issues/1886#issuecomment-941089881_

---

@GuilhemN,

Be able to configure a serializer for a method in a controller, or even for the entire controller class, or for a model. Models are better.

In large projects, migrating from one serializer to another is long and problematic, it would be great to be able to configure this parameter for each model, by default - a common `use_jms' ...

example: 
`@SWG\Schema(ref=@Model(type=Generate\Command::class, options={"use_jms": false}, groups={"default"}))`

Best solution - jms to symfony annotation/attributes conveter 😂

**Comment by GuilhemN** [comment]
Sorry for the late reply...
We sure could have this, and it shouldn't be too hard to implement I'd say:
- Always register both the symfony and JMS object describers (as long as their respective libraries is installed), but modify their registration priority based on the `use_jms` global field
- In both the `JMSModelDescriber` and the `ObjectModelDescriber`, check the existence of the `use_jms` field you suggested in the `supports` function
- Add the options to models hash: https://github.com/nelmio/NelmioApiDocBundle/blob/4bc5c3c27ae8c194bb4bcb152268bc2b056bc5b2/Model/Model.php#L52

PR very much welcome to implement this, I don't think I'll have time to do it myself unfortunately.
