### ISSUE TITLE
Unable to specify server_url and servers urls

### ISSUE THREAD

**Issue by arturssmirnovs** [nelmio/NelmioApiDocBundle#2060]
This commit (https://github.com/nelmio/NelmioApiDocBundle/commit/181f4b276356f34ea307b5d44ec7ff6cc189ea27) broke functionality of defining servers urls to area, as well you can't specify now custom server_url, its only taken from request parameters and can't be rewrited.

1. First issue is that if you specify servers for area it is rewrited by: https://github.com/arturssmirnovs/NelmioApiDocBundle/blob/master/Render/RenderOpenApi.php#L77

2. Second issue is that you can't specify custom server_url for default area. As its taken from: https://github.com/arturssmirnovs/NelmioApiDocBundle/blob/master/Render/RenderOpenApi.php#L54

Real word scenario for second issue is when you have HTTPS connection managed by Cloudflare or some loadbalancer & end system gets 80 port request, doc generates links as http, but it would be nice to force overwrite them with server_url to https.

**Comment by GuilhemN** [comment]
I guess we could only overwrite the servers in https://github.com/arturssmirnovs/NelmioApiDocBundle/blob/master/Render/RenderOpenApi.php#L77 if it's not already defined explicitly in the OpenApi documentation, would that do?
Would you be willing to submit a PR with this change?

**Comment by arturssmirnovs** [comment]
@GuilhemN I think i managed to find best solutions: https://github.com/nelmio/NelmioApiDocBundle/pull/2061/files

1. If command line provided server-url variable = server_url 
2. if area servers has defined return them
3. if fallback_url has defined return them
4. Otherwise return null

**Comment by arturssmirnovs** [comment]
@GuilhemN when you plan to release new tag version? :)

**Comment by GuilhemN** [comment]
Done @arturssmirnovs, https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.11.0 ;)
