### ISSUE TITLE
Cannot update past 4.2.0 because of doctrine/annotations v2 not being supported

### ISSUE THREAD

**Issue by pkly** [nelmio/NelmioApiDocBundle#2073]
It seems that something broke in the newer versions, as swagger got updated to support annotations v2, this bundle did not, as such I'm unable to update this bundle with my setup past the 4.2 version.

I'm not sure if I could help more than simply updating the composer file, as I'm not well versed in the internals of the bundle.

**Comment by GuilhemN** [comment]
Thanks for the report!
Having a quick look at their upgrade file I don't think we need more than just updating the composer file.

I'll check that in https://github.com/nelmio/NelmioApiDocBundle/pull/2074

**Comment by pkly** [comment]
@GuilhemN any chance for a .1 release? Thanks for taking care of it so quickly.

**Comment by GuilhemN** [comment]
Sure, there you go: https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.11.1 😉
