### ISSUE TITLE
Connect the OpenAPI Context with Loggers from Symfony

### ISSUE THREAD

**Issue by chrisguitarguy** [nelmio/NelmioApiDocBundle#2077]
Seems like the OpenAPI library's `Context` has a logger: https://github.com/zircote/swagger-php/blob/a060ea2494ae6336eb4481f5c276d7c7ef038eda/src/Context.php#L66

that is uses a few places: https://github.com/zircote/swagger-php/blob/a060ea2494ae6336eb4481f5c276d7c7ef038eda/src/Analysers/AttributeAnnotationFactory.php#L47

This bundle should connect the logger from Symfony to the context. Name here: https://github.com/nelmio/NelmioApiDocBundle/blob/b4df34cdf78cf42c02afb85f9d10181bbf835da5/Describer/OpenApiPhpDescriber.php which already has the logger.

I can pick this up later, but it'd be a create "first issue" for anyone looking to contribute. I just had an error when rendering API docs that was silent and hard to debug becuase the default logger seemed to not work as expected.

**Comment by pkly** [comment]
It appears to already be connected though - https://github.com/nelmio/NelmioApiDocBundle/blob/b42ac43bebe0dc3372e9feb0ef0a43ae3cfbb349/DependencyInjection/NelmioApiDocExtension.php#L98

**Comment by chrisguitarguy** [comment]
Right, hte logger is connect to our internal classes, but not to the openapi library's context itself.

**Comment by zilionis** [comment]
ApiDocGenerator::generate method have:
`$generator = new Generator();`

it will be solved just by adding logger:

`$generator = new Generator($this->logger);`

**Comment by GuilhemN** [comment]
@zilionis have you tried that patch? I'm mostly wondering if this wouldn't create a lot of warnings noise with the current codebase, but if not I'm happy to merge #2131 :)
