### ISSUE TITLE
Enum: Items as enum string problem

### ISSUE THREAD

**Issue by webspec2012** [nelmio/NelmioApiDocBundle#2081]
I'm trying to do the following:

`
#[OA\Property(type: 'array', items: new OA\Items(type: 'string', enum: ChannelAclRoleEnum::class), nullable: false)]
public readonly array $roles;
`

The scheme is being formed:

roles:
  title: "..."
  type: "array"
  items:
     type: string
     enum: "App\\...\\ChannelAclRoleEnum"
  nullable: false

Expected:

roles:
  title: "..."
  type: "array"
  items:
     type: string
     enum: ["value1", "value2", "value3"]
  nullable: false

**Comment by mario-fehr** [comment]
see #2078
