### ISSUE TITLE
Use of Model for response is unclear

### ISSUE THREAD

**Issue by ShinoOoesu** [nelmio/NelmioApiDocBundle#2085]
Symfony version : 6.2
Bundle version : 4.1.11

First of all sorry if the issue exists already but I did not find the correct Answer yet.

So, I would like to indicate on my documentation, a response have a Foo::class model. According to the bundle's documentation.

I need to do this: 

``` php
use OpenApi\Attributes as OA;

// shows `username` as `required` in the OpenAPI schema (not nullable)
#[OA\Response(response: 200, content: new Model(type: UserDto::class, groups: ["default"]))]

```

Therefore, I did this

```php
#[OA\Response(response: 200, content: new Model(type: Game::class))]
```

However, when try to get a response with the "try it out' feature I got a 500 error with this message:

`` Nelmio\ApiDocBundle\Model\Model::__construct(): Argument #1 ($type) must be of type Symfony\Component\PropertyInfo\Type, string given``

What did I do wrong?

Your sincerly

**Comment by AchillesKal** [comment]
Same here!

**Comment by AchillesKal** [comment]
OK, I think I figured it out. We are using the wrong Model class. There are multiple classes with the same name. You need to use the ```Nelmio\ApiDocBundle\Annotation\Model```. I was using the ```Nelmio\ApiDocBundle\Model\Model``` and I had the same error with you.

**Comment by AchillesKal** [comment]
I think it's the wrong model class, it must be ```Nelmio\ApiDocBundle\Annotation\Model``` not ```Nelmio\ApiDocBundle\Model\Model```

**Comment by ShinoOoesu** [comment]
> I think it's the wrong model class, it must be `Nelmio\ApiDocBundle\Annotation\Model` not `Nelmio\ApiDocBundle\Model\Model`

That was it, but honestly it's confusing, because, a good practice is to provide attributes AND annotation

**Comment by Nemestos** [comment]
> I think it's the wrong model class, it must be `Nelmio\ApiDocBundle\Annotation\Model` not `Nelmio\ApiDocBundle\Model\Model`

Same problem here, thx !
