### ISSUE TITLE
`TypeError` in `ApiPlatformDescriber`: Argument #1 ($documentation) must be of type ApiPlatform\Documentation\DocumentationInterface

### ISSUE THREAD

**Issue by Aerendir** [nelmio/NelmioApiDocBundle#2089]
With ApiPlatform v.3.1.6

> TypeError: Nelmio\ApiDocBundle\Describer\ApiPlatformDescriber::__construct(): Argument #1 ($documentation) must be of type ApiPlatform\Documentation\DocumentationInterface, ApiPlatform\OpenApi\OpenApi given, called in /srv/app/var/cache/test/ContainerU6TwUpp/getNelmioApiDoc_Describers_ApiPlatformService.php on line 24

**Comment by cruiservlad** [comment]
Have the same issue. @Aerendir do you found solution?

**Comment by Aerendir** [comment]
@cruiservlad , there is no solution other than adapt the code to the new interface (it is an interface if I remember well).

But as I don't know much about the project, I don't know if it is required to maintain a retro-compatibility or not.

In the meantime, I simply didn't updated to the latest version of ApiPlatform, waiting for direction from maintainers of this bundle.

**Comment by BPavol** [comment]
I have same issue. For me it is caused by service `lexik_jwt_authentication.api_platform.openapi.factory` -> `Lexik\Bundle\JWTAuthenticationBundle\OpenApi\OpenApiFactory::__invoke()`. It returns `\ApiPlatform\OpenApi\OpenApi`. That class does not extends `\ApiPlatform\Documentation\DocumentationInterface`. 

That problem should be fixed in `lexik/jwt-authentication-bundle` package probably.

**Comment by AlphaX343** [comment]
Up?

**Comment by AlphaX343** [comment]
Hey @Aerendir, do you have news from the maintainers?

**Comment by Aerendir** [comment]
No, as you can see, no one replied 😔

In the meantime, I'm using a fixed constraint in Composer:

```json
    "require-dev": {
        ...
        "nelmio/api-doc-bundle": "dev-master#523e27cb836573e9b684b823311cdc4f91794c51",
        ...
```

**Comment by mimo-lbp** [comment]
How i fix this error : 

- Removed type "DocumentationInterface" in vendor\nelmio\api-doc-bundle\Describer\ApiPlatformDescriber.php in front of parameter 1 $documentation

![image](https://github.com/nelmio/NelmioApiDocBundle/assets/136328516/1f2bb08c-8c2a-4f0c-9c92-1c65cf1da088)
![image](https://github.com/nelmio/NelmioApiDocBundle/assets/136328516/91a3e16b-dd0f-4c3c-98d9-559eb9201aed)

**Comment by Aerendir** [comment]
@mimo-lbp , this is not a fix as at next `composer update` the changes will be overwritten.

Try to set the `repositories` to use my PR: https://stackoverflow.com/a/47610532/1399706

**Comment by soyuka** [comment]
Lmk if I can provide a fix in API Platform it's also possible. I'm available on the Symfony slack today.

**Comment by mimo-lbp** [comment]
I don't think the error come from Api platform

In vendor\nelmio\api-doc-bundle\Describer\ApiPlatformDescriber.php 
![image](https://github.com/nelmio/NelmioApiDocBundle/assets/136328516/61241720-7410-46f3-a042-59822c2daea0)

When fix ?

**Comment by GuilhemN** [comment]
Sorry for the late reply, https://github.com/nelmio/NelmioApiDocBundle/pull/2109 should fix this issue.
It is released in 4.12.0, https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.12.0

Can you give it a try? Thanks!

**Comment by Aerendir** [comment]
@GuilhemN , yes, it will fix the issue 🎉

**Comment by Aerendir** [comment]
I confirm it works! 🎉

Many thank you!
