### ISSUE TITLE
Symfony date constraint generate unexpected Open API Specification

### ISSUE THREAD

**Issue by alxvgt** [nelmio/NelmioApiDocBundle#2095]
### Problem
Here is a constraint is used to validate a datetime in a payload :
```
#[LessThanOrEqual('now')]
```
This constraint is read by the bundle and a the generated OAS part is:
```
maximum: 0
```
In that specific case, it seems the bundle does not handle correctly the Symfony constraint. In that specific case, maybe the bundle can simply ignore it and generate nothing in OAS.

### Issue

It seems the problem happen in `SymfonyConstraintAnnotationReader.php:119` in that section. The `int` cast could be improved or another behavior could be implemented.
```
...
            } elseif ($annotation instanceof Assert\LessThanOrEqual) {
                $property->maximum = (int) $annotation->value;
            }
...
```

### Symfony documentation
https://symfony.com/doc/current/reference/constraints/LessThanOrEqual.html#comparing-dates

**Comment by DjordyKoert** [comment]
Fixed by https://github.com/nelmio/NelmioApiDocBundle/pull/2148
