### ISSUE TITLE
Auto-document MapQueryString and MapQueryParameter

### ISSUE THREAD

**Issue by kylekatarnls** [nelmio/NelmioApiDocBundle#2116]
Hello 👋 

[Symfony 6.3 introduced 2 new attributes: **MapQueryParameter** and **MapQueryString**](https://symfony.com/blog/new-in-symfony-6-3-query-parameters-mapper)

When using `#[OpenApi\Attributes\Parameter]` on an argument also flagged by `#[MapQueryParameter]` or a property of an object flagged by `#[MapQueryString]` I would expect the description/example/etc. to appear in the doc.

I'm not immediately available to help but if no one else does it, I can give it a try some day.

Thanks 🙏

**Comment by matiasng37** [comment]
There's a pull request for this feature: https://github.com/nelmio/NelmioApiDocBundle/pull/2112

**Comment by DjordyKoert** [comment]
This has been merged in [v4.18.0](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.18.0) 😄

**Comment by e1sep0** [comment]
Hi, how can i disable this feature, when i have custom resolver? 
F.E. In resolver i want to get Referer from Header, and have DTO with param `referer`
So, in Api doc i get 2 parameters, but i want just one (from resolver)

<img width="999" height="760" alt="Image" src="https://github.com/user-attachments/assets/7264bafe-0843-42ef-8136-8597439a274d" />
