### ISSUE TITLE
Bad formatted JSON references in documentation files

### ISSUE THREAD

**Issue by AlexMinaev19** [nelmio/NelmioApiDocBundle#2139]
When I generate documentation files in `JSON` format, I have errors for schema references.

For example, I generated API documentation and have this endpoint:
```json
"\/v1\/user\/profile": {
    "get": {
        "tags": [
            "user"
        ],
        "operationId": "get_v1_user_get_profile",
        "responses": {
            "200": {
                "description": "Returns the profile of a user",
                "content": {
                    "application\/json": {
                        "schema": {
                            "$ref": "#\/components\/schemas\/ProfileResponse"
                        }
                    }
                }
            }
        }
    }
}
```

As you can see, the `"$ref"` property has escaped slashes.

I checked the implementation of the https://github.com/zircote/swagger-php and they use the next flags for `json_encode` function: `JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_INVALID_UTF8_IGNORE`

Can we add `JSON_UNESCAPED_SLASHES` to the `JsonOpenApiRenderer::render()` function? It should solve the problem. Or maybe we have to sync it with the `swagger-php` package and have consistency?

**Comment by raziel057** [comment]
I also noticed this issue. I tried the suggested solution and seems to work fine. It seems strange to me that this issue is not detected in tests. Maybe it's only relevant when running it on Windows or it depend on a PHP configuration?

![image](https://github.com/nelmio/NelmioApiDocBundle/assets/652505/6cca1894-3831-416f-9f73-ecdc0d697296)

**Comment by raziel057** [comment]
After checks it doesn't seems related to the OS or PHP config as slash are always escaped by default:
https://onlinephp.io?s=s7EvyCjg5eLlUskqzs9TsFXISy1XKC5Jcc5JLC7W0LSGSujalRblAGXVM0pKCqz09UtSi0v0ckrVrUFaU5Mz8hVAquJT85LzU1I1wFo0rQE%2C&v=8.2.0

**Comment by DjordyKoert** [comment]
fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/2157
