### ISSUE TITLE
Bundle cannot be used without Doctrine Annotations

### ISSUE THREAD

**Issue by derrabus** [nelmio/NelmioApiDocBundle#2143]
Symfony's FrameworkBundle automatically integrates Doctrine annotations by exposing an `annotation.reader` service that this bundle consumes. However, it is possible to disable that integration:

```YAML
framework:
    annotations: false
```

If I do that, the container won't compile anymore:

> The service "nelmio_api_doc.model_describers.object" has a dependency on a non-existent service "annotations.reader".

Modern Symfony 6 projects would rather use PHP attributes than Doctrine Annotations, so enabling the annotations integration isn't really necessary anymore. NelmioApiDocBundle could not use the annotations reader for anything in such a scenario because there are no annotations it could read from.

Symfony 6.4 triggers a deprecation if the annotations integration is enabled and Symfony 7 simply won't provide that service anymore.

NelmioApiDocBundle should continue to work if I disable the integration of Doctrine Annotations. In that case, Doctrine-style annotations would not be taken into account anymore. Furthermore, NelmioApiDocBundle should not list Doctrine Annotations as a mandatory dependency anymore. Applications that still use Doctrine Annotations should directly depend on that library instead.

**Comment by DavidGarciaCat** [comment]
Just speaking loudly, as I am not sure... Working on a Symfony 6.3 project where all the Controller's Routes and OpenAPI details are defined as Attributes (not annotations) seem to work. Can we expect this setting to cause a significant problem? Can't it just be detached from the Framework configuration file that manages the annotations?

**Comment by derrabus** [comment]
I don't understand your question, I'm afraid.

**Comment by shakaran** [comment]
Could we progress with the PR https://github.com/nelmio/NelmioApiDocBundle/pull/2151 and release a new version at least in master?

**Comment by denisvanmorgan** [comment]
hi, any updates on this?

**Comment by faizanakram99** [comment]
i am working on this

**Comment by killerwolf** [comment]
i am facing the same issue when upgrading to symfony 6.4,
activating annotations in the framework bundle is mandatory if we want nelmio to work properly

**Comment by zenoleg** [comment]
Yep, faced the same problem with NelmioApiDoc and just downloaded the doctrine/annotations + turned on the 'annotations' option in framework bundle
