### ISSUE TITLE
Symfony 7 support for version 4.x

### ISSUE THREAD

**Issue by DavidGarciaCat** [nelmio/NelmioApiDocBundle#2147]
Good day,

I started testing `Symfony 7 BETA3` and found this bundle does not offer compatibility with the new framework version.

I don't know if it will be enough to upgrade the `composer.json` dependencies or if there are other steps you guys want to follow, but if you can give me some guidance, then maybe I can work on an update and send a PR in the upcoming hours/days (unless you want to work on it by yourselves).

Cheers,

**Comment by mvanduijker** [comment]
I think [this](https://github.com/nelmio/NelmioApiDocBundle/issues/2143) should be fixed first before we can make it possible to support symfony 7.

**Comment by DjordyKoert** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/2164
