### ISSUE TITLE
Method name Clash with FosRestBundle

### ISSUE THREAD

**Issue by emhovis** [nelmio/NelmioApiDocBundle#2165]
Can't load any areas, immediately met with the error: 

Multiple definitions for @Nelmio\ApiDocBundle\Annotation\Operation->method

Restricting Zircote/swagger-php to <4.7.16 fixes the issue.

**Comment by DjordyKoert** [comment]
Could you provide some more details / example of the issue?

**Comment by emhovis** [comment]
After looking into it a bit more- it seems like some sort of clash with FosRestBundle.

I'm using FosRestBundle's Annotations\Get and OA\Operation in the same controllers (in over 1000 controllers). Removing the Annotation\Get seems to remove the error, but at the cost of losing rest functionality.

This only becomes an issue after swagger-php 4.7.16, FosRest hasn't had any changes in several months. 

Without looking too much into the internals of the ApiDocBundle, I'm not sure if that will need to be addressed here or in the swagger-php repo

**Comment by emhovis** [comment]
This issue is still present. 
I've narrowed the conflicting commit to be issue to be https://github.com/zircote/swagger-php/pull/1487/commits/c84d201338eaa1f095d7edff828299215db96c5c

Will dig more into it when I get a chance

**Comment by emhovis** [comment]
I've finally got some time to look more into the issue... think I've narrowed down at least closer to what the actual problem is.

When using FOS Rest for defining operations, you can no longer explicitly define that operation in the Operation attribute/annotation. 
E.g. using below worked prior but now causes the error:
```php
/**
     * @Operation(
     *      tags={"example"},
     *      summary="Get a list of all examples",
     *      method="GET"
     * )
*/
#[Annotations\Get(path: '/path_here}', name: 'route_name')] 
```
Removing the method="GET" removes the error.

It seems to me that the swagger-php tries to both inference the method from rest annotation *and* from the explicitly defined method in its own Operation annotation, which now causes an error. This behavior seemingly stems from the above changes mentioned in my previous comment.

**Comment by emhovis** [comment]
Turns out,  method="GET" was the issue. method="get" is the correct way. 

The bugfix in zircote-swaggerphp fixed an issue where the defined value in the Operation was effectively being ignored if it was set prior (which FOS/rest-bundle seems to do.)
