### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by DjordyKoert** [nelmio/NelmioApiDocBundle#2168]
Hey there,

In the last couple of months I have opened a few PR which I am not getting any kind of response on from any of the maintainers (if there even are more than 1). This is not exclusively to my PR's because other PR's also stay unresponded and/or unmerged. 

I understand that this is a project which people contribute to and maintain in their own free time but it makes me sad to see that a lot of nice features and fixes stay ignored/open because this is a very cool project which helps myself (and others) a lot.

I already try to help whenever I can by responding to tickets & reviewing some PR's every once in a while but it seems all of this effort goes unnoticed or doesn't result into anything.

Would it be possible to get some kind of update about the current state of this project? 😄

**Comment by DjordyKoert** [comment]
I have been contacted by @GuilhemN asking me if I would like to become a maintainer.

I am now happy to announce that I have become a maintainer for this project 🥳

**Comment by kevinpapst** [comment]
That is fantastic to read 👍 

I had a longer answer written, asking literally the same, but then I thought that time will show. I am glad to read that it happened, thanks to @GuilhemN and to you @DjordyKoert for your effort to keep this bundle alive!

Now I will upgrade to the latest release, you merged quite a lot of stuff. Excited to test that! Keep up the good quality 😁
