### ISSUE TITLE
Allow arbitrary array instead of throwing UndocumentedArrayItemsException

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#2175]
Life is not easy, and sometimes you just wants to throw some array around without having to document them.

Currently when you do this, the bundle fails with an `UndocumentedArrayItemsException`.

I propose to log this as a notice (warning ?) and use the swagger type `{}` with is `an array of arbitrary types` (from https://swagger.io/docs/specification/data-models/data-types/#array). 

The change is fairly simple and I will probably do a MR.

**Comment by DjordyKoert** [comment]
Fixed with https://github.com/nelmio/NelmioApiDocBundle/pull/2184
