### ISSUE TITLE
nullable enums not properly described

### ISSUE THREAD

**Issue by DjordyKoert** [nelmio/NelmioApiDocBundle#2177]
Found in https://github.com/nelmio/NelmioApiDocBundle/pull/2112#issuecomment-1877476168
> Ah yup that would make more sense, that is also the way it is described to do it here https://swagger.io/docs/specification/data-models/enums/. 
> But I also think this is just a problem with the way enums are currently described as can be seen here: https://github.com/nelmio/NelmioApiDocBundle/blob/ed742a7650bb3b8c70bda102876a184678fa2447/PropertyDescriber/ObjectPropertyDescriber.php#L40-L46
Enum's should not be handled here, because they are quite simple schema's. I will go ahead and create a different issue for this.

**Comment by bnowak** [comment]
Hello, I've created [draft PR](https://github.com/nelmio/NelmioApiDocBundle/pull/2226) connected to this topic. It seems that this PR fixed nullable enums for OAS 3.0, but unfortunately broke it for OAS 3.1.
