### ISSUE TITLE
NullablePropertyProcessor fails with OA\Generator::UNDEFINED

### ISSUE THREAD

**Issue by redheadedstep** [nelmio/NelmioApiDocBundle#2187]
I upgraded to v4.17 last night and discovered a new error with class that was added recently.  The NullablePropertyProcessor class fails with the error 

```
foreach() argument must be of type array|object, string given (from \/codebuild\/output\/src3434373490\/src\/vendor\/nelmio\/api-doc-bundle\/Processor\/NullablePropertyProcessor.php on line 22)
```

This is caused by the previous line that returns the schemas from the Analysis.  The return value is not an array of Schemas, but is `OA\Generator::UNDEFINED`.  This causes the issue on line 22.  

```
// NullablePropertyProcessor Line 20
$schemas = $analysis->openapi->components->schemas; // returns OA\Generator::UNDEFINED and not Schema[]
```

There should be a sanity check before running the `$schemas` through a `foreach` loop.  Also, what is this class meant to do?  It is not included in the default list of `processors`, but is added seperately in the services yaml.  From what I can see, there is no way to disable this class in the config file.

I reverted to v4.16.2 and this issue is gone (mostly because the NullablePropertyProcessor file does not exist in 4.16.2)

**Comment by DjordyKoert** [comment]
The processor was a replacement for this logic. https://github.com/nelmio/NelmioApiDocBundle/blob/f43a4ba27dc9c0837e94ca483b0b257c40e56ce5/PropertyDescriber/NullablePropertyTrait.php#L26-L33
