### ISSUE TITLE
[v4.18.0] Doc with attribute MapQueryParameter does not work with arrays

### ISSUE THREAD

**Issue by dougetovski** [nelmio/NelmioApiDocBundle#2190]
Hello,

Since we've migrated to version `v4.18.0`, routes with attributes `#[MapQueryParameter]` mapped on an array does not work anymore.

`{"message":"User Warning: @OA\\Items() is required when @OA\\Schema() has type \u0022array\u0022 in ","errors":[]}`

We tried the previous version (`v4.17.1`) and it works correctly.

Steps to reproduce :

```php
    #[SWG\QueryParameter(
        name: "categories[]",
        description: "Categories",
        required: false,
        schema: new SWG\Schema(type: 'array', items: new SWG\Items(ref: new SWG\Schema(type: 'string')))
    )]
    #[SWG\Response(
        response: Response::HTTP_OK,
        description: "data",
        content: new SWG\JsonContent(properties: [
            new SWG\Property('test', type: 'string', example: 'test')
        ]),
    )]
    #[Route(path: '/my-api', methods: [Request::METHOD_GET])]
    public function myApi(#[MapQueryParameter] array $categories = []): Response
    {
        return new JsonResponse($categories);
    }
```
As you can see, query parameter `categories` have the correct schema
`schema: new SWG\Schema(type: 'array', items: new SWG\Items(ref: new SWG\Schema(type: 'string')))`.
Still `#[MapQueryParameter] array $categories = []` causes an error.

We also tried on `v4.18.1`, same error

Thanks in advance.

**Comment by DjordyKoert** [comment]
Fixed with https://github.com/nelmio/NelmioApiDocBundle/pull/2197. Additionaly this bundle now also generates proper docs from the various validate filters which you can add to the `MapQueryParameter` attribute https://www.php.net/filter.filters.validate.
