### ISSUE TITLE
Orphaned MapQueryString schema since v4.18.0

### ISSUE THREAD

**Issue by cgrabenstein** [nelmio/NelmioApiDocBundle#2191]
Since version v4.18.0, a schema is automatically generated for the objects that we use in combination with the [`#[MapQueryString]`-attribute](https://symfony.com/blog/new-in-symfony-6-3-mapping-request-data-to-typed-objects). However that schema is never referenced and thus turns up as orphaned when linting our specs (using [vacuum](https://github.com/daveshanley/vacuum)). We will probably have to disable the rule that checks orphaned components for now, which is unfortunate.

Is there a way to disable the schema generation for the MapQueryString objects? And if not, what would be a sensible way to handle this situation? We do appreciate the automated documentation of the query parameters, so ideally we can continue to build upon that without an orphaned schema being created.

**Comment by DjordyKoert** [comment]
swagger-php offers a custom processor to cleanup unused components https://github.com/zircote/swagger-php/blob/master/src/Processors/CleanUnusedComponents.php. This processor is not used by default by swagger-php.

You can tag this processor as a service with the `nelmio_api_doc.swagger.processor`tag with a priority lower than 0 to ensure the generated models for the `MapQueryString` attribute are cleaned up as a final step before generating the final spec.
