### ISSUE TITLE
Bug Report - Incorrect Swagger Generation for Array Query Parameters

### ISSUE THREAD

**Issue by emil-1996** [nelmio/NelmioApiDocBundle#2202]
Issue Description:
I have identified a discrepancy in the Swagger documentation generation for the products/list endpoint when utilizing an array of query parameters. The current implementation in the list function of the provided code is not generating the expected Swagger path.

```
public function list(#[MapQueryString] ?ListRequest $listRequest): JsonResponse

#[OA\Property(description: "List of product ids", type: "array", items: new OA\Items(type: "integer"))]
private ?array $ids = null;
```

Swagger Request:
`swagger generate products/list?ids=1&ids=2`

Expected Swagger Request:
`products/list?ids[]=1&ids[]=2`

Issue Details:
The Swagger generation for the products/list endpoint is currently incorrect when dealing with array query parameters. The expected behavior is to append square brackets ([]) to the query parameter name when multiple values are present. However, the current implementation generates a query parameter string without square brackets, resulting in incorrect Swagger documentation.

Steps to Reproduce:
Make a request to the products/list endpoint with multiple values for the ids query parameter.
Observe the Swagger documentation generated for the request.

Expected Outcome:
The Swagger documentation should reflect the correct syntax for array query parameters, with square brackets appended to the parameter name.

Actual Outcome:
The generated Swagger documentation lacks the square brackets, leading to an inaccurate representation of the query parameter structure.

**Comment by DjordyKoert** [comment]
Thank you! fixed in https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v4.19.1
