### ISSUE TITLE
Error with Model Attribute

### ISSUE THREAD

**Issue by AdrienBr** [nelmio/NelmioApiDocBundle#2237]
Hello,
Symfony version : 5.4
Bundle version : 4.22.1

When I use this attribute : 
```
    use OpenApi\Attributes as OA;
    use Nelmio\ApiDocBundle\Annotation\Model;

    ...

    #[OA\Response(
        response: 200,
        description: "Lorem Ipsum",
        content: new OA\JsonContent(
            ref: new Model(type: MyEntity::class, groups: ['openapi'])
        )
    )]
```

I get this error : 
```
Argument 3 passed to Nelmio\\ApiDocBundle\\ModelDescriber\\ObjectModelDescriber::__construct() must be an array of Nelmio\\ApiDocBundle\\PropertyDescriber\\PropertyDescriberInterface or a single Nelmio\\ApiDocBundle\\PropertyDescriber\\PropertyDescriberInterface.
```

Is there anything wrong with my usage of OA attribute ? 

Thanks

**Comment by DjordyKoert** [comment]
Could you perhaps try dumping `dd()` the argument by manually changing the class inside ur vendor (assuming it's happening on your local running version)?

This should not be happening so I'm quite curious about what value is being passed on your end.

**Comment by MaximeLemolt** [comment]
Hello @DjordyKoert i'm a colleague of @AdrienBr , here's the dump you asked for :
![dump](https://github.com/nelmio/NelmioApiDocBundle/assets/57484207/ea0a6a0a-d443-46c2-bea8-f412b60dc3c6)

The `RewindableGenerator` object is made up of all the `PropertyDescriber` classes:
- ArrayPropertyDescriber
- BooleanPropertyDescriber
- CompoundPropertyDescriber
- DateTimePropertyDescriber
- DictionaryPropertyDescriber
- FloatPropertyDescriber
- IntegerPropertyDescriber
- NullablePropertyDescriber
- ObjectPropertyDescriber
- PropertyDescriber
- RequiredPropertyDescriber
- StringPropertyDescriber

Thanks

**Comment by MaximeLemolt** [comment]
@DjordyKoert there's still a problem despite your fix :

```php
{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","status":500,"detail":"Attempted to call an undefined method named \"supports\" of class \"Symfony\\Component\\DependencyInjection\\Argument\\RewindableGenerator\"."}
```

**Comment by DjordyKoert** [comment]
Just to be curious, may I ask if you are manually defining the `nelmio_api_doc.object_model.property_describer` service?

**Comment by MaximeLemolt** [comment]
@DjordyKoert yes we do manually defining the service :
```php
    Nelmio\ApiDocBundle\ModelDescriber\ObjectModelDescriber:
        arguments:
            $mediaTypes: [ ]
            $propertyDescribers: !tagged_iterator nelmio_api_doc.object_model.property_describer
            $nameConverter: '@serializer.name_converter.camel_case_to_snake_case'
        tags: [ nelmio_api_doc.model_describer ]
``` 

I checked again, and this time everything worked fine. Thanks
