### ISSUE TITLE
[Bug]: 'Type' Expected, given string when using 'ref: new Model(type: Entity::class)' in attribute

### ISSUE THREAD

**Issue by danroberts108** [nelmio/NelmioApiDocBundle#2245]
### Version

4.24

### Description

When attempting to specify what an API call returns in an attribute, I am defining it as so: 
```
#[OA\Response(
        response: 200,
        description: 'Returns a movie by ID',
        content: new OA\JsonContent(
            ref: new Model(type: Movie::class)
        )
)]
```

But I am receiving the error `Nelmio\ApiDocBundle\Model\Model::__construct(): Argument #1 ($type) must be of type Symfony\Component\PropertyInfo\Type, string given` despite pretty much using the example in the documentation.

`Model::class` is a doctrine entity and as such should be parsed fine as far as I can tell?

### Additional context

Symfony 6.4 Project, running on PHP 8.2

**Comment by DjordyKoert** [comment]
You are using the wrong `Model` class :)
https://github.com/nelmio/NelmioApiDocBundle/blob/9fb5170b5f7a88d1aaade05e3eb399e697ac0941/src/Model/Model.php

You should be using this one: https://github.com/nelmio/NelmioApiDocBundle/blob/9fb5170b5f7a88d1aaade05e3eb399e697ac0941/src/Annotation/Model.php

```php
use Nelmio\ApiDocBundle\Annotation\Model;

**Comment by danroberts108** [comment]
Ah yes, didn’t see there were two types! Thank you.
