### ISSUE TITLE
Property id does not exist on inherited entity

### ISSUE THREAD

**Issue by gavinwilliams** [nelmio/NelmioApiDocBundle#225]
When using inheritance mapping on an entity that is set to be the output, the following is thrown in NelmioApiDocBundle

Property id does not exist

``` php

// Controller
    /**
     * Gets sessions for a specific trainer
     * @param Trainer $trainer
     * 
     * @ApiDoc(
     *  section="Trainer Calendar",
     *  output="FitFix\CoreBundle\Entity\Session"
     * )
     */
    public function getSessionsAction(Trainer $trainer){
        }

// Entity

class Session extends Event {

}

```

Any idea how to get around this bar overriding the property in my subclass?

**Comment by vpassapera** [comment]
This is still a thing

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
