### ISSUE TITLE
[Question]: Is it possible to view a web form when mediaType is "application/json"?

### ISSUE THREAD

**Issue by m4n50n** [nelmio/NelmioApiDocBundle#2267]
### Version

4.25

### Question

Is it possible to view a web form when mediaType is "application/json" instead of viewing the plain text "editor"?
I find it much more visually comfortable to fill in data when doing "Try it out" using a form.

Thanks!

**Comment by DjordyKoert** [comment]
I don't think this is possible. This bundle uses https://github.com/swagger-api/swagger-ui so a issue / PR would not to be created there :)

**Comment by m4n50n** [comment]
> I don't think this is possible. This bundle uses https://github.com/swagger-api/swagger-ui so a issue / PR would need to be created there :)

Perfect, thanks!
