### ISSUE TITLE
[Bug]: CSRF token is always in a schema

### ISSUE THREAD

**Issue by Hricer** [nelmio/NelmioApiDocBundle#2293]
### Version

4.26.2

### Description

After updating the library, the csrf token is always in the schema even though the form has option `'csrf_protection' => false`.

Only global disable csrf_protection in framework config works.

**Comment by Hricer** [comment]
@stollr I will be happy if you check this behavior.

**Comment by stollr** [comment]
@Hricer Where do you set the option `'csrf_protection' => false`?

**Comment by Hricer** [comment]
@stollr during form creation

``` php
$form = $this->createForm(MyApiForm::class, $task, [
    'csrf_protection' => false,
]);
```

framework.yaml

``` yaml
framework:
  csrf_protection: true
```

**Comment by Hricer** [comment]
I got it. Of course I have to set `'csrf_protection' => false`  in setDefaults.

```php
class MyApiForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        ...
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'csrf_protection' => false,
        ]);
    }
}
```

@stollr Thanks :)
