### ISSUE TITLE
[Question]: GitHub Sponsors

### ISSUE THREAD

**Issue by yblatti** [nelmio/NelmioApiDocBundle#2296]
### Version

4.26.0

### Question

Hi @DjordyKoert ,

I work as a dev for a non-profit (@asit-asso), we started using NelmioApiDocBundle recently, and we love it.

We're getting a small yearly budget for sponsoring open source projects we use, targeting the ones that are maintained by small teams or solo devs.

Have you considered GitHub Sponsors ?

Thanks

Yves

**Comment by DjordyKoert** [comment]
Hi @yblatti 

I had never really thought of it honestly, but it's great to hear that you (and maybe others) are interested in this.

**Comment by yblatti** [comment]
Cool,

I'm selecting the 2024 projects/maintainers in the coming weeks.

Ping me if you enable it :)

**Comment by DjordyKoert** [comment]
Hey @yblatti, my sponsors profile has finally been approved 😁

https://github.com/sponsors/DjordyKoert

**Comment by yblatti** [comment]
Awesome ! I add you on our 2024 donation round.

And thanks again for your great work ❤️

**Comment by DjordyKoert** [comment]
Thank you! ❤️
