### ISSUE TITLE
[Bug]: UuidPropertyDescriber::describe()" method will require a new "array $context" argument in the next major version of its interface

### ISSUE THREAD

**Issue by motoronik** [nelmio/NelmioApiDocBundle#2300]
### Version

4.27.0

### Description

Hi all :)

After update on
- nelmio/api-doc-bundle -> 4.27.0
- zircote/swagger-php -> 1.11.0

I have deprecation record 

`User Deprecated: The \"Nelmio\\ApiDocBundle\\PropertyDescriber\\UuidPropertyDescriber::describe()\" method will require a new \"array $context\" argument in the next major version of its interface \"Nelmio\\ApiDocBundle\\PropertyDescriber\\PropertyDescriberInterface\", not defining it is deprecated.","context":{"exception":{"class":"ErrorException","message":"User Deprecated: The \"Nelmio\\ApiDocBundle\\PropertyDescriber\\UuidPropertyDescriber::describe()\" method will require a new \"array $context\" argument in the next major version of its interface \"Nelmio\\ApiDocBundle\\PropertyDescriber\\PropertyDescriberInterface\", not defining it is deprecated.","code":0,"file":"/var/www/app/vendor/symfony/error-handler/DebugClassLoader.php:341`

I think I need to add an argument `array $context = []` in `UuidPropertyDescriber::describe `

Should I make a pull request or will you add it yourself?

**Comment by dmamchyts** [comment]
Same problem
