### ISSUE TITLE
[Bug]: tags within api definition are not unique

### ISSUE THREAD

**Issue by maglnet** [nelmio/NelmioApiDocBundle#2308]
### Version

v4.26.2

### Description

Hi,

when having the same tag for multiple methods / routes the resulting api definition has the same tag multiple times but the specification says that tag names must be unique.

Within the specification for the `tags` within the OpenAPI object, the [OpenAPI specification](https://swagger.io/specification/) says:
> Each tag name in the list MUST be unique.

Perhaps I'm doing something wrong?

Example class:
```php

use OpenApi\Attributes as OA;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;

class ExampleController extends AbstractController
{

    /**
     * example method foo
     *
     * @return JsonResponse
     */
    #[Route('/foo')]
    #[OA\Tag('Example')]
    public function exampleFoo(): Response
    {
        new JsonResponse(['foo']);
    }

    /**
     * example method bar
     *
     * @return JsonResponse
     */
    #[Route('/bar')]
    #[OA\Tag('Example')]
    public function exampleBar(): Response
    {
        new JsonResponse(['bar']);
    }
}
```

this results in a tag list like this:
```json
{
    "tags": [
        {
            "name": "Example",
            "description": "Example"
        },
        {
            "name": "Example",
            "description": "Example"
        }
    ]
}
```

but imho it should result in a tags list like this:
```json
{
    "tags": [
        {
            "name": "Example",
            "description": "Example"
        }
    ]
}
```

Best regards,
Matthias

**Comment by DjordyKoert** [comment]
This looks like an issue for https://github.com/zircote/swagger-php
