### ISSUE TITLE
[Bug]: Using #[NotNull] / #[NotBlank] doesn't influence nullable

### ISSUE THREAD

**Issue by RobertMe** [nelmio/NelmioApiDocBundle#2309]
### Version

4.26.1

### Description

It is possible (/feasible?) to apply `#[NotNull]` / `#{NotBlank]` constraints on nullable properties in some scenarios (i.e.: not let Symfony serializer error when value is not provided by allowing it to assign `null` instead). But while these annotations are handled by this bundle, they don't seem to affect `nullable`, but only `required` of the object type?

So IMO the `SymfonyConstraintAnnotationReader` should not just only update the list of required fields, but also do `$property->nullable = false;` (or at least if it's unset / default)

**Comment by jeremyVignelles** [comment]
Also interested in this
