### ISSUE TITLE
The "Nelmio\ApiDocBundle\Processor\MapRequestPayloadProcessor" class implements "OpenApi\Processors\ProcessorInterface" that is deprecated[Bug]: 

### ISSUE THREAD

**Issue by habib-halaoui** [nelmio/NelmioApiDocBundle#2324]
### Version

master

### Description

Hi, I have this deprecated message

The "Nelmio\ApiDocBundle\Processor\MapRequestPayloadProcessor" class implements "OpenApi\Processors\ProcessorInterface" that is deprecated. How i can solve It please ? 

### JSON OpenApi

<details><summary>JSON OpenApi</summary>

```json

Replace this text with your JSON (`bin/console nelmio:apidoc:dump`)

```

</details>

**Comment by xammmue** [comment]
I think you can't do anything about it yourself (other then propose some code changes in nelmio of course).
Seems to be related to this other issue from one month ago: https://github.com/nelmio/NelmioApiDocBundle/issues/2295

As it is just a deprecation message you shouldn't need to worry about it yet

**Comment by ThibaultPelloquin** [comment]
@DjordyKoert Hi!

I don't understand why this is a problem?

The ProcessorInterface was empty so it was not usefull, but it doesn't force you to use the Pipeline...

For me you can simple remove this from your three Processors :

```php
# remove this
use OpenApi\Processors\ProcessorInterface

# remove the implements
final class (...)  implements ProcessorInterface
```

And in your ApiDocGenerator :

```php
# remove this
use OpenApi\Processors\ProcessorInterface

# keep only array
* @return array<ProcessorInterface|callable> The array of processors
```

Or you can make your own ProcessorInterface, in the Processor directory with this in it :

```php
public function __invoke(Analysis $analysis): void
```

and modify the 4 `use` listed on top ?

Have a nice day!

**Comment by DjordyKoert** [comment]
Yup that's my bad. I looked too deep into it and wanted to also fully remove all deprecated method calls at the same time (which is what I was struggling with).

Fix ready in https://github.com/nelmio/NelmioApiDocBundle/pull/2332
