### ISSUE TITLE
[Bug]: explicit setting of default value in Property causes error "Multiple definitions for [property]"

### ISSUE THREAD

**Issue by heiglandreas** [nelmio/NelmioApiDocBundle#2330]
### Version

4.25.0

### Description

Since v4.25.0 we have the issue that we can no longer declare default values in a Property definition when this value differs from the value declared in code.

As an example we have this code in a larger codebase:

```php
class X 
{
	#[Property(type: 'boolean', default: true)]
    public int $aboutEnabled = 0;
}
```

When running `bin/console nelmio:apidoc:dump` this results in 

```
15:13:00 CRITICAL  [app] User Warning: Multiple definitions for @OA\Property()->default
     Using: 
  Skipping: \X->aboutEnabled in /path/to/X.php ["exception" => ErrorException { …}] ["log_uid" => "nelmio:apidoc:dump#8509bba1f254"]
15:13:00 CRITICAL  [console] Error thrown while running command "'nelmio:api:dump'". Message: "User Warning: Multiple definitions for @OA\Property()->default\n     Using: \n  Skipping: \X->aboutEnabled in /path/to/X.php" ["exception" => ErrorException { …},"command" => "'nelmio:api:dump'","message" => """  User Warning: Multiple definitions for @OA\Property()->default\n       Using: \n    Skipping: \X->aboutEnabled in /path/toX.php  """] ["log_uid" => "nelmio:apidoc:dump#8509bba1f254"]

In DefaultLogger.php line 31:
                                                                                                           
  User Warning: Multiple definitions for @OA\Property()->default                                           
       Using:                                                                                              
    Skipping: \X->aboutEnabled in /path/to/X.php  
                                                                                                           

nelmio:apidoc:dump [--area [AREA]] [--format FORMAT] [--server-url SERVER-URL] [--html-config HTML-CONFIG] [--no-pretty]
```

With version v4.24.1 everything works as expected and we get the expected OpenAPI output.

When I move the code https://github.com/nelmio/NelmioApiDocBundle/blob/12a0ff1334b439874a604c3cf6f2df7994cea54f/src/ModelDescriber/ObjectModelDescriber.php#L157-L162 behind this part https://github.com/nelmio/NelmioApiDocBundle/blob/12a0ff1334b439874a604c3cf6f2df7994cea54f/src/ModelDescriber/ObjectModelDescriber.php#L173-L176 everything works as expected as we were used to in version v4.24.1

The problem that we have is that we are using this package to create an API documentation for a legacy code-base where a lot of such quirks are necessary to declare the values that will be set from a user-perspective.

As far as I understood the code and the general working so far an explicitly manually set value of a property should always overwrite any inflected value from code-analysis. 

Am I wrong in this assumption? Or has this changed?

### JSON OpenApi

See above

**Comment by DjordyKoert** [comment]
> As far as I understood the code and the general working so far an explicitly manually set value of a property should always overwrite any inflected value from code-analysis.

You are correct explicitly set values should always have priority.
