### ISSUE TITLE
[Question]: How to add a 400 response to all endpoints

### ISSUE THREAD

**Issue by davidrojo** [nelmio/NelmioApiDocBundle#2339]
### Version

4.30

### Question

I want to add a 400 response to all documented methods with an error schema, but I don't want to add it to each method manually.
Is there a way to define it in nelmio_api_doc.yaml and be applied to all methods?

**Comment by SAMBILI** [comment]
try this
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme

you may need to install the c compiler

**Comment by DjordyKoert** [comment]
I think this relates to https://github.com/nelmio/NelmioApiDocBundle/issues/2274

It's currently not possible to automatically document a response (`2xx`,`4xx`, `default`) to multiple routes automatically.
