### ISSUE TITLE
[Question]: Use of DOMPurify detected as vulnerability from DependencyCheck

### ISSUE THREAD

**Issue by mcaif** [nelmio/NelmioApiDocBundle#2348]
### Version

4.32.0

### Question

We are using [DependencyCheck](https://github.com/jeremylong/DependencyCheck) to detect the use of external libraries with vulnerabilities and a few weeks ago 2 files from this project were detected by this tool when using version 3.0.6 of DOMPurify (Check artifacts attached):

https://github.com/advisories/GHSA-mmhx-hmjr-r674

[artifact_{fee3bae6-6c40-52e0-a4e1-7e693d7c0408}.tar.gz](https://github.com/user-attachments/files/17241065/artifact_.fee3bae6-6c40-52e0-a4e1-7e693d7c0408.tar.gz)

We don't know how are you using DomPurify at files ~/public/redocly/redoc.standalone.js and ~/public/swagger-ui/swagger-ui-bundle.js. It would be of great help if this can be checked and upgraded this dependency to use a DOMPurify version of 3.1.3 or superior.

**Comment by DjordyKoert** [comment]
Should be fixed with https://github.com/nelmio/NelmioApiDocBundle/pull/2383 & https://github.com/nelmio/NelmioApiDocBundle/pull/2384
