### ISSUE TITLE
FatalErrorException: Compile Error when require nelmio/api-doc-bundle

### ISSUE THREAD

**Issue by pmgtech** [nelmio/NelmioApiDocBundle#275]
So I accidently installed nelmio/te-api-doc-bundle when I removed it and changed to nelmio/api-doc-bundle I get the following error:

`FatalErrorException: Compile Error: Symfony\Component\ClassLoader\DebugClassLoader::loadClass(): Failed opening required 'path/to/vendor/nelmio/te-api-doc-bundle/Nelmio/ApiDocBundle/NelmioApiDocBundle.php' (include_path='.:/Applications/mampstack-5.4.20-0/php/lib/php:/Applications/mampstack-5.4.20-0/frameworks/smarty/libs') in /path/to/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/DebugClassLoader.php line 96`

I've been unable to figure why this is happenning,
I'm using Symfony 2.2.10-DEV

**Comment by corleonis** [comment]
There is a bug in APC that causes to load classes with same names in different order thus providing wrong version to the requester. It's intermittent issue and hard to trace but clearing APC opcode and user cache should resolve the issue.
