### ISSUE TITLE
Using JMS\Discriminator for multiple input/output types.

### ISSUE THREAD

**Issue by h4cc** [nelmio/NelmioApiDocBundle#285]
We are using JMS\Discriminator for our Entities and would like to express that in the apidoc.

Currently, we can just use the Base Entity, that does not contain all the information :(

Would be a very cool feature, if it would be possible to introspect the discriminations and supply multiple input or output types in the documentation.

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
