### ISSUE TITLE
Add Table of Contents for API Documentation

### ISSUE THREAD

**Issue by rajasaur** [nelmio/NelmioApiDocBundle#296]
When we have a lot of APIs and print out the TOC, it tends to be a very long page. It would help to have a TOC like how apiary and a few other services have so that you can click to get to that section. 

This should work atleast for @ApiDoc tags where a section has been defined. I made some modifications to get this: Please see http://imgur.com/e7n2Hse

I used http://scrollnav.com/ which seems to be a 1.5KB file min-zipped and all we need to add is a directive indicating which tags behave as anchors. So, to get the screenshot above, the following is all thats required (and the CSS accompanying that):

```
            jQuery('#resources').scrollNav({
                sections: 'div#section > h1',
                showTopLink: true
            });
```

I can do a PR if this looks okay.

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
