### ISSUE TITLE
Support for collections to output

### ISSUE THREAD

**Issue by felicitus** [nelmio/NelmioApiDocBundle#306]
My API returns a list of objects. The annotation is as follows:

```
@ApiDoc(
description="Retrieves all SI Prefixes in the database",
output="PartKeepr\SiPrefixBundle\Entity\SiPrefix"
 )
```

This works fine, however, it doesn't indicate that `PartKeepr\SiPrefixBundle\Entity\SiPrefix` is an array. I could, of course, add a collection, but simply putting up a separate collection with proper type hints leads to lots of duplication. I would have expected to specify the output as JMSType specification, e.g. something like this:

```
@ApiDoc(
description="Retrieves all SI Prefixes in the database",
output="ArrayCollection<PartKeepr\SiPrefixBundle\Entity\SiPrefix>"
 )
```

However, this doesn't work. Is there any other way to specify that a collection is returned?

**Comment by magnetik** [comment]
+1

**Comment by cbrunnkvist** [comment]
the same :+1:

**Comment by psliwa** [comment]
+1 :+1:

**Comment by foaly-nr1** [comment]
+1

**Comment by adnedelcu** [comment]
+1

**Comment by duncangrist** [comment]
How is this requirement different from what was already merged here:
https://github.com/nelmio/NelmioApiDocBundle/pull/469

?

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.

version 3 should be able to do all that with the swagger php support.
