### ISSUE TITLE
jms/i18n-routing-bundle causing APis to show up multiple times

### ISSUE THREAD

**Issue by paul999** [nelmio/NelmioApiDocBundle#309]
Hello,

When using jms/i18n-routing-bundle for a site with locales on different domains, the API shows up the number of locales plus one in the documentation (See image), when using app/console route:debug, they are there 3 times as well, with different names:

```
 nl_en__RG__vrbh_site_apiorganisation_createorganisation POST     ANY    ANY  /api/organisation
 nl__RG__vrbh_site_apiorganisation_createorganisation    POST     ANY    ANY  /api/organisation
 en__RG__vrbh_site_apiorganisation_createorganisation    POST     ANY    ANY  /api/organisation
```

Iam not sure if this is a issue with your bundle, or if it needs fixing somewhere else. Do you know any way to fix this?
![bug_router](https://f.cloud.github.com/assets/65767/1818361/b03cf014-6ffa-11e3-9dd6-cf9c0615ed9e.png)

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.

if somebody wants to do a pull request to the doc (README) with a tip for this jms configuration, please do.
