### ISSUE TITLE
Unable to distinguish query and body parameters

### ISSUE THREAD

**Issue by Tobion** [nelmio/NelmioApiDocBundle#310]
It's not possible to distinguish query and body parameters in the doc.

For example it's not possible to document an API route like 
> POST `/resource.json?token=...` with a JSON string as POST body

The sandbox can also not be used for such an endpoint because setting the "content" will disable all parameters and not send them at all.

I think we need to be able to define per parameter whether it can be passed via query string or via request body or both. I also don't see the need for the "filters". This is just semantics that can be clarified via text or can be achieved via grouping of parameters as @christianriesen suggested.

I would image something like
For a GET route the parameter can of course only be passed as query string.
```
parameters={
    {"name"="token", "dataType"="string", "required"=true, "description"="Access token"},
    {"name"="from", "dataType"="integer", "required"=false, "default"="0", "group"="Pagination", description"="Offset"}
    {"name"="count", "dataType"="integer", "required"=false, "default"="20", "group"="Pagination",  "description"="Number of results"},
    {"name"="category", "dataType"="string", "required"=false, "group"="Filter",  "description"="Filter results by category"},
},
```
But for a POST,PATCH etc route:
```
parameters={
    {"name"="token", "dataType"="string", "required"=true, "source"="query|body", "description"="Access token"},
    {"name"="data", "dataType"="string", "required"=true, "source"="body", description"="JSON data"}
},
```
1. Remove "filters" section
2. Introduce "group" attribute
3. Introduce "default" attribute
4. Introduce "source" (or better name) to specify where the parameter can be passed: `body`, `query`, `body|query` (body or query but body has higher priority), `query|body` (prefer query).
5. It would be nice to be also able to ducument HTTP headers similarly. It can be regarded as a parameter as well and with `source=header`. (Or traditionally with a new "headers" section, but which would need the same attributes like "required" etc.).
6. Ability to document a plain raw request body (no parameter name) like for plain JSON or XML.
7. The "requirements" section with path placeholders are also just parameters with `source=path`.
8. In the sandbox one should be able to select which source to use when multiple are available for a parameter (query|body|header|path) and the sandbox builds the request accordingly.
9. Maybe remove the "dataType" property because it does not really add useful information because in the URL/Body it's always a string. It more resembles what client expects for a format, e.g. 12 letter hash or numbers which is not a datatype. If we really need an extra column for it, then it should inherit the routing requirement for a path placeholder like "my dataType description (`[^/]+`)".

**Comment by solazs** [comment]
Just ran into this issue, +1 tor "source".

It IS necessary to be able to pass both POST and GET parameters at once, but the sandbox does not support this now.

**Comment by evancauwenberg** [comment]
+1 also, for the POST request is post a JSON object to the API and that is currently not possible via the sandbox.

**Comment by stonyherr** [comment]
+1, I need to be able to both POST a json object and include additional parameters via the query string.

**Comment by danielsippel** [comment]
+1 
It should be configurable to get the sandbox submitting the parameters as Request Payload like this:

`{"accountOwner":"sdfjifdskl","bankName":"sdf2iewsd","iban":"DE7209829082389023980","bic":"BLABIC"}`

**Comment by BreaGaudioso** [comment]
+ 1

**Comment by gototog** [comment]
+1

**Comment by Tobion** [comment]
Closing as the swagger does exactly what I proposed here. You can define if parameters are in the header, query, path, formData, or body. See https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject

Also we are using https://github.com/zircote/swagger-php and the swagger UI by now.
