### ISSUE TITLE
Unable to use only one parser exclusively

### ISSUE THREAD

**Issue by KamilKopaczyk** [nelmio/NelmioApiDocBundle#323]
I'm trying to use my custom parser exclusively, but results (generated parameters in documentation) are a merged lists from multiple (one from your bundle and my custom one) parsers.

According to the documentation ([here](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md#used-parsers)):

> By default, all registered parsers are used, but sometimes you may want to define which parsers you want to use.

However setting parsers property for ApiDoc input has not affected used parsers. It doesn't change the behaviour at all. Looking through the code i couldn't find any file where 'parsers' property is used.

---

I also tried using priority for tagged parser service.
According to the documentation ([here](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md#configuration-in-depth)):

> The bundle provides a way to register multiple input parsers. The first parser that can  handle the specified input is used, so you can configure their priorities via container tags.

Priorities are set correctly, all parsers are sorted and added to extractor.
But then, when extracting data, all of the parsers are used, not just the first supported with highest priority.

Is this a bug or am i doing something wrong?

**Comment by smurfy** [comment]
Having the same problem.

**Comment by sebvie** [comment]
same problem

**Comment by dbu** [comment]
if this is still a problem in version 3, please try to debug the feature and send a pull request to fix it @sebvie
