### ISSUE TITLE
How can i generate documentation for route like login_check?

### ISSUE THREAD

**Issue by ajaypatelbardoli** [nelmio/NelmioApiDocBundle#340]
How can i generate documentation for route like login_check? because there are several routes which are not directally point to any method.

**Comment by chesser25** [comment]
> @ajaypatelbardoli You can define your route using annotations in a controller by creating an empty method (which won't be called because intercepted by the security) but the annotations will work (i think):
> 
> ```
> //MyController.php
> /**
>  * @ApiDoc(.....)
>  *
>  * @Post("/login_check", ....)
>  */
> public function checkAction(){...}
> ```

That helped, thanks so much!!!
