### ISSUE TITLE
Ignoring "Assert" in output doc if excluded

### ISSUE THREAD

**Issue by Bup3** [nelmio/NelmioApiDocBundle#342]
I tried some things to hide the "user" field from output.

I think it is a bug. Or not?

``` php
<?php

namespace AcmeDemo\UserBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

use JMS\Serializer\Annotation\ExclusionPolicy;
use JMS\Serializer\Annotation\Groups;
use JMS\Serializer\Annotation\Exclude;

/**
 * TestUser
 *
 * @ORM\Table(name="user_addon")
 * @ORM\Entity()
 * @ExclusionPolicy("all")
 */
class TestUser
{
    /**
     * @var integer
     * @Groups({"public", "list", "details"})
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     * @Groups({"public", "list", "details"})
     *
     * @ORM\Column(name="name", type="string", length=100)
     * @Expose
     */
    private $name;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="User", inversedBy="test")
     * @ORM\JoinColumn(name="test", referencedColumnName="id", onDelete="CASCADE")
     * @Groups({"details"})
     * @Assert\NotNull()
     * @Exclude
     */
    private $user;
}
```

Why i use `@Assert\NotNull()` ??
I would say the api documentation that the field is required in INPUT but not visible in OUTPUT ...

Thanks in advance :)

![doc](https://f.cloud.github.com/assets/2842771/2217866/563f9f00-9a23-11e3-98b5-bf83ca52509c.png)

**Comment by nnmer** [comment]
same problem.
"dev-master" branch still has this problem

**Comment by antoinemineau** [comment]
I have this issue, for a workaround i removed the assert Not Null and I created a custom callback such as :

`
public function hasNotNullFields(ExecutionContextInterface $context, $payload)
{
        if ($this->getSelection() == null) {
            $context->buildViolation('This value should not be null.')
                ->atPath('selection')
                ->addViolation();
        }
        
}
`

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed. version 3 is quite a rewrite, maybe the problem does not exist anymore?
