### ISSUE TITLE
Enable translations

### ISSUE THREAD

**Issue by kix** [nelmio/NelmioApiDocBundle#354]
Currently the doc generated is english-only. Maybe we should add locale and translator support for `Formatter`s?
First of all, the translator should be injected into the formatter. Then, depending on configuration or command line option we should generate the documentation using the needed locale.
This would include adding `{% trans %}{% endtrans %}` into the Twig templates, and maybe the Markdown formatter also could be refactored so that the strings are taken from message catalogs.

**Comment by dbu** [comment]
pull request welcome ;-)
