### ISSUE TITLE
filtering doc regarding roles

### ISSUE THREAD

**Issue by Deamon** [nelmio/NelmioApiDocBundle#356]
Hi everyone,
I'm actually creating an API andI faced this problem : 
I would like to give access to the doc to my users but only show them methods they are allowed to use.

I figured how to use the @Secure annotation but it only show the method as restricted but it still appearing in the doc.

Maybe there could be a param in the @ApiDoc annotation or a global param to filter the methods in the generated doc and not only show "keys" in font of them?

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
