### ISSUE TITLE
first_name and second_name ignored in "repeated" form field

### ISSUE THREAD

**Issue by alanhartless** [nelmio/NelmioApiDocBundle#368]
Repeated type for forms can take a "first_name" and "second_name" parameter to name the repeated fields.  For example,
$builder->add('plainPassword', 'repeated', array(
            'first_name'        => 'password',
            'second_name'       => 'confirm'
        ));

But, NelmioApiDoc is ignoring those and generating:
user[plainPassword][first] and user[plainPassword][second].  

It should also honor the name options as otherwise, first and second will not work.

Thanks,
Alan

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
