### ISSUE TITLE
Add exporting to RAML

### ISSUE THREAD

**Issue by yoshz** [nelmio/NelmioApiDocBundle#384]
Today I discovered the existence of [RAML](http://raml.org/) and played with it a bit using the Anypoint Portal API.

> RESTful API Modeling Language
> RESTful API Modeling Language (RAML) is a simple and succinct way of describing practically-RESTful APIs. It encourages reuse, enables discovery and pattern-sharing, and aims for merit-based emergence of best practices. The goal is to help our current API ecosystem by solving immediate problems and then encourage ever-better API patterns. RAML is built on broadly-used standards such as YAML and JSON and is a non-proprietary, vendor-neutral open spec.

It would be awesome to add some kind of support of RAML to this bundle like:
- Add export possibility to RAML format
- Generate documentation/sandbox from RAML

Does anyone has any ideas or suggestions to implement the spec?

**Comment by SoboLAN** [comment]
@yoshz I'm very very interested in having something like this.

Maybe we can work together on a pull request. If this sounds interesting to you, send me an email so we can discuss about it.

**Comment by oktapodia** [comment]
:+1:

**Comment by jerome-fix** [comment]
+1

**Comment by Olousouzian** [comment]
👍

**Comment by Neirda24** [comment]
👍

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.

version 3 introduced a swagger domain model dependency that is used to collect the documentation which is then rendered. might be already supported or easier to add now.
