### ISSUE TITLE
Constraing cannot be converted

### ISSUE THREAD

**Issue by sinevar** [nelmio/NelmioApiDocBundle#394]
I don't know whether this is something specific in my symfony2 configuration or this is something wrong with this bundle. Can you guys check the following?

app/console api:doc:dump --format=html > /tmp/tt.tx
PHP Catchable fatal error:  Object of class Symfony\Component\Validator\Constraints\Currency could not be converted to string

I use FOSRestBundle:

use Symfony\Component\Validator\Constraints\Currency;
.
.
.
/*
- @Rest\QueryParam(name="currency", requirements=@Currency, nullable=false, strict=true)

To fix the situation, I created the __toString() method in Currency class but this does not seem to be the nicest solution. Did you ever experience similar problem?

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
