### ISSUE TITLE
Choices values autoloading can cause excessive memory use

### ISSUE THREAD

**Issue by mikaelrandy** [nelmio/NelmioApiDocBundle#398]
Since PR #329 (v2.5.2), the annotation parser [attempts to load every possible values of FormType ​​"choice" type fields for display in the sandbox](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/FormTypeParser.php#L183) 

But in the case of a form where a field is bound to a Doctrine entity (cf. exemple bellow), the parser loads the entire table, which can cause huge memory usage, even "memory limit exceed" errors. 

This is a big regression for me. 
I have no clear idea on how to solve it. Can be check if the list of choices is static or not before loading, or allow to disable this feature.

Any idea ?

```php
<?php

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', 'text', [
                'max_length' => 255,
                'required' => true
            ])
            ->add('program_id', 'entity', [
                'required' => true,
                'class' => 'Some\Namespace\Entity\Program',
                'query_builder' => function ($repo) {
                    return $repo->createQueryBuilder('program');
                },
                'property_path' => 'program'
            ]); 
    }
}
```

**Comment by nakashu** [comment]
I'll like to bump this up ... 
cigoe .. what would be the way you want to fix it... so maybe we can create the PR ?
