### ISSUE TITLE
Add option to scan all routes and not just annotated ones

### ISSUE THREAD

**Issue by Seldaek** [nelmio/NelmioApiDocBundle#4]
- optional filtering by URL prefix

**Comment by dbu** [comment]
also, option to configure doc in .yml and other external sources for when the php file can not be annotated but needs additional information.

**Comment by GuilhemN** [comment]
@dbu that's already possible using https://github.com/nelmio/NelmioApiDocBundle/blob/master/Describer/ExternalDocDescriber.php :)
