### ISSUE TITLE
Not encode Json in filter Description

### ISSUE THREAD

**Issue by ivan1986** [nelmio/NelmioApiDocBundle#416]
*    filters= {
     *      {"name"="from", "dataType"="integer", "description" = "Таймштамп начала"},
     *      {"name"="to", "dataType"="integer", "description" = "Таймштамп окончания"}
     *    }
![1](https://cloud.githubusercontent.com/assets/156418/3356339/08e2a2ea-fac0-11e3-8b42-aaea12308bcb.jpg)
![2](https://cloud.githubusercontent.com/assets/156418/3356340/0ae12f08-fac0-11e3-8f5a-11574356f7ae.jpg)

**Comment by VBelozyorov** [comment]
So... Is 
```
{{ value|json_encode(constant('JSON_UNESCAPED_UNICODE'))|replace({'\\\\': '\\'})|trim('"') }}
```
will be ok? @willdurand @stof
