### ISSUE TITLE
Need Default Parameter Support in Web Docs

### ISSUE THREAD

**Issue by jonmchan** [nelmio/NelmioApiDocBundle#421]
It is great that we have default parameter support in markdown and the sandbox, but we should also have default parameter support in the standard docs somewhere, especially for those that disable sandbox or for first glance. Code-wise, it is a trivial thing to add, but we're already at 5 columns for the Parameters table - do we want to add a 6th or would there be a better place to put it?

Related to #420 and #408 .

**Comment by TroodoNmike** [comment]
definitely +1

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
