### ISSUE TITLE
[Question] Using configuration file instead of annotation.

### ISSUE THREAD

**Issue by aRn0D** [nelmio/NelmioApiDocBundle#435]
Hi there, 

I just finished to write a simple API with the [SyliusResourceBundle](https://github.com/Sylius/SyliusResourceBundle). I wanted to use this bundle to generate the documentation but I can not :(. I only use the [ResourceController](https://github.com/Sylius/SyliusResourceBundle/blob/master/Controller/ResourceController.php) to manage my resources, I have not several controllers for each of them. Is it plan (or possible, perhaps I miss something...) to move "annotation" into configuration file (yaml ou XML for example.) ? 

Do you like this idea, is a PR could be welcome?
Thanks.
/cc @pjedrzejewski @masev

**Comment by oktapodia** [comment]
I made this feature because I wanted to use that ;)

**Comment by oktapodia** [comment]
#592

**Comment by oktapodia** [comment]
Following https://github.com/nelmio/NelmioApiDocBundle/pull/737

**Comment by Neirda24** [comment]
@willdurand : Hi.

Why these were closed ? It could be great to have a yaml configuration as annotations can become pretty heavy.

**Comment by GuilhemN** [comment]
@Neirda24 it will be possible in 3.0, see https://github.com/nelmio/NelmioApiDocBundle/pull/953.

**Comment by Neirda24** [comment]
@GuilhemN : Not exactly... I meant something that would allow us to define ApiDoc not trough annotation exclusively but through a yaml (or several) also.

**Comment by GuilhemN** [comment]
@Neirda24 that's what permit https://github.com/nelmio/NelmioApiDocBundle/pull/953:
```yml
# /app/config.yml
nelmio_api_doc:
    documentation:
        paths:
            /foo:
                get:
                    tags: ["foo", "bar"]
```

**Comment by Neirda24** [comment]
@GuilhemN : 
Thank you for your quick reply :).

So you confirm that we will be able to not use annotations at all anymore ? If so A documentation should be added maybe ? When do you think 3.0 will be released ?

**Comment by GuilhemN** [comment]
@Neirda24 using the swagger specification, yes it will be. However, i don't think it will be the most convenient way to document your api as you'll have to duplicate your paths in several places.

> If so A documentation should be added maybe ? 

That's on the todo list :)

> When do you think 3.0 will be released ?

It will depend of the time I can spend, the most important tasks remaining are https://github.com/nelmio/NelmioApiDocBundle/pull/948 and writing docs.

**Comment by dbu** [comment]
3.0 is released now. the documentation is rather short, further contributions are welcome ;-)
