### ISSUE TITLE
Extra parameter added to docs when a formType is used

### ISSUE THREAD

**Issue by NicParry** [nelmio/NelmioApiDocBundle#437]
When I add an formType class to the input annotation, a parameter with type object (FormType) is added to the parameters. 

Something has changed as this did not always happen. If this is intentional how can I remove the object parameter?

**Comment by aguidis** [comment]
+1

Did anyone find a fix ?

**Comment by braca** [comment]
+1 is there a fix?

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
