### ISSUE TITLE
Enable multi line strings in ApiDoc annotation.

### ISSUE THREAD

**Issue by m3co-code** [nelmio/NelmioApiDocBundle#443]
In my current project I am facing the problem that we have very long descriptions in our annotations. Can we somehow enable a mechanism to add line breaks in the annotations? 

Of course I would create a PR for this on my own, but I first wanted to discuss if this is desired and how a implementation could look like.

**Comment by mfsianoopj** [comment]
Hi, 

Nelmio is very helpful in documenting. But as pointed out by others above in his thread, the description part sometimes happens to be a bit large and when it extends to multiple lines, the character '*' gets rendered in the HTML output. It would be great if its handled.

Thanks

**Comment by devantoine** [comment]
Similar to this, if markdown is working in the PHPDoc how to get line breaks without HTML?
Currently my PHPDoc is a mix of markdown and html :/

Reading [these slides](https://speakerdeck.com/gordalina/rest-apis-made-easy-with-symfony2), at the end the generated documentation gots line break but I'm not able to reproduce this.

Any clue?
