### ISSUE TITLE
Dynamic parameter in annotation documentation

### ISSUE THREAD

**Issue by L0rD59** [nelmio/NelmioApiDocBundle#448]
Hi,

i have a form with birthday date field with year range like this `$formBuilder->->add('birthday', new DateType(), array('years' => range((date('Y') - 100), date('Y'))))` and i wanna have the same in annotation documentation : 

```
@NelmioApiDocBundle\Annotation\ApiDoc(
     *  parameters={
     *  {"name" = "customer[birthday][year]", "dataType"="integer", "required"=true, "format"="[1914-2014]", "description"="Year of birth of customer"}
     * }
```

How can achieve that ?

Thx for replies,

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
