### ISSUE TITLE
missing required definition in parameters leads to undefined index

### ISSUE THREAD

**Issue by dbu** [nelmio/NelmioApiDocBundle#450]
bug probably was introduced in #218

```
     * @ApiDoc(
     *     description="Test",
     *     parameters={
     *         { "name"="param", "dataType"="string" }
     *     },
     * ...
```

The annotation parsing does not complain about a missing required attribute, but also not set to a default value. This leads to "ContextErrorException: Notice: Undefined index: required in /vagrant/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php line 74" with 2.6. i guess the annotation parsing logic should just add a default=false value to the information.

/cc @konradpodgorski

**Comment by ivaaaan** [comment]
you solved this problem? how?

**Comment by dbu** [comment]
best would be to fix the code. but the workaround is to always specify the "required" attribute to either true or false
