### ISSUE TITLE
Add summary in the documentation

### ISSUE THREAD

**Issue by thankswho** [nelmio/NelmioApiDocBundle#454]
Is there a way to simply add a summary in the documentation ?

Like the list of all sections with an anchor, all routes in each section.. don't know !

Is there a way ?

**Comment by Goutte** [comment]
May I suggest making the `motd` a bit more salient in the documentation ? I did not knew the _meaning of the acronym_ and found it by sheer luck while browsing the source to figure out which template to override. I had ~~skimmed~~ read the documentation throughout beforehand, mind.

I expect filling the masthead with custom content is something most of us want to do.

Also, thank you all for this awesome bundle! :kissing_cat:
