### ISSUE TITLE
Form field description parameter is unreliable

### ISSUE THREAD

**Issue by kix** [nelmio/NelmioApiDocBundle#463]
In my case, the `NelmioApiDocBundle` is only added to the AppKernel in `dev` and `test` environments. I don't need it loaded in production due to performance reasons, and I can't come up with a reason I would need it loaded in `prod`.

However, when describing my form types, I use `'description'` option in fields, as the [documentation suggests](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.md). But since the ApiDocBundle is not loaded, Symfony doesn't know how to handle this option, so I get an exception.

How should I deal with this case? I'm convinced I shouldn't need to enable the ApiBundle in `prod` environment.

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
