### ISSUE TITLE
How to get rid of the FormType suffix for embedded form collections?

### ISSUE THREAD

**Issue by sandermarechal** [nelmio/NelmioApiDocBundle#473]
In my project I have a few forms that embed a collection of other forms. For example, a product translated into multiple langauges. My problem is that the FormTypeParser on line 156 generates a description like this:

```
array of objects (ProductTranslationFormType)
```

This is because the classname of the subform is named SomeNameFormType. This is annoying because the output properties (generated from e.g. JMS Serializer metadata) read this:

```
array of objects (ProductTranslation)
```

I would like to get rid of the FormType suffix. I am happy to write a PR for this, but I wonder what the best way is to implement this. Off the top of my head I can see three solutions.
1. The quick fix. Simply strip any "Form", "Type" and "FormType" suffix in the FormTypeParser around line 156.
2. Add some methods and configuration to the FormTypeParser so you can register new mapping types. If a mapping type exists for a FQCN of a sub form, use the defined mapping name instead. Example:
   
   ```
   $parser->addMapType(ProductTranslationFormType::class, 'ProductTranslation');
   ```
3. Some kind of ApiDoc annotation on the form type itself that is used by the parser.

Any ideas/suggestions on the best way to implement this?

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
