### ISSUE TITLE
@Input accepts array

### ISSUE THREAD

**Issue by mangelsnc** [nelmio/NelmioApiDocBundle#474]
Hi to everybody!

This it's a really nice bundle to get ready the documentation of an API at the time you write it, but I found something I think forces you to do the things in an only way: the annotation _input_ accepts only  a FormType or a Entity... why not also plain text? or an array, like _statusCodes_?

I found this way will do more flexible this annotation.

**Comment by dbu** [comment]
version 3 is a complete rewrite and uses swagger-php annotations. please check if this is still a problem with version 3 and a recent symfony version.
