### ISSUE TITLE
body formats issue leads to memory running out

### ISSUE THREAD

**Issue by haylingsailor** [nelmio/NelmioApiDocBundle#475]
I just upgraded from a 2.4.\* version, and found PHP would run out of memory during document generation (even if set as high as 500MB), the result being a partially truncated file which was broken (e.g. formatting strange and none of the API rules could be opened with a click).

The error reported by symfony was:
[2014-08-15 10:52:36] request.CRITICAL: Uncaught PHP Exception Twig_Error_Runtime: "Variable "bodyFormats" does not exist in "NelmioApiDocBundle::layout.html.twig" at line 20" at /www/elasticlicensing.com/api/vendor/twig/twig/lib/Twig/Template.php line 332 {"exception":"[object](Twig_Error_Runtime: Variable "bodyFormats" does not exist in "NelmioApiDocBundle::layout.html.twig" at line 20 at /www/elasticlicensing.com/api/vendor/twig/twig/lib/Twig/Template.php:332)"} []

My config.yml originally had a very simple config:

nelmio_api_doc:
    name: myApi

If I explicitly disable the sandbox, then it is fine:

nelmio_api_doc:
    name: myApi
    sandbox:
        enabled: false

But obviously that isn't a solution for some...

(We can't use the sandbox as our API uses a signing process similar to AWS - i.e. each request has a unique signature)

**Comment by abulford** [comment]
I've just encountered an almost identical error involving 'bodyFormat' when upgrading from 2.5.2 to 2.7.0:
```
[Twig_Error_Runtime]                                                                       
  Variable "bodyFormat" does not exist in "NelmioApiDocBundle::layout.html.twig" at line 18
```
The solution ended up being as simple as just clearing Twig's cache, which can be done via [Symfony's console](http://symfony.com/doc/current/cookbook/console/usage.html):
```
php app/console cache:clear
```

I can't comment on the memory issue as I didn't experience that myself, but hopefully this will be useful for anyone else who finds this page while searching for a solution to the bodyFormat error message.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
