### ISSUE TITLE
File Upload In Sandbox Broken

### ISSUE THREAD

**Issue by jonmchan** [nelmio/NelmioApiDocBundle#501]
The File Upload functionality is broken - it is submitting garbage data in the REQUEST body. Something broke between my branch and getting it into master... I suspect it is all the swagger additions. I did check my branch and it still works, so it isn't the original code. When I have a chance, I will debug this.

**Comment by UFOMelkor** [comment]
Any news on this? File upload is still broken. #535 fixes this for me but has been closed. If you tell me what was wrong with #535 I would be happy to create a pull request.

**Comment by Wirone** [comment]
I've spent at least 1 hour on my API developing, testing and vituperating "wtf why my files can't be seen in controller's action?".. Then I checked headers.

First I was thinking it is something about FOSRestBundle, it took me a while to get here. Would be great if it was fixed.

**Comment by jonmchan** [comment]
I fixed this last year - but I don't know why it wasn't merged. The fix is very trivial - delete passing any Content-type and allow the browser JS engine take care of it. @Wirone , if you'd like it to work now, you can look at my PR #535 .

**Comment by carlosdanielmou** [comment]
+1

**Comment by AlmogBaku** [comment]
Is there any progress on this issue? @willdurand

**Comment by hidabe** [comment]
What about it? @willdurand

**Comment by hidabe** [comment]
Fix please... it work:
https://github.com/jonmchan/NelmioApiDocBundle/commit/45f5c91bcfb9da0642e6155e2d1df9041c7863f8

**Comment by s1yamuza** [comment]
Same problem here...

**Comment by brice** [comment]
Same problem here

**Comment by mremi** [comment]
+1 Any news about this please?

**Comment by guillermogfer** [comment]
I also came across with this issue too...

**Comment by willdurand** [comment]
Does [this fix](https://github.com/jonmchan/NelmioApiDocBundle/commit/45f5c91bcfb9da0642e6155e2d1df9041c7863f8) work?

**Comment by willdurand** [comment]
ping @mremi @guillermogfer @brice @s1yamuza

**Comment by brice** [comment]
Works for me.

**Comment by mremi** [comment]
:+1: @willdurand

**Comment by mremi** [comment]
@willdurand When do you plan to bump a new release? Thx

**Comment by willdurand** [comment]
@mremi here you go: [2.10.2](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.10.2)

**Comment by mremi** [comment]
Nice!

**Comment by UFOMelkor** [comment]
Thank you!

**Comment by ghanbari** [comment]
thank you

**Comment by jonmchan** [comment]
wow, that took forever. :smile: Glad my PR finally made it in after a whole year!

**Comment by guillermogfer** [comment]
Nice job ;)
