### ISSUE TITLE
Do not show "Requirement" when empty

### ISSUE THREAD

**Issue by JeroenDeDauw** [nelmio/NelmioApiDocBundle#502]
For the third filter here, no requirement has been defined. Can in such a case the requirement line be omitted?

![requirement](https://cloud.githubusercontent.com/assets/146040/4102728/a102c8d4-3139-11e4-8cc2-ddeadc7a2d56.jpg)

The filters are defines as follows:

```
 * @QueryParam(name="page", default="1", requirements="[1-9][0-9]{0,1}", description="Specifies the page in the result set")
 * @QueryParam(name="per_page", default="100", requirements="[1-9][0-9]{0,2}", description="The maximum number of items to receive per page")
 * @QueryParam(name="type", nullable=true, description="Only show items of this type.")
```

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
