### ISSUE TITLE
JMS MaxDepth attribute

### ISSUE THREAD

**Issue by chrisjohnson00** [nelmio/NelmioApiDocBundle#509]
I have a large object graph and needed to specify the MaxDepth for JMS serialization.  However, when I include the class for the 'output', I get the full depth listed in my docs.  I'd like to have the docs honor the max depth settings on my related classes.  
Note: some my objects have a max depth of 1, while others have 3; so the solution would need to support this as well.
I tried to get this working myself... but failed.  Is a bit over my head, so I'm submitting this in hopes a larger brain can help me!

**Comment by nazar256** [comment]
I also faced the same problem. Because of that I have not actual ApiDoc. But worse thing is that someday it may cause infinite loops.

**Comment by kuborgh-tvogt** [comment]
Old request, but I second it, and strongly.

**Comment by benji07** [comment]
:+1:

**Comment by kuborgh-tvogt** [comment]
I already does some parsing, just MaxDepth is not parsed. Infinite recursion is prevented in JmsMetadataParser.
Reading the MaxDepth and adding it to the recursion call should not be so difficult.

**Comment by kuborgh-tvogt** [comment]
I cannot do this in production quality, but basically:
```php
        // iterate over property metadata
        foreach ($meta->propertyMetadata as $item) {
            if (!is_null($item->type)) {
                $name = $this->namingStrategy->translateName($item);

                if (isset($item->maxDepth)) {
                    // respect max depth setting in api doc
                    if ($depth > $item->maxDepth) {
                        continue;
                    }
                }

```

and add a $depth parameter to doParse()

**Comment by kuborgh-tvogt** [comment]
For my particular project, simply disabling to descend into nested classes at all would also help a lot, and it's an even more trivial fix, just add a configuration condition to line 170 in JmsMetadataParser. But I can't figure out how to pass configuration parameters into this parser.

**Comment by taliah** [comment]
I need the MaxDepth function, too. Without it entities which relate to each other (mn) cause an infinite loop in my project, but I have to enable both because we need to persist from both entities. At the moment we are only able to persist from one of both.
Have already someone found a solution which does not require to fork a 3rd party bundle?

**Comment by fnagel** [comment]
+1

**Comment by guillermogfer** [comment]
+1

**Comment by sromano88** [comment]
+1 to read @MaxDepth annotation.

**Comment by egordanilenko** [comment]
+1

**Comment by tetronomis** [comment]
Any update on that issue?

**Comment by jamescaruso** [comment]
+1

**Comment by stingus** [comment]
+1

**Comment by Bored0ne** [comment]
+1

**Comment by KeKKai** [comment]
@willdurand is there any possibility this issue will be resolved?

**Comment by GregoirePiat** [comment]
+1

**Comment by mitrae** [comment]
+1

**Comment by sebastiengregoire** [comment]
+1

**Comment by Andreeey** [comment]
+1

**Comment by dbu** [comment]
pull requests welcome ;-)
