### ISSUE TITLE
Split views into multiple parts

### ISSUE THREAD

**Issue by Spomky** [nelmio/NelmioApiDocBundle#510]
If a developer want to override a part of the file [method.html.twig](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/method.html.twig), he must rewrite the entire file.

Is it possible to split the file into small files and allow to override any part of method.html.twig an easier way?

For example:

Create a new file `Resources\views\method.https.html.twig`

```
{% if data.https %}
    <span class="icon lock" title="HTTPS"></span>
{% endif %}
```

And update `Resources\views\method.html.twig` L14-L16:

```
{% include 'NelmioApiDocBundle::method.https.html.twig' %}
```

With such files, a developper can only override `method.https.html.twig` and not the whole `method.html.twig` file.

**Comment by zomberg** [comment]
+1

**Comment by bilel-noomene** [comment]
+1

**Comment by dbu** [comment]
pull requests are welcome ;-)

**Comment by Spomky** [comment]
Sure. Will try to find time to help you
