### ISSUE TITLE
Inconsistencies in parameter arrays returned by handlers and parsers.

### ISSUE THREAD

**Issue by bezhermoso** [nelmio/NelmioApiDocBundle#520]
Currently, the resolution of the parameter arrays is done by `AbstractFormatter`. IMO, we could improve this by moving this logic to `ApiDocExtractor` itself. Ideally, the formatters would just expect that certain properties already exists in each parameter/filter item.

I would elect to use the `OptionsResolver` component for this. In fact, I have a working implementation for this but unfortunately I intertwined it with an existing PR (https://github.com/nelmio/NelmioApiDocBundle/pull/499)

If you guys agree with this approach, I will extract the option resolution stuff into a separate PR.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
