### ISSUE TITLE
[Question] How does everyone handle documenting _embedded resources from willdurand/Hateoas bundle?

### ISSUE THREAD

**Issue by erestar** [nelmio/NelmioApiDocBundle#521]
Are there any plans to add a Hateoas Parser when creating the response in the Extractor?

**Comment by jessegreathouse** [comment]
(thumbsup)

**Comment by BenjaminCanape** [comment]
+1

**Comment by kirkhelek** [comment]
+1 Any way, is there another way to reach it?

**Comment by develth** [comment]
I dived a little bit into the code and build a solution for parsing the data into the api doc:

https://gist.github.com/develth/def3ed03dbb6b63e43770b368d3327b4

**Comment by dbu** [comment]
@develth do you want to do a pull request with the solution?

**Comment by develth** [comment]
@dbu - should i pull it into rhis project? That would reqiure the hateoas bundle in AliDocBundle, wouldn't it?

**Comment by dbu** [comment]
i was closing a million things in the last hours so did not look that closely. i think we do not want to make the hateoas bundle a dependency of the nelmio bundle. but i think its ok to just have the class in the apidoc bundle and in the configuration check if the hateoas bundle is available when the user tries to enable hateoas support (or even use something like true/false/auto to automatically enable hateoas support by default, if the bundle is available)

**Comment by dbu** [comment]
and for the tests, we would have hateoas in require-dev which seems fine.
