### ISSUE TITLE
Annotation section to a class

### ISSUE THREAD

**Issue by Chrysweel** [nelmio/NelmioApiDocBundle#530]
Hello.

I have a question. 
Can I include annotation "section" to all Class?

Now I have include this same annotation in all my functions of a controller... 

Thanks in advance

**Comment by nass600** [comment]
+1. PreAuthorize annotation at class level does not propagate to the controller methods

**Comment by NikitaKharkov** [comment]
I thing it will be cool if you can implement section to all class. And if we have a route with another section just rewrite parent.
Examples:
```
    /**
     * Class OwnerController
     * @ApiDoc(section="owner") 
     * @Route("/owner")
     */
    class OwnerController extends FOSRestController
    {
        /**
        * @ApiDoc(section="ownerUser")
        * [here section ownerUser]
        **/ 
         public function listAction(): Response {}

       /**
        * [here section owner]
        **/ 
         public function listAction(): Response {}
     }

**Comment by woofiewilly** [comment]
+1. It's been 3 years and this seems like a fairly simple feature that should already be a thing.

**Comment by dbu** [comment]
happy for a pull request that adds the feature. there are now active maintainers again that will review pull requests and merge them.

**Comment by NikitaKharkov** [comment]
Can you add link to pull request?

**Comment by woofiewilly** [comment]
Why is the issue closed if there is no PR?

**Comment by dbu** [comment]
its super old and nothing ever happened. as said, if one of you wants to work on it, please do and the maintainers will review it and help getting it merged. this bundle is no business, features happen because the person who needs them implements them, or pays somebody to implement it...
