### ISSUE TITLE
Allow class to be defined as a container parameter

### ISSUE THREAD

**Issue by Aaike** [nelmio/NelmioApiDocBundle#532]
I think it would be good if the class options for input and output could be defined as container parameters rather than specifying the actual class
for example instead of doing:

```
output={
 "class"="Acme\UserBundle\Entity\User"
}
```

you could do 

```
output={
 "class"="fos_user.user_class"
}
```

This comes in handy when the rest controller is created in a parent bundle and all you need is to change the class that the controller uses.

i've implemented this in my fork : https://github.com/Aaike/NelmioApiDocBundle/commit/5bc47eb7feda9ecdc6eff8e0954b1ffd8f14c1dd

maybe it can be merged ?

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
