### ISSUE TITLE
How to change twig template for custom styling (proposal)

### ISSUE THREAD

**Issue by koemeet** [nelmio/NelmioApiDocBundle#537]
Hi,

Currently you cannot simply override the template that gets rendered by the `HtmlFormatter`. It is hardcoded to `NelmioApiDocBundle::resources.html.twig`. Since I cannot use the default symfony `app/Resources/views/NelmioApiDocBundle` solution, I need to change the template that gets rendered.

Can I make a PR, that adds a configuration option to override the resources template?

``` php
protected function render(array $collection)
    {
        return $this->engine->render('NelmioApiDocBundle::resources.html.twig', array_merge(
            array(
                'resources' => $collection,
            ),
            $this->getGlobalVars()
        ));
    }
```

**Comment by syzop** [comment]
This would be useful for me as well.

**Comment by stof** [comment]
Why couldn't you use the Symfony template override ?

**Comment by steffenbrem** [comment]
@stof Because it would not be configurable then. I am creating a bundle that uses Nelmio and also needs to be overridable, if that makes sense.

**Comment by syzop** [comment]
Sorry, disregard, it works fine. I was simply using the wrong name.
The following works: app/Resources/NelmioApiDocBundle/views/method.html.twig (etc..)

**Comment by Fabmilan** [comment]
Hello there,

I actually try to override template but it doesn't work.
I created app/Resources/NelmioApiDocBundle/views/layout.html.twig but it is not overriding the template.

Any ideas ? Thx a lot ;)

**Comment by stof** [comment]
Well, there is no `layout.html.twig` in this bundle, so this explains why overwriting this template has no effect: the bundle does not use it.

**Comment by Fabmilan** [comment]
Thx for your answer but it is a little bit weird. There is a layout.html in this bundle actually ^^

{% extends "NelmioApiDocBundle::layout.html.twig" %}

And this is the only file including assets (css, js, ...) and <html> structure.

**Comment by Indurain** [comment]
According to documentation I "just follow the convention: app/Resources/{BUNDLE_NAME}/views/{PATH/TO/TEMPLATE.html.twig}"; so I made 
app/Resources/ApiDocBundle/views/Components/layout.html.twig but it doesn't worked. So thanks to syzop (but not according to conventions)
I created app/Resources/NelmioApiDocBundle/views/layout.html.twig and it works forme.

**Comment by yonisolo** [comment]
Hi there,
I know this topic was originaly for Symfony3.x but in Symfony4, the standard overriding doesn't work,
under:
templates->bundles->NelmioApiDocBundle->Resources->views->SwaggerUI->index.html.twig
the overriding doesn't work at all...
Is there anybody to help for this please?

**Comment by dbu** [comment]
lets use template overwriting for that

**Comment by skhattane** [comment]
@yonisolo for symfony 4 the exact path is :
templates->bundles->NelmioApiDocBundle->SwaggerU**i**->index.html.twig (with the "i" of "SwaggerUi" in lowercase)

**Comment by yonisolo** [comment]
@skhattane yes you're right thanks for pointing this typo error

**Comment by bradesignstudio** [comment]
I have a bundle under, and a project that require the bundle. How can I override this index.html.twig inside the bundle, not the project? Creating a folder templates/bundles.... on bundle root folder does not work.

**Comment by dbu** [comment]
please do not comment on closed issues, but rather open a new issue referencing this one, @bradesignstudio

we discussed in #1330 that it would be nice to have the possibility to extend the template instead of just replacing it. if somebody does a pull request for that, the bundle will get a configuration option to specify the template to use, and you could have your bundle contain the template and configure nelmio to use that template.
