### ISSUE TITLE
Support for swagger 2.0

### ISSUE THREAD

**Issue by dersteve** [nelmio/NelmioApiDocBundle#538]
Do you plan on supporting the swagger 2.0 specification?

**Comment by dubrox** [comment]
+1

**Comment by wodka** [comment]
Any update on the progress - is there some way to support you adding it?

**Comment by nemke** [comment]
+1

**Comment by cadupont** [comment]
+1

**Comment by maver1ck** [comment]
Any update on progress ?
Unfortunatelly Swagger Converter from 1.2 to 2.0 isn't working very good.

**Comment by willdurand** [comment]
ping @bezhermoso

**Comment by JulianStier** [comment]
+1

**Comment by ccazette** [comment]
+1

**Comment by carl-boisvert** [comment]
+1

**Comment by marco-msg-ferrari** [comment]
+1 Can we help?

**Comment by edamov** [comment]
+1

**Comment by andreaslarssen** [comment]
+1

**Comment by peternijssen** [comment]
+1

**Comment by edvinasme** [comment]
has there been any work started regarding this?

**Comment by andreaslarssen** [comment]
And can we help?

**Comment by andreaslarssen** [comment]
@bezhermoso, how's the work going? Anything we can do to help? If you don't have the time to work on this, maybe you could fill us in on the idea? I'm going to need this soon, and I'm not going to write my own, so I could put in some hours,

**Comment by andreaslarssen** [comment]
What do you guys think? Would it make more sense to add a Swagger2Formatter, or make The SwaggerFormatter handle versions?

**Comment by bezhermoso** [comment]
Hi guys,

I see quite a lot of interest in this, and pardon me for not being around to respond -- I am doing this on my free-time and things has been really busy at work lately, I hope you guys understand. 

Here is an update:

My initial implementation was a part of a project and was using the vendor namespace for that project. Basically it simply was just a wrapper around the existing formatter but reformats it to conform with Swagger 2.0 specs. It was ugly. Therefore I decided to redo everything from scratch and make it a stand-alone formatter and not relying on the existing one.

I will be creating a pull request today with what I have so far (it is in its early stages), and I think it would be a good place for us to discuss how you guys want it to work. For example, right now a separate configuration group is necessary (`nelmio_api_doc > swagger2` vs `nelmio_api_doc > swagger`), etc.

Luckily I will be able to afford to spend some time to work on this in the coming week or two.

**Comment by bezhermoso** [comment]
PR (work-in-progress) here: https://github.com/nelmio/NelmioApiDocBundle/pull/705

**Comment by Diwann** [comment]
new PR https://github.com/nelmio/NelmioApiDocBundle/pull/744 :-) 
it's coming \o/

**Comment by manuelbcd** [comment]
+1

**Comment by hpatoio** [comment]
I think this should be closed. It seems that PR #744 has been refused.

**Comment by willdurand** [comment]
Yep. But there should be a good news about OpenAPI/Swagger and this bundle. Stay tuned.

**Comment by Diwann** [comment]
Hi, any news about the good news?

**Comment by willdurand** [comment]
It is under discussion in #900
