### ISSUE TITLE
Collections support for Swagger?

### ISSUE THREAD

**Issue by dersteve** [nelmio/NelmioApiDocBundle#547]
When using arrays as let's say return parameter, does the generated Swagger.json support this and be compatible with the swagger spec (v.1.2) when it comes to arrays/collections?

In swagger it should have a type='array' and items='...actual type goes here... with $ref element..'. have a look at this example http://petstore.swagger.wordnik.com/api/api-docs/pet

It seems the official spec for handling arrays is not really concrete about the syntax I think. It leaves the chapter for arrays out; for more information see here https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#43-data-types

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
