### ISSUE TITLE
Odd regression between 2.6 and 2.7

### ISSUE THREAD

**Issue by gnat42** [nelmio/NelmioApiDocBundle#551]
So I wanted to update to 2.7 however when I do I get some odd parameter show up in the description and sandbox. I've taken a screenshot of the issue. However as a description suppose the form being used is named 'ibd'. With 2.7 I get the first parameter as [ibd] with the input hint being [object ibd] Value. I don't even know where this comes from or what to do with it. Its obviously not there with 2.6. Is this something I'm doing wrong?

![2 6](https://cloud.githubusercontent.com/assets/325591/5351763/7aeec1de-7f18-11e4-8d94-78719ed2e1d3.png)

![2 7](https://cloud.githubusercontent.com/assets/325591/5351768/807dd3f6-7f18-11e4-8d63-1b49110dc1e8.png)

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
