### ISSUE TITLE
FormTypeParser requires PHP 5.4.

### ISSUE THREAD

**Issue by TomiS** [nelmio/NelmioApiDocBundle#556]
I ran into problems when trying to update ApiDocBundle. It's because we're still using PHP 5.3. and at least the following line of code requires PHP 5.4
https://github.com/nelmio/NelmioApiDocBundle/blob/2.7.0/Parser/FormTypeParser.php#L287

Is this intended, as Symfony only requires PHP 5.3? And if it is, would it be a good idea to state the required PHP version in composer.json?

**Comment by willdurand** [comment]
5.4 is dead now, so I think we should not add any hack right now
