### ISSUE TITLE
Escaping double quote char in description param

### ISSUE THREAD

**Issue by ogizanagi** [nelmio/NelmioApiDocBundle#559]
This is minor, but escaping a double quote char in the `description` parameters for `QueryParam` or `RequestParam` annotations results in the following on the doc:
`""false"" to disable.`=> `\"false\" to disable.`

``` php
    /**
     * [...] 
     * @QueryParam(name="from_date", default="now", requirements="^(\d+|now|false)$", strict=true, nullable=true, description="UNIX Timestamp. ""false"" to disable.")
     * [...]
     * @param string|int $from_date
     * @return array
     */
    public function cgetAction($from_date) { [...] }
```

**Comment by ekkinox** [comment]
+1

**Comment by aminin** [comment]
+1

**Comment by franciscomemoli** [comment]
+1

**Comment by franciscomemoli** [comment]
I found a temporal solution doing this
*      {"name"="extradata", "dataType"="string", "required"=false, "description"="This is my JSON {""yearsold"": ""25"", ""name"":""Fran""}"},
using double double quotes.
Hope this help you.

**Comment by dbu** [comment]
version 3 is a complete rewrite and starts using swagger-php for annotations. please check if this is still a problem with version 3 and a recent symfony version.
