### ISSUE TITLE
"Notice: Undefined index: actualType" when using an JMS exclusion policy

### ISSUE THREAD

**Issue by Zzortell** [nelmio/NelmioApiDocBundle#561]
Hello,
When I use on my entity (an User extending a FOS User) any JMS exclusion policy I have an error :
```
Notice: Undefined index: actualType in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\symfony\vendor\nelmio\api-doc-bundle\Nelmio\ApiDocBundle\Extractor\ApiDocExtractor.php line 444
```
I don't know that to do !

**Comment by jessevanmuijden** [comment]
seems to be an ongoing issue with this actualType

**Comment by Zzortell** [comment]
Ok. I personally temporarily place this code at line 443 pending the fixing of the issue :
```php
			if ( empty($info['dataType']) && !isset($info['actualType']) && function_exists('dump') ) { //Zz
				dump($name, $info);
			}
            if ( empty($info['dataType'])     && isset($info['actualType']) ) {  //Zz
                $array[$name]['dataType'] = $this->generateHumanReadableType($info['actualType'], $info['subType']);
            }
```
I hope it will be fix soon because my doc is wrong during this time. Good luck !

**Comment by gabrielAnglada** [comment]
Same error here and Zzortell patch works fine!

I also hope it will be fixed as soon as possible, thanks!

**Comment by willdurand** [comment]
Feel free to open a PR :)
