### ISSUE TITLE
Required form fields for PUT method always false?

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [nelmio/NelmioApiDocBundle#565]
Is there a reason why for the PUT request the required form fields are always false, while for the POST / PATCH methods they reflect what is specified in the form class?

If this has to do with the idempotence of the PUT method, my inclination was to do it the other way round (POST/PATCH does not require all the form fields while PUT does)... 

PUT request:
![put](https://cloud.githubusercontent.com/assets/1670232/5773543/04d551ce-9d64-11e4-81bb-e5fa34d5a7e5.png)

POST / PATCH requests:
![post](https://cloud.githubusercontent.com/assets/1670232/5773545/074aef18-9d64-11e4-8a39-ede95a4de617.png)

![patch](https://cloud.githubusercontent.com/assets/1670232/5773843/8f861850-9d67-11e4-9439-640450069343.png)

**Comment by nakashu** [comment]
bump .. 
Noticed this also. Can someone please explain the reasoning, or link to a resource explaining it.
If the main reason for it is possibility to do partial update with PUT, should then also PATCH have all fields optional ?

**Comment by willdurand** [comment]
Well, PUT should not be all set to `false`, and `PATCH` should get a diff, not single values.

**Comment by nakashu** [comment]
Sorry. am confused from the answer. Are saying that it is a bug then ?
That PUT documentation should respect definitions?

**Comment by michaelpopok** [comment]
Up the original question.

In [this article](http://williamdurand.fr/2012/08/02/rest-apis-with-symfony2-the-right-way/#put-vs-patch-fight) @willdurand has stated:
> Updating a resource in REST means replacing it actually, especially if you use the PUT HTTP verb.

So as I understand all fields for an entity should be required in case of `PUT` action (can be exceptions in some cases). Anyway I believe that this check should be removed [in Extractor](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/ApiDocExtractor.php):
```php
if ('PUT' === $annotation->getMethod()) {
    // All parameters are optional with PUT (update)
    array_walk($parameters, function ($val, $key) use (&$parameters) {
        $parameters[$key]['required'] = false;
    });
}
```

**Comment by judgedim** [comment]
@michaelpopok  I suggest you provide PR :)

**Comment by kuborgh-hgiesenow** [comment]
I think someone mixed up PUT with PATCH. 
For PATCH it makes sense, that there are no required field, as the resource must already exists and there is afaik no way to clear a filled field.

**Comment by tristanlins** [comment]
Is there a chance to merge the fix https://github.com/kuborgh/NelmioApiDocBundle/commit/72ab9b9b7c2c231ed4d34db4736a9cde08d7d840 from @kuborgh-hgiesenow ?
I'm still confused of this issue :-D

**Comment by willdurand** [comment]
Can someone open a Pull Request for that?

**Comment by kuborgh-hgiesenow** [comment]
The codebase (especially tests) have changed too much since 2.10.0, so it's not mergable anymore. I had no time to look at it again. 
@tristanlins feel free to open a new PR (based on mine if you wish to)
