### ISSUE TITLE
Documentation for FOSUserBundle

### ISSUE THREAD

**Issue by sergiu-popa** [nelmio/NelmioApiDocBundle#568]
Hello,

I'm creating a POST in my RestController (using FOSRestBundle) to create a new user (using FOSUserBundle User Manager). This is my code:

``` php
public function postUsersAction(ParamFetcher $paramFetcher)
{
  $request = $this->getRequest();
  $userManager = $this->container->get('fos_user.user_manager');
  $user = $userManager->createUser();
  $user->setUsername($request->get('username'));
  $user->setEmail($request->get('email'));
  $user->setPlainPassword($request->get('plainPassword'));
  $user->addRole($request->get('role'));
  $validator = $this->get('validator');

  $errors = $validator->validate($user, array('Registration'));
  if (count($errors) == 0) {
    $userManager->updateUser($user);
    $param = array("slug" => $user->getUsername());
    $view = RouteRedirectView::create("byexample_demo_userrest_get_user", $param);
  } else {
    $view = $this->get_errors_view($errors);
  }
  return $view;
}
```

How should I document the method using Nelmio? Using my user class (which extends FOSUserBundle User class) as output and the registration form type as Input? I tried this and it's not working. Do I need to manually specify the parameters, like username, email and password?

``` php
* 
   * @ApiDoc(
   *  description="Create a new user object",
   *  input="FOS\UserBundle\Form\Registration\RegistrationType",
   *  output="Lxo\MyBundle\Entity\User"
   * )
```

Thank you

**Comment by foaly-nr1** [comment]
Wouldn't this be the correct input form type class ```FOS\UserBundle\Form\Type\RegistrationFormType```?

**Comment by bizmate** [comment]
I am also unsure on how to use the input doc correctly. I get nothing in the sandbox or documentation with i try to use it. Using an entity with JMS annotations and it should be supported as far as i know

**Comment by foaly-nr1** [comment]
@bizmate it's a form type, not an entity.

**Comment by bizmate** [comment]
@foaly-nr1  you should be able to also use normal classes with JMS annotations as per documentation

From documentation -
input: the input type associated to the method (currently this supports Form Types, classes with **JMS Serializer** metadata, classes with Validation component metadata and classes that implement JsonSerializable) useful for POST|PUT methods, either as FQCN or as form type (if it is registered in the form factory in the container).

as and when you have a working example pls share on a gist or something

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
