### ISSUE TITLE
"Input" configuration does not support validation groups or complex Assertions when using Form Type

### ISSUE THREAD

**Issue by catchamonkey** [nelmio/NelmioApiDocBundle#574]
When pointing the input to a Form Type, it correctly reads **some** validation data from the related Entity class (annotations in this case). It reads if it's required, but not more complex rules like Length, min max etc.
Also, you cannot specify which validation groups the route is using for the docs, so they all use, all the validation defined.

Is this a fairly easy addition?

Something like;

```
input={
     "class"="Acme\Bundle\Entity\User",
     "validation_groups"={"creation"}
 }
```

**Comment by Avtonom** [comment]
+1

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
