### ISSUE TITLE
@param annotation override (ParamConverter)

### ISSUE THREAD

**Issue by Soullivaneuh** [nelmio/NelmioApiDocBundle#579]
I have the following controller's action:

``` php
/**
 * @param Plan $plan The plan id
 *
 * @ApiDoc(
 *  description="Returns plan details",
 *  output={
 *      "class"="AppBundle\Entity\Plan",
 *      "groups"={"details"}
 *  }
 * )
 *
 * @return Response
 */
public function getAction(Plan $plan) // [...]
```

This render the following documentation:
![image](https://cloud.githubusercontent.com/assets/1698357/6314821/ef21bc90-b9ed-11e4-9474-b564744372f6.png)

I want to change the `plan` parameters to `plan_id` or `id` and add some requirements, so I test with this annotation:

``` php
/**
 * @param Plan $plan The plan id
 *
 * @ApiDoc(
 *  description="Returns plan details",
 *  requirements={
 *      {
 *          "name"="plan_id",
 *          "dataType"="integer",
 *          "requirement"="\d+",
 *          "description"="The plan's id"
 *      }
 *  },
 *  output={
 *      "class"="AppBundle\Entity\Plan",
 *      "groups"={"details"}
 *  }
 * )
 *
 * @return Response
 */
public function getAction(Plan $plan) // [...]
```

And then, I have this:
![image](https://cloud.githubusercontent.com/assets/1698357/6314831/30989e50-b9ee-11e4-8a7c-0d6d71bacc0c.png)

I can't remove the `plan` parameters, even if I remove the `@param` annotation, that I want to keep.

Is that an issue or a misconfiguration? How to solve it?

I'm using `2.7.x-dev` version.

Thanks.

**Comment by satanasdiabolo** [comment]
You should put your `@param` after your `@ApiDoc` and you should not have `plan` parameter anymore

**Comment by Soullivaneuh** [comment]
@satanasdiabolo sorry but this didn't change anything.

Did this:
```php
    /**
     * @ApiDoc(
     *  description="Returns plan details",
     *  output={
     *      "class"="AppBundle\Entity\Plan",
     *      "groups"={"details"},
     *      "parsers"={
     *          "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
     *      }
     *  }
     * )
     *
     * @param Plan $plan The plan id
     *
     * @return Response
     */
```

Result: Same as second screenshot but with reverse ordering of parameters.

**Comment by satanasdiabolo** [comment]
That's strange, I have a similar Action, and on I have not this problem.
Here is my documentation
```php
/**
 * @ApiDoc(
 *  description="Item Details",
 *  section="Item",
 *  requirements={
 *      {
 *          "name"="id",
 *          "dataType"="integer",
 *          "description"="Id of the item",
 *          "requirement"="\d+"
 *      }
 *  },
 *  output="\AppBundle\Entity\Item",
 *  statusCodes={
 *      200="Returned if everything is fine",
 *      404="Returned if the id of the item does not exists"
 *  }
 * )
 * @Get("/{id}", requirements= {"id"= "\d+"})
 *
 * @param Item $item
 * @return Item
 */
```
And the result:
![image](https://cloud.githubusercontent.com/assets/1850524/6571040/f71b2648-c703-11e4-825a-d6e1c9993480.png)
 I use the latest version of API Doc and I had the same result with the previous dev version

**Comment by Soullivaneuh** [comment]
Why `@return Item` and not `Response`?

Tried with this version:
```sh
$ composer info --installed | grep nelmio
nelmio/api-doc-bundle                    dev-master e23a7d7 Generates documentation for your REST API from annotations
```

And after a fresh upgrade to 2.8.0:
```sh
$ composer info --installed | grep nelmio
nelmio/api-doc-bundle                    2.8.0              Generates documentation for your REST API from annotations
```

Nothing change, same issue.

**Comment by satanasdiabolo** [comment]
I use FOSRestBundle, and with the configuration I've made, if I return an object, the Bundle do the rest.

**Comment by allan-simon** [comment]
what i did personnaly is to put 

```
     *  requirements={
     *      {
     *          "name"="plan",
     *          "dataType"="integer",
     *          "requirement"="\d+",
     *          "description"="The plan's id"
     *      }
     *  },
```

in my doc so that "plan" overide the Plan

**Comment by allan-simon** [comment]
@satanasdiabolo   the difference is that you have explicitly put the route 

```
 * @Get("/{id}", requirements= {"id"= "\d+"})
```
so it knows the parameter is `{id}`
but @Soullivaneuh  has not put expliclity the annotation so you dump the route generated you will see that

```
public function getAction(Plan $plan)
```
is turned into

```
/action/{plan}
```
hence why this bundle is generating a `param`  requirement

**Comment by Soullivaneuh** [comment]
@allan-simon Thanks for your example.

Unfortunately, this work only if your requirement has the same name as the parameter name.

What I want to do:

```php
     *  requirements={
     *      {
     *          "name"="id",
     *          "dataType"="integer",
     *          "requirement"="\d+",
     *          "description"="The plan's id"
     *      }
     *  },
```

But with this configuration, I got again double parameter.

Maybe an "object link relation" option exists?

**Comment by allan-simon** [comment]
yes the example i gave was actually working only because i was playing with the edge base of the requirements getting the same name so one was hidding the other. 

I think you can just an explicit route 

```
 * @Get("/actions/{id}", requirements= {"id"= "\d+"})
``
(without changing your method signature)

**Comment by Soullivaneuh** [comment]
Indeed but we have to set the route and loose the rest routes auto generation. Very painful.

Btw, I tested it. Works, but got an extra method definition coming from nowhere:

![plan_other](https://cloud.githubusercontent.com/assets/1698357/6992616/cfcbe77e-dad8-11e4-82ec-8976e0c3a63f.png)

**Comment by allan-simon** [comment]
then i have to admit I don't know :/ , I haven't used this bundle for long, I just happened to have run into the same issue as you.

**Comment by hiromik** [comment]
@Soullivaneuh It's been a while and I've also seen your post on SO about it, did you find any fix? I don't wanna lose the automatic route generation just for this, and btw is that return value block showing json part of NelmioApiDocBundle, it looks nice and I'd like to have the same feature.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
