### ISSUE TITLE
Sandbox sends filters as POST parameters instead of query string if POST parameters are present

### ISSUE THREAD

**Issue by solazs** [nelmio/NelmioApiDocBundle#580]
Filters are sent in query parameters on GET, which is fine, but on PUT (and also POST/PATCH...) calls they are sent as POST  parameters despite being declared using the QueryParam annotation, which should always be interpreted as GET parameters.

```
    /**
     * @Annotations\QueryParam(
     *   name="admin",
     *   requirements="^([tT][rR][uU][eE]|[fF][aA][lL][sS][eE])",
     *   default=false,
     *   description="Run in admin mode")
     *
     * @ApiDoc(
     *   requirements ={
     *     {"name"="id", "dataType"="integer", "required"=true, "requirement"="\d+"},
     *     {"name"="_format", "requirement"="xml|json", "description"="response format"}
     *   },
     *   input = "Acme\DemoBundle\Form\SomeType"
     * )
     **/
```

The generated docs contain an "admin" filter and all the parameters from SomeType, which is all right, but the request is the following:

```
GET parameters:
none

POST parameters:
admin (from queryparam)
name (from the Form)
```

but is should be:

```
GET parameters:
admin

POST parameters:
name
```

**Comment by sairuskvk** [comment]
Confirmed ... maybe it is proper behaviour than it will be awesome to have configuration option to change that sending queryparam as query string instead of POST in body.

**Comment by AlmogBaku** [comment]
confirmed, happening to me too

**Comment by stelzek** [comment]
any abilidy to override behavior?

**Comment by solazs** [comment]
I've tried to force filters to be processed as GET parameters, but I'm afraid this is done from JavaScript.
Can anyone point me to the unuglified and unminimified JavaScript code of Resources/public/all.js, because debugging that takes more patience than I've got.

**Comment by solazs** [comment]
I've modded the Bundle to force all filters as GET parameters. The problem is that filters are handled as parameters and passed as data to jquery.ajax. There is no way to specify query parameters in jquery, so I had to append filters to the URL manually.

I've created a [pull request](https://github.com/nelmio/NelmioApiDocBundle/pull/757) addressing this issue.

**Comment by willdurand** [comment]
Ok let's discuss the PR #757 now.
