### ISSUE TITLE
Swagger /items and /items/{id} have the same "nickname"

### ISSUE THREAD

**Issue by jdeniau** [nelmio/NelmioApiDocBundle#587]
Given this controller:

``` php
class ItemController
{
    public function getItemsAction();
    public function getItemAction($id);
}
```

The swagger generated nicknames will be `get_items` for each action.
Is there a way to separate the two functions ? or maybe just override the nickname of a action in the `@ApiDoc` class:

```
@ApiDoc(
    nickname="getItems"
)
```

Thank you

**Comment by IgorN** [comment]
Do you have any news about this trouble?

**Comment by ZandorZ** [comment]
I think there is no "nickname" attribute

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
