### ISSUE TITLE
Notice: Undefined index: required

### ISSUE THREAD

**Issue by ivaaaan** [nelmio/NelmioApiDocBundle#589]
I have error: 
`( ! ) Notice: Undefined index: required in vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php on line 75`
My api block:
```
    /**
     * This method create and send mission to uds.
     *
     * @Route("/mission/create")
     * @Method({"POST"})
     * @ApiDoc(
     *  resource="Missions",
     *  description="This method create and send mission to uds.",
     *  statusCodes={
     *      200="Returned when successful",
     *      400="Returns in case of transmission error parameters"
     *  },
     *  parameters={
     *    {"name"="client_name","dataType"="string","Required"="true","description"="Client name","required"=true}
     * }
     * )
     */
```
APIDoc version: ` "nelmio/api-doc-bundle": "~2.8"`

**Comment by maxvanceffer** [comment]
I have the same error.

**Comment by maxvanceffer** [comment]
OK, you can fix it just for right now change Required to "required"=true and remove double entries oif required. And check all annotations for api doc, they all must contains required param

**Comment by aaronahearne** [comment]
If your'e finding this error is being thrown without a file name or a line number listed, you may be missing the "required" field in one of your parameter declarations.
