### ISSUE TITLE
Add support for 'collection' type in both the doc and the sandbox

### ISSUE THREAD

**Issue by willdurand** [nelmio/NelmioApiDocBundle#59]

**Comment by AlmogBaku** [comment]
@willdurand do you have a lead? I want to help solving this issue.

**Comment by foaly-nr1** [comment]
@AlmogBaku
![image](https://cloud.githubusercontent.com/assets/282458/10352239/db76f938-6d45-11e5-87e6-e9f1ffb47dcb.png)

**Comment by dbu** [comment]
collections are supported with the swagger-php annotations in version 3 of this bundle
