### ISSUE TITLE
Javascript error when we do requests in sandbox

### ISSUE THREAD

**Issue by xavividal** [nelmio/NelmioApiDocBundle#594]
Hi, 

The public API works as expected but with nelmio api doc version 2.8.0 we find all requests in sandbox are returning this error:
Firefox:
0 [Exception... "Illegal value"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: http://localhost:8000/app_dev.php/prices/doc/#get--prices-airline

Safari:
0 Error: SyntaxError: DOM Exception 12

Chrome:
0 SyntaxError: Failed to execute 'open' on 'XMLHttpRequest': '' is not a valid HTTP method.

The ajax request is not even launched, there are no logs or console errors in browser developer tools.

**Comment by dopee** [comment]
I can confirm this. Our client uses it to test the API. Reverting back to 2.7.0 for the moment.

**Comment by piron4o** [comment]
Same bug for me too.

**Comment by xavividal** [comment]
Yes, confirmed. We override the template too. False alarm ;)
