### ISSUE TITLE
add possibility to see sample of result

### ISSUE THREAD

**Issue by allan-simon** [nelmio/NelmioApiDocBundle#598]
I don't know if it's in the scope of the project but it would be great to have

  * a sample of request/response (at least response)
  * for Object field (in response) of the documentation , have it clickable and it shows a sample of the field in the object 

maybe it can get populated from fixtures (but maybe it will overcomplicate it ? but of course the user can choose just not to put so for most of people it will not make a simple doc harder)

**Comment by willdurand** [comment]
Feel free to contribute (I know I already told you that 5min ago, but there is no other alternative yet)
