### ISSUE TITLE
Ability to use @return from PHPdoc of a controller action to populate "output" 

### ISSUE THREAD

**Issue by allan-simon** [nelmio/NelmioApiDocBundle#601]
Currently I have to duplicate the doc for phpdoc and nelmio
```
     * @ApiDoc(
     *    resource=true,
     *    description="get list of analyst",
     *    output="array<MVMS\ApiBundle\Entity\Analyst>"
     * )
     * @return Analyst[]
```

it would be great if output was able to parse the @return tag

**Comment by willdurand** [comment]
Feel free to contribute :)

**Comment by allan-simon** [comment]
In a way if you close the issue, people that would be interested in contributing but are looking on ideas will not see it, and it more or less means that one can propose idea only if he makes the PR also.

**Comment by willdurand** [comment]
There are more issues than people working on this bundle unfortunately, so I try to get a better view of what is needed/urgent. Be sure that I am doing my best...

**Comment by allan-simon** [comment]
ok, I understand, no hard feelings.
