### ISSUE TITLE
Validation parsed with wrong name when SereazlizedName used

### ISSUE THREAD

**Issue by maZahaca** [nelmio/NelmioApiDocBundle#607]
Environment:
ApiDoc - last stable version

Problem: 
I set as input for API doc DTO class, which has some properties marked with JMS\Serializer\Annotation\SerializedName and some Validation annotations.
Nelmio\ApiDocBundle\Parser\JmsMetadataParser works fine (adding the name specified in the SerializedName), but Nelmio\ApiDocBundle\Parser\ValidationParser adds property name.

So, in docs I get two names SereazlizedName and PropertyName.
SereazlizedName only must be used for both cases

**Comment by Feniksss** [comment]
+1 I have the same issue.

**Comment by ktounet** [comment]
+1 same issue.

The mergeParameters function doesn't care about of serializedName, because the parsers are independents and it's a property specific to JMS Serializer.

**Comment by psampaz** [comment]
+1 exactly the same issue here

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
