### ISSUE TITLE
[Question] How can I work around open issue regarding entity choices/collections?

### ISSUE THREAD

**Issue by nspyke** [nelmio/NelmioApiDocBundle#618]
With #398 and #543 yet to be merged, how can I work around the issue now to prevent the list of choices being loaded and overloading my database?

I'm using a FormType as my input. Currently have no defined output.
 
Symfony 2.6.6
NelmioApiDocBundle 2.8.0

Currently I've done this in each entity
```php
public function __toString()
{
    return (string)null;
}
```

but this is not a suitable solution as it still outputs an array of empty strings for every record in the relation. For some relations this can be over 10,000.

**Comment by willdurand** [comment]
Feature has been merged. It will be part of release v2.9.0
