### ISSUE TITLE
Output annotation for properties added through JMSSerializer event subscriber (used with FOSRestBundle)

### ISSUE THREAD

**Issue by bgatellier** [nelmio/NelmioApiDocBundle#620]
Hi,

I had to add some properties to my serialized entity through the event subscriber of the JMSSerializerBundle ([see doc](http://jmsyst.com/libs/serializer/master/event_system)), as these properties are generated with a service (so they cannot be in the entity class).
Here is my implementation:

``` php
public function onPostSerialize(ObjectEvent $event)
{
    $groups = $event->getContext()->attributes->get('groups')->get();
    $visitor = $event->getVisitor();
    $entity = $event->getObject();

   if (in_array('list', $groups) || in_array('details', $groups)) {
       // Get the path of the thumbnails
       $picture_path = $this->cache_manager->getBrowserPath($entity->getPicturePath(), 'mobile');
       $thumbnail_path = $this->cache_manager->getBrowserPath($entity->getPicturePath(), 'mobile_thumbnail');

       // Add these paths as new keys of the serialized object
       $visitor->addData('image', $picture_path);
       $visitor->addData('miniature', $thumbnail_path);
   }
}
```

The serialized object is used by the FOSRestBundle, so I added the _ApiDoc()_ annotation to the controller, including the _output_ one:

``` php
/**
 * @ApiDoc(
 *  resource = true,
 *  output = {
 *   "class" = "array<Acme\DemoBundle\Entity\MyEntity>",
 *   "groups" = {"list"},
 *   "parsers" = {
 *     "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
 *   }
 *  },
 *  statusCodes = {
 *   200 = "Returned when successful"
 *  }
 * )
 */
public function cgetAction(ParamFetcher $param_fetcher)
{
}
```

The _output_ parameter of the annotation shows the entity properties in the API documentation as usual, but the one added with the event subscriber are not displayed (however they are returned when using the sandbox).
I have tried to add the these serialized properties as properties of the entity, but as they are not registered in DB, they does not show up in the documentation as well :(
So I have no idea about how to make these properties appear in the API documentation.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
