### ISSUE TITLE
Allow specifying the array name for jms parsed inputs

### ISSUE THREAD

**Issue by jhogendorn** [nelmio/NelmioApiDocBundle#623]
From #577:

> When you utilise a formtype as the input, you get the various elements as a subarray. Theres no way to get this behaviour currently when you utilise the jms serializer. [...]

When you specify a form as the input for the api endpoint, you end up getting input in the format of `formname[fieldname]` which makes sense. when you specify an entity and are looking for the jms serializer / validator inputs to populate the fields, they come out as a flat set of `fieldname`'s, and theres no way to make them mimic or match the style shown by the forms.

[This Patch](https://github.com/jhogendorn/NelmioApiDocBundle/commit/383ef0ea707dafd76b067a0c35d59620f044642c) Allows you to specify the name so that you can have this subarray'd style of inputs.

**Comment by jhogendorn** [comment]
I've updated this branch against master.

https://github.com/nelmio/NelmioApiDocBundle/compare/master...jhogendorn:feature/allownamingjmsinputs

I'd love to make this into a pull request that can be accepted, just let me know how I can help :)

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
