### ISSUE TITLE
Cannot include entity properties added by EventListener in output documentation

### ISSUE THREAD

**Issue by advancingu** [nelmio/NelmioApiDocBundle#625]
I have an entity that is serialized for output via API. In my ApiDoc I add the following:

```
output={
     *    "class"="Org\MyBundle\Entity\MyEntity",
     *    "groups"={"serialization_group"}
     *  },
```

This creates a `Return` section in the documentation where all exposed Entity attributes for `serialization_group` are documented.

The issue now is that this there is no way to also include documentation for attributes that are added by a serialization event listener (`serializer.post_serialize` event). In my case, the entity has one attribute which depends on a service for serialization, so I cannot directly expose the attribute via annotation but only through an event listener. Consequently the attribute is not listed in the documentation.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
