### ISSUE TITLE
Use manual route causing APIs to show up multiple times

### ISSUE THREAD

**Issue by radoslavius** [nelmio/NelmioApiDocBundle#628]
Hello,
if I want to use pluralize "users" instead of default "user" so it causes APIs to show up multiple times

![image](https://cloud.githubusercontent.com/assets/3509024/7792990/c07fe6e0-02b9-11e5-8315-d5f750a4f925.png)

routing_api.yml:

<pre>
ApiCustomersController:
    resource: "@AppBundle/Controller/Api/CustomersController.php"
    type:     rest
    defaults: {_format: json}
    prefix:   /api
</pre>

CustomersController.php:

<pre>
    /**
     * Post customer
     *
     * @ApiDoc(
     *   statusCodes={
     *     201="Returned when successful",
     *     400="Returned when some required parameter missing or is wrong type or email is duplicated",
     *   }
     * )
     *
     * @Rest\View(template=":api:customer.html.twig", templateVar="parameters")
     * @Rest\Put("users")
     *
     * @param Request $request
     *
     * @return mixed
     */
    public function putUserAction(Request $request)
    {
</pre>

![image](https://cloud.githubusercontent.com/assets/3509024/7793236/8fb841bc-02bc-11e5-878a-0639ca4c5e09.png)

Am I doing something wrong?

thanks

**Comment by radoslavius** [comment]
If I use the path /api/users/{guid}.{_format} so it seems to be ok. Originally I had only put method. Now I've added a post.

```php
/**
     * Post customer
     *
     * @ApiDoc(
     *   statusCodes={
     *     201="Returned when successful",
     *     400="Returned when some required parameter missing or is wrong type or email is duplicated",
     *   }
     * )
     *
     * @Rest\View(template=":api:customer.html.twig", templateVar="parameters")
     *
     * @param Request $request
     *
     * @return mixed
     */
    public function postUserAction(Request $request)
    {
        $this->processForm($request, new Customer());
    }

    /**
     * Update customer
     *
     * @ApiDoc(
     *   statusCodes={
     *     200="Returned when successful",
     *     400="Returned when some required parameter missing or is wrong type or email is duplicated",
     *   }
     * )
     *
     * @Rest\View(template=":api:customer.html.twig", templateVar="parameters")
     * @ Rest\Put("users")
     *
     * @param Request $request
     *
     * @param string $guid GUID of user
     *
     * @return mixed
     */
    public function putUserAction(Request $request, $guid)
    {
        $customer = $this->getDoctrine()->getRepository("AppBundle:Customer")->findBy(array('guid' => $guid));
        $this->processForm($request, $customer);
    }
```

![image](https://cloud.githubusercontent.com/assets/3509024/7793863/c940d360-02c4-11e5-9900-1973cb96dbea.png)

**Comment by radoslavius** [comment]
Problem is still exist. If I want use dont pluralize one route and use this:

```php
    /**
     * Get url for document
     *
     * @ApiDoc()
     *
     * @param string $guid GUID of user
     *
     * @Rest\View()
     * @Rest\Get("/users/{guid}/get_editor/{productID}", name="get_users_get_editor")
     * @Rest\Get("/users/{guid}/get_editor/{productID}/{documentID}", name="get_users_get_editor_with_document")
     * @Rest\RequestParam(name="documentID", nullable=true, strict=false, default=null)
     *
     * @return array
     */
    function getUsersGet_editorAction($guid, $productID, $documentID)
    {

```

so apidoc show these routes twice:
![image](https://cloud.githubusercontent.com/assets/3509024/7830214/ec2b3e2e-044a-11e5-8b52-590adc7ac363.png)

**Comment by radoslavius** [comment]
The problem is probably somewhere in my configuration or in FOSREST, but I do not know where. Apidoc returns the correct results as debug: router:
<pre>
$ php app/console debug:router | grep /get_editor
 cs__RG__get_users_get_editor                                   GET      ANY    ANY  /users/{guid}/get_editor/{productID}
 cs__RG__get_users_get_editor_with_document                     GET      ANY    ANY  /users/{guid}/get_editor/{productID}/{documentID}
 cs__RG__get_users_get_editorget_users_get_editor               GET      ANY    ANY  /api/users/{guid}/get_editor/{productID}.{_format}
 cs__RG__get_users_get_editorget_users_get_editor_with_document GET      ANY    ANY  /api/users/{guid}/get_editor/{productID}/{documentID}.{_format}
</pre>
Controller:
```php
    /**
     * Get url for document
     *
     * @ApiDoc()
     *
     * @param string $guid GUID of user
     *
     * @Rest\View()
     * @Rest\Get("/users/{guid}/get_editor/{productID}", name="get_users_get_editor")
     * @Rest\Get("/users/{guid}/get_editor/{productID}/{documentID}", name="get_users_get_editor_with_document")
     * @Rest\RequestParam(name="documentID", nullable=true, strict=false, default=null)
     *
     * @return array
     */
    function getUsersGet_editorAction($guid, $productID, $documentID)
    {
```
Config:
<pre>
ApiDocumentsController:
    resource: "@AppBundle/Controller/Api/DocumentsController.php"
    type:     rest
    defaults: {_format: json}
    prefix:   /api
</pre>

**Comment by ipalo** [comment]
Hi @radoslavius i had the same issue and found the solution to avoid duplication here: https://github.com/FriendsOfSymfony/FOSRestBundle/issues/813

I hope this help you ;)
