### ISSUE TITLE
Symfony Validator parser doesn't extract description

### ISSUE THREAD

**Issue by bastien-wink** [nelmio/NelmioApiDocBundle#633]
I'm using Symfony Validator constaints as an input of @ApiDoc. 
The "description" column is blank on the ApiDoc instead of being my field description.

My test code : 

``` php
//...
     /**
     * @Route("/favorite/remove")
     * @Method({"POST"})
     * @ApiDoc(
     *  description="Method description",
     *  input={
     *      "class"="MyApp\ApiBundle\Validator\Place\Category"
     *  }
     * )
     */
    public function removeAction() {
            //...
         }
```

``` php
 //...
use Symfony\Component\Validator\Constraints as Assert;

class Category
{
    /**
    * A comment for my name field
    * @Assert\Type(type="string")
    */
    public $name;

}
```

The description fields is nowhere on this class : 
nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Parser/ValidationParser.php

I guess it should be extracted like we do in JmsMetadataParser.php  ($this->commentExtractor->getDocCommentText)

I'm happy to code that is you agree with me.

**Comment by maxpowel** [comment]
I would be happy if you include this feature :)

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
