### ISSUE TITLE
In sandbox GET actions appends _format="" parameter

### ISSUE THREAD

**Issue by clubdesarrolladores** [nelmio/NelmioApiDocBundle#650]
I have this action:

```
GET /mobile/profile
```

When i test in sandbox, the resultant request is:

```
GET /mobile/profile?_format=
```

because of that i get this response from server:

```
415 Unsupported Media Type
```

``` json
{
  "code": 415,
  "message": "Format '' not supported, handler must be implemented"
}
```

Tip: if you write at least one character in the textarea "content" then the parameter is overrited and all works fine.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
