### ISSUE TITLE
DEPRECATED - choice_list

### ISSUE THREAD

**Issue by gnorby88** [nelmio/NelmioApiDocBundle#651]
Hello.

I'am updated my project from symfony 2.6 to 2.7 and i received this message:

DEPRECATED - The Symfony\Component\Form\Extension\Core\View\ChoiceView class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\View\ChoiceView instead. DEPRECATED - The Symfony\Component\Form\Extension\Core\View\ChoiceView class is deprecated since version 2.7 and will be removed in 3.0. Use Symfony\Component\Form\ChoiceList\View\ChoiceView instead.

DEPRECATED - The "choice_list" option is deprecated since version 2.7 and will be removed in 3.0. Use "choice_loader" instead. DEPRECATED - The "choice_list" option is deprecated since version 2.7 and will be removed in 3.0. Use "choice_loader" instead.

**Comment by mrsuh** [comment]
same thing

**Comment by gnorby88** [comment]
+ DEPRECATED - The "pattern" option in file "/home/developer/www/bagobago/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.

DEPRECATED - The "_method" requirement of route "nelmio_api_doc_index" in file "/home/developer/www/bagobago/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead.

**Comment by willdurand** [comment]
should be fixed
