### ISSUE TITLE
Boolean value in sandbox sent as string

### ISSUE THREAD

**Issue by ifdattic** [nelmio/NelmioApiDocBundle#652]
Using the input form the boolean values are sent as string. In Symfony application using boolean type validation / checkbox input form it's recognized as true value. It would be better if normal `false` & `true` is sent for boolean values (at least when `application/json` is used).

Some examples of request:

``` json
{
    "create_task": {
        "name": "Task name",
        "date": "2016-06-06",
        "important": "0"
    }
}
```

``` json
{
    "create_task": {
        "name": "Task name",
        "date": "2016-06-06",
        "important": "1"
    }
}
```

**Comment by MGDSoft** [comment]
I have the same problem

 @ApiDoc(
     *   section = "Basic usage",
     *   input = "AppBundle\Form\Type\Api\TransactionApiType",
...

in my formType

$builder
    ->add('tutorial_enabled', null, ['required'=> false, 'property_path' => 'tutorialEnabled', 'description' => 'Tutorial enabled'])

I think "property_path" is not reading

**Comment by ReservedDeveloper** [comment]
+1 to this. I have no property_path setting, simply a very basic boolean field.

`$builder->add('myBoolField', 'boolean');`

**Comment by logickphp** [comment]
I have the same problem:

I my class:

`
/**
     * @ApiDoc(
     *      resource=true,
     *      description="Crea un área",
     *      views = { "default" },
     *      requirements={
     *          {
     *              "name"="descripcion",
     *              "dataType"="string",
     *              "requirement"="\[[:alnum:]]+",
     *              "description"="Descripción de la nueva Área (Único)"
     *           },
     *           {
     *              "name"="activa",
     *              "dataType"="integer",
     *              "requirement"="\d+",
     *              "description"="Estado del área [1|0] Activo|Inactivo"
     *           }
     *
     *      }
      */
`

Then in sandbox allways add quotes to my integer param "activa", It's BAD. 

When I test with postman or Insomnia rest clients works well. 

PLEASE FIX THE SANDBOX !!!

**Comment by Lube** [comment]
Anyone found a workaround?

**Comment by idchlife** [comment]
Well guys, boolean is boolean, but number is being sent as string...

**Comment by lsmith77** [comment]
indeed it seems like this Bundle should be changed to send boolean values as such when using JSON.

**Comment by lsmith77** [comment]
here is a quick hack to make it work .. 
https://github.com/nelmio/NelmioApiDocBundle/pull/989
