### ISSUE TITLE
How to set form fields format (pattern) ?

### ISSUE THREAD

**Issue by edamov** [nelmio/NelmioApiDocBundle#655]
Please, can you tell me how I can set form fields format?

![image](https://cloud.githubusercontent.com/assets/2741880/8267172/80679846-175e-11e5-9c82-510436676b11.png)

**Comment by ruijl** [comment]
I'm also looking for this answer. I'm using a form type as POST input. This form has a date field which is rendered as text input. I want to set the format to 'YYYY-MM-DD' for example.

**Comment by nhajiyani** [comment]
I believe you could just use pattern inside filters

filters={
     *      {"name"="application_type", "dataType"="string", "pattern"="an|ios", "required"="true"},
     *  },

That should do it

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
