### ISSUE TITLE
Array parameters in sandbox

### ISSUE THREAD

**Issue by ivodvb** [nelmio/NelmioApiDocBundle#657]
Hi all!

When I add a filter which can hold a list of ids ([1, 45, 343, 4345, 914234]) I cannot enter that list in sandbox mode.

Filter promotorIds
![image](https://cloud.githubusercontent.com/assets/3462689/8326715/41f48512-1a63-11e5-8a2a-2a3ba97b6049.png)

``` php
    /**
     * Some method documentation.......
     *
     * @ApiDoc(
     *  resource=true,
     *  description="Load list of events",
     *  statusCodes={
     *      200="Returned when successful",
     *      400="Bad user input",
     *      500="In case of server error, our bad!"
     *  }
     * )
     *
     * @param ParamFetcher $paramFetcher
     *
     * @QueryParam(array=true, name="promotorIds", requirements="\d+", strict=true, description="Array with promotor IDs", nullable=true)
     *
     * @return array response data
     */
    public function getEventsAction(ParamFetcherInterface $paramFetcher)
```

The sandbox mode
![image](https://cloud.githubusercontent.com/assets/3462689/8326762/a829f59c-1a63-11e5-8937-0a23f1822a7b.png)

I expected a way to add one or multiple promotor ids. Now I see a single input field in which I cannot specify a list of promotor ids. When I want to test my API method I manually have to write the URL /events.json?promotorIds[]=1&promotorIds[]=2&offset=0&limit=100

See https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/method.html.twig#L219

How are you guys dealing with this?

Many thanks for your time!

**Comment by felicitus** [comment]
+1 from my side. See the related issue from DunglasAPIBundle here: https://github.com/dunglas/DunglasApiBundle/issues/121

**Comment by aderuwe** [comment]
+1

Is this even doable to implement somehow?

**Comment by Vooodoo** [comment]
+1 here !

Seems that you need to parse

**Comment by aderuwe** [comment]
Thinking now that having "array" parameters into an API call is the actual problem, not this issue.

**Comment by tranthienbinh1989** [comment]
+1
same issue with me.

**Comment by philippwaller** [comment]
Any update concerning this demand? I facing the same issue for an mandatory parameter.

**Comment by romanga** [comment]
this can be fixed relatively easy imo:
to support 
/events.json?promotorIds[]=1&promotorIds[]=2&offset=0&limit=100 in sandbox
layout.html.twig needs to be slightly modified as follow: 
layout.html.twig:469
{code}
 if (key.endsWith("[]")) {
                                    subkey = key.substr(0, key.length-2);
                                    if (!params[subkey]) {
                                        params[subkey] = [];
                                    }
                                    params[subkey].push(value);
                                } else {
                                    params[key] = value;
                                }
{code}

I can create PR

**Comment by smilesrg** [comment]
+1

**Comment by egils** [comment]
+1

**Comment by vazgen** [comment]
+1

**Comment by deivid11** [comment]
+1

**Comment by jmalinens** [comment]
+1

**Comment by Weyn** [comment]
+1

**Comment by jhogendorn** [comment]
+1

**Comment by bvisonl** [comment]
+1

**Comment by gohiei** [comment]
+1

**Comment by casg23Limeon** [comment]
+1

**Comment by kokmok** [comment]
+1

**Comment by Andrej-in-ua** [comment]
+1

**Comment by truttmann** [comment]
+1

**Comment by sujayjaju** [comment]
+1

**Comment by NeilJ247** [comment]
+1

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version. if it does not work, i hope one of the many people that wrote `+1` can debug and send a fix pull request.
