### ISSUE TITLE
Support layout translations for templates

### ISSUE THREAD

**Issue by shakaran** [nelmio/NelmioApiDocBundle#664]
I would translate to spanish the text of the following template, but I cannot found a file with keys because it is raw strings in this template:

https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/resources.html.twig

Could you add a messages.yml file and put the translations keys?

Also for every twig template in https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views

**Comment by shakaran** [comment]
BUMP

**Comment by dbu** [comment]
you can overwrite the twig template in your project
