### ISSUE TITLE
Inherit annotations

### ISSUE THREAD

**Issue by Taluu** [nelmio/NelmioApiDocBundle#669]
Something I happen to stumble upon just recently (a few minutes actually) : it would seem that the `@ApiDoc` annotation is not inherited for controllers inheriting another controller.

Somehting to do would be to look for a `{@inheritDoc}` annotation if there is no `@ApiDoc` annotation ? WDYT ?

**Comment by dbu** [comment]
inheriting doc is default, so looking for annotations in parent class if no class level annotation is found sounds like a good thing for the principle of least astonishment. even though controllers probably should not have a class hierarchy usually. if you can do a pull request for that it would be nice
