### ISSUE TITLE
Routing.yml options are deprecated in symfony 2.7

### ISSUE THREAD

**Issue by skonsoft** [nelmio/NelmioApiDocBundle#679]
Hello,

There are some attributes are deprecated in symfony 2.7 in routing.yml file.

Here is what i got as warning:

DEPRECATED - The "pattern" option in file "/var/www/dev/my_project/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead. 

DEPRECATED - The "_method" requirement of route "nelmio_api_doc_index" in file "/var/www/dev/my_project/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/config/routing.yml" is deprecated since version 2.2 and will be removed in 3.0. Use the "methods" option instead. 

Can you fix this please ?

Thank you.

**Comment by sarcher** [comment]
Should be fixed now in #690. Comments welcome if anything else related needs fixing.

**Comment by jewome62** [comment]
+1

**Comment by odoucet** [comment]
:+1:
