### ISSUE TITLE
private function getGlobalVars()

### ISSUE THREAD

**Issue by leshgancomp** [nelmio/NelmioApiDocBundle#682]
Please set this function to protected (in file ApiDocBundle\Formatter\HtmlFormatter) or create getters for all variables. Because I`m create some bundle extends NelmioApiDocBundle and can`t overwrite CSS or JS files.

**Comment by shakaran** [comment]
:+1: Customization of CSS and JS in very needed in this project (even l18n)

**Comment by willdurand** [comment]
I accept PRs :)
