### ISSUE TITLE
How to display "output" format in generated documentation

### ISSUE THREAD

**Issue by Oliboy50** [nelmio/NelmioApiDocBundle#693]
Is it possible to display an expected response format type in the generated documentation?

I though it would work if I used the "output" parameter... But nope.

```
    /**
     * @ApiDoc(
     * ...
     *    output = "{ nice_stuff: [ { id: int, name: string, complicated: { stuff: int, something: string } }, ... ], bad_stuff: [ { ... }, ... ] }"
     * ...
     * )
     */
```

Even if it only displays it as string (i.e. not a pretty formatted JSON stuff), I'd be happy :D

NB: I don't use JMS bundles... nor FOSRest :)

**Comment by nnmer** [comment]
+1 
needed the way to show custom output structure.

**Comment by nnmer** [comment]
what confusing is in the manual does not covered all the possible variables for the documentation. In the code there are "documentation", "response" etc values, but I didn't succeed to use them.

**Comment by ktounet** [comment]
See https://github.com/nelmio/NelmioApiDocBundle/issues/400#issuecomment-47078707

**Comment by nnmer** [comment]
@ktounet works, thanks!

**Comment by Oliboy50** [comment]
Indeed, thanks ;)
