### ISSUE TITLE
How to document output with HateoasBundle

### ISSUE THREAD

**Issue by antonioperic** [nelmio/NelmioApiDocBundle#708]
Hi,
I am using NelmioApiDocBundle for creating documentation. Also I am using HateoasBundle with HAL standard for outputting responses. How can I document my responses, is it even possible to have all fields showed: embeded, links etc

Tnx

**Comment by BenjaminCanape** [comment]
Hey,

Did you find an answer to that ?
 I'm facing the same problem: the documentation shows the properties but not the relations of the resources.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
