### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by NeuralClone** [nelmio/NelmioApiDocBundle#710]
There's been some discussion about the tests failing to pass in #614. Since this problem seems to go beyond the scope of that PR, I thought it made sense to create a discussion that's focused mainly on this particular problem. Hopefully this will lead to a separate PR and make it easier to fix any potential problems with that PR as well as others.

As you can see, the tests have been failing for a few months now:

https://travis-ci.org/nelmio/NelmioApiDocBundle/builds

I'm currently trying to sort out these problems with the hope of creating a PR to fix them. However, I have no idea how much time I'll be able to devote to this. I'm not incredibly familiar with the inner workings of this bundle and the failures don't appear to be trivial. Still, I'm going to give it a go since it's potentially holding back other fixes from getting merged.

**Comment by ip512** [comment]
I roughly fixed tests failures, so I'd like to share what I noticed
- on ApiDocExtractorTest, some tests are based on annotation objects that are retrieved based on a numeric index, which seems to have changed. I suggest to base tests on route names (https://github.com/ip512/NelmioApiDocBundle/commit/7bb3bfdde0c653a8a92f2b6ac0b979e8fa1280a9#diff-89c2af55b55b1ff3e4c8623330d95cc6R40)
- on MarkdownFormatterTest, SimpleFormatterTest and DunglasApiParser an 'id' property is missing on expected results, for routes generated by Tests/Fixtures/Model/Popo.php. I don't know if these properties should be expected or not, maybe @dunglas has an idea ?
- FormTypeParserTest fails, I have no idea why

**Comment by NeuralClone** [comment]
Unfortunately, I haven't had a tremendous amount of time to devote to this issue since opening this but on a quick glance what you've discovered definitely looks like a big step in the right direction. Thank you for sharing this! :+1:
