### ISSUE TITLE
Notice: Undefined index: required 

### ISSUE THREAD

**Issue by vortexgin** [nelmio/NelmioApiDocBundle#714]
dear admin, 

i have a problem when composer update today, my site show error message like this : 
Notice: Undefined index: required 

vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Formatter/AbstractFormatter.php at line 75 vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Controller/ApiDocController.php at line 26

**Comment by willdurand** [comment]
should be fixed now
