### ISSUE TITLE
Put an example of JSON

### ISSUE THREAD

**Issue by sdecandelario** [nelmio/NelmioApiDocBundle#716]
I'm documenting a POST and PUT method, and the content is a JSON with all the info of the entity. I want to put an example of the complete JSON in the documentation of the method, but i don't see the option to do this.

There is any way to put a example of JSON that go with the content of the petition? There is a way to put it in the sandbox?

Anyone have the same problem?

**Comment by winterstefan** [comment]
Unfortunately, I didn't find this option, either.

For displaying example responses, I use the [PHPMarkdown Extra](https://michelf.ca/projects/php-markdown/extra/) features with the [built-in description field](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/method.html.twig#L53).
Yep, this will be displayed *above* the requirements / params / response section. But maybe you could document your example request in this way, too?


#### PHP doc block

![phpdoc](https://cloud.githubusercontent.com/assets/665964/10022084/6174db42-614b-11e5-9139-9561df70fb4e.png)

#### Result

![preview](https://cloud.githubusercontent.com/assets/665964/10022088/663a6e1c-614b-11e5-83fb-3e976efba47b.png)

**Comment by sdecandelario** [comment]
Thanks @winterstefan but i want to put an example call. By the way i think with this is posible to fix the problem. I try and tell you.
