### ISSUE TITLE
Apply markdown to the parameters' descriptions

### ISSUE THREAD

**Issue by Goutte** [nelmio/NelmioApiDocBundle#717]
The parameters' descriptions do not support HTML tags; they are escaped. (as they should, probably?)

How about some markdown instead ? What do you think ?

**Comment by Goutte** [comment]
This looks like a [trivial feature to implement](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/views/method.html.twig#L78), so maybe you have reasons for not doing it in the first place ?
Æsthetics ? Backwards compatibility ?

**Comment by willdurand** [comment]
I accept PRs :)
