### ISSUE TITLE
The format_param method of sending the request method will be removed in Symfony 3.0

### ISSUE THREAD

**Issue by weaverryan** [nelmio/NelmioApiDocBundle#725]
See symfony/symfony#8967

This change means that query or POST parameters containing `_format` won't be respected anymore. The `format_param` method of sending the request format relies on this, and it won't work anymore.

Perhaps only the header method should be supported?

**Comment by willdurand** [comment]
You're right. So, if I understand correctly, we can't use `_format` anymore. How do we create `PUT` or `DELETE` forms then?

**Comment by weaverryan** [comment]
@willdurand `PUT` and `DELETE` forms use the `_method` parameter, right? So that's a different situation?

**Comment by willdurand** [comment]
Wow. Sleep deprivation is not good I guess. I misread and get confused.. Sorry :(

**Comment by weaverryan** [comment]
It's :ok: :)

**Comment by tacman** [comment]
So does this mean the bundle can't be used with Symfony 3 yet?  It looks like composer is requiring Symfony 2 (~2.3), will you be releasing a 3.0 branch?  On a related note, thanks for this bundle, it really makes it easy for programmers to see the API calls!

**Comment by weaverryan** [comment]
@tacman you're right - the real thing is that the `composer.json` file needs to be updated, then we can see if anything breaks in the tests :). We've created a running list of bundles and whether they are 3.0 compat yet: https://docs.google.com/spreadsheets/d/1GOxJ2lNpLxN12YyZ87Bhsxb0iLAQ7e4UDZbJSly8Sy8/edit#gid=0. Hopefully this one won't be too much work and someone will make it happen. Because I agree - this bundle rocks :)

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
