### ISSUE TITLE
Implementing a menu

### ISSUE THREAD

**Issue by peternijssen** [nelmio/NelmioApiDocBundle#735]
Hi,

Since we nog have the "view" possibility since a couple of releases, I think it would be nice to generate a menu out of this. The views allow you to nicely split multiple API requests from each other.

Any guidance on how to set this up properly?

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.

**Comment by dbu** [comment]
if you are still interested, please have a look at the current template and propose ideas
