### ISSUE TITLE
All parameters are merged from bottom to top, but parameters option in ApiDoc annotation is ignored

### ISSUE THREAD

**Issue by fstr** [nelmio/NelmioApiDocBundle#739]
Currently it's possible to add the "parameters" option to the @ApiDoc annotation.
```
     * @ApiDoc(
     *      views = { "default"},
     *      authentication=true,
     *      input={
     *          "class" = "\MyEntity",
     *          "groups" = {"put"}
     *      },
     *      parameters={
     *          {"name"="name", "dataType"="integer", "requirement"="foobar", "format"="integer", "description"="this will be the new description"}
     *      },
     * )
```

Since this setting is at the top most level, it should overwrite previous settings for the given parameter.

Currently this parameters setting has no effect if there are more specific settings in MyEntity.

I would propose to merge the ApiDoc parameters option in the end on top of all other settings.

A use case would be, if you have an internal type (custom JMS Type for example) that you want to shield from the API docs and just show it as a simple array or something in the docs.

**Comment by willdurand** [comment]
Wanna work on this?
