### ISSUE TITLE
Output object as array key

### ISSUE THREAD

**Issue by Vandersteen** [nelmio/NelmioApiDocBundle#741]
Hello everyone,

I am having trouble finding if the following is implemented in this bundle:

Let's say I have

```
     * @ApiDoc(
     *  resource=true,
     *  description="Get a specific product for your company.",
     *  statusCodes={
     *      200="Returned when successful",
     *      401="Returned when not Authenticated",
     *      404="Returned when the product does not exist (for your company)"
     *  },
     *  output={
     *      "class"="AppBundle\Entity\Product",
     *      "groups"={}
     *  },
     * )
```

Now When I output this object I actualy put it in a array-key so that I could later on add messages / links in output.

E.g. for this route:

```
    return JsonResponse(['product' => $product], 200);
```

Where $product is the `AppBundle\Entity\Product`.

I tried adding the `name` in the output but without success

```
     *  output={
     *      "class"="AppBundle\Entity\Product",,
     *      "name"="product",
     *      "groups"={}
     *  },
```

But that doesn't work. 
Is this possible with this bundle or will I have to make some changes myself ?

**Comment by willdurand** [comment]
Do you know why you put `"groups"={} by chance?

**Comment by Vandersteen** [comment]
Oh i'm going to add serialization groups soon, so it's ready to be plugged in.

**Comment by fstr** [comment]
Actually you do not return a Product Entity, but a wrapper object that contains a product entity.
```
*  output={
*      "class"="AppBundle\Entity\DataWrapper"
*  }
```
And the class you define in your output looks something like this.
```
class DataWrapper
{
    /**
     * My cool product
     *
     * @Type("AppBundle\Entity\Product")
     * @var Product
     */
    protected $product;

    public function __construct()
    {
        $this->product = new Product();
    }
}
```
Return Parameter
With this setup, the generated docs will represent what you wanted to achieve :).

Parameter | Type | Versions | Description
------------ | -------------|--------------- | --------------
product | object (Product) | * | My cool product

Later you can sinply add a message property and a link property of type String to your DataWrapper class.

**Comment by willdurand** [comment]
I'd remove the `groups` line as well, because IIRC it changes serializer's output.

**Comment by Vandersteen** [comment]
Thanks alot for the clarification !

**Comment by willdurand** [comment]
Problem solved?

**Comment by Vandersteen** [comment]
Yes I believe so, 
I will need to add alot of DataWrappers Classes but it works.
