### ISSUE TITLE
Securing a route for a view

### ISSUE THREAD

**Issue by pdias** [nelmio/NelmioApiDocBundle#746]
Hello,

I have this:

```
    /**
     * Get courses
     *
     * @ApiDoc(
     *   resource = true,
     *   description = "Get courses",
     *   views = { "digitalis" },
     *   output = "ArrayCollection<ApiBundle\Entity\digitalis\t_cursos>",
     *   tags = {
     *      "Beta"
     *   },
     *   statusCodes = {
     *     200 = "Returned when successful",
     *     404 = "Returned when unsuccessful"
     *   }
     * )
     *
     * @Rest\View()
     *
     * @param ParamFetcherInterface $paramFetcher The ParamFetcher object
     *
     * @return array
     *
     * @throws InvalidArgumentException
     */
```

And in my security.yml

```
...

access_control:
        - { path: ^/documentation, roles: [ IS_AUTHENTICATED_FULLY ] }
        - { path: ^/documentation/digitalis, roles: [ IS_AUTHENTICATED_FULLY, ROLE_DIGITALIS ] }

```
But any user who is authenticated, and without the ROLE_DIGITALIS access to the path.
Can you help me, although this issue is not directly connected to this bundle.

Thanks in advance.

**Comment by fstr** [comment]
access_control works with regular expressions.

The regex: ```^/documentation``` matches both URLs and thus it will stop at the first access_control restriction.

If you want this to work, you should use a more strict regular expression:
```
access_control:
    - { path: ^/documentation$, roles: [ IS_AUTHENTICATED_FULLY ] }
    - { path: ^/documentation/digitalis$, roles: [ ROLE_DIGITALIS ] }
```
And in my opinion you also need to remove the role IS_AUTHENTICATED_FULLY from the second restriction. It's either role_a OR role_b OR role_c. Not role_a AND role_b AND role_c.

So yea this question is not really related to this project.
See also: http://symfony.com/doc/current/book/security.html#securing-url-patterns-access-control

**Comment by pdias** [comment]
Thank. I see my error.
