### ISSUE TITLE
JsonSerializableParser has no support for default values

### ISSUE THREAD

**Issue by fstr** [nelmio/NelmioApiDocBundle#747]
Hi,

most Parsers seem to have support for a Default value:
https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/JmsMetadataParser.php#L146
https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/ValidationParser.php#L112

The JsonSerializableParser is not supporting this:
https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/JsonSerializableParser.php#L57

When merging different Parser results, this can lead to errors in case the JsonSerializableParser is called first and then the ValidationParser.

https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/ApiDocExtractor.php#L487

This line results in:
```
$v1['default'] = $v1['default']
```
Which will then cause a PHP notice, since the 'default' array key was never set in the JsonSerializableParser result. This will lead to an exception in Symfony (HTTP 500).
```
 Notice: Undefined index: default 
```

There are two solutions here that should/can be both implemented at the same time.
- Add default value support to JsonSerializableParser
- Only set/access $v1[$name] if it exists

I can work on a patch later.

**Comment by willdurand** [comment]
> Add default value support to JsonSerializableParser
> Only set/access $v1[$name] if it exists

We could implement both I'd say :)

**Comment by fstr** [comment]
```
$myClassProperty = '';
``` 
If the default value of a class property is an empty string the condition below treats it as no-value and tries to access $v1[$name].
```
 $v1[$name] = $value ?: $v1[$name];
```

So I can change the condition to accept an empty string as a default value (option a), or set it to null in this case (option b) or combine both, in case due to some settings $v1[$name] would still not be set (option c)

a)
```php
isset($value) ?: $v1[$name]
```

b)
```php
if (isset($v1[$name])) {
    $v1[$name] = $value ?: $v1[$name];
} else {
    $v1[$name] = $value ?: null;
}
```


c)
```php
if (isset($v1[$name])) {
    $v1[$name] = isset($value) ?: $v1[$name];
} else {
    $v1[$name] = isset($value) ?: null;
}
```

I vote for option c) since an empty string is a valid initialization value for a variable in my opinion. And it's the safest way to access an array.
