### ISSUE TITLE
why validationParser can't detect format from validation annotations?

### ISSUE THREAD

**Issue by ghanbari** [nelmio/NelmioApiDocBundle#753]
please see this [answer](http://stackoverflow.com/questions/33222064/how-specify-parameters-format-in-nelmio-apidocbundle?answertab=active#tab-top), why [validationParser](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/ValidationParser.php) can detect format from FormType properties, but can not guess they from validation annotations that define on entity properties?

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.

**Comment by ghanbari** [comment]
thank you
