### ISSUE TITLE
Annotation ApiDoc could not be found.

### ISSUE THREAD

**Issue by przemoli** [nelmio/NelmioApiDocBundle#756]
Following code will trigger: `[Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotations\ApiDoc" in method AppBundle\Controller\BandController::getAction() does not exist, or could not be auto-loaded in src/AppBundle/Resources/config/api_routing.yml (which is being imported from "app/config/routing.yml"). `

I have configuration copied from documentation, with ApiDoc showing empty list of routes if this annotation is removed (as expected, since this is first route I tried to document).

```php
use FOS\RestBundle\Controller\FOSRestController;
use FOS\RestBundle\Controller\Annotations\RouteResource;
use Nelmio\ApiDocBundle\Annotations\ApiDoc;

/**
 * @RouteResource("Band")
 */
class BandController extends FOSRestController
{
  /**
   * @ApiDoc(
   *   description="Get band by id"
   * )
   */
  public function getAction($id)
  {}
}
```

As best as I could find, this issue was not reported here, but a year back SonataMedia bundle had issues with this error message reported. Updating ApiDoc was recommended as fix.

I use ApiDoc in version 2.10.

**Comment by willdurand** [comment]
Did you enable Doctrine Annotations?

**Comment by przemoli** [comment]
I just realized that I used app/console g:c to generate controller with yml.

So how one turn on Doctrine Annotations? Can ApiDoc be used with yml?

**Comment by willdurand** [comment]
I think you should have the following content in `app/autoload.php`:

```php
<?php

use Doctrine\Common\Annotations\AnnotationRegistry;

$loader = require __DIR__.'/../vendor/autoload.php';

AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

return $loader;
```

**Comment by przemoli** [comment]
OK. I think I will sent PR with updated documentation (Installation) with above instructions. So this issue can be closed.
