### ISSUE TITLE
Resource path is not equal to resource file name

### ISSUE THREAD

**Issue by wildpascal** [nelmio/NelmioApiDocBundle#759]
The path value in "apis" is not equal to the file name where the resource is stored.

``` javascript
{
    "swaggerVersion": "1.2",
    "apis": [
        {
            "path": "\/users",
            "description": null
        }
    ],
    "apiVersion": "0.1",
    "info": {
        "title": "Test",
        "description": "API",
        "TermsOfServiceUrl": null,
        "contact": null,
        "license": null,
        "licenseUrl": null
    },
    "authorizations": {
        "apiKey": {
            "type": "apiKey",
            "passAs": "header",
            "keyname": "Authorization"
        }
    }
}
```

The value of path parameter is /users but the file is named users.json and its not equal.

> The API Declaration provides information about an API exposed on a resource. There should be one file per Resource described. The file MUST be served in the URL described by the path field.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
