### ISSUE TITLE
Forms containing form types that inherit from parents

### ISSUE THREAD

**Issue by cdwlighting** [nelmio/NelmioApiDocBundle#771]
I have some form widgets taht are included on a form, these widgets are not showing up in the API doc.

Build methods from the forms involved.

Please see the forms here:
https://gist.github.com/cdwlighting/45c41aa4d9ed4705c0d7

Here is what the Doc shows:
Parameters
Parameter   Type    Required?   Format  Description
memberReferral  object (MemberReferralWidget)   false  
memberReferral[referral]    string  true        Person Making Referral
pointTransferReferral   object (PointsTransferWidget)   false  
pointTransferReferral[referral] string  true        Person Making Referral

What is expected:
Parameters
Parameter   Type    Required?   Format  Description
memberReferral  object (MemberReferralWidget)   false  
memberReferral[referral]    string  true        Person Making Referral
pointTransferReferral   object (PointsTransferWidget)   false  
pointTransferReferral[referral] string  true        Person Making Referral
PointTransferReferral[pointsToTransfer] string true Number of Points to Transfer to New Person,
pointTransferReferral[email] email true Person to invite.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
