### ISSUE TITLE
Notice: Array to string conversion

### ISSUE THREAD

**Issue by sasasimic** [nelmio/NelmioApiDocBundle#773]
I have in @RequestParam 
requirements={"rule"="@Symfony\Component\Validator\Constraints\Emial", "error_message"="e-mail address is not valid"} 

when i open /api/doc i got Notice: Array to string conversion
what is the problem ?

**Comment by willdurand** [comment]
This is fixed in #766

**Comment by willdurand** [comment]
Done: [2.11.2](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.11.2).
