### ISSUE TITLE
How can I define a parameter in Headers in sandbox of Nelmio api doc Bundle?

### ISSUE THREAD

**Issue by abidichrak** [nelmio/NelmioApiDocBundle#774]
I want to define a parameter in Headers in sandbox of Nelmio api doc Bundle.

How can define this in annotation of Nelmio ApiDoc ?

**Comment by sagikazarmark** [comment]
I have the feeling that this is impossible at the moment. However it would be a good addition.

**Comment by ariault-blanchard** [comment]
Hello,

I am in the same situation and i think it will be great to have this too :)

It's very useful at the moment though :)

**Comment by yarcowang** [comment]
The [doc](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/the-apidoc-annotation.rst) does have such field:

```
headers: an array of headers; available properties are: name, description, required, default. Example:
```

But I didn't see it could work.

**Comment by zied-ellouze** [comment]
@yarcowang 
A priori the header support has been added from version 2.13.0
https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.13.0
to test

**Comment by yarcowang** [comment]
@zied-ellouze Thanks. Get it.
