### ISSUE TITLE
Describe a model inside a field

### ISSUE THREAD

**Issue by AlmogBaku** [nelmio/NelmioApiDocBundle#776]
Is there an option to describe a json-model that need to be sent to a field?

**Comment by lgoral** [comment]
I think i will prepare in few days PR for it with proposed solution for two fields responseExample and requestExample

**Comment by lgoral** [comment]
Two fields
* responseExample: example of response body from endpoint. This properties can be a string value or array with
 `file` key and path value to example with the response; Examples:

    ```
class YourController
    {
        /**
         * @ApiDoc(
         *     responseExample={
         *         "file": "../src/AppBundle/Resources/getActionExample.json"
         *     }
         * )
         */
        public function myFunction()
        {
            // ...
        }

        /**
         * @ApiDoc(
         *     responseExample='{"that_is_json_key": "my sample json"}'
         * )
         */
        public function myFunction()
        {
            // ...
        }
    }
```

* requestExample: example of response body from endpoint. This properties can be a string value or array with
 `file` key and path value to example with the response; Examples:
```

    class YourController
    {
        /**
         * @ApiDoc(
         *     requestExample={
         *         "file": "../src/AppBundle/Resources/getActionExample.json"
         *     }
         * )
         */
        public function myFunction()
        {
            // ...
        }

        /**
         * @ApiDoc(
         *     requestExample='{"that_is_json_key": "my sample json"}'
         * )
         */
        public function myFunction()
        {
            // ...
        }
    }
```

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
