### ISSUE TITLE
Markdown formatter spacing

### ISSUE THREAD

**Issue by erikeuserr** [nelmio/NelmioApiDocBundle#777]
After a api:doc:dump --format=markdown the markdown file displays like this: (The enumeration does not display well).
#### Requirements

**postalcode**
- Type: string
- Description: A postalcode
  **housenumber**
- Type: integer
- Description: A housenumber without addition

It has to be displayed like this.
#### Requirements

**postalcode**
- Type: string
- Description: A postalcode

**housenumber**
- Type: integer
- Description: A housenumber without addition

A simple \n inside the requirements foreach will do the trick

``` php
        //Line 41 Markdownformatter.php
        if (isset($data['requirements']) && !empty($data['requirements'])) {
            $markdown .= "#### Requirements ####\n\n";

            foreach ($data['requirements'] as $name => $infos) {
                $markdown .= sprintf("**%s**\n\n", $name);

                if (!empty($infos['requirement'])) {
                    $markdown .= sprintf("  - Requirement: %s\n", $infos['requirement']);
                }

                if (!empty($infos['dataType'])) {
                    $markdown .= sprintf("  - Type: %s\n", $infos['dataType']);
                }

                if (!empty($infos['description'])) {
                    $markdown .= sprintf("  - Description: %s\n", $infos['description']);
                }

                //Right here
                $markdown .= "\n";
            }

            $markdown .= "\n";
        }
```

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
