### ISSUE TITLE
an error occured when installing Nelmio Api doc 2.11.2

### ISSUE THREAD

**Issue by abidichrak** [nelmio/NelmioApiDocBundle#779]
I get an error when i install Nelmio Api doc 2.11.2 
Here is the error : 
An Exception was thrown while handling: Warning: filemtime(): stat failed for ..../vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/views/resources.html.twig

Thank you for helping me

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.

**Comment by apstf** [comment]
But what if someone can't move to version 3, for that we will have to move to latest Symfony or 3.x atleast which we can't.

**Comment by dbu** [comment]
the reported error sounds a lot like some network problem or filesystem error, maybe in combination with a virtual machine or disk full or something. the file is present in the reported version: https://github.com/nelmio/NelmioApiDocBundle/blob/2.11.2/Resources/views/resources.html.twig
