### ISSUE TITLE
Issue with repeated type

### ISSUE THREAD

**Issue by smartpierre** [nelmio/NelmioApiDocBundle#782]
Hi guys,

I have a small issue with my registration form (I'm using FOSUserBundle).
Nelmio is associating the repeated field password with the field 'userProfile'
However, the form is working correctly in my controllers.

The output :
https://img42.com/BpYZZ

The code :
https://gist.github.com/smartpierre/074903340d17ecc3b7f2

So, if you have any idea....

Thanks !

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
