### ISSUE TITLE
Issue with Form parser

### ISSUE THREAD

**Issue by spdionis** [nelmio/NelmioApiDocBundle#783]
Apparently if you use a field named `class` in a form it will not render in the docs. You are forced to choose a different name.

Happens with all form types.

example:

```
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('class', 'text');
    }
```

**Comment by dbu** [comment]
tihs is probably not relevant anymore as php 7 makes `class` a reserved keyword
