### ISSUE TITLE
Exception with FOS Rest and array default value in QueryParam

### ISSUE THREAD

**Issue by chosroes** [nelmio/NelmioApiDocBundle#787]
Hi,
I got this Exception, because I have an array as default value in a QueryParam Annotation:

An exception has been thrown during the rendering of a template (\"Notice: Array to string conversion\") in \"NelmioApiDocBundle::method.html.twig\" at line 223.

@QueryParam(map=true, name="exemple", default={"hello":"world"})

The error comes from this code : {% if infos.default is defined %} value="{{ infos.default }}"

Thank you to get an eye on this bug.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
