### ISSUE TITLE
security.token_storage is null when including NelmioApiDocBundle in AppKernel

### ISSUE THREAD

**Issue by schingeldi** [nelmio/NelmioApiDocBundle#788]
Symfony 2.7
NelmioApiDocBundle  2.11.2

I have a very strange behaviour where I have no answer to. I run my application where I use a service which uses security.token_storage as a dependency. Everything worked fine.

But when I add 

  new Nelmio\ApiDocBundle\NelmioApiDocBundle(),

to ApKernel.php the token_storage has a token which is null and my whole application breaks.

I did not even include anything in config.yml or routing.yml (but I tried if this fixes the issue) but it doesn't. So just by adding the bundle the authentication seems to be working differently. 

Can anyone think about a reason why this is the case. Maybe a hint where to look at. I tried debugging a lot but couldn't find it. 
Any ideas are appreciated.

Thanks a lot and best reagrds
Roman

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
