### ISSUE TITLE
Class without Identifier Dunglas/ApiBundle and NelmioApiDocbundle

### ISSUE THREAD

**Issue by rbaraut** [nelmio/NelmioApiDocBundle#797]
When I try to generate the documentation with nelmioApiBundle command. I'm creating the api with Dunglas api bundle

`php app/console api:doc:dump --format=html > api.html`

I have the following error

[RuntimeException]
  Class "Doctrine\Common\Collections\Collection" have no identifier.

**Comment by dunglas** [comment]
I'm not sur it's related. Can you paste the code of this entity please?

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
