### ISSUE TITLE
How to format output data when result is not a class?

### ISSUE THREAD

**Issue by Seb33300** [nelmio/NelmioApiDocBundle#802]
Hello,

I would like to show on the documentation a table with the list of returned data.
It seems that it is what the "output" do. But I only found examples with classes given.

My service is returning a custom PHP array.
How can I define the list of returned data in the output to generate a table like this?
![Image of table](https://camo.githubusercontent.com/2f5ec1d07d03c4cdea3e9cb180f01b94d201c57f/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f313331343535312f323430343937322f31643832376266362d616134352d313165332d393238642d3833643061336666616264332e706e67)

Thanks

**Comment by createproblem** [comment]
Created a new data model. Its a good way cuz everything is auto generated such as serializer annotations, or asserts annotations. The next is you can also use it as an input type. And you've type hinting. 

In short: Don't use ugly inline array. Stay object orientated.
