### ISSUE TITLE
Multiples controllers with same action name not showing

### ISSUE THREAD

**Issue by Seb33300** [nelmio/NelmioApiDocBundle#809]
Hello,

If we have multiple controllers with an action having the same name, for instance "testAction()".

Only one method will be displayed in the documentation.
Can you reproduce this bug?

Seb

**Comment by maxpou** [comment]
Hi,
I cannot reproduce this bug in my [project](https://github.com/maxpou/symfony-rest-beer-edition). Note: I simply put this code on two controllers :

```php
/**
* @ApiDoc()
*/
public function testAction()
{}
```

I think those two methods are binding to the same route. Ensure with: `php app/console debug:router | grep test`.

**Comment by Seb33300** [comment]
Hi,
I have this bug when I set the same route on the 2 actions, but with a different route prefix set on each controller.

**Comment by maxpou** [comment]
Provide more information.. we can't help you.

**Comment by charliefancelli** [comment]
Same this for me.
For exemple you have 2 Controllers : "TestController" and "MeController".

You set a prefix like /test for TestController and declare a popAction in it.
So the route should be /test/pop

You set a prefix like /me for MeController and declare a popAction in it.
So the route should be /me/pop

But if we debug the routes we only have /test/pop or /me/pop (the first declare is erase by the second one)

**Comment by charliefancelli** [comment]
Same this for me.
For exemple you have 2 Controllers : "TestController" and "MeController".

You set a prefix like /test for TestController and declare a popAction in it.
So the route should be /test/pop

You set a prefix like /me for MeController and declare a popAction in it.
So the route should be /me/pop

But if we debug the routes we only have /test/pop or /me/pop (the first declare is erase by the second one)

**Comment by maxpou** [comment]
@charliefancelli It's not related to NelmioApiDocBundle... but in the [FOSRestBundle](https://github.com/FriendsOfSymfony/FOSRestBundle) instead!
