### ISSUE TITLE
[RFC] Publishing NelmioApiDocBundle docs on symfony.com

### ISSUE THREAD

**Issue by javiereguiluz** [nelmio/NelmioApiDocBundle#813]
In http://symfony.com/doc/bundles/ we're publishing the documentation of the most relevant Symfony bundles. NelmioApiDocBundle is one of the few missing Top10 bundles. I'd like to transform your documentation from Markdown to RST format in order to integrate it on symfony.com.

Please, tell me if you agree with this before submitting a pull request. Thanks!

**Comment by willdurand** [comment]
I do agree. @Seldaek WDYT?

**Comment by Seldaek** [comment]
Yeahhh I can't say I am really maintaining this so I don't think I should have an opinion ;) Sounds good to me though
