### ISSUE TITLE
Resources are not populated for external annotation providers

### ISSUE THREAD

**Issue by scaytrase** [nelmio/NelmioApiDocBundle#819]
https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/ApiDocExtractor.php#L144-L149

These lines prohibit of resource population for the external annotation providers.

An option would be populate list of annotation first and then iterate them as native routes above

https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/ApiDocExtractor.php#L126-L140

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
