### ISSUE TITLE
Use hydra context to describe route

### ISSUE THREAD

**Issue by MatthieuCutin** [nelmio/NelmioApiDocBundle#820]
Hey,

I'm using Hydra context to provide additionnal information about my routes such as hydra:title.

But in the documentation, every of my get (or any other method) actions got the same description (the description of the first one) because of the lines  from 172 to 175 of the DunglasApiProvider : https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/AnnotationsProvider/DunglasApiProvider.php

``` php
private function getOperationHydraDoc($method, array $hydraDoc)
{
    foreach ($hydraDoc['hydra:supportedOperation'] as $supportedOperation) {
        if ($supportedOperation['hydra:method'] === $method) {
            return $supportedOperation;
        }
    }
}
```

which returns the first that matched.

I modified that by passing the context to getOperationHydraDoc to match the correct operation : 

``` php
private function getApiDoc(
...
) {
    $method = $operation->getRoute()->getMethods()[0];
    if ($collection) {
        $operationHydraDoc = $this->getCollectionOperationHydraDoc($resource->getShortName(), $method, $entrypointHydraDoc);
    } else {
        $operationHydraDoc = $this->getOperationHydraDoc($operation->getRoute()->getMethods()[0], $resourceHydraDoc, $operation->getContext());
    }
...
}

...

private function getOperationHydraDoc($method, array $hydraDoc, $context = null)
{
    $contextTitle = isset($context['hydra:title']) ? $context['hydra:title'] : null;
    foreach ($hydraDoc['hydra:supportedOperation'] as $supportedOperation) {
        $operationTitle = isset($supportedOperation['hydra:title']) ? $supportedOperation['hydra:title'] : null;
        if ($supportedOperation['hydra:method'] === $method and ($contextTitle == null or $contextTitle === $operationTitle)) {
            return $supportedOperation;
        }
    }
}
```

As you can see in my repo : https://github.com/MatthieuCutin/NelmioApiDocBundle/blob/master/Extractor/AnnotationsProvider/DunglasApiProvider.php

If you think this may be useful for the community i will be glad to make a PR.
Thank you @npotier for you support.

Thank you for you Bundle :)

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
