### ISSUE TITLE
How i can get all specified views

### ISSUE THREAD

**Issue by behram** [nelmio/NelmioApiDocBundle#822]
I want to expose all doc links via all unique views. How i can do this? I looked all services but any of them returns all unique views

**Comment by devchunin** [comment]
I need a solution for this issue too

**Comment by behram** [comment]
@devchunin i solved this issue with routing options. you can inspect below links;

 - https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Resources/config/routing_rest.yml#L7
 - https://github.com/ojs/ojs/blob/master/src/Ojs/ApiBundle/Service/Twig/ApiTwigExtension.php#L29
 - https://github.com/ojs/ojs/blob/master/app/Resources/NelmioApiDocBundle/views/layout.html.twig#L699

**Comment by behram** [comment]
i solved problem, so closing issue
