### ISSUE TITLE
enable request listener: terrible idea ?

### ISSUE THREAD

**Issue by maxpou** [nelmio/NelmioApiDocBundle#829]
Hi everyone,

Today I inspect my API with the [JMSDebuggingBundle](https://github.com/schmittjoh/JMSDebuggingBundle) (in a nutshell, this bundle provides advanced debugging tools).

I found something interesting. When I analyze an API request (a simple HTTP GET) :

| Caller | Requested Service | Time |
| --- | --- | --- |
| ... | ... | ... |
| Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher::lazyLoad() | nelmio_api_doc.event_listener.request | 257.999 ms |
| appDevDebugProjectContainer::getNelmioApiDoc_EventListener_RequestService() | nelmio_api_doc.extractor.api_doc_extractor | 98.001 ms |
| ... | ... | ... |
| appDevDebugProjectContainer::getNelmioApiDoc_EventListener_RequestService() | nelmio_api_doc.formatter.html_formatter | 169 ms |
| appDevDebugProjectContainer::getNelmioApiDoc_Formatter_HtmlFormatterService() | templating | 184 ms |
- Created services : 407
- Service calls : 546
- Time : 1512 ms

I've got several bundles and NelmioApiDocBundle is the time-consuming winner :(

So I disable the request listener in my `config.yml`:

``` yml
nelmio_api_doc:
    #...
    request_listener:
        enabled: false
```

Now I've got this:

| Caller | Requested Service | Time |
| --- | --- | --- |
| ... | ... | ... |
| appDevDebugProjectContainer::getTwigService() | nelmio_api_doc.twig.extension.extra_markdown | 10.001 ms |
- Created services : 373
- Service calls : 498
- Time : 841 ms

That's all! (and all my tests still passing)

So my question is: **Is it really a good idea to enable by default the request listener?** This feature seems time consuming...

In advance, thank you.

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version. if its still there, a pull request to the README to tell people they might want to disable that listener when they don't need it would be nice.
