### ISSUE TITLE
Specify output status code

### ISSUE THREAD

**Issue by emiliemarchand** [nelmio/NelmioApiDocBundle#830]
When generating output documentation the status code shown in the **return block** is always 200. However in my case I am returning a 201, as we can see in the statusCodes annotation. Is there a way to override the value shown for the output? Or maybe just hide it when the statusCodes annotation is provided?

Here are my annotations:

```
/**
   * @ApiDoc(
   *   resource=true,
   *   section="Job",
   *   description="Create a new job",
   *   input="AppBundle\Form\ApiJobType",
   *   output={
   *       "class"="AppBundle\Entity\Job",
   *       "groups"={"api_create"},
   *       "parsers"={
   *         "Nelmio\ApiDocBundle\Parser\JmsMetadataParser"
   *       }
   *   },
   *   statusCodes = {
   *     Codes::HTTP_CREATED = "Returned when successful",
   *     Codes::HTTP_BAD_REQUEST = "Returned when the form has errors"
   *   }
   * )
   *
   * @param Request $request
   * @return Response
   */
```

And the result:
![response_status_code](https://cloud.githubusercontent.com/assets/1138942/14046151/b6908570-f275-11e5-8130-7aa23482ca63.PNG)

**Comment by maxpou** [comment]
Hi Emily,
Outpout require a HTTP Code 200 (see  Nelmio\ApiDocBundle\Annotation\ApiDoc.php line 287). I don't know why :-/

Instead, you can use another great parameter : responseMap!

```php
     * @ApiDoc(
     *    //...
     *    statusCodes = {
     *        201 = "Returned when successful",
     *        400 = "Returned when the form has errors"
     *    },
     *    responseMap = {
     *        201 = {
     *            "class" = Job::class,
     *            "groups"={"api_create"}
     *        },
     *        400 = {
     *            "class" = ApiJobType::class,
     *            "form_errors" = true,
     *            "name" = ""
     *        },
     *    }
     * )
```

**Comment by emiliemarchand** [comment]
Thanks Maxpou! I'll use the responseMap instead for now. But I still think the http code shouldn't be hardcoded for the ouput

**Comment by AlexandreHagen** [comment]
@emiliemarchand I think too !

**Comment by willdurand** [comment]
> But I still think the http code shouldn't be hardcoded for the ouput

:+1:

**Comment by mvrhov** [comment]
As this has been merged IMO it should be closed.

**Comment by fscholly** [comment]
Where can I find documentation about Response Map options please ? I would to doc this kind of response.

 `$errors = $this->get('validator')->validate($athleteWeight);
        if (count($errors)) {
            return $this->view($errors, Response::HTTP_BAD_REQUEST);
        }`

` responseMap = {
     *          201 = {
     *               "class"  = "AppBundle\Entity\AthleteWeight",
     *               "parsers"= {"Nelmio\ApiDocBundle\Parser\JmsMetadataParser"},
     *               "groups" = "show"
     *          },
     *          400 = {
     *               "class"  = "",
     *               "form_errors"=true, 
     *               "name" = ""
     *           },
     *      },`
Code above show something like :

 400 - Returned when the request was not valid
status_code 	integer 	* 	The status code
message 	string 	* 	The error message
errors 	errors 	* 	Errors

But my response is :
[{
"property_path":"...",
"message":"..."
}]

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
