### ISSUE TITLE
collections always have boolean default value of `true`

### ISSUE THREAD

**Issue by duncangrist** [nelmio/NelmioApiDocBundle#831]
It appears that `CollectionParser.php` hardcodes collections to always have a default value of `true`, which can result in the following swagger 1.2:

``` json
{
    "paramType": "form",
    "name": "data",
    "type": "array",
    "defaultValue": true,
    "items": {
        "type": "string"
    },
    "description": "My description"
}
```

Is this expected behaviour? Doesn't seem very logical to me as by their very nature collections cannot have a scalar default value.

The problem seems to be in `CollectionParser.php`, line 70:

``` php
...
'default' => true,
...
```

Surely this should be:

``` php
...
'default' => null,
...
```

I have a PR ready to be submitted if this is indeed a bug...

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version. if its still there, please send the pull request. the default could be [] , not sure if null is better.
