### ISSUE TITLE
Argument 2 passed to xxx must be of the type array, string given"

### ISSUE THREAD

**Issue by NadaBen** [nelmio/NelmioApiDocBundle#834]
hello
please i need some help here
how to insert an array type in sandbox 
it shows me this error Argument 2 passed to xx must be of the type array, string given"

my function is as follows:
`         /**
     \* @ApiDoc(description="Uploads photo with tags.")
     *
     \* @Rest\FileParam(name="image", image=true, description="Image to upload.")
     \* @Rest\RequestParam(name="tags", requirements=".+", nullable=false, map=true, description="Tags that associates photo.")
     \* @Rest\View()
     */
    public function postPhotoAction(ParamFetcher $paramFetcher, array $tags)
    {
        $em = $this->getDoctrine()->getManager();

```
    $photo = new Photo();
    $form = $this->createForm(new PhotoType, $photo);

    if ($tags) {
        $tags = $em->getRepository('TestTaskTagsBundle:Tag')->findOrCreateByTitles($tags);
    }

    $form->submit($paramFetcher->all());

    if (!$form->isValid()) {
        return $form->getErrors();
    }

    foreach ($tags as $tag) {
        $photo->addTag($tag);
    }

    $em->persist($photo);
    $em->flush();

    return array('photo' => $photo);
}`
```

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
