### ISSUE TITLE
Merge ReqestParam with Nelmio's parameter

### ISSUE THREAD

**Issue by devantoine** [nelmio/NelmioApiDocBundle#847]
When using `@RequestParam` annotation from FosRestBundle it would be nice to merge it in the doc with the parameter having the same name:

```
 * @RequestParam(name="supplier", nullable=false)
 * @ApiDoc(
 *     parameters={
 *         {"name"="supplier", "dataType"="Supplier", "required"=true, "description"="Supplier's data"}
 *     }
 * )
```

Like so it would be possible to add more informations to the `@RequestParam`. Currently `@RequestParam` override Nelmio's parameter.

I've already edited the code to act like that, I could do a simple PR.

**Comment by Ener-Getick** [comment]
if #848 is accepted (it's a long term issue/work), it would be really easy to implement :-)

**Comment by devantoine** [comment]
Seems like a huge change, not sure it'll be implemented any time soon.

Meanwhile my change is only the following one in ApiDoc:

    public function addParameter($name, array $parameter)
    {
        $parameter = isset($this->parameters[$name]) ? array_merge($parameter, $this->parameters[$name]) : $parameter;
        $this->parameters[$name] = $parameter;
    }

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
