### ISSUE TITLE
Retarget the bundle

### ISSUE THREAD

**Issue by GuilhemN** [nelmio/NelmioApiDocBundle#848]
[The 2.0 version of this bundle](https://github.com/nelmio/NelmioApiDocBundle/releases/tag/2.0.0) has now been released 4 years ago ! Thanks a lot @willdurand !

A powerful language exists to describe rest APIs: [Swagger](http://swagger.io/). So I'm wondering if it wouldn't be the time to release a new major version of this bundle which would be lighter.
I found a [great library](https://github.com/gossi/swagger) abstracting a swagger configuration so we could use it to have cleaner files and BTW, instead of having our own html formatters, we could use the ones supporting swagger like the [SwaggerUiBundle](https://github.com/activelamp/swagger-ui-bundle).

This bundle would be easier to maintain and we can imagine a great future for it !
Maybe it would be better to develop a new bundle from scratch but that would force a lot of people to update their app...

Any thought about it @willdurand ? :-)

**Comment by Ener-Getick** [comment]
[here](https://github.com/nelmio/NelmioApiDocBundle/compare/master...Ener-Getick:SWAGGER?expand=1) is a small part of what I would like to do.

**Comment by GuilhemN** [comment]
I created [a new bundle](https://github.com/EXSyst/ApiDocBundle) that aims to replace the NelmioApiDoBundle. Feel free to review/contribute :)

**Comment by willdurand** [comment]
Great, but why not reusing NelmioApiDoBundle so that people don't get lost? You don't need to promote it because everyone knows it, etc.?

**Comment by GuilhemN** [comment]
Sure that would be great. In fact, EXSystApiDocBundle is my proposal to https://github.com/nelmio/NelmioApiDocBundle/issues/900 (it was created before it, but it was already my vision of NelmioApiDocBundle's future).
I only got one feedback so I don't know if the others agree to my implementation.

If you agree I can move my repository as a `dev` branch of this repository, it may be easier to get feedbacks on it.

**Comment by willdurand** [comment]
Sure. Let's ping @Seldaek for the push/pull rights and @joelwurtz who started #900.

**Comment by Seldaek** [comment]
I sent an invite to @joelwurtz, sorry for the delay, xmas and all :)

**Comment by Seldaek** [comment]
Oh maybe I misunderstood. You wanted me to add @GuilhemN? Should I add Joel anyway or not?

**Comment by GuilhemN** [comment]
@Seldaek thanks ! And no problem for the delay, I didn't progress much anyway ;)

**Comment by GuilhemN** [comment]
Closing as it's now a Work In Progress :)
Thanks !
