### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by tarlepp** [nelmio/NelmioApiDocBundle#858]
It would be very helpful if this repository contains a changelog which tells what is added in each version and what's only on the master branch atm.

Just spended couple of hours to get headers annoations to work, and then I realize that I was using stable version, and that version doesn't support header annotations...

**Comment by dbu** [comment]
good point. @GuilhemN can we try to do request this in all pull requests?

at least, there is a UPGRADE-3.0.md to help with the upgrading to version 3.

**Comment by GuilhemN** [comment]
Done, thanks to @dbu :)
