### ISSUE TITLE
Confusion with naming strategies (underscore vs. camelCase)

### ISSUE THREAD

**Issue by Gregoire-M** [nelmio/NelmioApiDocBundle#867]
I have a model class called `Address`, with a `$zipCode` property (camelCase):

``` php
    /**
     * @Type("string")
     */
    private $zipCode;
```

For this object, my API expects a JSON property `zip_code` (underscore). I think that's the default behaviour of the JMS serializer.

The generated API doc parameters look like this:

| Parameter | Type | Required ? | Format | Description |
| --- | --- | --- | --- | --- |
| address[zip_code] | string | false |  |  |

When I add validation annotations to populate the "Format" column, here is the result:

``` php
    /**
     * @Assert\NotNull()
     * @Assert\Length(max="20")
     * @Type("string")
     */
    private $zipCode;
```

| Parameter | Type | Required ? | Format | Description |
| --- | --- | --- | --- | --- |
| address[zip_code] | string | false |  |  |
| address[zipCode] |  | true | {length: max: 20} |  |

As you can see, there's a duplication of the property, with 2 different naming strategies.

If I underscore the property in my model class, it works fine. But I don't want to overrule my naming conventions for that.

Is it a bug, or something I'm doing wrong?

**Comment by Nanakii** [comment]
I have the same issue, can we have some feedback on this ?

**Comment by Mairu** [comment]
You can use `@SerializedName("zipCode")` annotation from JMS to use only camelCase notation as workaround.

**Comment by CaptainQuirk** [comment]
Having the same difficulty here. I don't want to use the camelCase version and using the underscore version in the ```@SerializedName``` annotation doesn't work : It get's dupplicated.

**Comment by CaptainQuirk** [comment]
Sorry ! You have to configure the parsers ! However, if you want the jms serializer to be respected and validation assertion to be taken into account, you're in trouble !

**Comment by sfarkas1988** [comment]
Is this a new issue or was it always this way? I've exactly the same problem and don't see a valid reason for it.

**Comment by jmaheux** [comment]
I used a custom parser for this. See my comment on [this other issue](https://github.com/nelmio/NelmioApiDocBundle/issues/529#issuecomment-254338664).

**Comment by develth** [comment]
I made a pull request where you can configure your validation parsers through config.yml

Here is an example of an SnakeCaseValidationParser

https://gist.github.com/develth/9b4e738538e27e1b6e117b4d2a4c7c03

Thanks to @jmaheux  for the hint.

**Comment by JustBlackBird** [comment]
Any progress on this? I'm in the same trouble with duplicated names.

**Comment by develth** [comment]
@JustBlackBird  check out my merge request.

**Comment by JustBlackBird** [comment]
@develth well, my question was addressed mostly to the bundle maintainers 😄 

As for the pull request, it's only part of a solution because it does not include custom ValidationParser (which actually could fix the problem).

**Comment by develth** [comment]
My PullRequest is about custom ValidationParser, configurable via config.yml

The ValidationParser you want to use is in my gist:
https://gist.github.com/develth/9b4e738538e27e1b6e117b4d2a4c7c03

**Comment by JustBlackBird** [comment]
@develth yep, I've seen the gist. At the same time I don't think it's not a good idea to copy-paste it into each project using NelmioApiDocBundle 😉

**Comment by develth** [comment]
For sure - its a simple solution for an custom ValidationParser that solves the issue. You can do your own - and set it with my pull request in the config ;)

**Comment by SulivanDotEu** [comment]
Here is an other gist in order to handle snake case and validation groups:

https://gist.github.com/SulivanDotEu/0cb89b7f7f8cda59313c757a6573ee6d

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
