### ISSUE TITLE
Can't flush in prod environment ?

### ISSUE THREAD

**Issue by TheKassaK** [nelmio/NelmioApiDocBundle#872]
Hello !

I just want to know something, when I try to test a webservice via /api/doc in my dev environment : Myurl/app_dev.php/api/doc, it's ok, no problem. 

But if I try in prod environment, my command flush() in my webservice doesn't work. Nothing is update on database.

Is it normal ? For security maybe ? Or something else ? Thanks !

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
