### ISSUE TITLE
Request File uploads breaked in 2.13.0

### ISSUE THREAD

**Issue by d3face** [nelmio/NelmioApiDocBundle#873]
As input for API i have as Parameter
image   file    true        Image data

in sandbox previous versions worked upload of files, now in 2.13.0
it gives me

Request body
image=cat.jpg

curl -X "POST" -d "image=cat.jpg" /path

But this need to upload file named cat.jpg, as multipart/data

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
