### ISSUE TITLE
Display documentation with duplicate routes

### ISSUE THREAD

**Issue by Chrysweel** [nelmio/NelmioApiDocBundle#876]
Hello.

I saw that my documentation shows duplicate information, the route shown twice. ( Into and out of the box.)

> /topics
> /topics
> /topics/{id}
> /topics/{id}

![nelmio](https://cloud.githubusercontent.com/assets/1416870/16185757/711c6ec4-36c6-11e6-9bd6-9590dfee6fd2.png)

Instead of appear as in the documentation, this is the captura of documentation official.

![nelmio-official](https://cloud.githubusercontent.com/assets/1416870/16185761/74b24c70-36c6-11e6-96c2-f3df28cc3d6c.png)

Must I include some annotation ?

**Comment by cve** [comment]
+1

**Comment by nateevans** [comment]
+1

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
