### ISSUE TITLE
Conflicts with symfony 2.7.15

### ISSUE THREAD

**Issue by EkanMagnia** [nelmio/NelmioApiDocBundle#879]
Hello.

I can not install Nelmio/ApiDocBundle because of the following error:

Problem 1
    - nelmio/api-doc-bundle dev-master conflicts with symfony/symfony[v2.7.15].
    - nelmio/api-doc-bundle dev-master conflicts with symfony/symfony[v2.7.15].
    - nelmio/api-doc-bundle dev-master conflicts with symfony/symfony[v2.7.15].
    - Installation request for nelmio/api-doc-bundle dev-master -> satisfiable by nelmio/api-doc-bundle[dev-master].
    - Installation request for symfony/symfony (locked at v2.7.15, required as 2.7.*) -> satisfiable by symfony/symfony[v2.7.15].

What version should I install or what should I do?

**Comment by cigoe** [comment]
Just hit this as well seems that ~2.11 is the latest version that will install with 2.7

**Comment by EkanMagnia** [comment]
You are right.that was the latest that worked for me.
