### ISSUE TITLE
Getting a semantical error on ApiDoc

### ISSUE THREAD

**Issue by sigzegv** [nelmio/NelmioApiDocBundle#881]
I am getting this kind of error, on a SF3 (with microkernel) project : 

> [Semantical Error] The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method blablablaAction does not exist, or could not be auto-loaded. 

I used "nelmio/api-doc-bundle": "^2.13", in my composer.json, the bundle is loaded from the kernel.
Then I put the `use Nelmio\ApiDocBundle\Annotation\ApiDoc;` in my controller and start using the @ApiDoc annotation, and the exception pops when I go to my /api/doc route. If I don't use any apidoc annotation, the /api/doc page display correctly it's green banner.
If I try to create an ApiDoc object in my controller, all works fine, namespace exists.

Here are my used packages : 

> ```
>     "php": "~7.0.0",
>     "symfony/symfony": "~3.0",
>     "symfony/security-bundle": "^3.0",
>     "symfony/twig-bundle": "^3.1",
>     "incenteev/composer-parameter-handler": "~2.1",
>     "sensio/distribution-bundle": "~5.0",
>     "symfony/monolog-bundle": "~2.8",
>     "symfony/validator": "^3.0",
>     "doctrine/doctrine-bundle": "~1.6",
>     "nelmio/api-doc-bundle": "^2.13"
> ```

If I force`$this->classExists['Nelmio\ApiDocBundle\Annotation\ApiDoc'] = true;` in the classExists from the DocParser, all works fine..

Am I missing something else ?

**Comment by Filip-Konkowski** [comment]
I have exactly the same problem. $this->classExists['Nelmio\ApiDocBundle\Annotation\ApiDoc'] = true; also works.
I am using 
"nelmio/api-doc-bundle": "2.11.0"
"symfony/symfony": "~2.7.0",
"doctrine/orm": "~2.4",

Any suggestions how it can be solved?

**Comment by GuilhemN** [comment]
If you don't use [the symfony standard edition](https://github.com/symfony/symfony-standard/blob/master/app/autoload.php), you must configure the `AnnotationRegistry` manually:
```php
use Doctrine\Common\Annotations\AnnotationRegistry;

AnnotationRegistry::registerLoader([$loader, 'loadClass']);
```

**Comment by Filip-Konkowski** [comment]
Hi GuilhemN,

I am using symfony standard edition in /app/autoload.php 
```
<?php

use Doctrine\Common\Annotations\AnnotationRegistry;
use Composer\Autoload\ClassLoader;

/**
 * @var ClassLoader $loader
 */
$loader = require __DIR__.'/../vendor/autoload.php';

AnnotationRegistry::registerLoader(array($loader, 'loadClass'));

return $loader;
```

Any other idea?

**Comment by GuilhemN** [comment]
First you should not depend on a patch (`"nelmio/api-doc-bundle": "2.11.0"`), i'll search if I can find another reason for this error.

**Comment by wraycode** [comment]
I am getting the same issue when trying to use 
     * @ApiDoc(
     *  resource=true,
     *  description="Register a new user for access to cg open API",
     *  views = { "default", "premium" }

The annotation "@Nelmio\ApiDocBundle\Annotation\ApiDoc" in method does not exist my autoload has use Doctrine\Common\Annotations\AnnotationRegistry;

composer.json   "nelmio/api-doc-bundle": "dev-master",

**Comment by GuilhemN** [comment]
@wraycode the master branch corresponds to the next major version (3.0) and `@ApiDoc` no longer exists in it (see https://github.com/nelmio/NelmioApiDocBundle/blob/master/UPGRADE-3.0.md).
You have to migrate your code or change your constraint (`~2.0` would be safer).

I close this as I didn't get an answer from the original author.

**Comment by wraycode** [comment]
thanks this is new from scratch app and just getting started with Nelmio appreciate the quick response
