### ISSUE TITLE
Why v2.13 has conflict with symfony ~2.7.8

### ISSUE THREAD

**Issue by mzmgh** [nelmio/NelmioApiDocBundle#883]
What is the solution of this conflict?

**Comment by willdurand** [comment]
There is no solution, except if you manage to understand why the NelmioApiDocBundle test suite fails with Symfony 2.7.8..

**Comment by bjuri** [comment]
@willdurand @Seldaek Guys, could you please provide backport merge with this commit https://github.com/nelmio/NelmioApiDocBundle/commit/05d3a512591771586e10dd215a63f81f0b4d3afb to the versions < 2.13
We have symfony version > 2.7 and this fix with incorrect formating was fixed only in 2.13.0 which is conflicted with our symfony...

**Comment by dbu** [comment]
version 3 has been released and supports recent symfony versions.
