### ISSUE TITLE
InvalidArgumentException on first-time Setup

### ISSUE THREAD

**Issue by AienTech** [nelmio/NelmioApiDocBundle#886]
Hi,
So after the first setup, as I followed documentation, I'm getting this `InvalidArgumentException`:
`The "AcmeDemoBundle" (from the _controller value "AcmeDemoBundle:Default:dummy") does not exist or is not enabled in your kernel!`

I've checked all of my configs and routes, but got nothing, I thought it might be a bug!

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
