### ISSUE TITLE
PHP 5.3 Compatibility

### ISSUE THREAD

**Issue by HitoTech** [nelmio/NelmioApiDocBundle#888]
Hi,

We are using this library to make the documentation for our PHP 5.3 project, and we have a bug since the last release.
After research, it seems to come from this commit https://github.com/nelmio/NelmioApiDocBundle/commit/8aa5e479d1f4ea7dce1572eb05bae71837e94718 .

`JSON_UNESCAPED_UNICODE` is PHP >= 5.4, while the composer.json file says the project is compatible >= 5.3.

I didn't made a PR because I don't know if we should fix the `JSON_UNESCAPED_UNICODE`, or the composer.json file. 
What do you think?

Thanks

**Comment by GuilhemN** [comment]
Php 5.3 support was removed in https://github.com/nelmio/NelmioApiDocBundle/commit/eab2d5d8fcbd759c4ae109b6060b7d90d4269952.
