### ISSUE TITLE
composer update Fatal error: Allowed memory size of xxx bytes exhausted (tried to allocate xxx bytes)

### ISSUE THREAD

**Issue by lgoral** [nelmio/NelmioApiDocBundle#892]
On that PR https://github.com/nelmio/NelmioApiDocBundle/pull/885 withoud changing composer.json build failing  with composer update Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 134217728 bytes)

https://travis-ci.org/nelmio/NelmioApiDocBundle/jobs/148937810

**Comment by ruscon** [comment]
Fixed https://github.com/nelmio/NelmioApiDocBundle/pull/912
