### ISSUE TITLE
Symfony Serializer Parser

### ISSUE THREAD

**Issue by karser** [nelmio/NelmioApiDocBundle#894]
Hello, I'm using Symfony serialization groups and I'd like to reflect them in the documentation.

```
     * @ApiDoc(
     *     output={"class"="AppBundle\Entity\User", "groups"={"login"}}
     * )
```

But ApiDocExtractor extracts the wrong fields because it uses the wrong parsers: ValidationParser and JmsMetdataParser.
![image](https://cloud.githubusercontent.com/assets/1675033/17490537/ee676b98-5dab-11e6-836a-17d0c32d290e.png)

I haven't found SymfonySerializer parser [there](https://github.com/nelmio/NelmioApiDocBundle/tree/master/Parser).
Is there a way to parse Symfony serialization groups?

**Comment by dbu** [comment]
i think that is still missing. contributions welcome!
