### ISSUE TITLE
Questions on requirements, filters, parameters, response, responseMap, and parsedResponseMap

### ISSUE THREAD

**Issue by schristiaans** [nelmio/NelmioApiDocBundle#896]
@jdeveloper @leevigraham @grEvenX @kbsali @dunglas In regard to `@ApiDoc`:
What is the difference between `filters`, `requirements`, and `parameters`?
Also how to use `response`, `responseMap` and `parsedResponseMap` in `@ApiDoc`?

**Comment by schristiaans** [comment]
Seems like this repo is no longer maintained.

**Comment by willdurand** [comment]
It is. 

I spent a lot of time writing documentation. It might be not enough but I did my best given my free time.

**Comment by willdurand** [comment]
Filters are part of the query string for filtering the results like pagination params, sorting, etc.

**Comment by schristiaans** [comment]
@willdurand Thank you so much! I decided to use RAML for documenting my API.
