### ISSUE TITLE
Problem when instantiating controllers as services

### ISSUE THREAD

**Issue by gotardo** [nelmio/NelmioApiDocBundle#897]
Hi,
I have been working on an API and annotating the controller actions to generate documentation with NelmioApiDocBundle. 
Everything worked fine until I changed the way I instantiate the Controllers and started declaring them as services. From that moment on, the documentation of the controllers declared as services are not working properly.
As a sample.
I have this in my `routing.yml`file:

```
my_api_getUser:
    path:     /user
    defaults: { _controller: api_controller.getUser:indexAction }
    methods:  [GET]
```

And this in my `services.yml`file:

```
api_controller.getUser:
    class: ApiBundle\Controller\User\GetController
```

The controller works properly and the documentation used to work before.

Am I commiting a mistake or is there any known issue when loading controllers this way?

Thanks a lot in advance.

**Comment by blackarcanis** [comment]
👍

**Comment by dbu** [comment]
version 3 is a complete rewrite. please check if this is still a problem with version 3 and a recent symfony version.
