### ISSUE TITLE
Add doc for dynamic routes

### ISSUE THREAD

**Issue by xavier-dubreuil** [nelmio/NelmioApiDocBundle#898]
Hello,

I develop a bundle that create dynamic routes for an API. How can I add documentation for those routes which don't have a specific controller action per route ?

**Comment by dbu** [comment]
look at https://github.com/nelmio/NelmioApiDocBundle/blob/master/Routing/FilteredRouteCollectionBuilder.php - i think you would need to see where in the bundle this is used and extend it to add your dynamic routes there.

the CMF ChainRouter might also help you, then you can add a route provider for your dynamic routes and use them everywhere in your project.
