### ISSUE TITLE
Resource duplication

### ISSUE THREAD

**Issue by nicodmf** [nelmio/NelmioApiDocBundle#899]
The resource is duplicated if  :
- the name of the sections is at plural
- the name of the controller is the same
- the resource is fos rest cget action

There is no duplication if the name is singular.

**An exemple** 
- section's name :  Events
- controller's name : EventsController
- action: EventsController::cget

![image](https://cloud.githubusercontent.com/assets/173332/17839389/7721cf34-67e6-11e6-8b8d-a449441fa02f.png)

**Comment by CesarCarrazana** [comment]
+1

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.

version 3 is a complete rewrite and might have fixed this. if its still an issue, please help by sending a pull request to fix it.
