### ISSUE TITLE
can't see output Description

### ISSUE THREAD

**Issue by duckr1031** [nelmio/NelmioApiDocBundle#906]
In My Controller:
output = {"class" = "UserBundle\Entity\UserWrapper",},
In My UserWrapper.php:
![image](https://cloud.githubusercontent.com/assets/21094356/18074428/13d371a2-6e9f-11e6-8673-123340747e5e.png)
I can't see output Description
![image](https://cloud.githubusercontent.com/assets/21094356/18074436/30b2b7ce-6e9f-11e6-93b9-98a5666c609b.png)
How Can I add output description, thanks!

**Comment by duckr1031** [comment]
@jdeveloper @leevigraham @grEvenX @kbsali @dunglas please help, thanks

**Comment by anadomingos** [comment]
I had the same problem and ended up installing JMSSerializerBundle

http://jmsyst.com/bundles/JMSSerializerBundle

How to use:

      use JMS\Serializer\Annotation as JMS;

      class MyClass {

          /**
            * This description with JSM annotation is visible in documentation.
            * 
            * @JMS\Type("string");
            * @JMS\Groups({ "someGroup" })
            * @JMS\SerializedName("parameterNameInDoc")
            * */
            protected $name;
    }

**Comment by dbu** [comment]
you can now also use swagger php annotations in version 3
