### ISSUE TITLE
Bug with api doc page

### ISSUE THREAD

**Issue by ruscon** [nelmio/NelmioApiDocBundle#911]
after updating from 2.12.0 to 2.13.0

![Image of Yaktocat](https://api.monosnap.com/rpc/file/download?id=NKPcILzYGTzilQbx1uKoWjMii0EWVu)

**Comment by Nikoms** [comment]
I will try to fix it... But can somebody tell me what's the purpose of this? Can I just hide these links?

**Comment by dbu** [comment]
might be a cached css or something? version 3 is now out and is a complete rewrite, i did not see the issue with it.
