### ISSUE TITLE
Exclude patterns

### ISSUE THREAD

**Issue by juansss** [nelmio/NelmioApiDocBundle#913]
Any possibility to exclude patterns in the bundle configuration?

**Comment by GuilhemN** [comment]
What do you mean exactly? Excluding some routes ?

**Comment by juansss** [comment]
@GuilhemN  For instance i dont want documentation on routes starting with internal_api_....

Is this possible?

**Comment by GuilhemN** [comment]
You can extend `ApiDocExtractor::getRoutes()` but it is not officialy supported.
This will probably be much easier to do in `3.0` (supported in the config).

**Comment by juansss** [comment]
@GuilhemN  Thanks!
