### ISSUE TITLE
Integer parameters being escaped in Sandbox

### ISSUE THREAD

**Issue by Lube** [nelmio/NelmioApiDocBundle#914]
Maybe im missing something but I cannot get this to work.

Annotation:
  /*\* 
- @Route(" ")
- @Method({"POST"})
- @ApiDoc(
-  resource=true,
-  description="Creates a Lote",
-  section = "RFID",
-  tags={
-    "a revisar: Nahu" = "#f0ad4e"
-  },
-  parameters={
-      {
-       "name"="evento[id]", 
-       "dataType"="integer", 
-       "actualType"="integer",
-       "required"=false, 
-       "description"="Id del evento"
-      },
-  }
- )
  */

Expected content generated { "event" : { "id" : 1} }

Actual content generated { "event" : { "id" : "1"} }

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.

version 3 is a complete rewrite and might have fixed the issue.
