### ISSUE TITLE
Parsing named array property does not seems to work

### ISSUE THREAD

**Issue by GasparMDQ** [nelmio/NelmioApiDocBundle#927]
I need to generate this documentation:
````
{
  "_links" : [
    "string" : {
       "":""
       "":""
    }
  ]
}
````

with this annotation:
````
    /**
     * @JMS\Expose
     * @JMS\Type("array<string,ApiBundle\Entity\Link>")
     * @JMS\SerializedName("_links")
     */
    public $links;
````

But all I get back is:

````
{
  "_links" : [
    {
       "":""
       "":""
    }
  ]
}
````

Which is the same result that I get if I use:
`
     * @JMS\Type("array<ApiBundle\Entity\Link>")
`
without the *string* value.

It looks like a bug, o maybe is a feature that is not available.
On the bundle code I found [this line](https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/JmsMetadataParser.php#L304) so the notation array<K, V> is recognised, but maybe is not yet implemented?

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
