### ISSUE TITLE
How to actually launch this thing so it will generate at least something?

### ISSUE THREAD

**Issue by Vladimir-Voloshin** [nelmio/NelmioApiDocBundle#928]
If those configurations
[https://github.com/nelmio/NelmioApiDocBundle/blob/master/Resources/doc/index.rst](url)
are enough for this bundle to generate docs? 
Can someone provide existing project one can review? Coz your docs are lame. Really.

**Comment by althaus** [comment]
It misses a link to the docs located at the Symfony page:

http://symfony.com/doc/current/bundles/NelmioApiDocBundle/index.html

**Comment by GuilhemN** [comment]
Link updated to point to symfony.com.
