### ISSUE TITLE
Symfony 3 - nelmio_api_doc_index route does not exist

### ISSUE THREAD

**Issue by Tytam** [nelmio/NelmioApiDocBundle#929]
Hi I started with Symfony just a month ago.

Does this work in Symfony 3?

On-The-Fly Documentation¶
By calling an URL with the parameter ?_doc=1, you will get the corresponding documentation if available.

Because i get this error:
{"code":500,"message":"An exception has been thrown during the rendering of a template (\"Unable to generate a URL for the named route \"nelmio_api_doc_index\" as such route does not exist.\") in \"NelmioApiDocBundle::layout.html.twig\" at line 17."}

This aproach works for me  http://myapp/api-docs/mycontroller ,
but http://myapp/mycontroller?_doc=1 does not.

It is no serious issue for me i can work with first approach but I find second aproach nicer.

Thanks for help

**Comment by dbu** [comment]
version 3 has been released and is a complete rewrite. maybe the problem has gone away now. (make sure to include the routing files as the README explains)
