### ISSUE TITLE
NemioApiDocBundle is not working

### ISSUE THREAD

**Issue by gabykant** [nelmio/NelmioApiDocBundle#936]
Something strange with this bundle.
Here is my routing config
```
ksoft:
    resource: "@KsoftBundle/Controller/"
    type:     annotation
    prefix:   /api
```

But when I add this inside the controller, I can't get the documentation displaying.
```
use Nelmio\ApiDocBundle\Annotation\ApiDoc;

class NodeController extends Controller{

    /**
     * @ApiDoc(
     *  resource=true,
     *  description="This is the incoming function. The entry point",
     * )
     **/
    /**
     * @Route("/home")
     */
    public function indexAction()
    {
        return new JSONResponse(array());
    }
}
```
What is missing here ?

**Comment by GuilhemN** [comment]
Maybe using a single doc block would fix your issue?
(e.g. `/** @ApiDoc() */ /** @Route() */ would become `/** @ApiDoc() * @Route() */`)

**Comment by dbu** [comment]
i think guilhem is right: the first block with ApiDoc is not attributed to the method. each thing can only have a single docblock in php.
