### ISSUE TITLE
AnnotationsProvider: allow to define resources

### ISSUE THREAD

**Issue by dominikzogg** [nelmio/NelmioApiDocBundle#946]
I would like to replace the code https://github.com/nelmio/NelmioApiDocBundle/blob/master/Extractor/ApiDocExtractor.php#L144-L149 with:

```{.php}
foreach ($this->annotationsProviders as $annotationProvider) {
    foreach ($annotationProvider->getAnnotations() as $annotation) {
        $route = $annotation->getRoute();
        if ($annotation->isResource()) {
            if ($resource = $annotation->getResource()) {
                $resources[] = $resource;
            } else {
                // remove format from routes used for resource grouping
                $resources[] = str_replace('.{_format}', '', $route->getPath());
            }
        }
        $array[] = array('annotation' => $this->extractData($annotation, $route, $this->getReflectionMethod($route->getDefault('_controller'))));
    }
}
```

to be able creating a xml based annotation provider which also defines resources.

Do i have a chance a PR would get merged?

**Comment by GuilhemN** [comment]
We're currently working on 3.0 and I don't know yet if we will release a last 2.x version but I think it is unlikely.

**Comment by dominikzogg** [comment]
@GuilhemN how close to a stable is the dev branch? Is it worth to implement already logic on its class/method signatures already exists?

**Comment by GuilhemN** [comment]
@dominikzogg we still have a lot to do so I can't tell yet. A lot of things may change so I don't advise to use it in prod but you can try it in your dev env.

**Comment by dominikzogg** [comment]
@GuilhemN thanks for your response

**Comment by dbu** [comment]
@dominikzogg i am cleaning up old issues in this repo :-)
version 3 is out now, can you check if this is still an issue and if so send a pull request?
