### ISSUE TITLE
[3.0]The SwaggerPhpDescriber only scan the kernel root dir.

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#947]
Hi,

Line 8 of the `NelmioApiDocBundle/Resources/config/swagger_php.xml`, the project path is set as `%kernel.root_dir%` 

If I'm not wrong, if should scan the whole source folders, no?

**Comment by GuilhemN** [comment]
Indeed, it should be changed :)
I'd like to make it configurable and default to `%kernel.root_dir%/../src`.

**Comment by GuilhemN** [comment]
Fixed in https://github.com/nelmio/NelmioApiDocBundle/pull/949.
