### ISSUE TITLE
[3.0] The ObjectModelDescriber fails for some output of the PropertyInfo component

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#950]
Data class: 

```
<?php

class TestClass
{
    /**
     * @var int[]
     */
    private $format;

    public function setFormat(array $format)
    {
        $this->format = $format;
    }

    /**
     * @return int[]
     */
    public function getFormat()
    {
        return $this->format;
    }
}

```

When the `ObjectModelDescriber` finds this class, the property info component extract this type:
```
array(1) {
  [0]=>
  object(Symfony\Component\PropertyInfo\Type)#1270 (6) {
    ["builtinType":"Symfony\Component\PropertyInfo\Type":private]=>
    string(5) "array"
    ["nullable":"Symfony\Component\PropertyInfo\Type":private]=>
    bool(false)
    ["class":"Symfony\Component\PropertyInfo\Type":private]=>
    NULL
    ["collection":"Symfony\Component\PropertyInfo\Type":private]=>
    bool(true)
    ["collectionKeyType":"Symfony\Component\PropertyInfo\Type":private]=>
    NULL
    ["collectionValueType":"Symfony\Component\PropertyInfo\Type":private]=>
    NULL
  }
}
```
(It's the `ReflectionExtractor` that does this. Not sure if it's a bug of the component, but I would prefer that it guesses the type from `PhpDocExtractor`)

Later the `ModelRegistry` fails to register it because it does not have a `collectionValueType`.

Not sure about what the right resolution is.

**Comment by GuilhemN** [comment]
I opened https://github.com/symfony/symfony/issues/21367.

**Comment by GuilhemN** [comment]
This will be fixed in [the next symfony patches](https://github.com/symfony/symfony/pull/21370#event-942205876) :)

**Comment by magnetik** [comment]
awesome ! Thanks for handling this :)
