### ISSUE TITLE
Using Your Own Annotations and how I can set ouput on there?

### ISSUE THREAD

**Issue by tarlepp** [nelmio/NelmioApiDocBundle#955]
It seems that `Nelmio\ApiDocBundle\Annotation\ApiDoc` does not support to override `$output` variable, why is that ?

We need this for dynamically set output vars from out endpoints.

Or what is the proper way to set custom output ?

**Comment by tarlepp** [comment]
And what I'm trying to complish is that I have controllers like:

`https://github.com/tarlepp/symfony-backend/blob/master/src/App/Controller/AuthorController.php`
`https://github.com/tarlepp/symfony-backend/blob/master/src/App/Controller/BookController.php`

Which both use my  `generic` REST controller + service + repository to get all that data, and my goal is to generate API docs automatically to these generic routes (controller + trait).

For now the only problem seems to be that I can't set  `output` from my own custom class that implements `Nelmio\ApiDocBundle\Extractor\HandlerInterface`.

So how do I do this?

**Comment by tarlepp** [comment]
Seems like same thing is also within input.

**Comment by GuilhemN** [comment]
It seems like the `ApiDoc` class misses `setInput` and `setOutput` methods. A PR in this direction is welcome if you need it.

**Comment by tarlepp** [comment]
Quite long time for response, and yes a PR would be the proper way to make this happen - unfortunately I didn't have the time for that when I was facing this problem.

I did following "hack" workaround for this to get it working in my app:
```php
$clazz = new \ReflectionClass(\get_class($annotation));
$property = $clazz->getProperty('output');
$property->setAccessible(true);
$property->setValue($annotation, $output);
```

Not so pretty, but it did the trick.

**Comment by GuilhemN** [comment]
> Quite long time for response

Well i'm not usually taking care of 2.x, I just went through some issues but i'm focusing on 3.0. Most of the other contributors don't have enough time anymore to take care of this bundle.

> I did following "hack" workaround for this to get it working in my app

Ok, thanks for your answer, don't hesitate to open a pr if you want to change it.
You can ping me on slack or on twitter in the future if you need me to answer something, I often miss github notifications.

**Comment by tarlepp** [comment]
Hmm, so maybe this should be a required feature within 3.0 ?

**Comment by GuilhemN** [comment]
This is already doable in 3.0:

```php
use Nelmio\ApiDocBundle\Model\Model;
use Symfony\Component\PropertyInfo\Type;

class MyRouteDescriber implements RouteDescriberInterface, ModelRegistryAwareInterface
{
    use RouteDescriberTrait, ModelRegistryAwareTrait;

    public function describe(Swagger $api, Route $route, \ReflectionMethod $reflectionMethod)
    {
        foreach ($this->getOperations($api, $route) as $operation) {
            $operation->getResponses()->get(200)->getSchema()
                ->setRef($this->modelRegistry->register(new Model(new Type(Type::BUILTIN_TYPE_OBJECT, 'My\OutputClass'))));
        }
    }
}
