### ISSUE TITLE
[3.0] Should we support forms?

### ISSUE THREAD

**Issue by GuilhemN** [nelmio/NelmioApiDocBundle#956]
The bundle currently supports forms as input, should we support it in 3.0?

**Comment by Alex-D** [comment]
It's sooooo convenient using Form as input, which avoid long doc and duplication.

**Comment by GuilhemN** [comment]
I'm not using forms very much. Porting https://github.com/nelmio/NelmioApiDocBundle/blob/master/Parser/FormTypeParser.php should be enough but I can't be sure of that, so if someone is willing to make a PR, please do it :)

**Comment by magnetik** [comment]
I'm willing to make the PR but I'm unsure of how to implement: I should add a type in the ModelDescriber?

**Comment by GuilhemN** [comment]
@magnetik yes, I think that's the way to go, probably with `return Type::BUILTIN_TYPE_OBJECT === $model->getType()->getBuiltinType() && FormInterface::class === $model->getType()->getBuiltinType()->getClassName();` in the `supports` method.

**Comment by magnetik** [comment]
Yeah that's what I started. 

I started on https://github.com/magnetik/NelmioApiDocBundle/tree/form I'll do a pull request when something is working  :)

**Comment by GuilhemN** [comment]
Great, thanks :)
