### ISSUE TITLE
Consider adding GitHub Topics to this repository

### ISSUE THREAD

**Issue by javiereguiluz** [nelmio/NelmioApiDocBundle#959]
Dear bundle maintainer(s), if you want to make this bundle easier to discover and want to help us creating a stronger Symfony ecosystem, please consider adding some GitHub topics to this repository.

[The official Symfony recommendation](https://symfony.com/blog/standardizing-the-github-topics-for-symfony-repositories) is to add `php`, `symfony`, `bundle` and `symfony-bundle` topics ... and then, your own specific topics.

Thanks for your help!

**Comment by GuilhemN** [comment]
:+1: 
ping @Seldaek

**Comment by Seldaek** [comment]
Done
