### ISSUE TITLE
[RFC] Integrate fabbot or styleci to build process in order to ensure CS rules

### ISSUE THREAD

**Issue by phansys** [nelmio/NelmioApiDocBundle#962]
In order to keep the clean codebase, some CS tool should be integrated to the build process, even in order to avoid undesired language constructions that don't match the required PHP version, as exposed at #961.
`fabbot` or `styleci` could be good.

**Comment by GuilhemN** [comment]
:+1: I agree but i can't do it myself (i can't edit the config PC the repository).

**Comment by dbu** [comment]
@Seldaek could you please activate styleci for this bundle? a .styleci.yml is already in the bundle code, but me and guilhem do not have permission to activate it.

**Comment by Seldaek** [comment]
Ok it should be on now

**Comment by Seldaek** [comment]
https://styleci.io/analyses/zG01nA

**Comment by dbu** [comment]
thank you!
