### ISSUE TITLE
Nested arrays of objects with the JMS\Inline annotation are not properly parsed

### ISSUE THREAD

**Issue by lrhoek** [nelmio/NelmioApiDocBundle#968]
Nested arrays of objects with the `JMS\Serializer\Annotation\Inline` annotation are not properly parsed by the JMS Metadata Parser.

For instance:

```php
use JMS\Serializer\Annotation as Serializer;

class OutputClass
{
    /**
     * @var SomeCollectionClass[]
     * @Serializer\Type("array<SomeCollectionClass>")
     */
    private $collection;
}

class SomeCollectionClass
{
    /**
     * @var SomeItemClass[]
     * @Serializer\Type("array<SomeItemClass>")
     * @Serializer\Inline()
     */
    private $items;
}
```

will result in:

| Parameter     | Type |
| ---      | ---       |
| collection[] | array of objects (SomeCollectionClass) |
| collection[][items][] | array of objects (SomeItemClass) |

instead of the desired:

| Parameter     | Type |
| ---      | ---       |
| collection[] | array of objects (SomeCollectionClass) |
| collection[][] | array of objects (SomeItemClass) |

The output from JMS itself is correct, a nested array, so I expect the problem to be in the parser.

**Comment by GuilhemN** [comment]
Is this still happening in 3.0?

**Comment by GuilhemN** [comment]
Closing in favor of https://github.com/nelmio/NelmioApiDocBundle/issues/1221.
