### ISSUE TITLE
[3.0] Routes with models are included even when not matching route filter

### ISSUE THREAD

**Issue by magnetik** [nelmio/NelmioApiDocBundle#970]
Hi,

I should try to include a test minimal repro but it seems that route are included in the swagger even when they are not matching the route filter when they have a model definition. 

Thanks

**Comment by GuilhemN** [comment]
I think I'll just get ride of Swagger-php parser, it is very annoying for us for no gain.

**Comment by GuilhemN** [comment]
see https://github.com/nelmio/NelmioApiDocBundle/pull/973
