### ISSUE TITLE
JmsParser does not allow the same collection twice

### ISSUE THREAD

**Issue by anadomingos** [nelmio/NelmioApiDocBundle#977]
I have 2 entities: AppBundle\Entity\User and AppBundle\Entity\School
In the School class, I have those annotations:

    /**
     * List of students.
     * 
     * @ORM\...
     * 
     * @JMS\Type("ArrayCollection<AppBundle\Entity\User>");
     * @JMS\Groups({ "mydoc" })
     * @JMS\SerializedName("students")
     * */
    protected $students;
    
    /**
     * List of teachers.
     * 
     * @ORM\...
     * 
     * @JMS\Type("ArrayCollection<AppBundle\Entity\User>");
     * @JMS\Groups({ "mydoc" })
     * @JMS\SerializedName("teachers")
     * */
    protected $teachers;

Let's say that in the controller I have this in the responseMap:

    /**
     * ....
     *       200 = {
     *             "class" = "AppBundle\Entity\School",
     *             "collectionName" = "schools",
     *             "collection" = true,
     *             "groups"={"mydoc"}
     *         },
     * ...
     */

When I check the documentation, I get:
schools[]
schools[][students][]
schools[][students][][name]
schools[][students][][email]
schools[][teachers][]

The teachers should also have "name" and "email".

So, I decided to check Nelmio code and I change it in order to work as I expected in this particular case.  
I hope it can be part of the project. Otherside, I could not update my composer anymore...

The changes were made in Parser\JmsMetadataParser.php->doParse(). I added the comments REMOVED and ADDED so you can easily check my changes. The "visited" saves the children of each class, so that it can be used in the next item and still avoiding infinite recursion.

      protected function doParse($className, $visited = array(), array $groups = array())
      {
        $meta = $this->factory->getMetadataForClass($className);

        if (null === $meta) {
            throw new \InvalidArgumentException(sprintf("No metadata found for class %s", $className));
        }

        $exclusionStrategies   = array();
        if ($groups) {
            $exclusionStrategies[] = new GroupsExclusionStrategy($groups);
        }

        $params = array();

        $reflection = new \ReflectionClass($className);
        $defaultProperties = array_map(function ($default) {
            if (is_array($default) && count($default) === 0) {
                return null;
            }

            return $default;
        }, $reflection->getDefaultProperties());

        // iterate over property metadata
        foreach ($meta->propertyMetadata as $item) {
            if (!is_null($item->type)) {
                $name = $this->namingStrategy->translateName($item);

                $dataType = $this->processDataType($item);

                // apply exclusion strategies
                foreach ($exclusionStrategies as $strategy) {
                    if (true === $strategy->shouldSkipProperty($item, SerializationContext::create())) {
                        continue 2;
                    }
                }

                if (!$dataType['inline']) {
                    $params[$name] = array(
                        'dataType'     => $dataType['normalized'],
                        'actualType'   => $dataType['actualType'],
                        'subType'      => $dataType['class'],
                        'required'     => false,
                        'default'      => isset($defaultProperties[$item->name]) ? $defaultProperties[$item->name] : null,
                        //TODO: can't think of a good way to specify this one, JMS doesn't have a setting for this
                        'description'  => $this->getDescription($item),
                        'readonly'     => $item->readOnly,
                        'sinceVersion' => $item->sinceVersion,
                        'untilVersion' => $item->untilVersion,
                    );

                    if (!is_null($dataType['class']) && false === $dataType['primitive']) {
                        $params[$name]['class'] = $dataType['class'];
                    }
                }
                

                // we can use type property also for custom handlers, then we don't have here real class name
                if (!class_exists($dataType['class'])) {
                    continue;
                }
                
                
                // <REMOVED>
               /*              
                // if class already parsed, continue, to avoid infinite recursion
                if (in_array($dataType['class'], $visited)) {           
                    continue;
                }
               */
                // </REMOVED>
             
                
                
                

                // check for nested classes with JMS metadata
                if ($dataType['class'] && false === $dataType['primitive'] && null !== $this->factory->getMetadataForClass($dataType['class'])) {
                    
                    // <ADDED>
                    // if class already parsed, get the previous saved children, to avoid infinite recursion
                    if (array_key_exists($dataType['class'], $visited)) {
                        
                        $children = $visited[ $dataType['class'] ];
                        
                    }else{
                        
                        $children  = $this->doParse($dataType['class'], $visited, $groups);
                        $visited[ $dataType['class'] ] = $children;
                    }
                    // </ADDED>
                    
                    // <REMOVED>
                //    $visited[] = $dataType['class']; 
                    // </REMOVED>
                    
         
                    if ($dataType['inline']) {
                        $params = array_merge($params, $children);
                    } else {
                        $params[$name]['children'] = $children;
                    }
                }
            }
        }

        return $params;
    }

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.

is this still an issue with version 3?
