### ISSUE TITLE
input doesnt allow collection as parameter?

### ISSUE THREAD

**Issue by ChrOst** [nelmio/NelmioApiDocBundle#978]
I tried the same syntax for input then you can use it with output
now the following works:

```
    /**
     * @ApiDoc(
     *     output={
     *      "class" = "MyBundle\Entity\myEntity",
     *      "collection" = true,
     *     }
     * )
     */
```

while doing the same with input it just renders an empty parameters "table":
```
    /**
     * @ApiDoc(
     *     input={
     *      "class" = "MyBundle\Entity\myEntity",
     *      "collection" = true,
     *     }
     * )
     */
```

I was testing around more, Array<> and ArrayCollection<> ofc didnt work either.
And as sending JSON Objects using the following Syntax is allowed and deserializable, it should be documentable too:
```
[{"name": "test"}, {"name": "testagain"},{"name": "last"}]
```

Removing the collection parameter, it of course renders the parameters in the correct way.

**Comment by GuilhemN** [comment]
I can't really help you on this but just note that 3.0 does support this:
```php
/**
 * @SWG\Parameter(
 *     name="body",
 *     in="body",
 *     @SWG\Schema(
 *         type="array",
 *         @Model(type="MyBundle\Entity\myEntity")
 *     )
 * )
*/
```

**Comment by MichaelHindley** [comment]
@GuilhemN 
say I had an input annotation in 2x that mapped to a single class, in 3.0, this functionality does not work?

@SWG\Schema type does not accept "object", so how does one use an object with properties like with the old input annotation?

**Comment by dbu** [comment]
3.0 is now released.
