### ISSUE TITLE
How to use the dataType array

### ISSUE THREAD

**Issue by numediaweb** [nelmio/NelmioApiDocBundle#979]
How can I make the sandbox send an array to the controller? 
```
     *     parameters= {
     *       {
     *         "name"="roles",
     *         "dataType"="array",
     *         "required"=true,
     *         "description"="Roles to patch for the logged user"
     *       }
     *     },
```

This turns a string.

Am I missing something? I checked the documentation but couldn't find anything related to arrays.

**Comment by bvisonl** [comment]
I've found a CHEATING (note the caps) for this... please don't hate me:

![image](https://cloud.githubusercontent.com/assets/4421747/25362340/48d8cdec-2921-11e7-9aa4-bec144f399e0.png)

You can just trick the url by passing & and [] into the same parameter. Note that you have to smuggle the first parameter value in before adding more &parameters[]=

**Comment by GuilhemN** [comment]
Note that this is supported in 3.0:
```php
/**
 * @SWG\Parameter(
 *     name="parameters",
 *     in="query",
 *     type="array",
 *     collectionFormat="multi",
 *     @SWG\Items(
 *         type="string"
 *     )
 * )
 */

**Comment by dbu** [comment]
i am closing old tickets without activity. feel free to open a new issue if needed.
