### ISSUE TITLE
The results of the "Sandbox" tool are blocked by AdBlock (in some cases) ...

### ISSUE THREAD

**Issue by josedacosta** [nelmio/NelmioApiDocBundle#986]
Hello,

The results of the "Sandbox" tool are blocked by AdBlock (in some cases) ...

Could you add an AdBlock presence checker,
Check the output and display an alert to indicate: there is a problem, think about checking AdBlock ...

AdBlock Plus
Https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb

Presence of "ads" in the url:

`` `
Request URL : 
GET http://test.com/ads
`` `

`` `
Response Headers [Expand] : 
0 error
`` `

`` `
Response Body [Raw] : 
`` `

Non-priority, because you can disable the url in AdBlock

thank you

**Comment by GuilhemN** [comment]
Closing as 2.0 is no longer maintained, should be fixed by 3.0.
