### ISSUE TITLE
option to not encode the HTML output of the results of the tool "Sandbox", for dump()

### ISSUE THREAD

**Issue by josedacosta** [nelmio/NelmioApiDocBundle#987]
Hello,

could you add an option to **not encode the HTML output** of the results of the **tool "Sandbox"**

Because when dump () output is unreadable ...

look :

![image](https://cloud.githubusercontent.com/assets/3801119/25304669/260abd4a-276c-11e7-836c-29680c5de8ed.png)

my patch :

/vendor/nelmio/api-doc-bundle/Nelmio/ApiDocBundle/Resources/views/layout.html.twig

```
// $container.html(attachCollapseMarker(prettifyResponse(rawData)));
$container.html(prettifyResponse(rawData).text());
...
// prettyPrint && prettyPrint();
...
// return $('<div>').text(text).html();
return $('<div>').text(text);
```

result :
![image](https://cloud.githubusercontent.com/assets/3801119/25304692/ae3c175e-276c-11e7-96a2-6fed8b0e94a6.png)

Detecting ...
IF it's JSON, THEN prettyPrint
IF NO (encode HTML OR not encode HTML) (depending on the option)

Or, by default in "/app_dev.php/" do not encode the output ...

thank you

**Comment by GuilhemN** [comment]
Closing as 2.0 is no longer maintained.
