### ISSUE TITLE
Multiple input/output with multi views

### ISSUE THREAD

**Issue by max21** [nelmio/NelmioApiDocBundle#997]
Hi,
It is possible to specify different input/output for different views (default or premium) ?

Thanks

**Comment by qweluke** [comment]
@max21 have you figured it out?

**Comment by max21** [comment]
Nope..

**Comment by GuilhemN** [comment]
Not exactly what you want but 3.1 provides areas support https://symfony.com/doc/current/bundles/NelmioApiDocBundle/areas.html and you can alter your documentation by registering a custom describer.

**Comment by qweluke** [comment]
@GuilhemN when this will be available?
There is no v 3.1 at this moment :(
https://github.com/nelmio/NelmioApiDocBundle/tags

**Comment by GuilhemN** [comment]
@qweluke I just released it https://github.com/nelmio/NelmioApiDocBundle/releases/tag/v3.1.0 :)
