### ISSUE TITLE
Ability to set output format

### ISSUE THREAD

**Issue by cadavre** [nelmio/NelmioApiDocBundle#999]
I believe it's what was mentioned in #994 .

What would be great: to define format of `output` parameter. Right now when I select JMSSerializer-enabled entity I get a table of "Parameter | Type | Versions | Description" rows.

Great option would be possibility to define this output format to another, like JSON – so it would be a JSON exemplary response instead of list of parameters.

**Comment by GuilhemN** [comment]
Closing as 2.0 is no longer maintain. If I understand well your issue, 3.0 fixes it.
